### ISSUE TITLE
Adding Microsoft.Intune.MAM.Xamarin.iOS nuget package to Xamarin Forms iOS app fails

### ISSUE THREAD

**Issue by rzdebskiy** [msintuneappsdk/ms-intune-app-sdk-ios#10]
Adding Microsoft.Intune.MAM.Xamarin.iOS nuget package to Xamarin Forms iOS project fails with the following error:
Package Microsoft.Intune.MAM.Xamarin.iOS 3.0.3989.3 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Package Microsoft.Intune.MAM.Xamarin.iOS 3.0.3989.3 supports: net452xamarinios10 (net452+Xamarin.iOS10,Version=v0.0)

Looks very much similar to this issue - https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/8 

Steps to reproduce:
Visual Studio 15.7.1 
1. New Project -> Cross Platform - Mobile App (Xamarin Forms).
2. Add Microsoft.Intune.MAM.Xamarin.iOS nuget package to Xamarin Forms iOS - error occurs

**Comment by Kyle-Reis** [comment]
@rzdebskiy we should have a fix available for this soon!

**Comment by Kyle-Reis** [comment]
The fix for this issue is now available in version 3.0.4072.4 of the Microsoft.Intune.MAM.Xamarin.iOS NuGet package.

**Comment by msintuneappsdk** [comment]
Closing issue.

**Comment by rzdebskiy** [comment]
Great, thank you @Kyle! Issue has gone.
