### ISSUE TITLE
“IntuneMAMConfigurator” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by niteeshkr20** [msintuneappsdk/ms-intune-app-sdk-ios#102]
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**
While Integrating intune sdk for ios got this issue.
<img width="421" alt="Screenshot 2020-08-17 at 2 38 33 PM" src="https://user-images.githubusercontent.com/24302315/90378746-5ccf6280-e097-11ea-9c2b-045ad8a250e6.png">

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios and follow the steps to integrate SDK.
2. While going through 7th step got this error pop up.

**Expected behavior:**
Shuold not give this issue while executing.

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3

**Smartphone (please complete the following information):**
 - Device: MacBook Pro (15-inch, 2018)
 - OS: iOS 10.15.5 

<<<<<<< HEAD
**Intune App SDK for iOS (please complete the following information):**
- Latest GitHub Version

**Comment by Kyle-Reis** [comment]
Hi @niteeshkr20, we'll look into this. In the meantime, you can work around this issue by right-clicking the IntuneMAMConfigurator executable and selecting "Open". Then in the Window that appears, select "Open" again. After this you should be able to run the IntuneMAMConfigurator from the terminal.

**Comment by niteeshkr20** [comment]
Hi @Kyle-Reis,

Thanks, Workaround worked.
