### ISSUE TITLE
Bug report template has merge conflicts

### ISSUE THREAD

**Issue by BenLeggiero** [msintuneappsdk/ms-intune-app-sdk-ios#105]
<<<<<<< HEAD
=======
---
name: Bug report template has merge conflicts
about: Bug report template
title: 'Bug report template has merge conflicts'
labels: 'meta','bug'
assignees: ''

---

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**
The bug report template has merge conflicts

**To Reproduce**
1. https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/new

**Expected behavior:**
The bug report template does not have merge conflicts

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. <img width="658" alt="Screen Shot 2020-09-01 at 15 44 06" src="https://user-images.githubusercontent.com/10189808/91909186-fab35780-ec69-11ea-8e04-5f7779fe0166.png">
<<<<<<< HEAD
- If your app is experiencing an issue during build, do you have app logs for the crash itself?  **Not Applicable**
- If your app is experiencing an issue post build, do you have app logs for the crash itself?  **Not Applicable**
=======
- If your app is crashing post-wrapping, do you have app logs for the crash itself?   **Not Applicable**
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors?   **Not Applicable**
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3

**Smartphone (please complete the following information):**
 - Device:   **Not Applicable**
 - OS:   **Not Applicable**

<<<<<<< HEAD
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?  **Not Applicable**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?  **Not Applicable**
- For errors during build, does the app build without Intune SDK integration?  **Not Applicable**
- For errors post build, does the app launch without being Intune SDK integrated?  **Not Applicable**
=======
**Intune app wrapping tool (please complete the following information):**  **Not Applicable**
- What version of the wrapper are you using? Are you using the latest version?  **Not Applicable**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?  **Not Applicable**
- For pre-wrapping errors, does the app build without being wrapped?  **Not Applicable**
- For post-wrapping errors, does the app launch without being wrapped?  **Not Applicable**
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
- Who is the customer?  **Not Applicable**
- Do you see a trend with it only being reproduced on a specific device?  **Not Applicable**

**Additional context:**
None

**Comment by Kyle-Reis** [comment]
Thanks for pointing this out @BenLeggiero. Fixed!
