### ISSUE TITLE
dyld: Library not loaded: @rpath/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub

### ISSUE THREAD

**Issue by bhandaribhumin** [msintuneappsdk/ms-intune-app-sdk-ios#106]
**Describe the bug:**
I try to add Intune SDK into [ms-identity-mobile-apple-swift-objc](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc) project for override policy.

<img width="341" alt="thumbnail_image001" src="https://user-images.githubusercontent.com/3336047/92112351-46513700-ee0b-11ea-90ec-d627882dc92b.png">

follow steps : https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app
**Screenshots and logs:**
step1: Drag IntuneMAMSwift.framework and IntuneMAMSwiftStub.framework to the Embedded Binaries list of the project target

<img width="800" alt="Screenshot 2020-09-03 at 12 55 32 PM" src="https://user-images.githubusercontent.com/3336047/92086115-5ce59700-ede7-11ea-8881-5004a5028410.png">

step2: 

<img width="800" alt="Screenshot 2020-09-03 at 12 56 18 PM" src="https://user-images.githubusercontent.com/3336047/92084815-8f8e9000-ede5-11ea-81bc-8156e016d7a1.png">

I want to override IntuneMAMPolicyManager these Azure AD settings at runtime so create bridge for access IntuneMAM.h from headers folder.
<img width="800" alt="Screenshot 2020-09-03 at 12 56 45 PM" src="https://user-images.githubusercontent.com/3336047/92085591-ab466600-ede6-11ea-9117-66c9002e4ae9.png">
<img width="800" alt="Screenshot 2020-09-03 at 12 56 58 PM" src="https://user-images.githubusercontent.com/3336047/92085626-b7cabe80-ede6-11ea-832c-f2eb42de88dc.png">

**Smartphone (please complete the following information):**
 - Device: [iPhone7]
 - OS: [iOS14]

Error Log:

dyld: Library not loaded: @rpath/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub
  Referenced from: /private/var/containers/Bundle/Application/25749B52-C070-4B87-AAC7-FC5771DC2291/MSALiOS.app/MSALiOS
  Reason: image not found
(lldb) 

<img width="1275" alt="Screenshot 2020-09-03 at 12 58 15 PM" src="https://user-images.githubusercontent.com/3336047/92085737-dd57c800-ede6-11ea-8928-af4a826dcc1f.png">

**Comment by bhandaribhumin** [comment]
working fine now but need to know how to create instance of intuneMAM

**Comment by Manikanta-GEP** [comment]
> working fine now but need to know how to create instance of intuneMAM
Hi @bhandaribhumin , Did you found out how to create instance.

**Comment by basav22** [comment]
> working fine now but need to know how to create instance of intuneMAM

How did you fix this? I am getting same error. Please share.

Thanks in advance.
