### ISSUE TITLE
Intune SDK binary references UIWebView, which Apple threatens to reject this December

### ISSUE THREAD

**Issue by BenLeggiero** [msintuneappsdk/ms-intune-app-sdk-ios#107]
**Describe the bug:**
When submitting an app which integrates the IntuneMAM SDK, Apple issues the following warning:

<img width="684" alt="Dear Developer, We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery: ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). After you’ve corrected the issues, you can upload a new binary to App Store Connect. Best regards, The App Store Team" src="https://user-images.githubusercontent.com/10189808/92499034-a0aa1900-f1b8-11ea-8bc3-010aeb539408.png">

**To Reproduce**
1. Integrate the Intune SDK into an app
2. Submit the app to App Store Connect

**Expected behavior:**
Apple does not issue warnings about the IntuneMAM SDK

**Screenshots and logs:**
- One screenshot above
- A screenshot of the IntuneMAM binary containing references to UIWebView: 
![A search of the hex data in the IntuneMAM binary, revealing UIWebView references](https://user-images.githubusercontent.com/10189808/92503023-e6b5ab80-f1bd-11ea-91e7-58a0a24fa424.png)

**Smartphone (please complete the following information):**
 - Device: Not applicable
 - OS: Not applicable

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? **12.8.0** Are you using the latest version? **Yes**
- What platform is your app based in (native, Xamarin based, Cordova, etc)? **Native: UIKit**
- For errors during build, does the app build without Intune SDK integration? Not applicable
- For errors post build, does the app launch without being Intune SDK integrated? **Yes**

- Who is the customer? Not sure what you mean by this
- Do you see a trend with it only being reproduced on a specific device? Not applicable

**Additional context:**
None yet

**Comment by Kyle-Reis** [comment]
Hi @BenLeggiero, we actually don't directly instantiate any UIWebView, but we do have code which handles the scenario where an app  might be doing so. We'll need to keep support for that scenario since not all of our customers are submitting their apps to the app store, and therefore UIWebView usage may extend beyond December, but nonetheless I think we can remove these references in our binary to prevent future rejection from the app store.

**Comment by Kyle-Reis** [comment]
Hey @BenLeggiero, this should be fixed in our [latest release](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/latest)(version 12.9.0)

**Comment by BenLeggiero** [comment]
Confirmed! Thanks for doing this 🙂
