### ISSUE TITLE
How do you ensure mdmEnrolledAccount() gets populated?

### ISSUE THREAD

**Issue by hank345** [msintuneappsdk/ms-intune-app-sdk-ios#109]
Hi,

I'm trying to get the `IntuneMAMEnrollmentManager.instance().mdmEnrolledAccount()` to return my MDM enrolled user, but I'm always getting nil returned.

The SDK docs says this:
```
/**
 *  Returns the UPN of the MDM enrolled user. Returns nil if the device is not MDM enrolled.
 *  For 3rd party applications, the application must also be managed and have IntuneMAMUPN
 *  set to the MDM enrolled user in managed app config.
 *
 *  @return UPN of the MDM enrolled account
 */
- (NSString *_Nullable)mdmEnrolledAccount;
```

And I think I fulfill those requirements:
- The device is MDM enrolled.
- The app is an in-house (LOB) app (we uploaded the IPA via Endpoint manager admin)
- The app is pushed out via Intune to the device.
- The app has an App protection policy assigned.
- The app has an App configuration policy assigned (with IntuneMAMUPN set to {{UserPrincipalName}}.

This page https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies implies that **IntuneMAMDeviceID** needs to be set to {{deviceID}}, but when I try that the Admin UI says "Invalid token"...

<img width="790" alt="Screenshot 2020-09-11 at 16 45 15" src="https://user-images.githubusercontent.com/4705451/92939547-36120b00-f44e-11ea-8dfd-c68e2774c3b4.png">

What am I missing?

Regards,

Henrik

**Comment by Kyle-Reis** [comment]
Also important to note: To receive MDM app config, the app must be pushed down/installed via Company Portal.

**Comment by hank345** [comment]
Thank you for your quick response @Kyle-Reis. 
That was it, you made my day a lot easier! Have a nice weekend! :)

**Comment by mkoorn** [comment]
> Also important to note: To receive MDM app config, the app must be pushed down/installed via Company Portal.

It would have been nice if this was part of the documentation. That would have saved me 3 days on getting the appconfig to work.

but thank you for posting it here, otherwise I still would be pulling my hairs out. 😁
