### ISSUE TITLE
Customize login screen

### ISSUE THREAD

**Issue by alexwalpole** [msintuneappsdk/ms-intune-app-sdk-ios#111]
Is it possible to customize the login in screen presented by `.loginAndEnrollAccount(nil)`? E.g. prevent the user from pressing the cancel button? I noticed with the MS Outlook app, the top is customized but its not clear how this was done. 
![Screen Shot 2020-09-14 at 11 21 39 AM](https://user-images.githubusercontent.com/30059432/93104945-76ef6700-f67c-11ea-9321-8e7a2a5796d6.png)

**Comment by Kyle-Reis** [comment]
Hey @alexwalpole, Outlook and other apps which customize the auth screen like this initiate their own AAD auth, then call the registerAndEnrollAccount Intune method to silently enroll. Currently, there is no way to configure this for apps calling loginAndEnrollAccount. Is your app just calling loginAndEnrollAccount immediately on launch? If so, one thing you could potentitally do is instead enable the AutoEnrollOnLaunch and MAMPolicyRequired settings mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk). Note: enabling these settings would mean that users who do not have MAM policy targeted to them by the IT admin would not be allowed to access the app. Would that meet your needs?

**Comment by alexwalpole** [comment]
Thanks for the response @Kyle-Reis. Unfortunately not. Some of our clients will not be using Intune but for those who do, we don't want their users to be able to avoid enrollment. The workflow we're likely going to ship is to call `loginAndEnrollAccount` only for clients requesting Intune for their users and call `loginAndEnrollAccount` again if their users press cancel, so they have to enroll with Intune.

**Comment by Kyle-Reis** [comment]
Not sure what the flow is like, but if users are given a choice to sign into different account types, it may make sense to allow them to cancel and go back to the initial choice on whether to sign in with AAD/Intune or other account type in case they may have accidentally selected the wrong option.
