### ISSUE TITLE
Unable to close or read Forget Popup as keyboard covers the screen on iPad

### ISSUE THREAD

**Issue by hirenhcm** [msintuneappsdk/ms-intune-app-sdk-ios#112]
Unable to close or read Forget Popup as keyboard covers the screen on iPad

**Describe the bug:**
When tapping on the link of forget PIN on iPad it opens up a popup saying that it has to re-enter the credentials. This also opens up the keyboard when covers the OK button and the message that is displayed on this popup. User is not not able to close the keyboard or tap on the popup OK button or read the message that it is trying to say. The only option is to kill the app and restart the App. iPad app is running in landscape mode.

**To Reproduce**
1. Let the login screen come where you are request to enter PIN. Make sure you app is in fixed on landscape mode.
2. Click on Forgot Pin. Instead of entering your PIN.
3. This is open the pop-up and also open the keyboard.
4. Using the keyboard dismiss button does not dismiss the keyboard. As the keyboard is over this pop-up there is no way to read the message to dismiss the popup.

**Expected behavior:**
Should be able to read the message and dismiss the pop-up. Keyboard should not open when tapping forgot PIN.

**Screenshots and logs:**
Attached
![IMG_0001](https://user-images.githubusercontent.com/2310937/93311763-750ddb00-f817-11ea-81b8-f689b7602d73.PNG)

**Smartphone (please complete the following information):**
 - Device: iPad 6th Gen
 - OS: 13.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? v12.0.8
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Cordova
- For errors during build, does the app build without Intune SDK integration? NA
- For errors post build, does the app launch without being Intune SDK integrated? NA

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device? Able to reproduce on all iPads

**Comment by Kyle-Reis** [comment]
Hi @hirenhcm, does this issue reproduce with the current release (12.9.0 for apps built with Xcode 11 and 13.0.0 for apps built with Xcode 12)?

**Comment by Kyle-Reis** [comment]
An investigation of this issue found that it is an issue in iOS 13, which is now fixed in iOS 14.
