### ISSUE TITLE
unable answer voip push call when app is killed, iPhone is locked and MAM policy need input PIN

### ISSUE THREAD

**Issue by renjwjx** [msintuneappsdk/ms-intune-app-sdk-ios#113]
**Describe the bug:**
App can not answer call when app support voip push call in following scenario.

**To Reproduce**

1. Kill App For Intune, Lock iPhone.
2. Wait for the Intune activities timer expired(need input PIN, when App is launched) (the default expired value is 30 mins on Intune server)
3. App  receive push call
When user answer the call, the call will failed to connect.

with the same reproduce step, if MAM does not need input PIN, it works fine when answer voip call.

**Expected behavior:**
user can answer voip call.

**Screenshots and logs:**
**After we have a investigate for this case, the flow is as following.**
 
When Receive push call, App is launched by iOS system.
App then let iOS system show Callkit view in iOS lock screen in the callback of push call(didReceiveIncomingPushWithPayload).
But as the activities timer is expired, intune SDK will show input PIN view and block App's didFinishLaunchingWithOptions().
Then user answer the call, the call will be failed as App has no chance to do initial(didFinishLaunchingWithOptions).

**For this push call case, does intune has solution for it?**

**Smartphone (please complete the following information):**

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
12.0.12
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Xcode native iOS app (Cisco Jabber)
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?
HSBC, Bank of American, ...

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hi @renjwjx, does this issue reproduce with the latest version of the SDK (12.9.0 if building with Xcode 11 and 13.0.0 if building with Xcode 12)?

**Comment by Kyle-Reis** [comment]
Hey @renjwjx, checking in again if you see this issue with current version of the SDK?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you're still experiencing this issue.
