### ISSUE TITLE
App fails to complete app enrolment with new SDKs (12.9.0 & 13.0).

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#116]
**Describe the bug:**
When App initiates the enrolment, it fails and shows an error message every time on SafariViewController (from Intune/ADAL).

If we use the 12.6.1 version, enrolment works just fine.

**To Reproduce**
Try app enrolment with the latest Intune SDK

**Expected behavior:**
App should be able enroll the user.

**Screenshots and logs:**
![Simulator Screen Shot - iPhone 11 - 2020-10-19 at 23 54 29](https://user-images.githubusercontent.com/2161122/96582734-59f02880-12f9-11eb-88d4-bce8e9bdb15c.png)

**Smartphone (please complete the following information):**
 - Device: all
 - OS: iOS 13.4

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? (tried 12.9.0 & 13.0)
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Xcode
- For errors during build, does the app build without Intune SDK integration? No
- For errors post build, does the app launch without being Intune SDK integrated? No

- Who is the customer?
Infor

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hi @Nookaraju, I've seen this error before, and it was coming from the MSAL SDK, and not Intune. Did you also move from ADAL to MSAL in addition to upgrading the Intune SDK?

**Comment by Nookaraju** [comment]
No, I still use ADAL. Should I use MSAL for the latest Intune SDK?

**Comment by Kyle-Reis** [comment]
Hi @Nookaraju, ADAL is still supported with the current version of Intune. Sorry, my memory was actually serving me poorly above. When I saw this error in the past, it was actually coming from ADAL, not MSAL. The error is actually defined in the ADAL code on line 34 of this file: https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/ADAL/src/ADAuthenticationContext%2BInternal.m

Did you recently update ADAL?

**Comment by Nookaraju** [comment]
Yes. to 4.0.10

the same version works fine with 12.6.1 but not 12.9.0 & 13.0

**Comment by niteeshkr20** [comment]
For this error you need to add **ADALRedirectScheme** in your info.plist instead of ADALRedirectUri and that should be in the proper format that is mentioned in the screenshot.

**Comment by Kyle-Reis** [comment]
@Nookaraju, you could also continue to use ADALRedirectUri, but you would need to specify the full redirect URI rather than just the scheme. You will also need to make sure the app registration which maps to your client ID includes the redirect URI in the above format

**Comment by Kyle-Reis** [comment]
@Nookaraju, checking in to verify that updating the redirect URI used for enrollment fixed the issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing this issue.

**Comment by Nookaraju** [comment]
Actually, We are using "aadRedirectUriOverride" in the code. Issue is not fixed.

            IntuneMAMSettings.aadRedirectUriOverride = redirectUri
