### ISSUE TITLE
Logging the user out (broker only used on first setup after factory reset)

### ISSUE THREAD

**Issue by andrejacobs-unily** [msintuneappsdk/ms-intune-app-sdk-ios#119]
**Describe the bug:**
We (still) use ADAL at the moment along with Intune MAM and have noticed an issue where the broker app is only ever called the first time the credentials have not been found in the keychain.
After a lot of testing (iOS 13 & 14) using Intune MAM 12.6.1 and 12.9.0 we discovered that the call to deRegisterAndUnenrollAccount adds the cleared cached tokens back.

Unfortunately all the nice documentation for ADAL was removed a while back in order to force people to upgrade to MSAL and how to exactly implement "logging out" behaviour is not documented anywhere (when using both ADAL and Intune MAM).

**To Reproduce**
1. Ensure the broker app is installed and that your user can login using ADAL and enroll into Intune MAM
2. The next steps describe "log out" code implementation
3. ADKeychainTokenCache.defaultKeychain().removeAll(forClientId: clientId, error: nil)
4. Check cache has been cleared: (lldb) po ADKeychainTokenCache.defaultKeychain().allItems(nil)
5. IntuneMAMEnrollmentManager.instance().deRegisterAndUnenrollAccount(account, withWipe: true)
6. Check cache has been cleared: (lldb) po ADKeychainTokenCache.defaultKeychain().allItems(nil)

**Expected behavior:**
Please provide documentation on what is the best way to log a user out and force him to use the broker app next login.
However I would state given the steps above that the cache would not be having new items added.
**The fix for now in our code base** is to just do another call to "ADKeychainTokenCache.defaultKeychain().removeAll(forClientId: clientId, error: nil)" after deRegisterAndUnenrollAccount.
This now works on iOS 13 & 14 with older 12.6.1 and newer 12.9.0 Intune MAM.

---

**Screenshots and logs:**
The following is details on the behaviour that causes cached tokens to be added back in the keychain. See above on our current fix for this issue.

Intune MAM 12.6.1 and 12.9.0
ADAL 4.0.4 (Tried with ADAL 4.0.10 as well)

On pressing Log out, just before clearing the cache

(lldb) po ADKeychainTokenCache.defaultKeychain().allItems(nil)

▿ Optional<Array<ADTokenCacheItem>>
  ▿ some : 3 elements
    - 0 : (authority=https://login.windows.net/redacted.com clientId=redacted accessToken=(nil) accessTokenType=(null) refreshToken=3765786 resource=(null))
    - 1 : (authority=https://login.windows.net/redacted.com clientId=redacted accessToken=140a538 accessTokenType=Bearer refreshToken=(nil) resource=https://msmamservice.api.application)
    - 2 : (authority=https://login.windows.net/redacted.com clientId=redacted accessToken=4c1c56e accessTokenType=Bearer refreshToken=(nil) resource=https://redacted.com/)

Then a call is made to clear ADAL tokens:
_ = ADKeychainTokenCache.defaultKeychain().removeAll(forClientId: clientId, error: nil)

(lldb) po ADKeychainTokenCache.defaultKeychain().allItems(nil)
▿ Optional<Array<ADTokenCacheItem>>
  - some : 0 elements
  
Then IntuneMAM is being cleared using this function

    func intuneMAMHandleLogout() {
        let enrollmentManager = IntuneMAMEnrollmentManager.instance()
        if let account = enrollmentManager.enrolledAccount() {
            enrollmentManager.deRegisterAndUnenrollAccount(account, withWipe: true)
        }
    }

After that function, checking the status of the cache results in items being added back (after the call to Intune MAM to deregister)

(lldb) po ADKeychainTokenCache.defaultKeychain().allItems(nil)
▿ Optional<Array<ADTokenCacheItem>>
  ▿ some : 2 elements
    - 0 : (authority=https://login.windows.net/redacted.com clientId=redacted accessToken=(nil) accessTokenType=(null) refreshToken=50bed34 resource=(null))
    - 1 : (authority=https://login.windows.net/redacted.com clientId=redacted accessToken=6f3bb0f accessTokenType=Bearer refreshToken=(nil) resource=https://msmamservice.api.application)

**This results in the next time we run the app that the broker is not used and a cached token is used (thus the user never logged out)**

---

**Smartphone (please complete the following information):**
 - Device: iPhone 11, iPhone 8
 - OS: iOS 14.0.1, iOS 13.3

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes 12.9.0 (tested on 12.6.1 as well)
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native [Swift 5]
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes

- Who is the customer? Both us and many other clients
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**
N/A

**Comment by Kyle-Reis** [comment]
Hi @andrejacobs-unily, the recommended sign out flow is to first call deregisterAndUnenrollAccoubt before clearing the ADAL token cache, as mentioned here: https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#deregister-user-accounts

It's interesting that you are seeing the tokens reappear in the cache, as I would expect that the unenrollment attempt would fail since the tokens are no longer there, but perhaps something in ADAL has since changed and the tokens remain available in memory and are added back to the cache when used.

**Comment by andrejacobs-unily** [comment]
Thank you very much @Kyle-Reis . I am going to swap our code around so that we first deregister the user from Intune MAM and then clear out all other login related data.

Did you want to close this?

**Comment by Kyle-Reis** [comment]
No problem! Closing out this issue now. Do let us know if you have any more issues.
