### ISSUE TITLE
ms-intune-app-sdk-ios-9.0.3 archives corrupt

### ISSUE THREAD

**Issue by rsneekes** [msintuneappsdk/ms-intune-app-sdk-ios#12]
Hi,

It seems that both ms-intune-app-sdk-ios-9.0.3 archives are are corrupt or something. They extract fine, but some header files are empty, others headers are bplists, libIntuneMAM.a is actually a header file etc. The download file is also around 700KB instead of around 20MB for version 8.1.1

Raymond

**Comment by msintuneappsdk** [comment]
Thanks for pointing this out. We have reverted the commit that is presenting an issue.

**Comment by Kyle-Reis** [comment]
Hey @rsneekes, this issue should be addressed now. Thanks for letting us know!

**Comment by rsneekes** [comment]
Seems to download fine now.

**Comment by JBenny25** [comment]
@msintuneappsdk the archive downloaded properly. However, the framework file is missing the headers as well as the module map. How then, should the SDK be integrated with the app?

**Comment by Kyle-Reis** [comment]
Hey @JBenny25, thanks for letting us know about this. I verified that our internal build had both the headers and module map, but something seems to have happened either during our release signing process or the commit to GitHub. We're getting ready to put out a new release and we'll be sure it addresses this issue.

**Comment by Kyle-Reis** [comment]
@JBenny25, your issue should be fixed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest)
