### ISSUE TITLE
Login Issue when I use ADAL login with intune

### ISSUE THREAD

**Issue by niteeshkr20** [msintuneappsdk/ms-intune-app-sdk-ios#120]
After integrating Intune sdk to my iOS app which is already using ADAL login. I am facing below issue during login  -

![Simulator Screen Shot - iPhone 11 Pro - 2020-10-23 at 10 15 39](https://user-images.githubusercontent.com/24302315/99685508-ac636700-2aa8-11eb-8bf8-a33b50093aa5.png)

 
Below is info.plist changes- 

`<key>IntuneMAMSettings</key>
    <dict>
        <key>ADALAuthority</key>
        <string>https://login.microsoftonline.com/comapnyname.com/</string>
        <key>ADALClientId</key>
        <string><!client ID--!></string>
        <key>ADALRedirectScheme</key>
        <string><!---Redirect URI Value---!></string>
        <key>AutoEnrollOnLaunch</key>
        <true/>
        <key>MAMPolicyRequired</key>
        <true/>
        <key>aadAuthorityUriOverride</key>
        <true/>
        <key>aadClientIdOverride</key>
        <true/>
        <key>aadRedirectUriOverride</key>
        <true/>
    </dict>
`
Not providing exact values due to security reasons.

I am unable to resolve the issue.
Could someone please help me with the issue?

**Comment by Kyle-Reis** [comment]
Hey @niteeshkr20, it looks like you may need to follow these instructions to grant your application access to the Intune MAM service: https://docs.microsoft.com/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional

**Comment by Kyle-Reis** [comment]
Hi @niteeshkr20, did the above resolve this issue for you?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing issues.
