### ISSUE TITLE
Evaluation finished synchronously for Diagnostic with non-compliant.

### ISSUE THREAD

**Issue by dragantr** [msintuneappsdk/ms-intune-app-sdk-ios#121]
**Describe the bug:**
Enrolling the app in MAM is failing and config policy is not applied. The device is enrolled with the Intune Portal app. 

**Expected behavior:**
Users should be able to enroll in the IntuneMAM and policy to be applied.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem:
_Evaluation finished synchronously for Diagnostic with non-compliant._

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.5.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - Intune v.12.2.0 
- What platform is your app based in (native, Xamarin based, Cordova, etc)?- Native - iOS

**Comment by Kyle-Reis** [comment]
Hey @dragantr, the log statement in the title does not indicate that MAM enrollment failed. Does your app implement the [IntuneMAMEnrollmentDelegate protocol](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/blob/master/Headers/IntuneMAMEnrollmentDelegate.h)? If so, what is the result from enrollmentRequestWithStatus?

**Comment by dragantr** [comment]
@Kyle-Reis I will close this. Thanks for your time.
