### ISSUE TITLE
First register timeout

### ISSUE THREAD

**Issue by NicolasLourenco** [msintuneappsdk/ms-intune-app-sdk-ios#122]
**Describe the bug:**
Hello,
Each time I connect my user for the first time, the enrollment fail.
The status code is 216:
`IntuneMAMEnrollmentStatusTimeout = 216,                         // The operation has timed out`

**To Reproduce**
1. Connect with MSAL
2. registerAndEnrollAccount
3. Failure
4. Connect with MSAL
5. registerAndEnrollAccount
6. it succeed

**Expected behavior:**
It should work at the first time.

**Smartphone (please complete the following information):**
 - Device: All devices
 - OS: 13, 14

**Intune App SDK for iOS (please complete the following information):**
- I'm using the latest version of MAM SDK and MSAL
- iOS (14)

**Additional context:**
The `aadAuthorityUriOverride` is overrided with the result of MSALResult.

**Comment by Kyle-Reis** [comment]
Hi @NicolasLourenco, I'm not sure why the enrollment would timeout only on the first time. Does this happen consistently? Is there any difference in the two MSAL acquireToken calls before each enrollment attempt?

**Comment by NicolasLourenco** [comment]
Hello. 
There’s absolutely nothing different in aquireToken calls. It’s consistently despite  the device or MS account.

**Comment by NicolasLourenco** [comment]
Also, in my case setting `VerboseLoggingEnabled` in MAMSettings do nothing 🤷

**Comment by Kyle-Reis** [comment]
@NicolasLourenco, were you doing any kind of debugging during the enrollment which might have paused execution (e.g. having some breakpoint set and stepping through some code)? Or does this reproduce without having any debugger attached?

**Comment by NicolasLourenco** [comment]
Hi @Kyle-Reis .
No, There's no breakpoints or something else who can pause the execution. Moreover, this behavior also appear with an Adhoc/Appstore build.

**Comment by Kyle-Reis** [comment]
@NicolasLourenco, if you don't explicitly override the authority, does the issue reproduce? Note: values set on the dynamic override AAD properties are persisted across application launches, or until the app explicitly clears them or unenrolls.

**Comment by Kyle-Reis** [comment]
Intune should be able to get the correct authority from the MSAL cache in this scenario. The authority override property is really for apps that call loginAndEnrollAccount and don't want the generic auth experience of the common authority. Also, are you overriding the client ID and redirect URI to match the values used by your app?

**Comment by NicolasLourenco** [comment]
No,
The authority ID is overridden since we have this information in the `MSALResult`.
With the common authority, the behavior is the same. We've got a timeout, then it works.

We don't override the client ID and redirect ID.
Our app is one app used by different companies. Like Word for iOS or something like that.

My latest tests are betters, but still unstable. (with and without common authority)
I've less timeouts but the enrollment still take 35/40seconds.

**Comment by Kyle-Reis** [comment]
Hi @NicolasLourenco, your app must be specifying a client ID and redirect URI when performing its own MSAL auth prior to calling registerAndEnrollAccount. The Intune enrollment attempt should use the same values.

**Comment by Kyle-Reis** [comment]
Hey @NicolasLourenco, checking in to see if you're still having trouble here?

**Comment by NicolasLourenco** [comment]
Hello, yes. We're still facing the issue.

We've found a workaround. If we ignore the timeout, the enrollment finally succeeds, but it's very long!
