### ISSUE TITLE
IntuneMAMEnrollmentStatusTimeout after upgrading from Intune SDK 12.2.0 to 14.0.0

### ISSUE THREAD

**Issue by dragantr** [msintuneappsdk/ms-intune-app-sdk-ios#123]
**Describe the bug:**
I update the app with the latest Intune SDK 14.0.0 from 12.2.0. Now the app is getting IntuneMAMEnrollmentStatusTimeout = 216 when app calls `IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)`. 
With 12.2.0 it works fine, but not with the latest SDK. 

**To Reproduce**
1. Run `IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)`
2. App will receive `IntuneMAMEnrollmentStatusTimeout` in the `IntuneMAMEnrollmentDelegate->enrollmentRequest`

**Expected behavior:**
Enrollment should succeed with Intune SDK 14.0.0

**Screenshots and logs:**
status.errorString = The operation failed because it did not complete in the expected timeout interval.
status.statusCode = 216

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 14.2

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - 14.0.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? - iOS, native

**Additional context:**
Is there any change in the implementation of Intune SDK 12.2.0 and 14.0.0?

**Comment by Kyle-Reis** [comment]
Hio @dragantr, which version of ADAL/MSAL is your app using?

**Comment by dragantr** [comment]
@Kyle-Reis MSAL v1.1.1

**Comment by dragantr** [comment]
@Kyle-Reis any news regarding this issue ?

**Comment by Kyle-Reis** [comment]
Hey @dragantr, are you setting custom ADALClientID and ADALRedirectURI settings for your app as mentioned here: https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-msal-settings-for-the-intune-app-sdk

**Comment by dragantr** [comment]
@Kyle-Reis Yes, they are properly set up and work with Intune 12.2.0
