### ISSUE TITLE
Policy prohibits using MFMailComposeViewController.

### ISSUE THREAD

**Issue by rooneytx** [msintuneappsdk/ms-intune-app-sdk-ios#126]
We are deploying a MAM wrapped iOS app with the ability to open the iOS native email app and pre-populate the email body with a url link.  When we press the action to trigger this we get the dialog "Alert - Your organization only allows you to transfer its data to other managed apps."

But when we pull the logs we see the message:

 IntuneMAM: Policy prohibits using MFMailComposeViewController. Returning nil from init.
2020-12-07T19:16:31.406Z	INFO		xxxxxxxx	0			 IntuneMAM: MAMAlert reason: 1, context:Document
2020-12-07T19:16:31.406Z	INFO		xxxxxxxx	0			 IntuneMAM: MAM_CHECKPOINT: Alert - Your organization only allows you to transfer its data to other managed apps.

We have the MAM policy set:
Send org data to other apps -> Policy managed apps
Select apps to exempt -> NativeEmail: mailto

**Expected behavior:**
With the exempt URL schema in place we expect to be able to launch the native email client message and see the context pre-populated. 

SDK version: 12.0.12
IOS iphone7, 18, 12 on 14.x

Build against cordova

**Comment by Kyle-Reis** [comment]
Hi @rooneytx, the exemption list is a set of URL schemes that the Intune SDK will allow to be opened without restrictions. Since in this scenario, the app is not opening a "mailto" URL, the exemption list does not apply here.

**Comment by Kyle-Reis** [comment]
@rooneytx - does your application's config.xml have access entries specified for "sms:" and "mailto:" with the launch-external attribute configured to "yes", as mentioned here? If not, could you give this a try?

**Comment by Kyle-Reis** [comment]
Hi @rooneytx, I apologize for accidentally replying to the closed issue previously. I saw that you already have the above config enabled. Some replies to [this SO thread](https://stackoverflow.com/questions/30355577/mailto-links-not-opening-mail-app-on-android-in-cordova-app) suggest that using window.location.href = [mailto URL] worked on iOS, although it's not clear if "worked" means the mailto URL was actually opened externally into the Mail app, or if the in-app view controller was shown. Could you give this a try?

**Comment by rooneytx** [comment]
Hi Kyle,

The Dev team had already tried this, it opens a web browser, not what we wanted.

Rooney

??

________________________________

**Comment by Kyle-Reis** [comment]
Hi @rooneytx - We've just closed the discussion on this scenario with the PM team and the decision is to go ahead and make a change in to the Intune SDK to allow the use of the MFMailCompose or MFMessageCompose view controllers if "mailto" or "sms" is defined in the sharing exemption list, respectively. This change should go out in our next release. I will update this thread once it's available.

**Comment by Kyle-Reis** [comment]
Hi @rooneytx the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (14.5.0) of the Intune SDK should allow apps to use the MFMailCompose and MFMessageCompose view controllers when the corresponding "mailto" or "sms" scheme has been included in the data transfer exemption list. Please reach out again if you run into any more issues!
