### ISSUE TITLE
IntuneMAMRegisterAndEnrollAccount error

### ISSUE THREAD

**Issue by kangsungoh** [msintuneappsdk/ms-intune-app-sdk-ios#128]
**Describe the bug:**
Error after calling IntuneMAMRegisterAndEnrollAccount

**Screenshots and logs:**
Error content: Each error occurs in two users.
error code-203
error message-The operation failed because the SDK could not access the user’s AAD token. The application should prompt the user for credentials to refresh the user’s AAD token.

error code-225
error message-The account is licensed for Intune but is not targeted with MAM policy.

**Smartphone (please complete the following information):**
 - Device: iPhone 7, iPhone X
 - OS: iOS 13.4.1, iOS 14.0.1

**Intune App SDK for iOS (please complete the following information):**
 - Latest version of IntuneSDK
 - What platform is your app based in (native, Xamarin based, Cordova, etc)? Native

**Comment by Kyle-Reis** [comment]
Hi @kangsungoh. The first error indicates that ADAL or MSAL was not able to use the cached AAD tokens on the device to silently enroll in Intune. Does your application authenticate with AAD before calling registerAndEnrollAccount?

The 2nd error indicates that the tenant administrator has not targeted any policies to this app for this user. This may be a valid scenario where user can still be allowed access to corporate data. Is this a general-purpose app that you ship to multiple customers who may or may not be using Intune? Or is it a custom line-of-business app used by a specific organization? If the latter, does the organization require that all users have Intune app protection policy applied?

**Comment by Kyle-Reis** [comment]
Hi @kangsungoh, checking in to see if you're still having trouble here.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you're still experiencing a problem.
