### ISSUE TITLE
IntuneMAMComplianceManager.h missing

### ISSUE THREAD

**Issue by softwarebouwer** [msintuneappsdk/ms-intune-app-sdk-ios#13]
IntuneMAM.h references IntuneMAMComplianceManager.h but that file does not exist.

**Comment by Kyle-Reis** [comment]
Thanks for pointing this out. We'll get the new header added along with the fix for issue #14

**Comment by Kyle-Reis** [comment]
@softwarebouwer, the header is available in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest).

**Comment by softwarebouwer** [comment]
@Kyle-Reis Thanks, compiles/links fine again.
