### ISSUE TITLE
Building for iOS, but the linked and embedded framework '{framework_name}.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by lorenraz** [msintuneappsdk/ms-intune-app-sdk-ios#131]
on Xcode 12.3 - I'm getting this compilation error when trying to integrate the frameworks (IntuneMAMSwift.framework and IntuneMAMSwiftStub.framework) according to option 1 in this guide: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app

this compilation error occurs also when I clone and try to run this project: https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App

I'm using the latest version of Intune SDK, for a native iOS app

![Screen Shot 2021-01-06 at 16 17 00](https://user-images.githubusercontent.com/20846424/103778307-baf6e500-503a-11eb-99e3-d39112c45d21.png)

**Comment by Kyle-Reis** [comment]
Hi @lorenraz, this is the same as issue #130. It should be addressed in next SDK update, but the workaround mentioned there should mitigate this for now.

**Comment by lorenraz** [comment]
@Kyle-Reis Thanks for the quick response

**Comment by Kyle-Reis** [comment]
@lorenraz - This issue should be addressed in our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 14.1.0)
