### ISSUE TITLE
Crash - Terminating app due to uncaught exception 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by laveur** [msintuneappsdk/ms-intune-app-sdk-ios#132]
**Describe the bug:**
Intune Integration using Default Enrollment crashes with the following exception:
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'All launch handlers must be registered before application finishes launching'
```

**To Reproduce**
1. Configure your application for default enrollment.
2. Authtenticate to download your App Protection Policy
3. (OPTIONAL) Set a pin if your app protection policy requires it.
3. See error.

**Expected behavior:**
It not to crash and finish launching the application.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: iPhone 11 X
 - OS: iOS13.6.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
I've used both 13.0.0 and 14.0.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native
- For errors during build, does the app build without Intune SDK integration?
N/A
- For errors post build, does the app launch without being Intune SDK integrated?
App Launches fine with and without the Intune SDK integrated.

**Additional context:**
Need to get this fixed before you upgrade your certificates.

**Comment by Kyle-Reis** [comment]
Hey @laveur, is your app calling [this method ](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler/3180427-register)in either Swift or Objective-C? If so, what where is it calling it from? didFinishLaunching?

**Comment by laveur** [comment]
@Kyle-Reis Yes we are calling it from didFinishLaunching. I would also point out that the version of our applications where the Intune SDK is not integrated works fine. And also add that our code does not directly call an of the Intune SDK's API.

**Comment by Kyle-Reis** [comment]
@laveur, can this call be moved to willFinishLaunching? The SDK delays the call of the app's didFinishLaunching delegate method to ensure conditional launch checks like the PIN prompt can be executed first.

**Comment by laveur** [comment]
@Kyle-Reis Thanks! I moved it another spot in our code and that fixed things right up.
