### ISSUE TITLE
Video continues to play even though the WKWebView’s view controller is dismissed already.

### ISSUE THREAD

**Issue by wenywang** [msintuneappsdk/ms-intune-app-sdk-ios#134]
**Describe the bug:**
Video continues to play even though the WKWebView’s view controller is dismissed already.

**To Reproduce**

1. We have imported Intune SDK’s frameworks(i.e. IntuneMAMSwift.framework and IntuneMAMSwiftStub.framework), and enabled Keychain Sharing in the target’s capabilities.
2. We created a view controller with a WKWebView, and load a m3u8 video request, the video starts to play.
3. We dismissed the view controller with the method dismiss(animated:completion:), the video continues to play as we can hear the sound.

**Expected behavior:**
If we remove IntuneMAMSwift.framework and IntuneMAMSwiftStub.framework from the project, then when we dismissed the view controller with the method dismiss(animated:completion:), the video stops to play. If we remove Keychain Sharing from the target’s capabilities, the result it the same. 
So we may conclude that the video playing behavior of WKWebView might have changed after integrating Intune iOS SDK.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: iPad 6th Gen
 - OS: iOS 13.3.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? -> Yes, we are using 14.0.0.
- What platform is your app based in (native, Xamarin based, Cordova, etc)? -> Native.
- For errors during build, does the app build without Intune SDK integration? -> No error during build.
- For errors post build, does the app launch without being Intune SDK integrated? -> The app launched with Intune SDK integrated, and can reproduce the issue.

- Who is the customer? -> MicroStrategy, Inc.
- Do you see a trend with it only being reproduced on a specific device? -> Can be reproduced on multiple devices.

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hi @wenywang - We’ve identified the root cause of this issue and now have a fix in review.

**Comment by Kyle-Reis** [comment]
Hi @wenywang. Our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 14.3.0) should address this issue. Thanks!
