### ISSUE TITLE
BitCode Error while building project with Bicode Enabled (Yes) using IntuneSDK

### ISSUE THREAD

**Issue by tulika17** [msintuneappsdk/ms-intune-app-sdk-ios#135]
**Describe the bug:**
Getting below while building the project for physical device. 
**IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub' does not contain bitcode.** You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/rajkhata/Desktop/android/marcel-mobile-app-ios/app/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub' for architecture arm64

**Expected behavior:**
Intune SDK should support BitCode.

**Smartphone (please complete the following information):**
 - Device: iPhone Any version
 - OS: 13.2

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 14.1.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? SwiftUI
- For errors during build, does the app build without Intune SDK integration? YES
- For errors post build, does the app launch without being Intune SDK integrated? YES

**Comment by Kyle-Reis** [comment]
Hi @tulika17, BitCode is not supported by the Intune SDK. Please see issue #9 for more info.

**Comment by tulika17** [comment]
Thanks @Kyle-Reis , But we have enabled BitCode in our project so what should we do now to integrate this Intune SDK.

**Comment by Kyle-Reis** [comment]
Hi @tulika17, if you wish to integrate the Intune SDK into your app, you'll need to disable BitCode in the Xcode project settings.
