### ISSUE TITLE
IntuneMAMRegisterAndEnrollAccount error

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#136]
**Describe the bug:**
Error after calling IntuneMAMRegisterAndEnrollAccount
New registrations are getting 204 and 205 errors.

    IntuneMAMEnrollmentStatusLocationServiceFailure = 204,          // Failed to connect to the location service to determine the user's endpoint, see error object for details
    IntuneMAMEnrollmentStatusEnrollmentEndPointNetworkFailure = 205,// Failed to connect to the enrollment endpoint, see error object for details

**Expected behavior:**

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS14.4

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
12.4.0

- Who is the customer?
Custom tenant
- Do you see a trend with it only being reproduced on a specific device?
All new registrations, previous users are able to re-register after a complete device reset.

**Comment by Kyle-Reis** [comment]
Hi @tritter, you'll need to update the Intune SDK to address this issue. Please see [this blog post ](https://techcommunity.microsoft.com/t5/intune-customer-success/intune-certificate-updates-action-may-be-required-for-continued/ba-p/1839655) as well as [release notes for version](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/12.8.0) 12.8.0 of the SDK.If you are still building with Xcode 11, then you should upgrade to [version 12.9.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/12.9.0). Otherwise, if you are building with Xcode 12, you should upgrade to the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (14.1.0).

**Comment by tritter** [comment]
@Kyle-Reis Thanks a lot, yes we did in our dev environment, but production recently started having issues. It took us just some time to figure this out because develop worked. Is there an easy way to keep informed of these changes, when there is a breaking change? Do the certificates expire every year?! If so we could schedule these in our routines. I will now try to make sure to keep the sdk to the latest version. But we're also still limited to ADAL because of the Conditional Access Policy (which still isn't working with MSAL), that's the main reason I didn't touch any updates.

**Comment by Kyle-Reis** [comment]
No problem! You can register to be notified via email when a new release of the SDK is available by selecting the "Watch" button under the "Code" tab of this repository. From there, you can review the release notes for the new release. You can also follow the [Intune Support Team](https://techcommunity.microsoft.com/t5/user/viewprofilepage/user-id/226779) on technet to be notified of breaking changes like this one. What is the issue you're having with MSAL + CA?

**Comment by tritter** [comment]
Check :) It still hangs in the authenticator App. So you'll get into an endless loop. (App -> Authenticator -> App -> Authenticator...)

**Comment by Kyle-Reis** [comment]
OK. Is that being tracked by the MSAL team?

**Comment by tritter** [comment]
No I have more issues if you want them. Multi-tenant also doesn't seem to work, logout doesn't seem to work. Our users are always restoring the complete iPad to re-login. I did all remove user accounts call possible but the session and registration stays in the keychain. Whats the best place to go? Also here on GitHub?

**Comment by Kyle-Reis** [comment]
If these issues are specific to MSAL on iOS, you should file them in the [MSAL repository](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues).

**Comment by tritter** [comment]
@Kyle-Reis Thanks I'll try harder ;)
