### ISSUE TITLE
We are able to share to my app from an unmanaged app even when Receive data from other apps is set to Policy Managed Apps

### ISSUE THREAD

**Issue by ryanbland** [msintuneappsdk/ms-intune-app-sdk-ios#139]
**Describe the bug:**
I am able to open documents from apps like dropbox or files (they are not policy managed or managed in any form) in my sdk app when the Policy for Receive data from other apps is set to Policy Managed Apps, we are also able to add documents from files app using the UIDocumentPickerViewController, which i would also expect not to work. 

**To Reproduce**
Set your Policy for Receive data from other apps to Policy Managed Apps
Share a document from a non policy managed app like dropbox or files
notice no error message is given stopping this from happening and the data is imported successfully

**Expected behavior:**
I expect the sdk to handle this and that I do not have to do any checks on ingestion of data into my app, I expect an alert stating this is not allowed on switching to the target app, or at the least for nothing to happen. 

**Smartphone (please complete the following information):**
 - Device: ipad pro 12.9
 - OS: 14.4

**Intune App SDK for iOS (please complete the following information):**
12.9 & 14.1.3

**Comment by Kyle-Reis** [comment]
Hi @ryanbland - Could you open a service request by going to "Troubleshooting + support" -> "Help and support" -> Intune. We'll likely need to take a look at Intune logs for your app to figure out what's going on. If you could collect them by calling the API mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app) and provide them to our support team that will be really helpful.

**Comment by ryanbland** [comment]
Thanks I have done so.

**Comment by Kyle-Reis** [comment]
Thanks! Closing out this issue as we will use the support ticket to track it.
