### ISSUE TITLE
Duplicate symbol MAMConditionalAccessEvent

### ISSUE THREAD

**Issue by softwarebouwer** [msintuneappsdk/ms-intune-app-sdk-ios#14]
With version 9.0.3 I get this linker error (Xcode 9.4.1), for device and simulator builds. Is there something new I maybe need to change in my project? 8.1.1 is compiling and working fine.

duplicate symbol _OBJC_CLASS_$_MAMConditionalAccessEvent in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
duplicate symbol _OBJC_IVAR_$_MAMConditionalAccessEvent._duration in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
duplicate symbol _OBJC_IVAR_$_MAMConditionalAccessEvent._funnelKey in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
duplicate symbol _OBJC_IVAR_$_MAMConditionalAccessEvent._remediation in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
duplicate symbol _OBJC_IVAR_$_MAMConditionalAccessEvent._result in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
duplicate symbol _OBJC_IVAR_$_MAMConditionalAccessEvent._silent in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
duplicate symbol _OBJC_IVAR_$_MAMConditionalAccessEvent._startTime in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
duplicate symbol _OBJC_METACLASS_$_MAMConditionalAccessEvent in:
    InTune/release/libIntuneMAM.a(ConditionalAccessEvent-D05887428D983D73.o)
ld: 8 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Kyle-Reis** [comment]
Thanks for pointing this out @softwarebouwer. You shouldn't need to make any changes because of this. It looks to be an issue in our static library. We'll get this addressed ASAP.

**Comment by Kyle-Reis** [comment]
This issue is now fixed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest).

**Comment by softwarebouwer** [comment]
@Kyle-Reis Thanks, compiles/links fine again.
