### ISSUE TITLE
Initial Login | LaunchScreen hangs

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#141]
**Describe the bug:**
Whenever the initial login happened to the authenticator app, the app hangs when the restart required message should appear. The bug is repeatable every time. After that you wait about 40 seconds, then the screen is gone and you see the default intune progress screen.

**To Reproduce**
1. Clean install
2. Call loginAndEnrollAccount:nil
3. Opens authenticator
4. Switches back to app.
5. Shows Splashscreen.
6. Waiting for ~ 30s
7. App continues "Checking organisational data for this app."
8. App needs restart.

**Expected behavior:**
After the splash the user should at least see the checking intune screen directly. It feels like the screen is not presented on the main thread? 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPad mini 6]
 - OS: [e.g. iOS14]

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- Latest 14.1.3
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- Objective-C

**Comment by tritter** [comment]
It is even crashing because of Intune... 1136 exhausted real (wall clock) time allowance of 10.00 seconds

**Comment by Kyle-Reis** [comment]
Hi @tritter, which version of ADAL or MSAL is the app linking to?

**Comment by tritter** [comment]
Hi @Kyle-Reis the latest MSAL (1.1.14).

**Comment by tritter** [comment]
@Kyle-Reis Latest ADAL (4.0.11) works perfectly! So definitely a combination of MSAL and Intune. Without Intune MSAL also seems to work, but as I need to use the CA-policy I need to use Intune first in combination with loginAndEnrollAccount.

**Comment by Kyle-Reis** [comment]
Thanks for the info @tritter. I'll take a look into this and let you know if I have any more questions.

**Comment by Kyle-Reis** [comment]
@tritter - I haven't been able to reproduce this issue. We'll likely need to take a look at Intune logs for your app to figure out what's going on. If you could collect them by calling the API mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app) and provide them to our support team that will be really helpful. A perf trace captured with Instruments would also be helpful in figuring out where all that time is being spent when the Authenticator kicks back to the app.

**Comment by tritter** [comment]
@Kyle-Reis Thanks for your quick reply. Im not able to upload the files directly but got two sessions, I rested the iPad. First install worked with install Authenticator, register device etc. Second time  (only by deleting the app) the hang is there. I will share tomorrow both logs. (Azure Team doesn't have time right now)

**Comment by tritter** [comment]
@Kyle-Reis Here is the Ticket! Initial Login | LaunchScreen hangs | Intune SDK‎ (#‎24365239‎)

**Comment by tritter** [comment]
Hi @Kyle-Reis do you have any updates on this?

**Comment by Kyle-Reis** [comment]
Hi @tritter. Sorry for the long delay in getting back here. I took some time away from the office during your last few replies and this issue fell off my radar. Were you able to get this resolved through the support case you filed?

**Comment by tritter** [comment]
@Kyle-Reis It feels like the issue isn't that common anymore with the latest release. So I will close this for now. Thanks!
