### ISSUE TITLE
MAM enrolment is not working with older SDK

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#146]
**Describe the bug:**
MAM enrolment is not working with an older Intune SDK

"IMP": It's breaking our production app, We didn't update to the newer Intune SDK as we see some issues and following up in another ticket.

Getting below error:
**"The Intune MAM SDK failed to connect to the location service to determine the user's endpoint, see error object for details"**

**Expected behavior:**
It should not give an error

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? (12.6.1) Are you using the latest version? No
- What platform is your app based in (native, Xamarin based, Cordova, etc)? iOS native

- Who is the customer? 
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by abasore** [comment]
Hello @Nookaraju, it looks like this is similar to this [closed issue](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/136). You can resolve this issue by updating the SDK to at least [12.9.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/12.9.0) for using Xcode 11. If you are using Xcode 12, then use the latest version [here](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios).

[This blog post](https://techcommunity.microsoft.com/t5/intune-customer-success/intune-certificate-updates-action-may-be-required-for-continued/ba-p/1839655) gives more insight into the reason for the issue.
