### ISSUE TITLE
Getting policy updates after enrollment

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#148]
**Describe the bug:**
`SDK Version: 14.1.3`
After successful login and enrollment using `IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)`
Policies are getting applied. However if we apply new policies from the endpoint manager then application is not getting required policy updates. Explored API's which SDK provides also but couldn't find any API to get policy updates after enrollments.
As of now, i am just doing un-enrollment and enrollment again on app restart.

**Is there any better way to get policy updates after enrollment ?**

**Comment by Kyle-Reis** [comment]
Hi @parveen-bhatia, policy updates happen automatically and the app cannot force them. Intune uses a "pull" model where the SDK periodically checks in with the Intune service to fetch the latest policies. The interval may vary based on load the Intune service was handling at the last check-in, but is typically every 30 minutes (if user already has policies applied to them).

**Comment by parveen-bhatia** [comment]
Hi, Thanks for the update.
I tried waiting for updates for more than 1hr. But couldn't see any updates even my application was active during that time.
Even couldn't see any update after restarting the application.
App is using delegates to listen for any changes.
```swift
        IntuneMAMPolicyManager.instance().delegate = self
        IntuneMAMEnrollmentManager.instance().delegate = self
```
Do we need to do something else to get the updates ? 
And is there any way so that we can configure the time to pull these updates for testing purpose ?

**Comment by parveen-bhatia** [comment]
Hi, any update on this ?

**Comment by neiljac1** [comment]
Hi @parveen-bhatia, the time is not configurable but you could force an update if you change the time on the device. Once the application is successfully enrolled, you don't need to call any other API to get policy updates. In the Intune logs you should see an entry containing "Beginning policy check-in request." each time the SDK checks in with the service.

**Comment by parveen-bhatia** [comment]
Yes, i tried force update by changing the time. Policy updates are working fine. Thanks.
Fine with closing this.

**Comment by Kyle-Reis** [comment]
Thanks @parveen-bhatia, please reach out again if you have any more questions or run into any issues.
