### ISSUE TITLE
"MSAL logging callback can only be set once per process and should never changed once set."

### ISSUE THREAD

**Issue by abuzarin93** [msintuneappsdk/ms-intune-app-sdk-ios#149]
**Describe the bug:**

please refer to my screenshot. my apps already have AD openid login. i just added registerandenrollintune func but the apps crash. 

Error in xcode: 
1) *** Terminating app due to uncaught exception of class '__NSCFConstantString'
terminating with uncaught exception of type __NSCFConstantString
CoreSimulator 732.18.0.2 - Device: iPhone 11 (7CE1832E-A797-4D17-A37A-115C37327F13) - Runtime: iOS 14.2 (18B79) - DeviceType: iPhone 11

2) "MSAL logging callback can only be set once per process and should never changed once set."

<img width="762" alt="Screenshot 2021-03-02 at 18 50 02" src="https://user-images.githubusercontent.com/10832233/109746765-e51aec80-7c10-11eb-95e9-d247c9974c3e.png">

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: [iPhone11](url)
 - OS:  iOS14.3

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by neiljac1** [comment]
Hi @abuzarin93. The Intune SDK sets the MSAL logger callback so that the MSAL log entries will be captured in the Intune log files. If your application also sets the logger callback in MSAL this error will occur. Removing the call to set the MSAL logger from your code should fix this issue.

**Comment by abuzarin93** [comment]
yeah it solve neiljac1. thanks i have commented out: 

//        MSALGlobalConfig.loggerConfig.setLogCallback { (_, message, containsPII) in
//            if let displayableMessage = message {
//                if !containsPII {
//                    #if DEBUG
//                    Logger.cLog(message: displayableMessage)
//                    #endif
//                }
//            }
//        }
