### ISSUE TITLE
Trying to change the Intune PIN fails

### ISSUE THREAD

**Issue by rvlente** [msintuneappsdk/ms-intune-app-sdk-ios#150]
Hello. I have the issue described here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/44. I have sent an email with our client ID to msintuneappsdk@microsoft.com. Could this please be approved? Thanks in advance.

@msintuneappsdk @Kyle-Reis

**Comment by neiljac1** [comment]
Hi @rvlente. Registering your apps' client ids should no longer be needed in the 14.1.3 release. What version of the SDK are you using?

**Comment by rvlente** [comment]
Hi @neiljac1. I actually have the issue on the Android version of my app, but since the other (now closed) request issue was in this repo I figured I'd create mine here as well. Also, the Android repo seems to be a lot less active than this one and there is some urgency to this request. I should have mentioned all this, sorry.

**Comment by neiljac1** [comment]
Hi @rvlente. No problem. Please send an email to msintuneappsdk@microsoft.com with your AAD client id so that access can be approved. Thank you.

**Comment by rvlente** [comment]
Hi @neiljac1, I have just sent the email. Thanks in advance.

**Comment by rvlente** [comment]
Hi @neiljac1, am I correct that the access has not yet been approved? The issue still occurs.

**Comment by Kyle-Reis** [comment]
@rvlente, checking in to see if things are working for you now?

**Comment by rvlente** [comment]
Hi @Kyle-Reis, I just checked but I still get the issue. I double-checked the client ID I sent and it is the same as in the image.

![image](https://user-images.githubusercontent.com/17492306/111807423-35fa3880-88d3-11eb-9bf2-717cfca4f554.png)

I appreciate you checking in! Let me know if I you need anything from me.

**Comment by rvlente** [comment]
Hi, I've just received word that my client ID was added and things seem to be working now. Thanks everyone!
