### ISSUE TITLE
App hangs on splash screen after setting pin and restart the application

### ISSUE THREAD

**Issue by Manikanta-GEP** [msintuneappsdk/ms-intune-app-sdk-ios#153]
@Kyle-Reis  After 'registerAndEnrollment' success, SDK prompted for a PIN and after setting the PIN close the App and Open the app, then App hangs on Splash scree.

1.Created a static library using libIntuneMAMSwift.xcframework and IntuneSwiftStub.xcframework for React native.
2.Did MSAL login and then called 'registerandenrollment', then app restarted.
3. Prompted for PIN and set pin successfully.
4. Then close the app and open again, then app hanging on Splash screen event after waiting for 10-15min no response.

Please help me with this.

**Comment by vigavadi** [comment]
@Manikanta-GEP Which version of Intune SDK are you using?

**Comment by Manikanta-GEP** [comment]
@vigavadi Currently i am using the latest version, that is released on 19th March 2021.

**Comment by abasore** [comment]
@Manikanta-GEP Are you still experiencing this problem with the latest SDK version (14.6.2)? If so, after step 3 that you outlined above, are you able to access the app after entering a pin?
