### ISSUE TITLE
When the policy is enabled, the lock screen will cause the APP to crash

### ISSUE THREAD

**Issue by 125299431** [msintuneappsdk/ms-intune-app-sdk-ios#155]
**Describe the bug:**

Integrates IntuneMAMSwift. Xcframework and IntuneMAMSwiftStub. xcframework, put the APP become active and lock screen, it will crash after 30 seconds

**To Reproduce**
1. Go to 'Start the APP'
2. Lock screen
3. Wait for 30 seconds
4. App crashed

**Expected behavior:**
APP should not crash

**Screenshots and logs:**
![image](https://user-images.githubusercontent.com/13616177/111864742-ba18f280-899d-11eb-8734-f069fea831eb.png)
![image](https://user-images.githubusercontent.com/13616177/111864778-ef254500-899d-11eb-8ce1-733eec30058a.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12 pro max]
 - OS: [e.g. iOS14.3]

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- ms-intune-app-sdk-ios-14.1.3
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- iOS
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?
- Yes. It is crashed everytime

**Additional context:**

**Comment by vigavadi** [comment]
@125299431 Can you try the latest version 14.3.0 and see if that fixes this crash?

**Comment by 125299431** [comment]
> @125299431 Can you try the latest version 14.3.0 and see if that fixes this crash?

I have upgraded the SDK to 13.3.0, but the APP still exits after the lock screen
I can't see the crash log after the upgrade.
This will happen after packaging, but connecting to the phone debugging will not happen
(我已经将SDK升级到了13.4.0，但是在锁屏之后，APP仍然会自动退出
不过在升级之后看不到崩溃日志了
打包后会出现这种情况，连接手机调试就不会出现)

**Comment by 125299431** [comment]
@Kyle-Reis  Can you help me with this problem

**Comment by Kyle-Reis** [comment]
Hi @125299431. Could you try setting the MaxFileProtectionLevel setting mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk) to NSFileProtectionCompleteUntilFirstUserAuthentication in the IntuneMAMSettings dictionary within the app's Info.plist?

**Comment by 125299431** [comment]
> Hi @125299431. Could you try setting the MaxFileProtectionLevel setting mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk) to NSFileProtectionCompleteUntilFirstUserAuthentication in the IntuneMAMSettings dictionary within the app's Info.plist?

Thank you very much for your reply.
I have solved the problem according to your guidance.

**Comment by Kyle-Reis** [comment]
Glad to hear it. Please reach out again if you have any other questions or issues.
