### ISSUE TITLE
How to Download to OneDrive 

### ISSUE THREAD

**Issue by abuzarin93** [msintuneappsdk/ms-intune-app-sdk-ios#156]
Hi i have integrated intune sdk 14.1.3 in my project.
currently my apps save file to local storage and we want to block that. 

we are using this:
if (nil == policy || (policy?.isSaveToAllowed(for: IntuneMAMSaveLocation.localdrive, withAccountName: AuthToken.sharedInstance.userUpn ?? ""))!

so we are able block the download functionality. but how to automatically download to onedrive (managed apps). do i need to use onedrive sdk cocoapods? or do we have the functionality in this intune sdk to auto download to onedrive? thanks.

**Comment by abuzarin93** [comment]
my current downloading feature is using alamofire sdk.

**Comment by Kyle-Reis** [comment]
Hi @abuzarin93 - functionality for saving content to OneDrive is not built into the Intune SDK. The OneDrive SDK should help with that.

**Comment by abuzarin93** [comment]
well noted Kyle, thankss
