### ISSUE TITLE
Include package manager support

### ISSUE THREAD

**Issue by omiz** [msintuneappsdk/ms-intune-app-sdk-ios#159]
Is it possible to add support for Swift Packager Manager as it is possible to work with xcframework in swift 5.3?

I understand that some additional work like the update on the info.plist might still need to be done but that also can be automated.

**Comment by abasore** [comment]
Hi @omiz, thank you for the comment. I agree that Swift Packager Manager would be useful here. At least for the near future, we do not have plans to supporting this. I am closing this issue for now.

**Comment by omiz** [comment]
is there any other package manager that is used or that you have plans to support?

Your response was quick so thank you for that.

**Comment by abasore** [comment]
For now, no there is no other package manager support.
