### ISSUE TITLE
Issue with encryption policy

### ISSUE THREAD

**Issue by mfpkb** [msintuneappsdk/ms-intune-app-sdk-ios#160]
**Describe the bug:**
I have created app protection policy and enabled "Encrypt org data" : "Require".
But after successful enrollment, following API is still returning **false**.

```swift
IntuneMAMPolicyManager.instance().policy()?.isFileEncryptionRequired
// or
IntuneMAMPolicyManager.instance().policy(forIdeintity: {upn})?.isFileEncryptionRequired
```

**Smartphone:**
 - iPhone 8 plus
 - iOS 14.2

**Intune App SDK for iOS:**
- SDK version is 14.1.3

**Comment by mfpkb** [comment]
Any update on this ?

**Comment by neiljac1** [comment]
Hi @mfpkb,

If your application is a single identity app, then the MAM SDK will automatically apply the "Encrypt org data" device level file encryption to the files created by your app. There's no need to call any APIs. If your application is a multi-identity app, then you'll need to call the IntuneMAMFileProtectionManager protect() APIs to let the MAM SDK know which files contain managed data.

The value returned by the isFileEncryptionRequired is controlled by a different policy meant to indicate the application should use the IntuneMAMFilePolicyManager encryptFile/decryptFile APIs to perform software level encryption. This policy is not yet available to set in the admin console or through the Graph API so isFileEncryptionRequired will always return FALSE.

Thanks,
Neil
