### ISSUE TITLE
Queries: File encryption API provided by SDK

### ISSUE THREAD

**Issue by mfpkb** [msintuneappsdk/ms-intune-app-sdk-ios#161]
**Queries:**
I have following queries regarding File encryption API's provided by MAM SDK.

- I couldn't see methods like `removeItemAtPath, moveItemAtPath` etc. in `IntuneMAMFile` or `IntuneMAMFileProtectionManager`. Does it mean that for similar functionality we should use `NSFileManager` provided by Apple ?
-  Can we also use Apple `NSFileManager` API's along with SDK File encryption API's to achieve certain functionality ?. For example: Copy file using `NSFileManager` and then encrypt using `IntuneMAMFile.protect(atPath`.
- As per below info dialog from the "**Encrypt org data**" policy on the intune portal. `Applications may optionally encrypt app data using Intune App SDK ...` Does it mean even if encryption is enabled its optional to use file encryption API's provided by SDK ?

<img width="561" alt="Screen Shot 2021-04-13 at 5 38 15 PM" src="https://user-images.githubusercontent.com/82405421/114624718-1d393480-9c7f-11eb-8c82-69255f0f8a25.png">

Will appreciate response on this.

**Comment by neiljac1** [comment]
Hi @mfpkb,

- If your application is a single identity app, then the MAM SDK will automatically apply the device level encryption to the files created by you app. There's no need to call any APIs. If your application is a multi-identity app, then you'll need to call the IntuneMAMFileProtectionManager protect() APIs to let the MAM SDK know which files contain managed data.
- Yes, the standard file APIs can be used including NSFileManager and C APIs.
- The optional encryption is referring to software level file encryption. You can use the IntuneMAMFileProtectionManager encryptFile and decryptFile APIs to perform software level file encryption.

Thanks,
Neil

**Comment by mfpkb** [comment]
Thanks.
