### ISSUE TITLE
Creating a class derived from IntuneMAMEnrollmentDelegate causes WKWebView to stay in memory (memory leak)

### ISSUE THREAD

**Issue by alexeystrakh** [msintuneappsdk/ms-intune-app-sdk-ios#162]
**Describe the bug:**

In a Xamarin.iOS (Forms) application, with the InTune iOS NuGet package integrated, you can reproduce a memory leak by creating a class derived from IntuneMAMEnrollmentDelegate. This causes WKWebView to stay in memory. It can be verified by Xamarin.Profiler or Safari dev tools. I have created a sample reproducing the issue:

https://github.com/alexeystrakh/intune-enrollment-memoryleak

**To Reproduce**
1. Create a blank Xamarin.Forms app
1. Add the [Microsoft.Intune.MAM.Xamarin.iOS](https://www.nuget.org/packages/Microsoft.Intune.MAM.Xamarin.iOS/) package
1. Create [IntuneEnrollmentDelegate.cs](/testFormsAppWithProfiler.iOS/IntuneEnrollmentDelegate.cs)
1. Create an interface to open a WebView as many times as needed

**Actual result**: 
WebView and corresponding WKWebView is retained in memory, the number of instances correlates with the number of WebView activations

**Expected behavior:** 
WebView is garbage collected

**Workaround**: 
Comment out the `IntuneEnrollmentDelegate` class to avoid memory leak

**Screenshots and logs:**
Attaching two Xamarin.Profiler sessions and the screenshot showing the leaked WebViews:

<img width="1915" alt="XamarinFormsiOS InTune MemoryLeak" src="https://user-images.githubusercontent.com/3697084/116179009-5fc12f00-a6cb-11eb-80ab-edd8987ae2df.png">

[Xamarin.Profiler sessions](https://github.com/alexeystrakh/intune-enrollment-memoryleak/tree/master/SolutionItems)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.4

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? **14.1.3**
- Are you using the latest version? No, I'm using **14.1.3 as it's used by the customer code**
- What platform is your app based in? **Xamarin**
- For errors post build, does the app launch without being Intune SDK integrated? **Yes, it launches and the memory leak is not there if you don't define IntuneMAMEnrollmentDelegate**

- Who is the customer? **Internal MS**
- Do you see a trend with it only being reproduced on a specific device? **No**

**Comment by Kyle-Reis** [comment]
Hi @alexeystrakh - I think this issue might be the same as the root cause for #134, which we've recently fixed. Could you try out the [latest release](https://www.nuget.org/packages/Microsoft.Intune.MAM.Xamarin.iOS) (version 14.3.5) of the Intune Xamarin.iOS bindings?

**Comment by alexeystrakh** [comment]
I've done the research and missed somehow issue #134. I've confirmed the upgraded version 14.3.5 of the NuGet package fixes the issue. Appreciate your quick answer!
