### ISSUE TITLE
App fails to compile after upgrading to intune sdk v14.3.5 - "No such module "IntuneMAMSwift"

### ISSUE THREAD

**Issue by mobilesavvy** [msintuneappsdk/ms-intune-app-sdk-ios#165]
**Describe the bug:**
Hi our application fails to compile with error "No such module "IntuneMAMSwift" after upgrading to 14.3.5 version of intune sdk.
We were using "14.0.0". Interestingly it fails to compile only with Big Sur Mac OS, but we are able to compile with Catalina Mac OS. We tested using Xcode 12.3, 12.4 

**To Reproduce**
1. Upgrade to latest intune SDK and compile your app
2. App compiles without issues

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes
- What platform is your app based in (native, Xamarin based, Cordova, etc)? - Cordova 
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? 

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device? Yes our app compiles in Catalina MAC OS but not in Big Sur MAC OS. 

**Additional context:**
Our apps started to crash with latest iOS v14.5 (integrated with Intune SDK v14.0.0)
Hence trying to upgrade to latest intune sdk version and found this issue.

**Comment by Kyle-Reis** [comment]
Hi @mobilesavvy, in both cases, did you remove the project's references to the old ".framework" files and instead link to ".xcframework" files? (see [release notes for version 14.1.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/14.1.0))

**Comment by Kyle-Reis** [comment]
Hey @mobilesavvy, checking in to see if you're still experiencing this issue?

**Comment by mobilesavvy** [comment]
Hi @Kyle-Reis - sorry overlooked. It worked after referencing the xcframework files.
Thanks for your time.
