### ISSUE TITLE
IntuneMAMErrorDomain when pasting from UIClipboard 

### ISSUE THREAD

**Issue by shafersystems** [msintuneappsdk/ms-intune-app-sdk-ios#168]
**Describe the bug:**
Copying and pasting within the same application should work regardless of the DLP settings.  However, if pasting using loadFileRepresentationForTypeIdentifier instead of dataForPasteboardType, the pasting fails with IntuneMAMErrorDomain - code: 18446744073709551615

**To Reproduce**
1.  Within an application, copy a PDF page to the clipboard.
2. Within the same application, paste the PDF page using the following code:
     NSItemProvider* provider =[UIPasteboard generalPasteboard].itemProviders.firstObject;
    [provider loadFileRepresentationForTypeIdentifier:(NSString *)kUTTypePDF completionHandler:^(NSURL * _Nullable url, NSError * _Nullable error) {
        if (!url || error) {
            NSLog(@"error:  %@",error.localizedDescription);
            return;
        }
        // Create a PSPDFDocument from the URL and import pages from that document.
    }];
    

**Expected behavior:**
PDF page is pasted.

Actual behavior:  url is nil, and error code is IntuneMAMErrorDomain - code: 18446744073709551615

NOTE:  The correct pasteboard data can be viewed when using  [pasteboard dataForPasteboardType: (NSString*)kUTTypePDF];  However, this is not an option for us since the third party library we are using utilizes loadFileRepresentationForTypeIdentifier. 

**Screenshots and logs:**
2021-05-27 08:53:53.898830-0500 MyApp for Intune[17650:5040052] error:  The operation couldn’t be completed. (IntuneMAMErrorDomain error -1.)

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 14.0

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?  The latest version
- What platform is your app based in (native, Xamarin based, Cordova, etc)?  native
- For errors post build, does the app launch without being Intune SDK integrated? copy and paste work fine on non Intune builds

**Comment by gastaffo** [comment]
Hey @shafersystems, does this repro with any data provided or is it specific to PDF?

**Comment by shafersystems** [comment]
Hi @gastaffo, PDF is the only file type that I've tried it with because it is the only type within our application that is copied as a file, and which uses loadFileRepresentationForTypeIdentifier.

Are you not able to reproduce the error?

**Comment by gastaffo** [comment]
Yea. So @shafersystems how are you copying the PDF page to the clipboard?

**Comment by shafersystems** [comment]
@gastaffo here's how we copy the PDF page to the clipboard:

1) Create a NSItemProvider.
2) Call registerFileRepresentationForTypeIdentifier:fileOptions:visibility:loadHandler: on the itemProvider.
3) In the load handler block, we export the copied pages to a temporary file, which is stored in the temporaryDirectory.
4) Return the URL of the temporary file in the completionHandler of the loadHandler.
5) Update the itemProviders property of the pasteboard. (pasteboard.itemProviders = @[itemProvider];)

This works fine in the non-Intune versions of our app.

**Comment by shafersystems** [comment]
Is there any way to get a more detailed response about the IntuneMAMError?

**Comment by gastaffo** [comment]
@shafersystems Im working on getting a repro. That particular error you are seeing is a decoding error.

**Comment by shafersystems** [comment]
Thank you !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gastaffo** [comment]
Hi @shafersystems. So I haven't been able to get a consistent repro. Here is the code I have been using to try and repro. Does it look the same as what y'all are doing?
```

NSItemProvider* itemProvider = [NSItemProvider new];
    [itemProvider registerFileRepresentationForTypeIdentifier:kUTTypePDF
                                                  fileOptions:NSItemProviderFileOptionOpenInPlace
                                                   visibility:NSItemProviderRepresentationVisibilityAll
                                                  loadHandler:^NSProgress * _Nullable(void (^ _Nonnull completionHandler)(NSURL * _Nullable, BOOL, NSError * _Nullable)) {
        NSString* tempPath = [NSTemporaryDirectory() stringByAppendingPathComponent:@"temp.pdf"];
        NSFileManager* defaultManager = [NSFileManager defaultManager];
        [defaultManager removeItemAtPath:tempPath error:nil];

        NSError* error = nil;
        [defaultManager copyItemAtPath:[[NSBundle mainBundle] pathForResource:@"test" ofType:@".pdf"] toPath:tempPath error:&error];
        completionHandler([NSURL fileURLWithPath:tempPath],false, nil);

        NSProgress* progress = [NSProgress progressWithTotalUnitCount:1];
        [progress setCompletedUnitCount:1];
        return progress;
    }];
    [UIPasteboard generalPasteboard].itemProviders = @[itemProvider];

    NSItemProvider* provider =[UIPasteboard generalPasteboard].itemProviders.firstObject;
    [provider loadFileRepresentationForTypeIdentifier:(NSString *)kUTTypePDF completionHandler:^(NSURL * _Nullable url, NSError * _Nullable error) {
        if (!url || error) {
        NSLog(@"error: %@",error.localizedDescription);
        return;
        }
        NSLog(@"%@",url);
    // Create a PSPDFDocument from the URL and import pages from that document.
    }];
```

In the final call back we get a nil error and a url that points to a file like 3784B113-C75A-4B71-B431-9BE8056D23EB.data

**Comment by shafersystems** [comment]
Hi @gastaffo, 

This is almost what we do, however there a few things we do differently.

In the registerFileRepresentationForTypeIdentifier method, we set fileOptions equal to 0. Also, we use PDFDocumentEditor's -exportPages:toPath:withCompletionBlock: (https://pspdfkit.com/api/ios/Classes/PSPDFDocumentEditor.html#/c:objc(cs)PSPDFDocumentEditor(im)exportPages:toPath:withCompletionBlock:) method to do the actual writing instead of using the NSFileManager to copy the entire file.

I'm not sure why this wouldn't work when using the Intune SDK when it works fine without it.

**Comment by gastaffo** [comment]
Hi @shafersystems,

I started using the PSPDF kit method and cannot get a reproduction. Here is the code I am using.
 ```
NSItemProvider* itemProvider = [NSItemProvider new];
    [itemProvider registerFileRepresentationForTypeIdentifier:kUTTypePDF
                                                  fileOptions:0
                                                   visibility:NSItemProviderRepresentationVisibilityAll
                                                  loadHandler:^NSProgress * _Nullable(void (^ _Nonnull completionHandler)(NSURL * _Nullable, BOOL, NSError * _Nullable)) {
        NSString* tempPath = [NSTemporaryDirectory() stringByAppendingPathComponent:@"temp.pdf"];
        NSFileManager* defaultManager = [NSFileManager defaultManager];
        [defaultManager removeItemAtPath:tempPath error:nil];

        NSURL* pdfUrl = [[NSBundle mainBundle] URLForResource:@"testbig" withExtension:@".pdf"];
        PSPDFDocument* document = [[PSPDFDocument alloc] initWithURL:pdfUrl];
        PSPDFDocumentEditor* editor = [[PSPDFDocumentEditor alloc] initWithDocument:document];
        [editor exportPages:[NSIndexSet indexSetWithIndex:1] toPath:tempPath withCompletionBlock:^(PSPDFDocument * _Nullable document, NSError * _Nullable error) {
            if(error)
            {
                NSLog(@"RETURNED: PDF ERROR: %@",error);
            }
            completionHandler([NSURL fileURLWithPath:tempPath],false, nil);
        }];
        NSProgress* progress = [NSProgress progressWithTotalUnitCount:1];
        [progress setCompletedUnitCount:1];
        return progress;
    }];
    [UIPasteboard generalPasteboard].itemProviders = @[itemProvider];

    NSItemProvider* provider =[UIPasteboard generalPasteboard].itemProviders.firstObject;
    [provider loadFileRepresentationForTypeIdentifier:(NSString *)kUTTypePDF completionHandler:^(NSURL * _Nullable url, NSError * _Nullable error)
    {
        if (!url || error) {
        NSLog(@"RETURNED: error: %@",error.localizedDescription);
        return;
        }
        NSLog(@"RETURNED: %@",url);
    }];
```
And after running it I get the output
`RETURNED: file:///<path to temp folder>/DA9B20C7-38F0-4E64-B06C-8F393BA3E599/09FD0F3B-E2D1-4495-8179-A91CABD804D1.data`

Is your app a multi-identity app? Also does this reproduce on multiple pdfs? Would you be willing to sending me the pdf and the pages to copy that reproduce the error?

**Comment by shafersystems** [comment]
@gastaffo, it isn't a multi-identity app.  It is using an app ID for Intune and a separate app ID for Office 365 though.  You can contact me at sales at shafersystems.com and I can provide you with the application itself so you might be able to reproduce the problem easier that way.  I can reproduce it 100% of the time and it isn't dependent upon a specific document.

**Comment by gastaffo** [comment]
Hi @shafersystems, It would be best if we get a support case for this issue going. In the endpoint manager (endpoint.microsoft.com) you can go to "Troubleshooting + support"->"Help and support"->"Intune" to start one.

**Comment by shafersystems** [comment]
Hi @gastaffo, I've created support [Case #:26129084] .  Is there anything else that I can do to help you?  If you have the PSPDFKit SDK, you can reproduce the problem by opening a PDF, copying a page, then closing the PDF, opening another and pasting the page in.  This works without Intune, but not with the Intune SDK.
