### ISSUE TITLE
Intune SDK 14.1.0 ADAL 4.0.9 crash on start with iOS 14.6 

### ISSUE THREAD

**Issue by arsalangolestanekh** [msintuneappsdk/ms-intune-app-sdk-ios#169]
Hi, after iOS 14.6 update I can not use Microsoft Intune SDK, app crash on start.
SDK version: 14.1.0
ADAL 4.0.9
Xcode 12.3
Issue was not seen on previous OS.
Please, help me to solve this issue, 

App is crashing on NSPersistentContainer.loadPersistentStores()

Intune logs before app crash:

IntuneMAM: Interface orientation view controller <name>: autoRotate=yes, supportedInterfaceOrientations=30 preferredInterfaceOrientationForPresentation=0

TID = 53143 ADAL 4.0.9 iOS 14.6 [2021-05-27 19:15:53] ADAL API call [Version - 4.0.9] - In function: -[ADAuthenticationContext acquireTokenSilentWithResource:clientId:redirectUri:completionBlock:], file line #364

TID = 53143 ADAL 4.0.9 iOS 14.6 [2021-05-27 19:15:53 - 487590CC-9B0F-4920-93BD-C57C78DB2539] ##### BEGIN acquireToken Silent idtype = (null) authority host: login.microsoftonline.com #####

TID = 53459 ADAL 4.0.9 iOS 14.6 [2021-05-27 19:15:53 - 487590CC-9B0F-4920-93BD-C57C78DB2539] No cached preferred_network for authority

TID = 53459 ADAL 4.0.9 iOS 14.6 [2021-05-27 19:15:53 - 487590CC-9B0F-4920-93BD-C57C78DB2539] Waiting on Authority Validation Queue

IntuneMAM: cmarHookedInitWithMemoryCapacity newURLCacheDir CMARScrubbedDir://////Application/00F27C07-6A4A-4302-8618-27632769C540///appName/005....86b/

**Comment by neiljac1** [comment]
Hi @arsalangolestanekh, 

Please update to the latest version of the SDK, 14.4.1, which can be found here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/14.4.1

Thank you,
Neil

**Comment by Kyle-Reis** [comment]
Hey @arsalangolestanekh, just want to confirm that upgrading Intune addressed this issue for you?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. As @neiljac1 mentioned, this is a known issue which should be addressed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest).
