### ISSUE TITLE
The token can't be issued because the identity or claim insurance provider was denied.

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#170]
**Describe the bug:**

We have Intune enrollment don with one UPN (say "xyz@abc.com)

The user was transferred from one unit/company to a different one so the email and UPN changed, from "xyz@abc.com" to xyz@dce.com"; 

The App (iOS - iPhone) is displaying an error message on enrolment call:
"The token can't be issued because the identity or claim insurance provider was denied."

The user had already tried to delete the app, reinstall and reconfigure with a new user account(UPN). The same error exists on Intune App Enrollment.

Is it an AD cache issue? How can the user clear the cache to solve the issue?

**Screenshots and logs:**
<img width="136" alt="screen_2" src="https://user-images.githubusercontent.com/2161122/119919063-41c74280-bf87-11eb-9c1f-619c4130a47b.png">

**Intune App SDK for iOS (please complete the following information):** 14.3.5	
- What version of the Intune SDK are you using? Are you using the latest version?14.3.5
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? No
- For errors post build, does the app launch without being Intune SDK integrated?No

- Who is the customer? Infor
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**
This is a production issue, please lets us know how we can fix this?

**Comment by Nookaraju** [comment]
@Kyle-Reis Can you help?

**Comment by Nookaraju** [comment]
@Kyle-Reis need your inputs in this issue

**Comment by Kyle-Reis** [comment]
Hi @Nookaraju. Is this a wrapped application, or is the app integrated with the Intune SDK and explicitly calling one of the Intune enrollment methods? Do you know if this error occurs on a new device with no previous authentication/enrollment state?

**Comment by Nookaraju** [comment]
@Kyle-Reis the app is integrated with Intune SDK and linked latest ADAL (pods). We call loginAndEnrollAccount from our app to start to intune enrolment. 

I will check with the user on behavior on a new device. It must not be a problem with a new device case.

**Comment by Kyle-Reis** [comment]
@Nookaraju - Thanks for the additional info. Does the app pass nil to loginAndEnrollAccount? If so, is the user actually prompted for credentials, or do they just see this error without inputing any creds?

**Comment by Nookaraju** [comment]
App passes UPN to loginAndEnrollAccount call. UPN is prefilled and prompted for the password.

**Comment by Kyle-Reis** [comment]
Thanks @Nookaraju, does the application specify a custom AAD authority or client ID to use for Intune enrollment?

This does appear to be some sort of AAD token cache issue, since it doesn't reproduce on a clean device. From above it sounds like Intune is using the correct (new) UPN to initiate a token acquisition request with ADAL. I'm wondering if it's possible that somehow incorrect authority is being used for this account (assuming the new account is in a separate AAD tenant)

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
