### ISSUE TITLE
Getting ipa failed error after upgrading Intune SDK version to V14.4.1

### ISSUE THREAD

**Issue by JeevanandhamRaja** [msintuneappsdk/ms-intune-app-sdk-ios#171]
**Describe the bug:**
Getting' ipa failed error' after upgrading Intune SDK version to V14.4.1 It happens only after integrating with 14.4.1. 
Working finr With version 12.4.0

**To Reproduce**
1. Download Intune SDK version 14.4.1
2. Open Xcode and Remove Intune SDK version 12.4.0 (Move to Trash)
3. Add Intune SDK version 14.4.1 and select all targets
4. Change iOS deployment target 12.3
4. Build and Archive 
5. Distribute archive with Development option
6. Error IPA failed 

**Expected behavior:**
IPA should be created 

**Screenshots and [logs:**]([url](url))
- Added screenshot 
- If your app is experiencing an issue post build, do you have app logs for the crash itself? No logs found post build.

**Smartphone (please complete the following information):**
<img width="780" alt="Screenshot 2021-05-28 at 1 09 58 PM" src="https://user-images.githubusercontent.com/84956173/119948187-36d7d680-bfb6-11eb-81af-de13f623b32b.png">

 - OS: [e.g. iOS12.3]
[](url)
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Intune SDK version to V14.4.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device? Not applicable

**Additional context:**

**Comment by JeevanandhamRaja** [comment]
Hi Kyle Reis,

Thank you for your response!

Yes, I have removed libIntuneMAM.a from the project reference along with old .framework references.

PFA the file (found only one file with .a extension in 12.4.0 version).

Thanks,
Jeevanandham R
+91 9566778534

________________________________

**Comment by Kyle-Reis** [comment]
@JeevanandhamRaj - Which version of Xcode are you using? Does the "Show logs" button above provide any more info on what exactly is causing the IPA generation to fail?

**Comment by JeevanandhamRaja** [comment]
Hi,

I am using Xcode 12.0.1. Also tried with Xcode 12.4 but no luck. Show logs button shows nothing while getting IPA failed error.

When trying with Jenkins we got below error. Kindly check.


2021-05-27 07:50:52 +0000 [MT] Starting export with options: <IDEFoundation.IDEDistributionExportOptions: 0x7fae82657040>
2021-05-27 07:50:52 +0000 [MT] Running step: IDEDistributionReformatArchiveStep with <IDEDistributionContext: 0x7fae826795d0; archive(resolved)='<IDEArchive: 0x7fae82658ee0>', distributionTask(resolved)='2', distributionDestination(resolved)='1', distributionMethod(resolved)='<IDEDistributionMethodDevelopmentSigned: 0x7fae823dd6a0>', team(resolved)='(null)'>
Chain (2, self inclusive):
<IDEDistributionContext: 0x7fae826795d0; archive = '<IDEArchive: 0x7fae82658ee0>', distributionMethod='<IDEDistributionMethodDevelopmentSigned: 0x7fae823dd6a0>', team='(null)'>
<IDEDistributionContext: 0x7fae82659370; archive = '<IDEArchive: 0x7fae82658ee0>', distributionMethod='(null)', team='(null)'>
</IDEDistributionContext: 0x7fae826795d0>
2021-05-27 07:50:52 +0000 [MT] Running step: IDEDistributionAnalyzeArchiveStep with <IDEDistributionContext: 0x7fae82588d90; archive(resolved)='<IDEArchive: 0x7fae82658ee0>', distributionTask(resolved)='2', distributionDestination(resolved)='1', distributionMethod(resolved)='<IDEDistributionMethodDevelopmentSigned: 0x7fae823dd6a0>', team(resolved)='(null)'>
Chain (3, self inclusive):
<IDEDistributionContext: 0x7fae82588d90; archive = '<IDEArchive: 0x7fae82658ee0>', distributionMethod='<IDEDistributionMethodDevelopmentSigned: 0x7fae823dd6a0>', team='(null)'>
<IDEDistributionContext: 0x7fae826795d0; archive = '<IDEArchive: 0x7fae82658ee0>', distributionMethod='<IDEDistributionMethodDevelopmentSigned: 0x7fae823dd6a0>', team='(null)'>
<IDEDistributionContext: 0x7fae82659370; archive = '<IDEArchive: 0x7fae82658ee0>', distributionMethod='(null)', team='(null)'>
</IDEDistributionContext: 0x7fae82588d90>
2021-05-27 07:50:52 +0000 [MT] [OPTIONAL] Didn't find info dictionary for <DVTFilePath:0x7fae82a428d0:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/libIntuneMAMSwift.xcframework/ios-arm64_x86_64-simulator/libIntuneMAMSwift.a'>: Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't load Info dictionary for <DVTFilePath:0x7fae82a428d0:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/libIntuneMAMSwift.xcframework/ios-arm64_x86_64-simulator/libIntuneMAMSwift.a'>" UserInfo={NSLocalizedDescription=Couldn't load Info dictionary for <DVTFilePath:0x7fae82a428d0:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/libIntuneMAMSwift.xcframework/ios-arm64_x86_64-simulator/libIntuneMAMSwift.a'>}
2021-05-27 07:50:52 +0000 [MT] [OPTIONAL] Didn't find info dictionary for <DVTFilePath:0x7fae827f6640:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/IntuneMAMConfigurator'>: Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't load Info dictionary for <DVTFilePath:0x7fae827f6640:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/IntuneMAMConfigurator'>" UserInfo={NSLocalizedDescription=Couldn't load Info dictionary for <DVTFilePath:0x7fae827f6640:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/IntuneMAMConfigurator'>}
2021-05-27 07:50:53 +0000 [MT] [OPTIONAL] Didn't find info dictionary for <DVTFilePath:0x7fae82764210:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/libIntuneMAMSwiftFileProvider.xcframework/ios-arm64_x86_64-simulator/libIntuneMAMSwiftFileProvider.a'>: Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't load Info dictionary for <DVTFilePath:0x7fae82764210:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Applications/MentalHealthUAT.app/ms-intune-app-sdk-ios-master/libIntuneMAMSwiftFileProvider.xcframework/ios-arm64_x86_64-simulator/libIntuneMAMSwiftFileProvider.a'>" UserInfo={NSLocalizedDescription=Couldn't load Info dictionary for <DVTFilePath:0x7fae82764210:'/Users/jenkins/workspace/ThriveToolkit_iOS_Pipeline/Thrive/outPut/MentalHealth.xcarchive/Products/Appli

Thanks,
Jeevanandham R

________________________________

**Comment by JeevanandhamRaja** [comment]
Hi Kyle,

I am using Xcode 12.0.1. Also tried with Xcode 12.4 but no luck. Show logs button shows nothing while getting IPA failed error.

I have sent Jenkins error details in previous mail. Please let me know if you didn't receive that mail.

Thanks,
Jeevanandham R
+91 9566778534

________________________________

**Comment by JeevanandhamRaja** [comment]
Hi Kyle, Kindly let me know if you have any update on this issue. Thanks!

**Comment by Kyle-Reis** [comment]
Hi @JeevanandhamRaja, for some reason the .app file seems to contain the entire contents of our repository. This should not be the case. How is the ms-intune-app-sdk-ios-master getting copied into the app bundle? Is this being done manually or by some custom script which executes as part of the build process? Please refer to our [developer guide](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios) for steps on how to link to to the Intune SDK.

**Comment by JeevanandhamRaja** [comment]
Hi Kyle,

Good morning! I am able to archive the app after adding the intune lib path in Library Serach paths in Xcode Build settings.

Here the problem is not able to run the application in device but app is working fine in Simulator.

PFB error details which I am getting while trying to install the application in device. Could you please help on this issue?


Unable to install "MentalHealthUAT"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620391
--
The application does not have a valid signature.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620391
User Info: {
    DVTRadarComponentKey = 487925;
    MobileDeviceErrorCode = "(0xE8008019)";
    "com.apple.dtdevicekit.stacktrace" = (
0   DTDeviceKitBase                     0x000000012bda293f DTDKCreateNSErrorFromAMDErrorCode + 220
1   DTDeviceKitBase                     0x000000012bde1124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
2   DVTFoundation                       0x000000010fc8db43 DVTInvokeWithStrongOwnership + 71
3   DTDeviceKitBase                     0x000000012bde0e65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
4   IDEiOSSupportCore                   0x000000012bc51d28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
5   DVTFoundation                       0x000000010fdbc2aa __DVT_CALLING_CLIENT_BLOCK__ + 7
6   DVTFoundation                       0x000000010fdbdecc __DVTDispatchAsync_block_invoke + 1191
7   libdispatch.dylib                   0x00007fff687bc6c4 _dispatch_call_block_and_release + 12
8   libdispatch.dylib                   0x00007fff687bd658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00007fff687c2c44 _dispatch_lane_serial_drain + 597
10  libdispatch.dylib                   0x00007fff687c35d6 _dispatch_lane_invoke + 363
11  libdispatch.dylib                   0x00007fff687ccc09 _dispatch_workloop_worker_thread + 596
12  libsystem_pthread.dylib             0x00007fff68a17a3d _pthread_wqthread + 290
13  libsystem_pthread.dylib             0x00007fff68a16b77 start_wqthread + 15
);
}
--


System Information

macOS Version 10.15.7 (Build 19H15)
Xcode 12.0.1 (17220)

Thanks,
Jeevanandham R


________________________________

**Comment by Kyle-Reis** [comment]
Hi @JeevanandhamRaja the error suggests a problem with how the app was signed. Is some change being made to the contents of the app bundle after it has been code signed? Also, if dev signing, try verifying that the UUID of the device you're testing with is included in the provisioning profile used to sign the app.

**Comment by JeevanandhamRaja** [comment]
HI Kyle,

Just to clarify, If I remove new changes made for Intune SDK integration, App is getting installed successfully with same device.

I am getting Unable to install app error only when I made changes to add Intune SDK 14.4.1 and trying to install in device.

Kindly let me know if we can have a webex session to solve this issue.

Thanks,
Jeevanandham R

________________________________

**Comment by Kyle-Reis** [comment]
Hey @JeevanandhamRaja - with the changes to link to the latest Intune release, is the ms-intune-app-sdk-ios-master directory still being copied into the app bundle? If so, can you try to find out where that is happening and remove the task/script which does this?

**Comment by JeevanandhamRaja** [comment]
Hi Kyle,

I hope only required files are getting copied to bundle.

I could find Intune SDK file/folders as shown in attached after archiving. Please confirm which are not required here. So that I will remove and check once.



Thanks,
Jeevanandham R

________________________________

**Comment by Kyle-Reis** [comment]
Hi @JeevanandhamRaja - I don't see anything attached to your last message, should there have been an image linked?

**Comment by JeevanandhamRaja** [comment]
Hi Kyle,

Yes, I have attached below image in last mail.

[cid:fc74c8bd-15b2-4287-8c86-e3097d49217f]
Thanks,
Jeevanandham R

________________________________

**Comment by Kyle-Reis** [comment]
Hi @JeevanandhamRaja, I'm not getting any image attachment. Could you try pasting the image into the GitHub UI?

**Comment by JeevanandhamRaja** [comment]
<img width="489" alt="Screenshot 2021-06-11 at 7 53 06 AM" src="https://user-images.githubusercontent.com/84956173/121932233-413df280-cd62-11eb-97a8-f22cc621010b.png">

**Comment by JeevanandhamRaja** [comment]
Hi Kyle, I have attached the image in GitHub UI.

**Comment by Kyle-Reis** [comment]
Hi @JeevanandhamRaja, where do the above files exist within the app bundle?

**Comment by JeevanandhamRaja** [comment]
Hi @Kyle-Reis , yes it is inside the ipa file. I have open the package contents of ipa and navigated to below path to see this file. 

Xcode/Archives/2021-06-11/MentalHealthUAT 11-06-21, 7.51 AM.xcarchive/Products/Applications/MentalHealthUAT.app/Frameworks

![image](https://user-images.githubusercontent.com/84956173/121933392-a47c5480-cd63-11eb-9c0d-58141da5a305.png)

**Comment by Kyle-Reis** [comment]
Thanks @JeevanandhamRaja. That looks good. Can you also confirm that the ms-intune-app-sdk-ios-master directory no longer exists in the root of the app bundle?

**Comment by JeevanandhamRaja** [comment]
Yes @Kyle-Reis. ms-intune-app-sdk-ios-master directory is no longer exists in the root of the app bundle.

**Comment by Kyle-Reis** [comment]
Thanks for confirming, @JeevanandhamRaja. Under the "General" tab In the Xcode settings for the app target as well as any extension the app includes which links to the Intune SDK, could you confirm that the "Embed & Sign" option is selected for the Intune frameworks:

![image](https://user-images.githubusercontent.com/7443106/122605064-ee578a00-d044-11eb-8bfc-29d57184c5a8.png)

**Comment by JeevanandhamRaja** [comment]
@Kyle-Reis Thanks for above details. Yes, I have selected embed and Sign option for the Intune frameworks for all required targets.

**Comment by JeevanandhamRaja** [comment]
@Kyle-Reis could you please share what I missed here. Still I am facing issue..

**Comment by Kyle-Reis** [comment]
Hi @JeevanandhamRaja - Is the IntuneMAMConfigurator tool being run automatically as part of the build process? I'm wondering if the project might be configured to run the tool against the compiled app's Info.plist, rather than pre-compilation and it is resulting in a change to the file after the app was built/signed (causing the app's signature to be invalidated). Some updates have been made to the tool since the 12.4.0 version of Intune. I'm wondering if this issue might not occur when linking to version 12.4.0 because the pre-compiled version already has all the changes needed for 12.4.0 and no update is made at build time.

**Comment by JeevanandhamRaja** [comment]
Hi Kyle,

Not sure if IntuneMAMConfigurator tool is being run automatically as part of the build process. Could you please let me know how to check this?

Also kindly share steps to integrate latest Intune SDK to existing iOS apps?

I have followed below instruction but no luck.
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios>
Microsoft Intune App SDK for iOS developer guide<https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios>
The Microsoft Intune App SDK for iOS lets you incorporate Intune app protection policies (also known as APP or MAM policies) into your native iOS app.
docs.microsoft.com



Thanks,
Jeevanandham R

________________________________

**Comment by abasore** [comment]
Hi @JeevanandhamRaja the IntuneMAMConfigurator tool would need to be run or added to your build process manually. The [docs here ](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#whats-in-the-sdk-repository)describe how to use the tool. The tool can be found in the SDK repo. 

For using the latest Intune SDK (14.6.2), you can download the IntuneMAM xcframeworks from the repo [here](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios). Are you having specific issues with integrating the latest version? The steps are largely the same for integrating previous version as the current one.
