### ISSUE TITLE
Documentation does not mention that Bit Code needs to be disabled

### ISSUE THREAD

**Issue by andrejacobs-unily** [msintuneappsdk/ms-intune-app-sdk-ios#172]
**Describe the bug:**
The Intune MAM frameworks have not been compiled with Bitcode and thus Xcode will not build your app.
The official docs: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios mention to Strip Swift Symbols but does not mention bitcode will need to be disabled as well.

**To Reproduce**
1. Create a new project to follow the steps of adding the Intune MAM SDK. https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios
2. Try to compile the app.

**Expected behavior:**
The app should compile and at least run. The docs need to state that you need to disable Bitcode.
We are lucky that we generally don't use this feature so it can be turned off. Not sure what folk that needs it will do.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yep latest release 14.4.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native
- For errors during build, does the app build without Intune SDK integration? yes
- For errors post build, does the app launch without being Intune SDK integrated? yes

**Comment by gastaffo** [comment]
Thanks for the catch. Will update those to include the mention of disabling bitcode.

**Comment by gastaffo** [comment]
Documentation has been updated. Closing issue https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#:~:text=The%20Microsoft%20Intune%20App%20SDK%20for%20iOS%20lets,mobile%20app%20when%20Intune%20actively%20manages%20the%20app.
