### ISSUE TITLE
enrollmentRequest delegate method of IntuneMAMEnrollmentDelegate not called

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#178]
**Describe the bug:**
I set up delegate methods for both enrollment and policy like
``
IntuneMAMPolicyManager.instance().delegate = self
``
``
IntuneMAMEnrollmentManager.instance().delegate = self
``

Delegate method `enrollmentRequest(with status: IntuneMAMEnrollmentStatus)` is being called after `enrollmentManager.registerAndEnrollAccount(upn)` only when there are intune policies available for the user. 

However when there are no intune policies available for the user then this delegate method is not being called.
Due to this behavior there is no call back, letting application know whether intune enrollment is successful or failure.

**Versions:**
SDK: 14.1.1
iOS: 14.x
MSAL: 1.1

**Comment by NicolasLourenco** [comment]
Hello, I'm facing the same issue.

**Comment by parveen-bhatia** [comment]
We are using this workaround to fix this. 
Every time user launch the app if user is not enrolled, then call `deRegisterAndUnenrollAccount`. In the delegate callback `unenrollRequest(with status:`, call `registerAndEnrollAccount` or `loginAndEnrollAccount`.
Doing so delegate methods are being called every time even when there are no intune policies applied.

**Comment by ensprit** [comment]
Hello, I'm facing the same issue.

**Comment by ensprit** [comment]
> **Describe the bug:** I set up delegate methods for both enrollment and policy like `IntuneMAMPolicyManager.instance().delegate = self` `IntuneMAMEnrollmentManager.instance().delegate = self`
> 
> Delegate method `enrollmentRequest(with status: IntuneMAMEnrollmentStatus)` is being called after `enrollmentManager.registerAndEnrollAccount(upn)` only when there are intune policies available for the user.
> 
> However when there are no intune policies available for the user then this delegate method is not being called. Due to this behavior there is no call back, letting application know whether intune enrollment is successful or failure.
> 
> **Versions:** SDK: 14.1.1 iOS: 14.x MSAL: 1.1

I am also facing same issue any one can help as

**Comment by nidhi-hearsay** [comment]
Any update on this? Seeing the same issue over here as well.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
