### ISSUE TITLE
Localization strings appearing as identifiers rather than properly localized strings

### ISSUE THREAD

**Issue by jdizoglio** [msintuneappsdk/ms-intune-app-sdk-ios#18]
In all enrollment screen, pin entry screens and alerts, messages and labels are the string identifiers and are not resolved to the localized string.

ex: Enter_Pin_Message, Touch_ID_Localized_Reason ...

**Comment by msintuneappsdk** [comment]
What language is set on the device under Language & Region on the iOS Settings?

**Comment by jdizoglio** [comment]
It was initially reported to us for Japanese. But we are seeing this in all languages (my verification was in english and US). Looking into the resource bundle, we don't see the string index that match these strings.

**Comment by msintuneappsdk** [comment]
Hi @jdizoglio can you/app developer have a look again at how the resource files are set up? The files look localized for all languages.

**Comment by jdizoglio** [comment]
The framework is included in our app projects embedded binaries. Don't the resources resolve internally your code and resource bundle? To support localization, are there other project configurations required?

**Comment by Kyle-Reis** [comment]
Hey @jdizoglio, I'm looking into this. Just to verify, you are using version [9.0.5](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/9.0.5) of the dynamic framework (IntuneMAM.framework)?

**Comment by jdizoglio** [comment]
correct, thank you.

**Comment by Kyle-Reis** [comment]
Hey @jdizoglio, I just tested out the enrollment flow in multiple languages and verified that localization is working. Maybe your copy of the framework was somehow corrupted? Have you tried re-downloading?

**Comment by jdizoglio** [comment]
Was the first thing we tried. Deleted the entire framework and reinstalled. We are building with Xcode 10.1. Maybe we had something from the older framework in the project that wasn't cleaned out. I'll go a head and retry.

**Comment by Kyle-Reis** [comment]
Hey @jdizoglio, were you able to resolve your issue?

**Comment by jdizoglio** [comment]
No. I am looking at the strings in the _IntuneMAM_ binary and I see "Account_Mismatch_Title" (one of the unresolved strings during enrollment) and in the _AppRestrictions.strings_ (en.lproj) it is "Account_Mismatch_Title_". All of the enrollment screen and alert strings on the tags.

**Comment by jdizoglio** [comment]
AppRestrictions.strings is a plist and was getting it's line feeds converted committing to our repo. We're committing the files as binary now. Would you consider no using a plist for stings files, similar to the other strings files in your bundle?

**Comment by jdizoglio** [comment]
This didn't work. We verified the keys in AppRestrictions.strings and the framework binary are the same.
plutil -p AppRestrictions.strings. You also have a bundle outside the framework package. Does this also need to be included?

**Comment by Kyle-Reis** [comment]
Hey @jdizoglio, the resource bundle you're referring to is not needed when using the dynamic framework. It is only required when using the static library (libIntuneMAM.a). Did you try cleaning the build folder after addressing the corruption issue? If you've tried this and the issue is still occurring, could you share which languages are supported in the app's localization settings? They can be found in Xcode by selecting the project file in the Navigator, select it again under “PROJECT” in the Window that appears, then select the “Info” tab. Could you also tell me whether "Use Base Internationalization" is enabled?

**Comment by jdizoglio** [comment]
@Kyle-Reis I cleaned the archive and rebuilt the app. I verified the strings files in the ipa with plutil and it was the correct one ( no line feed conversion). I deployed through our azure portal and still issues resolving strings.

![img_9333](https://user-images.githubusercontent.com/889666/49045236-34962680-f185-11e8-9b09-cd062650f198.PNG)

**Comment by Kyle-Reis** [comment]
OK, were you able to find the app's localization settings in Xcode? It should look something like this:

![image](https://user-images.githubusercontent.com/7443106/49092738-a37c8980-f230-11e8-8ba7-eae4c1cedbd0.png)

Could you share what is configured here?

**Comment by jdizoglio** [comment]
<img width="614" alt="screen shot 2018-11-27 at 11 12 55 am" src="https://user-images.githubusercontent.com/889666/49105519-9ca44580-f235-11e8-910e-66f0d4115537.png">

**Comment by jdizoglio** [comment]
We add the framework to our project as an embedded framework. How do set your bundleForClass when loading resources? If this was correct, I would expect the default en to replace any unsupported languages. But I guess you have resources images loading fine (or maybe these are set via Interface Builder)

**Comment by Kyle-Reis** [comment]
Hey @jdizoglio, could you verify that IntuneMAMResources.bundle exists at the following path in the app bundle: Frameworks/IntuneMAM.framework/IntuneMAMResources.bundle

**Comment by jdizoglio** [comment]
@Kyle-Reis, yes

**Comment by jdizoglio** [comment]
@Kyle-Reis  Is there something else we can do on this? This issue is customer facing and we need to get them a fix.

**Comment by Kyle-Reis** [comment]
Hey @jdizoglio, do you know why the number of localized files differs between languages? Also, do you know what reference language(s) was used when adding new languages? Was it just "Base"?

**Comment by jdizoglio** [comment]
We should update, but it's because our extensions support subsets of our app languages. Just 'Base'.

**Comment by Kyle-Reis** [comment]
How did you get some languages to show "0 Files Localized"? Xcode won't let me add a language without selecting a file to localize. Were the files removed at a later time? Or did you edit the pbxproj directly?

**Comment by jdizoglio** [comment]
It's most likely the various Xcode version and project migration that caused the 0 file.

**Comment by jdizoglio** [comment]
@Kyle-Reis The issue appears to be fixed. I don't have the how or why answer for you. Our latest builds are resoling the localization strings for the intune framework. Grasping straws, but I only see project changes related to removing older classes out and adding new ones into our app. Perhaps this fixed something in xCode project.

However, I think we are good and can close this issue. We are seeing consistent results in both local and build server binaries. Thank you for helping out.
