### ISSUE TITLE
RemediateCompliance is failing with a conditional access

### ISSUE THREAD

**Issue by NicolasLourenco** [msintuneappsdk/ms-intune-app-sdk-ios#180]
**Describe the bug:**
When calling `complianceManager.remediateCompliance(forIdentity: identity, silent: silent)` the flow for signin/enrollment always fails.

The `IntuneMAMComplianceDelegate` is called the `IntuneMAMComplianceInteractionRequired` status.
The `IntuneMAMEnrollmentDelegate` is also called next to the compliance delegate with status `IntuneMAMEnrollmentStatusAuthRequired (203)` and the error: 
```
Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=No account provided for the silent request. Please call interactive acquireToken request to get an account identifier before calling acquireTokenSilent.}
```

My first idea is to compare the `MSALPublicClientApplicationConfig` and the `MAMSettings` but all seems to be ok.
Also, I don't know which parameter I should use on `remediateCompliance`, it's the UPN (looks like `azertyuio-875d-4959-9053-8c7cfbb9bc24.FGHJKL-b943-4670-af76-c40c4d15d3b3`) or the identifier (looks like `email@company.com`)? 

**To Reproduce**
1. acquireToken
2. remediateCompliance
3. acquireSilentToken to finish the sign in

**Expected behavior:**
`IntuneMAMComplianceDelegate` and `IntuneMAMEnrollmentDelegate` are called with success status 🤷🏼 

**Smartphone (please complete the following information):**
 - Device: iPhone 7 / iPhone XS
 - OS: iOS 13/14

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? The latest
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native

**Comment by vigavadi** [comment]
Hey @NicolasLourenco. Are you getting `MSALErrorServerProtectionPoliciesRequired` error when you first call `acquireToken`?

**Comment by NicolasLourenco** [comment]
Yes

**Comment by vigavadi** [comment]
Thanks for confirming. 
So when IntuneMAMComplianceDelegate returns `IntuneMAMComplianceInteractionRequired` status, you should call `remediateCompliance(forIdentity: identity, silent: false)`.
Only when you get `IntuneMAMComplianceCompliant` status back in the `hasComplianceStatus` method of IntuneMAMComplianceDelegate, should you be making further token requests.
`remediateCompliance` should be called with UPN (`email@company.com`)

**Comment by NicolasLourenco** [comment]
Thanks for your response. 
So what you mean is to make 2 calls to `remediateCompliance`
- First one, after the `acquireToken` with `MSALErrorServerProtectionPoliciesRequired `
- Second one, on `IntuneMAMComplianceDelegate ` with `IntuneMAMComplianceInteractionRequired `

Is this right?
Because in this state, I'm getting the error: 
```
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application
```

it's pretty weird, without conditional access, the enrolment succeed without any errors

**Comment by vigavadi** [comment]
Hey @NicolasLourenco Yes that is correct. If you wish to avoid it, you can call it with **silent: false** the first time itself and it should prompt for credentials then. 
As for the error you mentioned, it seems like the redirect URI that you are using isn't configured properly. 
Are you specifying `ADALRedirectUri` in your IntuneMAMSettings dictionary in the Info.plist file?

**Comment by NicolasLourenco** [comment]
Sorry but it's weird to made another call to remediateCompliance (with silent: false).
Doing this will prompt the credentials a second time. It's not really user friendly.

**Comment by vigavadi** [comment]
It wouldn't prompt for credentials if it can successfully acquire a token silently.  The issue seems to be that token cannot be acquired successfully. 
Have you configured the settings in IntuneMAMSettings dictionary in the Info.plist file as mentioned here: [Configure Settings for Intune SDK](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk)
Based on this error you mentioned: 
`Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application`

It seems that the redirect URI isn't configured properly.

`

**Comment by NicolasLourenco** [comment]
It seems that the cache / keychain is the cause.
When implementing the solution, I've updated my code/configuration several times who caused a bad state in my keychain.
Disconnecting all the accounts (in the browsers/authenticator) and deleting the apps seems to works.
