### ISSUE TITLE
Add support for React Native and current support statement from Intune SDK team

### ISSUE THREAD

**Issue by msharsur** [msintuneappsdk/ms-intune-app-sdk-ios#182]
![image](https://user-images.githubusercontent.com/32535747/124882668-40f5e780-dfee-11eb-8a0f-7441d6d343f5.png)
Add support for React Native #21

React Native has become a common framework for building cross platform apps and the support statement around the use of the Intune SDK for that has been the above for the last 1-2 years. Is there any update to this or plans to have a sample built around this use case?

**Comment by vigavadi** [comment]
@msharsur Thank you for reaching out. We do not have any plans around providing support for React Native at the moment.

**Comment by abasore** [comment]
Closing this issue as support is not planned.

**Comment by sdevansh96** [comment]
> ![image](https://user-images.githubusercontent.com/32535747/124882668-40f5e780-dfee-11eb-8a0f-7441d6d343f5.png) Add support for React Native #21
> 
> React Native has become a common framework for building cross platform apps and the support statement around the use of the Intune SDK for that has been the above for the last 1-2 years. Is there any update to this or plans to have a sample built around this use case?

Facing the same issue.
Were you able to integrate intune sdk for react native app?

**Comment by ansarikhurshid786** [comment]
I am looking for the same. anyone know
