### ISSUE TITLE
Add prebuilt binary Carthage support

### ISSUE THREAD

**Issue by erikkerber** [msintuneappsdk/ms-intune-app-sdk-ios#184]
**Describe the bug:**

Carthage works well with closed-source SDKs distributed via GitHub, though to work zipped versions of the product need to be added to the releases page:

https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-zip-files

**To Reproduce**
1. Add ms-intune to a Cartfile (`github "msintuneappsdk/ms-intune-app-sdk-ios" "14.1.0"`)
2. Carthage update/bootstrap
3. Receive error 

```
Dependency "ms-intune-app-sdk-ios" has no shared framework schemes for any of the platforms: iOS
```

The error is a bit misleading, because the SDK can be resolved with archives as linked to above.

**Expected behavior:**

Carthage pulls work as expected

An example repo distributing closed source binaries: https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.10.2

**Screenshots and logs:**

```bash
carthage update --platform iOS  ms-intune-app-sdk-ios
*** Checking out ms-intune-app-sdk-ios at "14.1.0"
*** xcodebuild output can be found in /var/folders/1t/qcb43kwd2695x8gysb2j1wn40000gn/T/carthage-xcodebuild.olcZ6Z.log
*** Skipped building ms-intune-app-sdk-ios due to the error:
Dependency "ms-intune-app-sdk-ios" has no shared framework schemes for any of the platforms: iOS
```

**Comment by abasore** [comment]
Hi @erikkerber, thanks for the detailed info on supporting Carthage for prebuilt Intune MAM frameworks. As of right now, we are not yet planning on adding zipped versions to our public release. However, this may be supported in the future since it would require minimal work on our end.
