### ISSUE TITLE
Send Data to Managed Apps policy: blocks App's authentication flow

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#185]
**Describe the bug:**
Our application uses `ASWebAuthenticationSession` for authentication with our backend. There is callback url scheme(deep link) to launch the app after authentication.
I configured intune protections policy:
**Send data to other apps: : Policy managed apps**

After successful authentication, `ASWebAuthenticationSession` is not able  to launch our app (not able to handle deep link to the app) and failing with below error:

**To Reproduce**
- Configured Intune protections policy: **Send data to other apps: : Policy managed apps**
- After successful enrollment, try to authenticate with our backend server

**Expected behavior:**
As we are not sending data to other apps, so applying this policy should allow launching url scheme to our app from `ASWebAuthenticationSession`

**Screenshots and logs:**
```
[default] Failed to open URL {app-id}-intunemam://{app-url}com.microsoft.intune.mam.appmdmmgtstate=0&com.microsoft.intune.mam.policysource=2&com.microsoft.intune.mam.identity=Parveen%2EBhatia%40itregappian%2Eonmicrosoft%2Ecom&com.microsoft.intune.mam.policy=1&com.microsoft.intune.mam.identity.oid=9bd6bcff%2D09f0%2D4770%2D8242%2D509fd5d32e37: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=229, _LSFunction=-[_LSDOpenClient openURL:options:completionHandler:]}
2021-07-19 13:56:02.200239-0400 appian-app[68211:7172555] -canOpenURL: failed for URL: "{app-id}-intunemam://{app-url}?com.microsoft.intune.mam.appmdmmgtstate=0&com.microsoft.intune.mam.policysource=2&com.microsoft.intune.mam.identity=Parveen%2EBhatia%40itregappian%2Eonmicrosoft%2Ecom&com.microsoft.intune.mam.policy=1&com.microsoft.intune.mam.identity.oid=9bd6bcff%2D09f0%2D4770%2D8242%2D509fd5d32e37" - error: "This app is not allowed to query for scheme com.appian.tempo.dev-intunemam"
```
![SendData-ManagedApps](https://user-images.githubusercontent.com/35345044/126232524-14bc88d8-e190-4223-9a7c-4894e7445760.png)

**Smartphone (please complete the following information):**
- iPhone 8+ (iOS 14.6)

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK for iOS 14.5.0
- MSAL 1.1.17

**Comment by vigavadi** [comment]
Hello @parveen-bhatia. Can you try setting SafariViewControllerBlockedOverride to true under the IntuneMAMSettings dictionary in the application's Info.plist?
You can find more details about this setting here:  [App initiated authentication](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#special-considerations-when-using-msal-for-app-initiated-authentication)

**Comment by parveen-bhatia** [comment]
Thanks @vigavadi, it worked after this setting.

**Comment by vigavadi** [comment]
@parveen-bhatia Happy to know that it worked. Do reach out if you have any other questions.
