### ISSUE TITLE
Crash during picking documents using UIDocumentPickerViewController

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#187]
**Describe the bug:**
When intune data protection policy `Receive data from other apps: None` is configured. Then SDK automatically restrict picking documents using `UIDocumentPickerViewController` and displays appropriate alert. But app is getting crashed immediately after that. 
**Note:** Crash is not happening while picking files from camera, image gallery and SDK displays appropriate alert.

**To Reproduce**
1. Apply `Receive data from other apps: None`  data protection policy 
2. Enroll the app
3. Try to pick documents using `UIDocumentPickerViewController`
4. SDK displays alert that action is blocked and crashes immediately after that

**Screenshots and logs:**
- Crash Logs: [Crash.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/6864334/Crash.txt)

**Smartphone (please complete the following information):**
 - iPhone 8+ (iOS 14.6)

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK 14.6.0

**Comment by vigavadi** [comment]
Hey @parveen-bhatia, Thank you for reaching out. When you try to initialize `UIDocumentPickerViewController`, there is a possibility that it can return nil if the object cannot be successfully initialized. `Receive data from other apps: None` is one such scenario.  Could you try and handle this nil case and see if it still crashes?

**Comment by parveen-bhatia** [comment]
Yes, that was the cause `UIDocumentPickerViewController` return nil in that case. Thanks.
