### ISSUE TITLE
Crash while app is in background

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#188]
**Describe the bug:**
Complete enrollment with intune. After app restart alert, launch the app. Move the app in the background. Sometimes app crashes in the background.

**To Reproduce**
1. Configure some intune policies
2. Launch the intune app and complete enrollment with intune
3. After restart prompt, launch the app again and finish any policy prompts
4. Move the app to background

**Logs:**
- Crash Logs: [AppCrashInBackground.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/6864680/AppCrashInBackground.txt)

**Smartphone:**
 - iPhone 8+ (iOS 14.6)

**Intune App SDK for iOS:**
- Intune SDK 14.5.0

**Comment by vigavadi** [comment]
Hey @parveen-bhatia, I checked the crash logs and it doesn't seem to originate from the SDK.

**Comment by abasore** [comment]
@parveen-bhatia Does this crash only happen when the SDK being integrated? One thing to check is the value of 'MaxFileProtectionLevel' set in your IntuneMAMSettings as described [here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk). A crash could be caused be loss of access to protected files: "With the highest file protection level (NSFileProtectionComplete), protected files can only be accessed while the device is unlocked. Ten seconds after the device is locked, the app will lose access to protected files."

**Comment by abasore** [comment]
Hello @parveen-bhatia, were you able to verify if that the app crash was not originating from the SDK? One test would be to remove the SDK and see if the crash persists.

**Comment by vigavadi** [comment]
@parveen-bhatia Just checking if your were able to reproduce the crash?

**Comment by parveen-bhatia** [comment]
Not able to replicate this issue after that. However we are waiting little more to make sure it is fixed.

**Comment by parveen-bhatia** [comment]
Fine to close this. QE's verified it is fixed now. Thanks @abasore & @vigavadi
