### ISSUE TITLE
Function of UITextViewDelegate not called

### ISSUE THREAD

**Issue by ThomasLombard** [msintuneappsdk/ms-intune-app-sdk-ios#189]
**Describe the bug:**
To interact with UITextView, we use the `addAttribute` function on `NSMutableString` to create a link of type `{name_of_scheme}://{action}`
Once this link has been created we have a delegate method on `UITextView` which is called 
`func textView(_ textView: UITextView, shouldInteractWith URL: URL, in characterRange: NSRange) -> Bool` that allow us to catch the link and create the action on our side to redirect the user to a new `UIViewController`
Unfortunately method seems to be block by the SDK because it works on our version without Intune but never gets called with Intune sdk

**To Reproduce**
1. Add a TextView to a UIViewController
2. Create a NSMutableString and add an attribute of type link with url of type `{scheme}://{action}`
3. Have your ViewController conform to UITextViewDelegate
4. `func textView(_ textView: UITextView, shouldInteractWith URL: URL, in characterRange: NSRange) -> Bool` is never call when tapping on link

**Expected behavior:**
Does this called is block on purpose ? We don't have any policy on `Restrict web content transfer with other apps` in our configuration but maybe I'm missing something
It's important for us to have those interaction because it's the only way to interact with `UITextView`

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: iOS 13.5.1

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK version: 14.6
- Native platform

**Comment by neiljac1** [comment]
Hi @ThomasLombard. Please try using the following delegate instead:

func textView(_ textView: UITextView,  shouldInteractWith URL: URL, in characterRange: NSRange, interaction: UITextItemInteraction) -> Bool

Thank you,
Neil

**Comment by ThomasLombard** [comment]
Hi @neiljac1 
Thanks a lot for the quick response, it works fine now 👍

**Comment by neiljac1** [comment]
Great.

**Comment by abasore** [comment]
Closing this issue based on the resolution.
