### ISSUE TITLE
App data (local storage) is cleared after killing the wrapped app

### ISSUE THREAD

**Issue by zalaris** [msintuneappsdk/ms-intune-app-sdk-ios#19]
Hey,
We have Cordova app wrapped using Intune wrapper tool. Everything works fine except it wipes local storage of the app after you kill it for the first time. When you run it for the second time and then save some data, the data stays untouched event if you kill the app again. I noticed that wrapping tool set MAMPolicyRequired property to YES in Info.plist. It is written in the Intune SDK guides that in this case the app is not restarted after MAM policy is fetched. If we manually set that property to NO then it restarts the app after successful authentication and all app data stays in local storage even after the app is manually killed.

Is it designed like that to wipe the app data after killing the app? Why it's not triggering restart automatically?

Thanks!

**Comment by Kyle-Reis** [comment]
Hey @Zalaris, I saw that you filed [this issue](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/13) for the same problem in our wrapper repository. As such I'm going to request that this issue be closed. I'll be investigating and following up in that issue.

**Comment by zalaris** [comment]
That's OK. 
Thanks!
