### ISSUE TITLE
iOS wrapper + MSAL

### ISSUE THREAD

**Issue by alloza95** [msintuneappsdk/ms-intune-app-sdk-ios#190]
**Describe the bug:**
When trying to log into our iOS application (Intune wrapped with —aa —ar —ac flags + MSAL) We get a MSALErrorDomain = -50000 after introducing our credentials.
By analysing intune logs, we can also find -50002 and -51115 errors.
We couldn’t find any useful information regarding those errors either in the official documentation or other sources.
This error only appears when wrapping our app with the previously mentioned flags. MSAL on its own works well.

**Comment by neiljac1** [comment]
Hi @alloza95. Both of those errors correspond to MSALErrorInteractionRequired which means an interactive authentication is required. i.e. the user has to enter their credentials to acquire a token as acquiring a token silently is not possible. 

Can you supply more details about the issue? Is the Intune SDK able to acquire a token and apply policy? Do these errors occur after that when your application tries to silently acquire a token for itself?

Thanks,
Neil

**Comment by alloza95** [comment]
Hi @neiljac1! We solved this errors yesterday, adding this in the app's manifest on Azure AD:
```json
"tags": [
    "AppCompliantCapable"
],
```

But now, when we "sign in" using the "acquire token interactive" to the app, we get the error code `unauthorized_client` and the error message `AADSTS53005: Application needs to enforce Intune protection policies.`

Note: In our Conditional Access on Azure AD we have a policy that requires "approved client app" and "app protection policy" for Grant access.

**Comment by neiljac1** [comment]
Hi @alloza95. App protection CA policies aren't supported with the wrapper tool. You will need to integrate with the SDK instead. Your application will need to call specific APIs to complete the CA flow. Please see the following documentation on the integration steps: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#app-protection-ca-support-optional

Thank you,
Neil
