### ISSUE TITLE
Sample code for 'Copy To' action extension?

### ISSUE THREAD

**Issue by fastharper** [msintuneappsdk/ms-intune-app-sdk-ios#198]
**Describe the bug:**
We tried implementing the instructions for the "Copy To" action extension but it didn't work. Can you make available a Swift or Obj-C sample app that implements this? 

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by abasore** [comment]
Hi @fastharper, were [these](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#copy-to-actions?) the instructions were you following. At the moment, I our sample apps don't have this demonstrated. Are there particular steps in the instructions that are blocking you?

**Comment by fastharper** [comment]
right, those are the instructions we followed. but it didn't work, and there was no clue as to what our mistake was. hence a sample app/project would be helpful.

**Comment by abasore** [comment]
@fastharper Yes definitely, I agree that adding that to our test apps would be helpful. At the moment we are not planning on adding this. Is there any step in particular that didn't work for your project?

**Comment by abasore** [comment]
Closing this for now. Feel free to open again if there are specific steps that are causing issues.
