### ISSUE TITLE
Intune ios SDK 9.0.5 - Intune MAM service Enrollment status Debug Message: An unknown status code 302 was received.

### ISSUE THREAD

**Issue by kiara544** [msintuneappsdk/ms-intune-app-sdk-ios#20]
My app uses Intune and ADAL SDK's. I am ADAL sdk version 2.7.5 and recently updated the intune sdk to 9.0.5 from 8.1.1.
When i had 8.1.1 sdk in my code Enrollmemnt status of Intune MAM Service in logs was - 
Debug Message: New MAM policies were received and applied to the application with status code 100. 

After Upgrading Intune SDK to 9.0.5 Enrollmemnt status of Intune MAM Service in logs is -
Debug Message: An unknown status code was received with status code 302.

App works fine without any issues but i am curious to know why Enrollment status changed.

**Comment by Kyle-Reis** [comment]
Hey @kiara544, this is a known issue which we are tracking. The 302 status code is meant to be an internal status code that we can recover from and shouldn't bubble up to the app. You can ignore this code (treat it as success).
