### ISSUE TITLE
App Protection Policy to Restrict cut, copy, and paste between other apps not working for TextFields

### ISSUE THREAD

**Issue by MelvinJohnBipsync** [msintuneappsdk/ms-intune-app-sdk-ios#208]
**Describe the bug:**
Our app is a note-taking app and we have WKWebViews to type up notes, UISearchBar to search for notes, and many other input fields such as UITextFields. 
 
With the App Protection Policy for `Restrict cut, copy, and paste between other apps` set to `Policy managed apps with paste in `  the app restricts pasting to TextFields such as UISearchBar and UITextView i.e when copying a text from our app and pasting the copied text in a text field such as UISearchBar or UITextView in the same app, the phrase `Your organization's data cannot be pasted here.` is pasted rather than the copied text. This however is not the case if one copies text from a WKWebview and paste it in the same WKWebview of the same app (the copied text is pasted).

**To Reproduce**
1. Have the app be managed by Intune with App Protection Policy for `Restrict cut, copy, and paste between other apps` set to `Policy managed apps with paste in `
2. Copy text from the managed app (WKWebview, Textfields, etc.)
3. Paste the copied text to UISearchBar or UITextField
4. Notice the phrase `Your organization's data cannot be pasted here.` is pasted rather than the copied text

**Expected behavior:**
With the App Protection Policy for `Restrict cut, copy, and paste between other apps` set to `Policy managed apps with paste in ` or any other policies, If one copies text from an app and paste it anywhere in the same app then the copied text should be pasted rather than `Your organization's data cannot be pasted here.`

**Screenshots and logs:**
https://user-images.githubusercontent.com/92740855/137887396-a8a6ee6c-4472-46f3-b233-57d81abaebe9.mp4

**Smartphone (please complete the following information):**
 - Device: Any iOS Device, Specifically iPad
 - OS: iOS Version 13.0 and Higher

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? 14.7.1
- Are you using the latest version? YES
- What platform is your app based in (native, Xamarin based, Cordova, etc)? NATIVE
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A

- Who is the customer? Bipsync
- Do you see a trend with it only being reproduced on a specific device? Reproducible on all Devices, Specifically iPad

**Additional context:**

**Comment by chadseippel** [comment]
@MelvinJohnBipsync Thanks for reaching out. Just to confirm, are you able to copy + paste without the use of WKWebViews? For example, copy from a UITextField and successfully paste into the same or another UITextField.

Also can you confirm if your app is single identity or multi-identity? (See: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#turn-on-multi-identity)

**Comment by MelvinJohnBipsync** [comment]
Hey @chadseippel any update on this? Our clients are still experiencing this issue.

**Comment by Mohamed-Raffi** [comment]
Hi @MelvinJohnBipsync Any update on this ? 
We are also facing the same issue.
Not able to restrict cut, copy, and paste in UISearchBar.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
