### ISSUE TITLE
Enrollment fails with "The operation could not be completed because the user is not licensed for MAM"

### ISSUE THREAD

**Issue by dtatcbrain** [msintuneappsdk/ms-intune-app-sdk-ios#210]
**Describe the bug:**
We get the error "The operation could not be completed because the user is not licensed for MAM" in the enrollmentRequestWithStatus callback after calling registerAndEnrollAccount. Prior to that, we log in with MSAL with the same account.

**To Reproduce**
1. Log in using MSAL through MSALPublicClientApplication.acquireTokenWithParameters
2. Call IntuneMAMEnrollmentManager.registerAndEnrollAccount

**Expected behavior:**
We expected the app to be enrolled

**Screenshots and logs:**
 I have attached a log exported from the Intune Diagnostics console (verbose logging enabled). There are probably several attempts in the log; the most recent enrollment attempt is around the timestamp 2021-10-27T11:05:17.159Z.

[IntuneMAMDiagnosticFiles 10.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/7425634/IntuneMAMDiagnosticFiles.10.txt)

**Smartphone:**
 - Device: iPhone XR, iPad Pro 9.7-inch
 - OS: iOS 15.1

**Intune App SDK for iOS:**
MSAL version 1.1.22, Intune SDK version 15.0.0
Native iOS app. We have the Cordova SDK included but it's a native Xcode project.

**Additional context:**
We have already looked at the suggestions in issues 51 and [52](https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App/issues/52) for the Chatr sample app which mention the same error message. We have
- enrolled the device
- checked that the user does have an Intune license
- set up policies for the app
- checked that the callback is for the expected user account
- reset the device to ensure we're not getting cached credentials for another account
- tried setting NSUserDefaults boolean IntuneAutoUnenrollEnabled before enrolling

but the error persists and the app is not enrolled.

We are logging in to the same Azure AD that the app is registered in.

**Comment by dtatcbrain** [comment]
Turns out this was because we hadn't assigned a security group to the Intune policy we had set up for the app, so no users had the policy assigned. I guess the error message was a bit off, but otherwise this was not an issue with our code or the SDK, but a matter of configuration in Endpoint Manager.

**Comment by gastaffo** [comment]
Thanks for updating the thread @dtatcbrain. Sorry for not responding to you earlier. If you have any other problems feel free to contact us again. Are you ok with us closing the issue?

**Comment by dtatcbrain** [comment]
No worries, I imagine the cause wasn't obvious from looking at the logs. Closing is fine :)
