### ISSUE TITLE
Intune Pin required screen is displayed to logged out users

### ISSUE THREAD

**Issue by philipsawyer** [msintuneappsdk/ms-intune-app-sdk-ios#213]
**Describe the bug:**
Intune Pin screen will display when a logged out user reenters the app after the Pin timeout time has occurred. 

**To Reproduce**
1. Navigate to 'Apps>>Apps Protection' Policy under Intune Portal.
2. Tap on ‘Properties’ and then tap on ‘Edit’ button beside ‘Access requirements’ property.
3. Select ‘Required’ option under ‘PIN for access’ and set 'Timeout(minutes of inactivity)' as '1'.
4. Launch app and login
5. Notice that Intune login screen gets displayed with pre-filled username
6. Enter the correct password and notice that 'To access your organization's data with this app, enter your pin' screen gets displayed.
7. Set the pin and then log-out. Now, Background the app.
8. Wait for 1 minute without performing any activity on the app.
9. Reopen the app and observe that 'Pin require' screen gets displayed on accessing the app in logout state, which is incorrect.

**Expected behavior:**
The Pin screen should not be displayed to a logged out user. 

**Smartphone (please complete the following information):**
- iPhone SE 14.3
- iPad Pro 15.0

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Using Intune SDK 14.7.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors post build, does the app launch without being Intune SDK integrated? Yes

- Who is the customer? Box Inc.
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**
We are experiencing this issue using Intune SDK 14.7.1 and the MSAL library (https://github.com/AzureAD/microsoft-authentication-library-for-objc) 1.1.22.
When our users log out, we call `deRegisterAndUnenrollAccount(upn, withWipe: false)` for all accounts that `IntuneMAMEnrollmentManager.instance().registeredAccounts()` provides and for the `IntuneMAMEnrollmentManager.instance().enrolledAccount()` that is provided.

**Comment by abasore** [comment]
@philipsawyer Thanks for detailed bug report! The newest release (15.1.0) that was just updated today should have a fix for that issue. If you are able to upgrade and test, can you let me know if the update works for you?

**Comment by abasore** [comment]
Closing this issue for now. Feel free to reopen if you are still seeing the issue in 15.1.0
