### ISSUE TITLE
'IntuneMAMCertificatePinningManager.h' file not found

### ISSUE THREAD

**Issue by philipsawyer** [msintuneappsdk/ms-intune-app-sdk-ios#216]
**Describe the bug:**
Linking against `libIntuneMAMSwiftFileProvider.xcframework` inside a File Provider extension fails to compile because it cannot find the `IntuneMAMCertificatePinningManager.h` which is included in `IntuneMAM.h`. This happens whether the app is being compiled against a device or simulator. 

Note: In the `IntuneMAMSwift.xcframework` the same `IntuneMAMCertificatePinningManager.h` is included in the `IntuneMAM.h` file and the actual `IntuneMAMCertificatePinningManager.h` file is located alongside the other headers as well.

**Expected behavior:**
The `libIntuneMAMSwiftFileProvider.xcframework` framework shouldn't cause the build to fail. 

**Screenshots and logs:**
<img width="1453" alt="intune-compile-failure" src="https://user-images.githubusercontent.com/5931196/141700216-5039578b-54ce-4aba-8c2b-424566e4a09b.png">

**Smartphone (please complete the following information):**
- Compile against simulator or device causes the same issue

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Intune 14.7.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? iOS
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? NA

- Who is the customer? Box Inc.
- Do you see a trend with it only being reproduced on a specific device? No

**Comment by gastaffo** [comment]
@philipsawyer That header should be included there, thanks for notifying us. We are working releasing a fix that will include the header there that should be out soon.

Until then if you need an immediate workaround copying the header from the `IntuneMAMSwift` framework should work, also deleting the import line from `IntuneMAM.h` if you don't need any of the APIs in `IntuneMAMCertificatePinningManager.h`

**Comment by gastaffo** [comment]
@philipsawyer If I may ask, what is your reason for choosing the static library over the framework?

**Comment by philipsawyer** [comment]
@gastaffo We are using the static library in our file provider extension in order to stay below the memory limits that extensions have placed on them. 
We use the regular framework in our main app.

**Comment by gastaffo** [comment]
@philipsawyer SDK versoin 15.1.4+ should have `IntuneMAMCertificatePinningManager.h` included now.

**Comment by philipsawyer** [comment]
Great, thank you!
