### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by sdevansh96** [msintuneappsdk/ms-intune-app-sdk-ios#218]
How to integrate intune sdk for React Native Apps?

**Comment by gastaffo** [comment]
@sdevansh96 Hey so we don't officially support React native, however it should work fine if you  integrating like you would any other native iOS framework. You could also try our App Wrapping tool which will take a finished IPA and then will inject the SDK into it. https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios

**Comment by goldena** [comment]
Hello,
Are there any updates on the integration with React Native as of June 2023?
Thanks!

**Comment by gastaffo** [comment]
Hi,
We still don't officially support React native, but it is possible for the SDK to still work within a React app. You would need to integrate it like other native iOS frameworks in your app or use our App Wrapping tool.

**Comment by maherhanafi-bw** [comment]
@gastaffo We have a similar scenario as our mobile application is a React Native one and we support Azure SSO as a way of login.
I know that the App Wrapping Tool has a limited set of features, but I couldn't find documentation to confirm that Single Sign-On is supported when using the App Wrapping Tool.
Any answer and/or recommendation is much appreciated.
Thanks

**Comment by gastaffo** [comment]
@maherhanafi-bw Sorry for the very long delay. Are y'all using the same AAD client id for all of your apps?

**Comment by gastaffo** [comment]
React-Native support has not been planned as of yet. Also to clarify this repo is for the Intune MAM SDK for iOS. For android the repo is here https://github.com/microsoftconnect/ms-intune-app-sdk-android
