### ISSUE TITLE
Intune-protected app can't share with Word

### ISSUE THREAD

**Issue by fastharper** [msintuneappsdk/ms-intune-app-sdk-ios#22]
Once the app is authenticated, we protect a file with IntuneMAMFileProtectionManager and then invoke the iOS UIActivityViewController.

With the Intune Data Protection Policy "Allow app to transfer data to other apps"

1. Policy Managed Apps. We see Copy to Word. We do not see the action extension Open In Word.
2. Policy Managed Apps with OS Sharing. We see no options at all. Not Copy to Word, not Open In Word.
3. Policy Managed Apps with Open-In/Share Filtering. We see no options at all. Not Copy to Word, not Open In Word.

Am I doing something wrong in code? Or what am I missing?

Our customers will expect our Intune-enabled app to be able to share with Word with all 3 of these settings.

**Comment by Kyle-Reis** [comment]
Hey @fastharper, a couple of questions:
1.)  What is the extension of the file you are attempting to share to Word? 
2.) What version of the SDK are you using?

**Comment by fastharper** [comment]
1. docx files
2. intune sdk 9.0.13

**Comment by Kyle-Reis** [comment]
Hey @fastharper, for scenario #2 in your list, were you testing on an MDM-enrolled device?

**Comment by Kyle-Reis** [comment]
Hey @fastharper, just checking in to see if you were able to resolve this before closing out this issue.

**Comment by Kyle-Reis** [comment]
Closing this issue out. Feel free to reopen if you're still experiencing this issue.
