### ISSUE TITLE
[iOS] How to get an access token after receiving the app protection policy in the IntuneSDK embedded self-made app?

### ISSUE THREAD

**Issue by auchan0164** [msintuneappsdk/ms-intune-app-sdk-ios#223]
I have set up Intune Conditional Access to require an app protection policy, and I'm trying to get an access token to the GraphAPI created by the AzureAD app from my homebrew app with the Intune SDK embedded, but it fails at the sign-in stage.

Please refer to the official page (https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#prerequisites
), I am calling MSAL authentication (acquireTokenInteractively()) and then calling the process to receive the app protection policy of IntuneSDK (registerAndEnrollAccount()). However, at the time of sign-in, it appears that you are trying to open this resource with a client app that cannot be used with the app protection policy. But at the time of sign-in, it appears that you are trying to open this resource with a client app that cannot be used with the app protection policy. The app you are using (Bundle ID) is included in the app protection policy.

Is there an error in the authentication process? Or is there something wrong with the security settings in Intune (or AzureAD)? Any advice would be greatly appreciated.

Error message
------------------------------------------
It appears that you are trying to open this resource with a client app that is not available with an app protection policy. please contact your IT department or see the list of protected applications here (https://docs.microsoft.com/en-us/azure/active- directory/conditional-access/concept-conditional-access-grant) for a list of protected applications.
------------------------------------------

Reference URL
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#prerequisites

The server side is configured as follows
<MSOffice365>.	
The sign-in user belongs to a security group.
You have an Intune license.
Multi-factor authentication is allowed.
	
<AzureAD	
Permissions Microsoft Graph Sites.Read.All is included
ReadWrite.All of Microsoft Graph is included
Read of Microsoft Graph is included.
All permissions include Microsoft Mobile Application Management's DeviceManagementManagedApps.ReadWrite.
	
<Intune>.	
Apps covered by the app protection policy contain self-created apps
The target group of the app protection policy includes the security group to which the user attempting to sign in belongs.
A device that attempts to sign in is registered.
An app that attempts to sign in is registered.
The app you registered has MAM SDK enabled Yes

The code to sign in and get an access token is shown below.

Sign-in branch process
```
           guard let currentAccount = account else {
                // We check to see if we have a current logged in account.
                // If we don't, then we need to sign someone in.
                
                let del = EnrollmentDelegateClass.init(viewController: self)
                IntuneMAMEnrollmentManager.instance().delegate = del
                IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)
                
                return
            }

            self.acquireTokenSilently(currentAccount)
            
            let currentUser = IntuneMAMEnrollmentManager.instance().enrolledAccount()
        
            if nil == currentUser || !currentUser!.isEmpty {
               let del = EnrollmentDelegateClass.init(viewController: self)
               IntuneMAMEnrollmentManager.instance().delegate = del
               IntuneMAMEnrollmentManager.instance().registerAndEnrollAccount(currentAccount.username!)
            }

        }
```

Sign-in & access token acquisition process
```
 func acquireTokenInteractively() {
        
        guard let applicationContext = self.applicationContext else { return }
        guard let webViewParameters = self.webViewParamaters else { return }
        
        let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
        parameters.promptType = .selectAccount

        applicationContext.acquireToken(with: parameters) { (result, error) in
            
            if let error = error {
                
                self.updateLogging(text: "Could not acquire token: \(error)")
                return
            }
            
            guard let result = result else {
                
                self.updateLogging(text: "Could not acquire token: No result returned")
                return
            }
            self.updateCurrentAccount(account: result.account)
            self.getContentWithToken()
            
            self.accessToken = result.accessToken

            do{
                switch self.methodText.text {
                    case "GET":
                        self.getHttp()
                    case "POST":
                        try self.postHttp()
                    case "PATCH":
                        try self.patchHttp()
                    case "DELETE":
                        self.deleteHttp()
                    case "PUT":
                        try self.putPicHttp()
                default:
                    break
                }

            }catch{
                self.updateLogging(text: "error")
            }
        }
    }
    
    
    
    func acquireTokenSilently(_ account : MSALAccount!) {
        
        guard let applicationContext = self.applicationContext else { return }
        
        /**
         
         Acquire a token for an existing account silently
         
         - forScopes:           Permissions you want included in the access token received
         in the result in the completionBlock. Not all scopes are
         guaranteed to be included in the access token returned.
         - account:             An account object that we retrieved from the application object before that the
         authentication flow will be locked down to.
         - completionBlock:     The completion block that will be called when the authentication
         flow completes, or encounters an error.
         */
        
        var requestError: NSError? = nil

        
        let parameters = MSALSilentTokenParameters(scopes: kScopes, account: account)
        
        applicationContext.acquireTokenSilent(with: parameters) { (result, error) in
            
            if let error = error {
                
                let nsError = error as NSError
                
                // interactionRequired means we need to ask the user to sign-in. This usually happens
                // when the user's Refresh Token is expired or if the user has changed their password
                // among other possible reasons.
                
                if (nsError.domain == MSALErrorDomain) {
                    
                    if (nsError.code == MSALError.interactionRequired.rawValue) {
                        
                        DispatchQueue.main.async {
                            self.acquireTokenInteractively()
                        }
                        return
                    }
                }
                
                self.updateLogging(text: "Could not acquire token silently: \(error)")
                return
            }
            
            guard let result = result else {
                
                self.updateLogging(text: "Could not acquire token: No result returned")
                return
            }
            
            self.accessToken = result.accessToken
            self.updateLogging(text: "Refreshed Access token is \(self.accessToken)")
            do{
                switch self.methodText.text {
                    case "GET":
                        self.getHttp()
                    case "POST":
                        try self.postHttp()
                    case "PATCH":
                        try self.patchHttp()
                    case "DELETE":
                        self.deleteHttp()
                    case "PUT":
                    try self.putPicHttp()
                default:
                    break
                }
            }catch{
                self.updateLogging(text: "error")
            }

            self.updateSignOutButton(enabled: true)
            self.getContentWithToken()
        }
    }
```

**Comment by auchan0164** [comment]
ty @vigavadi

When I added "msalConfiguration.clientApplicationCapabilities = ["ProtApp"]" to the code and executed it, the following error message was returned.

`Could not acquire token: Error Domain=MSALErrorDomain Code=-50004 "(null)" UserInfo={MSALCorrelationIDKey=7D88A53C-BDAB-4EBA-AEBF-76666AC084AE, MSALOAuthErrorKey=unauthorized_client, MSALBrokerVersionKey=6.5.87, MSALHomeAccountIdKey=e8cf6060-5426-46b5-aa98-f86f7d0e8767.058df8c3-05b8-4dec-ac4e-0997b89017d5, MSALErrorDescriptionKey=AADSTS53005: Application needs to enforce Intune protection policies. Trace ID: 81799e44-f565-4f4d-9576-b4a95718e402 Correlation ID: 7d88a53c-bdab-4eba-aebf-76666ac084ae Timestamp: 2022-01-12 23:50:46Z, MSALOAuthSubErrorKey=protection_policy_required, MSALDisplayableUserIdKey=***@***.onmicrosoft.com`

https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#app-protection-ca-support-optional
App Protection CA support (optional)
and added the IntuneMAMComplianceDelegate class, and used the swift code as is
`func identity(_ identity: String, hasComplianceStatus status: IntuneMAMComplianceStatus, withErrorMessage errMsg: String, andErrorTitle errTitle: String) {
        switch status {
        case .compliant:
           //Handle successful compliance
        case .notCompliant, .networkFailure,.serviceFailure,.userCancelled:
            DispatchQueue.main.async {
              let alert = UIAlertController(title: errTitle, message: errMsg, preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { action in
                    exit(0)
                })) 
                self.present(alert, animated: true, completion: nil) 
            }
        case .interactionRequired:
            IntuneMAMComplianceManager.instance().remediateCompliance(forIdentity: identity, silent: false)
   }`

The error message says "You need to apply the Intune protection policy in your application", but if you wait a moment, you will see the message that the application protection policy is being received as shown in the attached image.
![iOS の画像](https://user-images.githubusercontent.com/96554541/149265114-760af224-0564-4a64-a96c-127b5b50770b.png)
After this, when I try to get the access token again, I get the error message "You need to apply Intune's protection policy on your application" again.

Does this mean that I am not receiving the application protection policy correctly? If so, can you please tell me the correct process for receiving it?

**Comment by vigavadi** [comment]
@auchan0164 It looks like you are missing the call to remediateCompliance as mentioned here: [MAM-CA APIs](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#new-apis)

Here's the complete flow:
1. App requests token for MAM-CA enabled resource
2. MSAL will send back "_App protection required_" error
3. On receiving this error, the app should call remediateCompliance within MAM SDK
`IntuneMAMComplianceManager.instance().remediateCompliance(forIdentity: identity, silent: false)`
4. After the SDK successfully remediates, it will send back the status in hasCompliance delegate method that you have already implemented.
5.  On receiving _compliant_ status in the delegate, the app can now make the token request again.

Also, you should be setting the IntuneMAMComplianceDelegate in willFinishLaunchingWithOptions AppDelegate method.

**Comment by auchan0164** [comment]
Thanks for the answer! @vigavadi 

I guess I did not read the documentation carefully.
I've added the code to handle it as per the flow you provided.

AppDelegate
`func identity(_ identity: String, hasComplianceStatus status: IntuneMAMComplianceStatus, withErrorMessage errMsg: String, andErrorTitle errTitle: String, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) {
       switch status {       
       case .compliant:           
       // Need to acquire token but don't know how to acquire here because I receive Azure configurations like clientId, redirect URI from backend server.           
       	ViewController().updateLogging(text: "success")           
       	ViewController().acquireTokenInteractively()          
       //Handle successful compliance       
       case .notCompliant, .networkFailure,.serviceFailure,.userCancelled:           
       	ViewController().updateLogging(text: "failure")       
       case .interactionRequired:           
       	IntuneMAMComplianceManager.instance().remediateCompliance(forIdentity: identity, silent: false)       
       		}    
       }`

ViewController
`func acquireTokenInteractively() {
                guard let applicationContext = self.applicationContext else { return }       
				guard let webViewParameters = self.webViewParamaters else { return }                
 		       let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)        
				parameters.promptType = .selectAccount        
				//parameters.claimsRequest = request
                applicationContext.acquireToken(with: parameters) { (result, error) in 
                       if let error = error {                
					print("\(error)")                
					if error._domain == MSALErrorDomain, let errorCode = MSALError(rawValue: error._code) {
                    switch errorCode {                    
					case .interactionRequired:                        
					// Interactive auth will be required                        
						self.updateLogging(text: "Could not acquire token: \(error)")                    
					case .serverDeclinedScopes: print("Failed with error \(error)");                        
						self.updateLogging(text: "Could not acquire token: \(error)")                    
					case .serverProtectionPoliciesRequired:                                                
						self.updateLogging(text: "Failed with error \(error)")                        
					if let info = error._userInfo as? AnyObject {
					if let userId = info[MSALDisplayableUserIdKey] as? String {
					 IntuneMAMComplianceManager.instance().remediateCompliance(forIdentity: userId, silent: false) 
					 	}
					 }
					 case .userCanceled:                       
					 	self.updateLogging(text: "Could not acquire token: \(error)")                    
					 case .internal:                                              
						 print("Failed with error \(error)");                        
						 self.updateLogging(text: "Could not acquire token: \(error)")                    
					 default:                        
					 	self.updateLogging(text: "Failed with unknown MSAL error \(error)")                    
					 		}                                    
					 	}                
					 	return            
					 }   
				 	guard let result = result else { 
					self.updateLogging(text: "Could not acquire token: No result returned")
					 
					return           
					 }
					 //IntuneMAMEnrollmentManager.instance().registerAndEnrollAccount(result.account.username!)
					 self.updateCurrentAccount(account: result.account)            
					 self.getContentWithToken()                        
					 self.accessToken = result.accessToken
					  //self.updateLogging(text: "Access token is \(self.accessToken)")            
					 do{                
					 switch self.methodText.text {                    
					 case "GET":                        
					 	self.getHttp()                    
					 case "POST":                        
					 	try self.postHttp()                    
					 case "PATCH":                        
					 	try self.patchHttp()                    
					 case "DELETE":                       
						 self.deleteHttp()                    
					case "PUT":                        
						try self.putPicHttp()                
					default:                    
						break                
						}
            }catch{                
			self.updateLogging(text: "error")            
		}        
	}    
}`

The following error message was returned after executing the access token acquisition process. As shown in the attached image, I think that IntuneMAMComplianceManager.instance().immediateCompliance() is being executed. If this is the case, does this mean that the problem is on the server side?

`Failed with error Error Domain=MSALErrorDomain Code=-50004 "(null)" UserInfo={MSALCorrelationIDKey=D10B936C-263F-4498-8A07-F585977F09B1, MSALOAuthErrorKey=unauthorized_client, MSALBrokerVersionKey=6.5.87, MSALHomeAccountIdKey=e8cf6060-5426-46b5-aa98-f86f7d0e8767.058df8c3-05b8-4dec-ac4e-0997b89017d5, MSALErrorDescriptionKey=AADSTS53005: Application needs to enforce Intune protection policies. Trace ID: f268f747-4d11-424c-9da6-4aa047942100 Correlation ID: d10b936c-263f-4498-8a07-f585977f09b1 Timestamp: 2022-01-13 19:40:23Z, MSALOAuthSubErrorKey=protection_policy_required, MSALDisplayableUserIdKey=kouki_Morita@syakaijpbs.onmicrosoft.com}`
![iOS の画像](https://user-images.githubusercontent.com/96554541/149398680-92a6cd43-fe50-4561-86b0-4353e934cbf8.png)

**Comment by vigavadi** [comment]
Hey @auchan0164, 

You can have a separate class  conforming to IntuneMAMComplianceDelegate which implements the hasComplianceStatus method.

```
class ComplianceDelegateClass: NSObject, IntuneMAMComplianceDelegate {
func identity(_ identity: String, hasComplianceStatus status: IntuneMAMComplianceStatus, withErrorMessage errMsg: String, andErrorTitle errTitle: String) {
        switch status {
        case .compliant:
           //Handle successful compliance
        case .notCompliant, .networkFailure,.serviceFailure,.userCancelled:
            DispatchQueue.main.async {
              let alert = UIAlertController(title: errTitle, message: errMsg, preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { action in
                    exit(0)
                })) 
                self.present(alert, animated: true, completion: nil) 
            }
        case .interactionRequired:
            IntuneMAMComplianceManager.instance().remediateCompliance(forIdentity: identity, silent: false)
   }
}
```
And the you can set the compliance delegate like this in the AppDelegate

```
func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        IntuneMAMComplianceManager.instance().delegate = self.complianceDelegate
        return true
    }
```
Let me know if this works!

**Comment by auchan0164** [comment]
hi @vigavadi 

As it turns out, it did not work.

I'm not very familiar with Swift, so maybe I don't understand it well enough.

I created a ComplianceDelegateClass that inherits from IntuneMAMComplianceDelegate, and implemented the willFinishLaunchingWithOptions method in AppDelegate.

However, "ComplianceDelegateClass" is a different class from AppDelegate, so "self" cannot be used, right?

Currently in AppDelegate, I have created the following methods and set the delegate, but I am getting the message "Instance will be immediately deallocated because property 'delegate' is 'weak'". I'm sorry if this is a newbie question, but I couldn't solve the problem by myself.
AppDelegate.swift
`func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        IntuneMAMComplianceManager.instance().delegate = complianceDelegate()
        return true
    }`

**Comment by vigavadi** [comment]
@auchan0164 You can initialize it in the AppDelegate class as 
`let complianceDelegate = ComplianceDelegateClass.init()`

And then you can use it as self.complianceDelegate 

```
func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        IntuneMAMComplianceManager.instance().delegate = self.complianceDelegate
        return true
    }
```

**Comment by auchan0164** [comment]
@vigavadi 

We received the app protection policy and were able to retrieve the access token from the Graph API.
Thank you so much for your help!

This is my first time using the issue, can I close it now?

**Comment by vigavadi** [comment]
@auchan0164 I'm glad it worked. I'll close this one now.
