### ISSUE TITLE
Build error - While building for Mac Catalyst, no library for this platform was found in 'ios/ms-intune-app-sdk-ios/IntuneMAMSwift.xcframework'

### ISSUE THREAD

**Issue by mobilesavvy** [msintuneappsdk/ms-intune-app-sdk-ios#224]
**Describe the bug:**
Hi Im trying to compile my project after a while and seeing this compile error. Nothing was changed meanwhile.

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - 14.3.5
- What platform is your app based in (native, Xamarin based, Cordova, etc)? - Cordova
- For errors during build, does the app build without Intune SDK integration? - Yes
- For errors post build, does the app launch without being Intune SDK integrated? 

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

Mac OS - BigSur
Xcode-12.5
Command - xcodebuild -workspace Plugin.xcworkspace -scheme Plugin

**Comment by abasore** [comment]
@mobilesavvy are you able to test with the latest 15.3.0 version?
