### ISSUE TITLE
Intune status in the `enrollmentRequest` will always return an error, if MSAL used.

### ISSUE THREAD

**Issue by pa-gaiki-ito** [msintuneappsdk/ms-intune-app-sdk-ios#225]
**Describe the bug:**
Hi ! I'm working on the migration from ADAL to MSAL in  iOS app.
However, only in the case of MSAL the status of the `enrollmentRequest` method is always returned as false.

https://www.higithub.com/msintuneappsdk/issue/intune-app-sdk-xamarin/52
It's very similar to this one.

**To Reproduce**
1. Replace SSO authentication library from ADAL to MSAL.
2. Make sure MSAL and Intune SDK are up to date.
3. Run.
4. called `IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(allowedAccountValue)` in the `application(_ application: UIApplication,willFinishLaunchingWithOptions ...` 
5. There are the following differences between ADAL and MSAL. 
```swift
// ADAL
func enrollmentRequest(with status: IntuneMAMEnrollmentStatus) {
     print("status.didSucceed") 
     // status code: 100
     // true: "New MAM policies were received and applied to the application."
}
```

```swift
// MSAL
func enrollmentRequest(with status: IntuneMAMEnrollmentStatus) {
     print("status.didSucceed") 
     // status code: 201
     // false: "There was an internal error in the Intune MAM SDK.  Please see the NSError object for more details."
}
```

**Expected behavior:**
- IntuneMAMEnrollmentStatus status is return  true by MSAL.

**Screenshots and logs:**
![スクリーンショット 2022-02-07 9 37 35](https://user-images.githubusercontent.com/78337576/152708768-6db20cda-c976-43d0-bf79-46203965bc13.png)

**Smartphone (please complete the following information):**
- Xcode: `13.2`
- MSAL: `1.1.24`

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
  - yes, using version -> `15.3.0`
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
  - iOS App (Deployment Target -> iOS13.0)
- For errors during build, does the app build without Intune SDK integration?
  - yes, can be built.

**Comment by neiljac1** [comment]
Hi @pa-gaiki-ito,

Can you try using MSAL 1.1.22 to see if it fixes your issue? There is a known compatibility issue in with Intune and MSAL 1.1.23+ which we will be fixing in an upcoming release.

Thank you,
Neil

**Comment by pa-gaiki-ito** [comment]
Hi @neiljac1 ,

Thank you for your reply.
I try it with version 1.1.22, 1.1.21 and 1.1.20  without success. The situation remains the same.

**Comment by neiljac1** [comment]
Hi @pa-gaiki-ito,

Can you send the Intune logs from your application to me at neiljac@microsoft.com?

Thanks,
Neil

**Comment by pa-gaiki-ito** [comment]
@neiljac1 
I sent you an email !
Thank you for your support.

**Comment by pa-gaiki-ito** [comment]
Hi, @neiljac1 

Thanks to your enthusiastic support, the problem is solved!

https://docs.microsoft.com/en-us/azure/active-directory/develop/redirect-uris-ios#msal-redirect-uri-format-requirements
> If you're migrating from ADAL, your redirect URI will likely have this format: <scheme>://[Your_Bundle_Id], where scheme is a unique string. This format will continue to work when you use MSAL.

In my case, since I was changing from ADAL, I used this setup as a reference.
However, in this case, it seems that Intune may not work correctly if it is embedded in an iOS application. I set `msauth.{bundleID}://auth` and added `redirectURI` and `ADALClientId` to IntuneMAMSettings in Info.plist, and the problem was solved.

This means that Intune will not function properly without the `msauth.{bundleID}://auth` setting.

**Comment by ensprit** [comment]
In Our application to create the custom plugin for MSAL, I updated the value in the plugin.xml 
```
<config-file target="*-Info.plist" parent="IntuneMAMSettings">
            <dict>
                <key>ADALClientId</key>
                <string>7904eb1c-2fd5-4301-8fae-4e15c75964c6</string>
                <key>ADALRedirectUri</key>
                <string>msauth.com.buildingrobotics.comfy://auth</string>
            </dict>
        </config-file>
```
[pa-gaiki-ito](https://github.com/pa-gaiki-ito) may where should I want correct the values in IntuneMAMSettings in Info.plist

**Comment by pa-gaiki-ito** [comment]
Hi @ensprit 

 In `info.plist` you will find a dictionary called `IntuneMAMSettings` if you have already created it. If not, you will need to create one.

- Also, in `PROJECT_NAME > Info > URLTypes > URL Shemes` , is `msauth.com.xxxx.xxxx` set?
- The same value must also be set in `info.plist > URL types > URLSchemes`.
