### ISSUE TITLE
Drag and drop sometimes calls the proper methods and sometimes does not

### ISSUE THREAD

**Issue by ryanbland** [msintuneappsdk/ms-intune-app-sdk-ios#229]
**Describe the bug:**
When doing a drag and drop into the app sometimes the correct methods are called and sometimes they are not, specifically we see the call to func tableView(_ tableView: UITableView, dropSessionDidEnter session: UIDropSession) is called but then the other calls to 
func tableView(_ tableView: UITableView, canHandle session: UIDropSession) -> Bool
func tableView(_ tableView: UITableView, dropSessionDidUpdate session: UIDropSession, withDestinationIndexPath destinationIndexPath: IndexPath?) -> UITableViewDropProposal 
func tableView(_ tableView: UITableView, performDropWith coordinator: UITableViewDropCoordinator) {

These functions are in a base class as an extension and are written is swift. 

**To Reproduce**
try to do a drag and drop with these methods in a base class. 

**Expected behavior:**
I expect all the methods to be called but right now only the dropSessionDidEnter and dropSessionDidEnd methods are called

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
iphone or ipad on latest os, with latest intune sdk

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 15.3
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native Swift

- Do you see a trend with it only being reproduced on a specific device? no any device

**Additional context:**

**Comment by ryanbland** [comment]
they are now set to allow all apps. However my account keeps getting an error on sign in stating that checking the policies took longer than the timeout (do you know how to fix this)?

Prior to my issue logging into intune from the app, I did go in and move them to the class rather than a parent and all but the func tableView(_ tableView: UITableView, performDropWith coordinator: UITableViewDropCoordinator), however the policy was set to managed apps at that time

**Comment by vigavadi** [comment]
@ryanbland Can you try a fresh install? Do you get this sign in issue every time?

**Comment by ryanbland** [comment]
I got the issue every time on the device, i delete the app and tried again, same issue, then removed intune from the device restarted it and installed it again and I still faced the same issue. On a different device i was able to login successfully, I know its not the original issue but do you have any clue as to why it would work on one device but not another?

**Comment by ryanbland** [comment]
also after doing a signout from the device that worked im now seeing the same error on that device, so now both my test devices will not work with intune

**Comment by vigavadi** [comment]
@ryanbland Maybe the enrollment fails due to some reason. Would you be able to share logs? You can send them to vigavadi@microsoft.com. 

Also, for the device where you could login successfully, were you able to check if the drop methods were being called with "Receiving data for other apps" set to "All apps" or trying to drag from a managed app if receiving is set to "Policy Managed apps"?

**Comment by vigavadi** [comment]
@ryanbland The CompanyPortal logs wouldn't contain any Intune SDK related info. Would you be able to implement 
`IntuneMAMDiagnosticConsole.display()`? 
That would bring up a diagnostic console that should allow you to share Intune logs.

**Comment by ryanbland** [comment]
ok so i did a login and it gave the failed due to timeout issue then i just let it sit, it gave that same login error again unprompted then gave the successful login prompt and restarted

**Comment by vigavadi** [comment]
Ah so enrollment would have been failing due to timeout. Are you able to get policies for both devices now?

**Comment by ryanbland** [comment]
so what is causing this timeout then? Ive never had this happen

**Comment by vigavadi** [comment]
That if the service takes longer than expected to return. Could be network related.

**Comment by ryanbland** [comment]
So Our customer confirmed to us that they have receive data set to All Apps, is there a reason that this would happen when that setting is set to all apps?

**Comment by ryanbland** [comment]
@vigavadi so the customer had the values set that you told me but still said the issue occurs, i was unable to reproduce within my intune environment. Is there any other settings that could cause that to happen?

**Comment by ryanbland** [comment]
is there any other reason for this to occur?

**Comment by vigavadi** [comment]
@ryanbland I apologize for the late response, I completely missed this. The only time you would run into this is if drop is blocked or if the app hasn't implemented the UITableViewDropDelegate methods. You mentioned that you weren't able to repro this. Is it possible to send logs from the customer? I could confirm if the policies are set correctly.
