### ISSUE TITLE
Non-UI Action extension - doesn't work

### ISSUE THREAD

**Issue by fastharper** [msintuneappsdk/ms-intune-app-sdk-ios#23]
I have followed the instructions to add a non-UI Action extension for our app, "Open in iManage".

However, it doesn't work. The instructions are literally like 1 paragraph, which is not enough for something of this complexity. And there is no sample app??!

iOS requires our app extension to declare NSExtensionPrincipalClass in the Info.plist, and this requires a Swift class (or Obj-C). I can confirm that our code in this class does in fact get called when we tap the "Open In iManage" action extension from Word.

But the Intune SDK documentation offers no guidance on how to implement this. In fact it says that the Intune SDK will handle it. But clearly it isn't.

What am I doing wrong? Am I missing something?

**Comment by Kyle-Reis** [comment]
Hey @fastharper, are you still having trouble getting the action extension set up?

**Comment by Kyle-Reis** [comment]
Hey @fastharper, just checking in again before closing out this issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still having issues here.

**Comment by JBenny25** [comment]
@Kyle-Reis We are having trouble setting up the extension as well. Can you please help with it?
How exactly is it linked with the SDK? Do we have any sample app for the same?
