### ISSUE TITLE
ADAL not registering error 201 - Missing Info.plist keys

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#230]
**Describe the bug:**
After upgrading to 15.3.2 a clean install results in an 201 error.
The weird thing, when I go back to the old SDK install the app > register, update to the latest SDK, it works!

**To Reproduce**
1. Update to sdk 15.3.2 from 15.3.0
2. Calling remediateComplianceForIdentity
3. Results in 201

**Expected behavior:**
Should register

**Smartphone (please complete the following information):**
- iOS 15.2.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
15.3.2
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
native, obj-c
- For errors post build, does the app launch without being Intune SDK integrated?
yes

- Who is the customer?
Company X
- Do you see a trend with it only being reproduced on a specific device?
Yes, on all devices

**Additional context:**
It could be that devices are using MSAL/ADAL as we migrated some versions ago. This seems to be introduced in the last version.
Error:
There was an internal error in the Intune MAM SDK.  Please see the NSError object for more details.
code	IntuneMAMEnrollmentStatusCode	IntuneMAMEnrollmentStatusInternalError
error	__NSMallocBlock__ *	domain: nil - code: 4371361344	0x0000000280d43840

The solution I found is to use ADAL again, I thought we should migrate to MSAL, Intune is currently unstable for production! We are using the Conditional Access Policy, this seems to get into trouble every time we try to use MSAL. In our production builds we are still using ADAL.

**Comment by tritter** [comment]
I found the reason, my ENV variables were not correctly written into the info.plist. ADAL seems to be ok with setting the clientID/authority in code. But MSAL *needs* the following variables (IntuneMAMSettings:ADALRedirectScheme | IntuneMAMSettings:ADALAuthority | IntuneMAMSettings:ADALClientId) inside the info.plist. Which doesn't make sense as we're actually using MSAL? So why isn't it MSALAuthority. It would be really nice if the error could be reflected somehow?

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
