### ISSUE TITLE
Getting Error on App Submission

### ISSUE THREAD

**Issue by dil-asagar** [msintuneappsdk/ms-intune-app-sdk-ios#234]
When we try to upload the iOS Build via Xcode or Transporter we get the following error:
`ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."`

We are using 15.4.0.
We were under the impression that this will not require a manual strip out the simulator architectures from the universal framework before you submit your app to the App Store.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 15.4.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?: native, Xcode 13.2.1
- For errors during build, does the app build without Intune SDK integration? Able to submit App without Intune SDK
- For errors post build, does the app launch without being Intune SDK integrated? N/a

**Comment by vigavadi** [comment]
Hey @dil-asagar, are you striping the simulator architecture from the binaries? You don't need to do that for IntuneMAMSwift.xcframework.

**Comment by dil-asagar** [comment]
@vigavadi : we are not anything specific... to strip out " simulator architecture". We realized the the "IntuneMAMSwift.xcframework" should do that automatically.

Our App Store Build when we are trying to Upload >> Apple is not accepting it & throwing that error.

**Comment by dil-asagar** [comment]
@vigavadi : we are using xcode 13.2.1  >> would be an issue?
Please let us know - any workaround.

**Comment by vigavadi** [comment]
@dil-asagar No that shouldn't be an issue. We checked the IntuneMAMSwift.framework and it seems to be fine. Do you have any scripts that you use that removes unused frameworks or modifies the binaries in any way before submitting to the App Store ?

**Comment by dil-asagar** [comment]
@vigavadi We have this existing script running for our other frameworks. 

`if [ "${CONFIGURATION}" = "Release" ]; then

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d ! -name 'BB*' | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done

fi
`

**Comment by vigavadi** [comment]
@dil-asagar Could you exclude IntuneMAMSwift and give it a try?

**Comment by dil-asagar** [comment]
@vigavadi just to be clear : are you asking asking us to modify this script and exclude "IntuneMAMSwift" ?
This script currently just handles "framework" not  "xcframework"
