### ISSUE TITLE
SwiftUI Example Please!

### ISSUE THREAD

**Issue by chasemac** [msintuneappsdk/ms-intune-app-sdk-ios#235]
Are there any examples of implementing Intune into SwiftUI project?

**Comment by vigavadi** [comment]
Hey @chasemac, we do not have any Intune SwiftUI sample projects available at the moment.

**Comment by vigavadi** [comment]
@chasemac Have you followed these steps for integrating Intune SDK: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios ?

**Comment by drmarkpowell** [comment]
+1 to creating a MS-provided SwiftUI example. We won't consider using this framework until there is SPM support as well as a SwiftUI quick start example.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
