### ISSUE TITLE
ADAL to MSAL migration for ios

### ISSUE THREAD

**Issue by ensprit** [msintuneappsdk/ms-intune-app-sdk-ios#237]
**Describe the bug:**
Intune status in the `enrollmentRequest` will always return an error, if MSAL used

**To Reproduce**

To Reproduce Steps to reproduce the behavior:

Replace SSO authentication library from ADAL to MSAL.
Make sure MSAL and Intune SDK are up to date.
Run.
called IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(allowedAccountValue) in the application(_ application: UIApplication,willFinishLaunchingWithOptions ...
There are the following differences between ADAL and MSAL.
// ADAL
func enrollmentRequest(with status: IntuneMAMEnrollmentStatus) {
     print("status.didSucceed") 
     // status code: 100
     // true: "New MAM policies were received and applied to the application."
}
// MSAL
func enrollmentRequest(with status: IntuneMAMEnrollmentStatus) {
     print("status.didSucceed") 
     // status code: 201
     // false: "There was an internal error in the Intune MAM SDK.  Please see the NSError object for more details."
}

IntuneMAMEnrollmentStatus status is return true by MSAL.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/22345280/161822508-ddac8bd2-43a0-4136-af2e-461c6bdaa5ad.png">

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
Xcode: 13.3
MSAL: 1.2.0
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- yes, using version -> 15.4.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- Cordova iOS App (Deployment Target -> iOS13.0 to 15.4)
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hi @ensprit, do you have an [app registration](https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app) for the application configured in AAD? If so, have you [configured the ADALClientId and ADALRedirectUri settings](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-msal-settings-for-the-intune-app-sdk) in the IntuneMAMSettings dictionary of the app's Info.plist?

**Comment by ensprit** [comment]
Yes, we added the keys 
<config-file target="*-Info.plist" parent="IntuneMAMSettings">
            <dict>
                <key>ADALClientId</key>
                <string>7904eb1c-2fd5-4301-8fae-4e15c75964c6</string>
                <key>ADALRedirectUri</key>
                <string>msauth.com.buildingrobotics.comfy://auth</string>
            </dict>
        </config-file>


But, still same issue

**Comment by Kyle-Reis** [comment]
Hi @ensprit, have you also followed [these steps](https://github.com/AzureAD/microsoft-authentication-library-for-objc#ios-only-steps) to add the scheme for your redirect URI to the app's CFBundleURLSchemes list?

**Comment by ensprit** [comment]
yes already added this key in CFBundleURLSchemes
```

<config-file target="*-Info.plist" parent="CFBundleURLTypes">
        <array>
            <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>msauth.com.mycompany.xxxx</string>
            </array>
            </dict>
        </array>
        </config-file>

```

 ```
<config-file parent="LSApplicationQueriesSchemes" target="*-Info.plist">
        <key>LSApplicationQueriesSchemes</key>
                <array>
                    <string>access</string>
                </array>
                <array>
                   <string>cydia</string>
                </array>
                <array>
                   <string>msauth</string>
                </array>
                <array>
                   <string>msauthv2</string>
                </array>
                <array>
                   <string>msauthv3</string>
                </array>
        </config-file>
```

**Comment by ensprit** [comment]
I am implemented the Cordova custom plugin

3. To handle a callback, add the following to appDelegate:
where should i need to add the code 

```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        
	return MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String)
}
```

**Comment by ensprit** [comment]
@Kyle-Reis how to add the key in project plist file  
### <config-file target="*-Info.plist" parent="IntuneMAMSettings">
            <dict>
                <key>ADALClientId</key>
                <string>XXXXX-2f89-XXXX-8fae-yuio</string>
                <key>ADALRedirectUri</key>
                <string>msauth.com.xxxx.xxxx://auth</string>
            </dict>
        </config-file>

**Comment by Kyle-Reis** [comment]
Hi @ensprit, why does the client ID need to change for each customer? If this app will be used by users in different AAD tenants, you can configure the authentication settings for the app registration in AAD to make the app accessible to users in any AAD tenant:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/7443106/169066485-664cf64d-1059-4a68-aae1-c88b5306c2f1.png">

Note: tenant administrators will need to approve the app for use in their tenant before users can use it. Hope this helps!

**Comment by ensprit** [comment]
@Kyle-Reis Thanks for the update, But our use case is each domain 'ADALClientId' keep in the Database. Whenever the user enters the email address, based on the domain get the 'ADALClientId' 

If any other option to update the 'ADALClientId' dynamic key in to plist

**Comment by ensprit** [comment]
@Kyle-Reis Please provide a Swift code to guide us that how to define these values and in which file we have to define these values.

**Comment by ensprit** [comment]
@Kyle-Reis I have struck here can you help me

**Comment by Kyle-Reis** [comment]
Hi @ensprit, you can assign a value to the Intune AAD override properties from any Swift file that imports the IntuneMAMSwift module like this:

IntuneMAMSettings.aadClientIdOverride = self.clientId
IntuneMAMSettings.aadRedirectUriOverride = self.Redirecturl
IntuneMAMSettings.IntuneMAMSettings.aadAuthorityUriOverride = "https://login.microsoftonline.com/tenant_id/"

The override values should be assigned before Intune enrollment is attempted.

**Comment by ensprit** [comment]
@Kyle-Reis thanks for the input, now working on the different tenant_id and client id
but after enrollment, we get delayed the msg 30 to 45 seconds "**your organization is protecting its data in this app. You need to restart the app to continue"**

May know the reason why it's getting delayed.

**Comment by Kyle-Reis** [comment]
Hi @ensprit, it's hard to say for sure what might be causing the delay, as enrollment is a network operation which might be impacted by poor connectivity and other factors external the Intune SDK or even the application. Do you have the debugger attached to the application when observing this delay?

**Comment by Kyle-Reis** [comment]
Hi @ensprit, just checking in to see if you're still having an issue here.

**Comment by ensprit** [comment]
> Hi @ensprit, just checking in to see if you're still having an issue here.

this issue fixed @Kyle-Reis
