### ISSUE TITLE
Offline wipe timer keeps expiring

### ISSUE THREAD

**Issue by lucac-apps** [msintuneappsdk/ms-intune-app-sdk-ios#239]
Offline wipe timer keeps expiring despite users reguraly use the app.

Any idea of what may cause this behaviour?

**Comment by neiljac1** [comment]
Hi @lucac-apps,

Can you upload logs via Outlook -> Settings -> Help & Feedback -> Collect Diagnostics -> Get Started -> Upload Outlook Logs then email the incident id to neiljac@microsoft.com?

Thanks,
Neil

**Comment by neiljac1** [comment]
Hi @aschemel-ZIG, the alert that's displayed when a wipe occurs will have a reason code in the form 6XX. The code for offline wipe is 608. Are you seeing this?

Thanks,
Neil

**Comment by sawaYch** [comment]
> Hi @aschemel-ZIG, the alert that's displayed when a wipe occurs will have a reason code in the form 6XX. The code for offline wipe is 608. Are you seeing this?
> 
> Thanks, Neil

Thanks, @neiljac1 . May I know where can I find the full list of reason code of 6xx? I have search over the iOS SDK source code and documentation and I can't find these reason code. It make me difficult to troubleshoot.

**Comment by neiljac1** [comment]
Hi @sawaYch, those reason codes are internal and aren't documented. If you have a specific code, I can let you know what caused the wipe.

Thanks,
Neil
