### ISSUE TITLE
How to get access token from Azure ADFS SSO?

### ISSUE THREAD

**Issue by fastharper** [msintuneappsdk/ms-intune-app-sdk-ios#24]
Our iManage server can be configured to work with Azure ADFS SSO. But how would this tie into the built-in authentication with the Intune SDK? What happens when re-authentication is needed? I assume the Intune SDK will show the re-authentication screen?

I could bypass the login requirement of the iManage server if I had a cookie/token set for the HTTPS calls. But I don't know how or where to get the token.

**Comment by Kyle-Reis** [comment]
Hey @fastharper, SSO between the Intune SDK and an app using ADFS is currently unsupported. For this scenario, you'll need to call our loginAndEnrollAccount API to successfully enroll users with the Intune MAM service.
