### ISSUE TITLE
How to implement IntuneMAMWebViewPolicy For React Native app

### ISSUE THREAD

**Issue by Ddv0623** [msintuneappsdk/ms-intune-app-sdk-ios#240]
Hi,
I working on implement Intune SDK to our React Native Mobile App.
I able to integrate Intune SDK to our app already.
Now we want to know more about using webview with IntuneSDK
I have read this page from MS: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#displaying-web-content-within-an-application

After read it I have some question:
- if we not config anything in Info.plist then webviews use inside the app will be managed always by intune is this correct?
- in React Native we open webview from javascript code, is there anything we need to do to make these webview as managed view?
- If webview from React Native is not a managed webview how can we create a React Native managed webview. Can you guys provide us some code example for it?
- is there anyway to test to make sure that the webview is managed?

**Comment by neiljac1** [comment]
Hi @Ddv0623,

If your application is a single identity app, then by default the webview will be managed once the application is enrolled. Multi-identity applications need to call setUIPolicyIdentity to switch to the managed user context before the webview will be managed. You can test this by setting the Restrict Cut,Copy,Paste policy to Managed Apps and try copying text from the webview and pasteing the text in Note or another unmanaged app. 

Thanks,
Neil

**Comment by Ddv0623** [comment]
Thanks for the info. I will close the issue now
