### ISSUE TITLE
QLPreviewController is not showing file preview for Microsoft Intune SDK integrated application

### ISSUE THREAD

**Issue by rohitkale07** [msintuneappsdk/ms-intune-app-sdk-ios#242]
**Describe the bug:**
I have integrated MS intune SDk in my application. Application has feature to preview all type files using QLPreviewController. File preview is not working after Intune SDK integration. If I use WKWebview to open same file, I can able to see the preview of file.

**To Reproduce**
1. Integrate Intune SDK in application
2. keep one file (like .png, .pdf, etc) in document directory of iOS application
3. Try to preview file using QLPreviewController

**Expected behavior:**
It should show file preview

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS 14.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - 15.4.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A

- Do you see a trend with it only being reproduced on a specific device? - reproducible on all devices and  all iOS version

**Comment by rohitkale07** [comment]
![Preview](https://user-images.githubusercontent.com/62232278/169230932-bdf9c419-c9cb-43b2-a366-797fd7efd401.jpeg)

**Comment by vigavadi** [comment]
Hey @rohitkale07, Are you able to view the file in QLPreviewController without Intune SDK/User with no Intune MAM policies targeted?

**Comment by rohitkale07** [comment]
> Hey @rohitkale07, Are you able to view the file in QLPreviewController without Intune SDK/User with no Intune MAM policies targeted?

Yes, I have checked and can confirm, in same application i.e. Intune integrated SDK, If I doen't enrol user, files can be preview in QLPreviewController successfully.
But when I enrol user (using Outlook app), application can't display preview of file in QLPreviewController

**Comment by rohitkale07** [comment]
I have find out the root cause of this behavior.
It is due to how application shows QLPreviewController on parent/top view controller
let say "topController" is top most view controller for application and "qlPreviewController" is of QLPreviewController's object
To show QLPreviewController we have 2 use case
1. if topController is on navigation controller then 
topController.navigationController.pushViewController(qlPreviewController, animated: true)
2. or app can use "show"
topController.show(qlPreviewController, sender: nil)

above 2 approach work for me as topController is on navigationController

Old issue in application was, it uses "present" method to launch "qlPreviewController". 
topController.present(qlPreviewController, animated: true, completion: nil)
But "present" is working fine if application doesn't have Intune user enrol. And "present" fail in application when user enrolled with Intune policy in application
