### ISSUE TITLE
Steps to Open App from Links in Outlook

### ISSUE THREAD

**Issue by chasemac** [msintuneappsdk/ms-intune-app-sdk-ios#243]
If a user taps on a link to a specific internal site in Outlook Mobile, I would like it to open the Intune iOS app I created instead of opening that link in the Edge browser. 

Can you let me know what steps are required to achieve this?

Thanks!

**Comment by vigavadi** [comment]
Hey @chasemac! You could add the URL protocol to the data transfer exemption list as mentioned here: https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios#data-transfer-exemptions

**Comment by vigavadi** [comment]
@chasemac Just wanted to check if you were able to try this out?

**Comment by chasemac** [comment]
I haven't had success yet. I've tried a lot of different things. I'm not the person at my company that manages Intune so it takes longer to try stuff because I have to get him to make the changes on the Intune side.

**Comment by vigavadi** [comment]
@chasemac Just checking if there's any update on this.

**Comment by chasemac** [comment]
I got it figured out. Closing the issue.
