### ISSUE TITLE
Error dialog is shown when loginAndEnrollAccount() is called.

### ISSUE THREAD

**Issue by t-shimizu-pr** [msintuneappsdk/ms-intune-app-sdk-ios#244]
Hi,
I'm trying to integrate Intune SDK for our app.
But, I'm a beginner at  Intune and Azure.
If you would help us, it is very grateful.
Thank you,

**Describe the bug:**
Calling this function,
```
IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)
```
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#apps-that-do-not-use-adal-or-msal

a dialog is shown;
```
Unexpected failure. Contact your IT administrator for help.
```

**To Reproduce**
1. Download "Intune Company Portal" app.
2. Sign in to the app.
3. call `loginAndEnrollAccount()` in `application(_:didFinishLaunchingWithOptions:)` or `viewDidLoad()`.

**Expected behavior:**
- The dialog is not shown.
or
- Sign in dialog is shown.

**Screenshots and logs:**
![Image from iOS](https://user-images.githubusercontent.com/75414936/169789950-a1e5382c-a55b-4a65-9e24-8d8269fef84d.png)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 15.4.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
    - Intune SDK 15.4.0
    - MSAL 1.2.1 (Swift Package)
        - If remove the MSAL, same dialog occurs.
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
    - Native (Swift)
- For errors during build, does the app build without Intune SDK integration?
    - Build is no error.
- For errors post build, does the app launch without being Intune SDK integrated?
    - The app runs fine.

- Who is the customer?
    - I would like to distribute via Apple App Store.
- Do you see a trend with it only being reproduced on a specific device?
    - I tried the device only now.

**Additional context:**
- I would like to distribute an app integrated with Intune SDK via Apple App store.
    - I'm using https://endpoint.microsoft.com/.
    - Additional settings ware required?
        - e.g. https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#set-up-and-configure-an-aad-app-registration

**Comment by vigavadi** [comment]
Hey @t-shimizu-pr, have you followed these steps to ensure you have MSAL setup correctly: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-msal-settings-for-the-intune-app-sdk ?

Additionally, you need to make sure that you have IntuneMAMSettings dictionary set up correctly as mentioned here: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk.

**Comment by t-shimizu-pr** [comment]
Hi @vigavadi ,

Adding URLType `msauth.com.microsoft.intunemam`, Sign in dialog is shown correctly.
(The error dialog is not shown.)

Although MSAL setup and IntuneMAMSettings dictionary is not configured, it is fine now.
Thank you so much.

**Comment by vigavadi** [comment]
@t-shimizu-pr I'm glad it's working.

**Comment by thuongtv-vn** [comment]
do you guys know why it must be msauth.com.microsoft.intunemam. Can we use other one?
