### ISSUE TITLE
16.0.0 Bug uploading to Apple

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#245]
**Describe the bug:**

**To Reproduce**
1. Archive & Export
2. Upload to Appl
3. Getting the following error:4. 
```*** Error: Invalid CFBundleSupportedPlatforms value. The CFBundleSupportedPlatforms key in the Info.plist file in "Payload/BeratungsApp Test.app/IntuneMAMResources.bundle" bundle contains an invalid value, [iPhoneSimulator]. Consider removing the CFBundleSupportedPlatforms key from the Info.plist file. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue. With error code STATE_ERROR.VALIDATION_ERROR.90542 for id 1c62f01e-f580-489f-8370-9d770d9814d4 Asset validation failed (-19208)```

**Expected behavior:**
No error, upload should go through.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- latest 16.0.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- Native
- For errors during build, does the app build without Intune SDK integration?
- Yes
- For errors post build, does the app launch without being Intune SDK integrated?
- Yes

**Comment by vigavadi** [comment]
@tritter This should be fixed with v16.0.1. Could you try it out?

**Comment by tritter** [comment]
@vigavadi yes its working again! Sorry for my late reply, I havent had a chance for a new deploy to the store.

Thanks a lot!
