### ISSUE TITLE
Show Sign in dialog for Intune user only.

### ISSUE THREAD

**Issue by t-shimizu-pr** [msintuneappsdk/ms-intune-app-sdk-ios#246]
Hello,

I would like to distribute an app integrated with Intune SDK via Apple App Store.

I will call `IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)` in `application(_:didFinishLaunchingWithOptions:)`.

I think that method shows sign in dialog.
If app's user uses Intune, It's OK.
But, for the others (they don't use Intune), I would like to hide the dialog.

Is there a solution?

My first idea is using `IntuneMAMEnrollmentManager.instance().enrolledAccount()`.
(If I can get the account, show the dialog.)
But, I can't get the account although signed in with Intune Company Portal app.

My current assumption is using no MSAL setup.
If MSAL is essential, please let me know.

ref:

> have you followed these steps to ensure you have MSAL setup correctly: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-msal-settings-for-the-intune-app-sdk ?

https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/244#issuecomment-1134793533

Regards,

**Comment by Kyle-Reis** [comment]
Hi @t-shimizu-pr, will non-Intune users/customers all still be using AAD accounts? Or is it possible that they might be using a completely separate identity provider?

**Comment by t-shimizu-pr** [comment]
Hi @Kyle-Reis ,

After discussion with our team, we are willing to cancel calling this method.
`IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)`

So, this issues's problem is gone.
Let me close this issue.

Thank you so much.
