### ISSUE TITLE
SDK v10.0.1 wont work with ADAL v4.0.0 (UIWebView / WKWebView)

### ISSUE THREAD

**Issue by fabiankoebel** [msintuneappsdk/ms-intune-app-sdk-ios#25]
the specified versions wont work together. The ADAuthenticationContext class is expecting an instance of WKWebView but gets passed an instance of UIWebView. This leads to an unrecognized selector crash.

**Comment by Kyle-Reis** [comment]
Hey @fabiankoebel, ADAL 4.x is not yet supported by the Intune SDK for iOS. I'll notify you once that has changed. In the meantime, you can use ADAL 2.x

**Comment by andrejacobs** [comment]
@Kyle-Reis Is this still true now (June 2019) with the 2x new Swift based Frameworks and ADAL 4.x?

**Comment by Kyle-Reis** [comment]
Yes, the current release only supports up to 2.x. ADAL 4.0 support is currently in development.

**Comment by Kyle-Reis** [comment]
Hey @fabiankoebel and @andrejacobs, ADAL 4.0 is now supported in our [latest release ](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest)(11.1.2)
