### ISSUE TITLE
Version 16 Upgrade Issues

### ISSUE THREAD

**Issue by chasemac** [msintuneappsdk/ms-intune-app-sdk-ios#250]
I'm having issues when I update to version 16.0.1. 

One of the issues is that the IntuneMAMEnrollmentManager.Instance().enrolledAccount() returns the OID instead of the UPN. Is there a way to get the UPN with version 16? I was relying on that email address. 

Thanks!
-Chase

**Comment by darosal** [comment]
Hi @chasemac, thanks for reaching out! The `enrolledAccount` method should be only returning a UPN while a new `enrolledAccountId` method should be returning the OID. The behavior of the original `enrolledAccount` method should be unchanged.

Can you confirm that `enrolledAccount` is the method returning an OID? If so, are you able to pull Intune logs using the IntuneMAMDiagnosticConsole and send them to me via email at darosal@microsoft.com? 

We should be able to use those logs to confirm that our UPN/OID mappings aren't broken.
