### ISSUE TITLE
isOpenFromAllowedForLocation .localStorage always returns false

### ISSUE THREAD

**Issue by Wschroe2** [msintuneappsdk/ms-intune-app-sdk-ios#251]
Our app is using isOpenFromAllowedForLocation to query the IntuneMAMPolicy object before attempting to open data from local storage (app container). We confirmed the policy allows saving to and opening from local storage, and the save scenario does not present any issues. We also tried passing a username as well as passing nil for the account parameter (per the [documentation](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#handling-open-from-scenarios)), but the results are the same regardless. Is there additional documentation or a code example for this topic? Does the below code seem to be missing anything?

Example call:

        guard let policy = IntuneMAMPolicyManager.instance().policy() else {
            return false
        }
        
        return policy.isOpenFromAllowed(for: .localStorage, withAccountName: user)

Thank you in advance!

**Comment by darosal** [comment]
Hi @Wschroe2, thanks for reaching out! Can you confirm what values you have set for the account's "Receive data from other apps" and "Open data into Org documents" policies in the endpoint manager?

The local storage location should only be allowed in isOpenFromAllowed if:
- "Receive data from other apps" = "All apps/All Apps with Incoming Org Data"

or if: 
- "Receive data from other apps" = "Policy Managed Apps" and "Open data into Org documents" = "Allow"

**Comment by darosal** [comment]
I also wanted to add, according to the documentation, the IntuneMAMPolicy object should be initialized with the identity of the account that is receiving the data (See the note in [Handling open-from scenarios](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#handling-open-from-scenarios)).

Instead of initializing with IntuneMAMPolicyManager's `policy` method to retrieve the IntuneMAMPolicy object, use the `policyForIdentity:` method.

**Comment by chrsdrhm** [comment]
Hi @darosal, I work with @Wschroe2 and manage our Intune policy.  So up until now we had "Receive data from other apps" configured as:

![image](https://user-images.githubusercontent.com/47731853/173702356-53a1e7c2-a6e0-42f5-804d-60fe5f343ae9.png)

I've reconfigured based on your response as:

![image](https://user-images.githubusercontent.com/47731853/173702464-463f2190-cbec-4178-9d63-9c6e2aeaee61.png)

I'll have @Wschroe2 re-test.  Maybe this is comparing apples to oranges, but I wanted to clarify... in the iOS [documentation ](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios#data-transfer)the "Save copies of org data" control for "select services" defines "Local Storage" as a managed location (not unmanaged locations like are accessible via the Files app).  Seems as though the receive data control does not have a similar "Local Storage" option, so I assume allowing "Open data into Org documents" would allow a user to attach any sort of file from the local (unmanaged) device storage (like an executable)?  If this is the case, I'll want to limit this change only to the app that requires this incoming data.  Thanks!

**Comment by darosal** [comment]
Hi @chrsdrhm, it is correct that we don't have a similar "Local Storage" option available for the open policy. However, the behavior for the local storage location is the same as it is for the save scenario. Here's what our [developer documentation](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#supported-open-locations) says about it:

IntuneMAMOpenLocationLocalStorage - This location represents app-sandbox storage that can only be accessed by the app. **_This location should not be used for opening files from a file picker or handling incoming files from an openURL._** If an identity can be associated with the app-sandbox storage, it should be passed in as the second argument. If there is no identity, nil should be passed instead. (e.g. an app might use separate app-sandbox storage containers for different accounts. In this case, the account that owns the container being accessed should be used as the second argument.)

It would also be worth taking a look at the [Special considerations for open locations](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#special-considerations-for-open-locations) section of our developer documentation as it contains more information about when to use LocalStorage vs Other for representing different file storage locations.

**Comment by chrsdrhm** [comment]
Thanks @darosal, I was more considering that if I make this policy update and apply it to both this SDK LOB app and also (for example) Outlook, users in Outlook would now be able to attach files from the local device outside of just the Photo Library / Camera.  I went the route of a new App Protection Policy for this particular LOB app to avoid that concern.

**Comment by darosal** [comment]
@chrsdrhm, got it. As long as _Policy managed apps_ is set as the value for _Receive data from other apps_, Outlook will only accept managed data into the managed account from other apps. This means that files shared to Outlook from the Files app through a share extension will only be allowed if originally shared out of and encrypted by a MAM enabled app. If composing an email within Outlook, Outlook will prevent attaching documents from the file picker that has access to the on device and icloud storage locations.

With this policy combination, a user would not be able to upload an executable, created outside of a managed app, to their iPhone's Files app and then share it to Outlook's managed account.

**Comment by chrsdrhm** [comment]
@darosal I follow, thanks for the explanation!  Haven't heard from @Wschroe2 just yet, we'll report back testing results for his open from scenario.
