### ISSUE TITLE
we are facing the issue already user login to ADAL, we release the MSAL while login getting the message is "Your organization only allows you to transfer its data to other managed apps"

### ISSUE THREAD

**Issue by ensprit** [msintuneappsdk/ms-intune-app-sdk-ios#254]
@Kyle-Reis and @hhawkins  we are facing the issue already user login to ADAL, we release the MSAL while login getting the message is 
**Your organization only allows you to transfer its data to other managed apps** 
<img width="335" alt="image" src="https://user-images.githubusercontent.com/22345280/175105434-54dc82db-42a7-437e-953b-c82f9d95e00f.png">

May know the reason getting this error message

_Originally posted by @ensprit in https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/237#issuecomment-1163443027_

**Comment by Kyle-Reis** [comment]
Hi @ensprit - Which version of the Intune SDK is the application using?

**Comment by ensprit** [comment]
@Kyle-Reis using <pod name="MSAL" spec="~> 1.2.0" />

**Comment by ensprit** [comment]
> @Kyle-Reis and @hhawkins we are facing the issue already user login to ADAL, we release the MSAL while login getting the message is **Your organization only allows you to transfer its data to other managed apps** <img alt="image" width="335" src="https://user-images.githubusercontent.com/22345280/175105434-54dc82db-42a7-437e-953b-c82f9d95e00f.png">
> 
> May know the reason for getting this error message
> 
> _Originally posted by @ensprit in [#237 (comment)](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/237#issuecomment-1163443027)_


<pod name="MSAL" spec="~> 1.2.0" />
Intune SDK [15.4.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/15.4.0)


@Kyle-Reis @hhawkins @chadseippel @oydang Can anyone check this issue, this will be block for us

**Comment by ensprit** [comment]
@Kyle-Reis any update above issue

**Comment by Kyle-Reis** [comment]
Hi @ensprit, Does the app call openURL at some point during or immediately after the authentication flow? In this scenario it sounds like the user has already enrolled and received MAM policies before the upgrade, so the policies are already in effect during the authentication that takes place after the upgrade. The message shown in the screenshot can be displayed when an application tries to open a URL into an an application which doesn't support Intune.

**Comment by ensprit** [comment]
> Hi @ensprit, Does the app call openURL at some point during or immediately after the authentication flow? In this scenario it sounds like the user has already enrolled and received MAM policies before the upgrade, so the policies are already in effect during the authentication that takes place after the upgrade. The message shown in the screenshot can be displayed when an application tries to open a URL into an an application which doesn't support Intune.

how to handle this, could you help us

**Comment by Kyle-Reis** [comment]
Hi @ensprit. I don't think that would be the right solution here. We shouldn't need to unenroll then re-enroll the user for MAM policies. I think the right first step would be to try to understand what might be triggering the alert to show up. Could you check if this issue reproduces with the latest versions of Intune+MSAL? If so, could you [collect the Intune diagnostic logs](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app) and send them to KyleReis@microsoft.com?

**Comment by ensprit** [comment]
> Hi @ensprit. I don't think that would be the right solution here. We shouldn't need to unenroll then re-enroll the user for MAM policies. I think the right first step would be to try to understand what might be triggering the alert to show up. Could you check if this issue reproduces with the latest versions of Intune+MSAL? If so, could you [collect the Intune diagnostic logs](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app) and send them to [KyleReis@microsoft.com](mailto:KyleReis@microsoft.com)?

Thanks, @Kyle-Reis After updating the latest versions of Intune(16.0.3)+MSAL(1.2.1) it is working fine. 

May know the RCA for this issue and why this issue happened to a few users on iOS versions 15.4.1 and 15.5

**Comment by Kyle-Reis** [comment]
Hi @enspirit, you're saying this issue happens when signing in with a new account?

If so, in your testing, did you previously sign out of the app before attempting to sign back into it?

**Comment by ensprit** [comment]
@Kyle-Reis No, First-time login users are getting this issue in MSAL Intune "Your organization only allows you to transfer its data to other managed apps"

**Comment by ensprit** [comment]
@hhawkins @Kyle-Reis @oydang @chadseippel @ShruthiAchutha @msintuneappsdk @gastaffo 

Any Updated Is the 16.0.5 new release of the above issue ("Your organization only allows you to transfer its data to other managed apps") was fix?

**Comment by ensprit** [comment]
@hhawkins @Kyle-Reis @oydang @chadseippel @ShruthiAchutha @msintuneappsdk @gastaffo

Any Updated Is the 16.0.8 new release of the above issue ("Your organization only allows you to transfer its data to other managed apps") was fix?

**Comment by Kyle-Reis** [comment]
Closing out this issue as we were able to work out the configuration issues in conjunction with the MSAL team over email.
