### ISSUE TITLE
Is there any way to register(enrollment) without calling ‘loginAndEnrollAccount’ nor setting AutoEnrollOnLaunch?

### ISSUE THREAD

**Issue by akikodx** [msintuneappsdk/ms-intune-app-sdk-ios#255]
Is there any way to register(enrollment) without calling ‘loginAndEnrollAccount’ nor setting AutoEnrollOnLaunch?

I integrated Intune SDK into my app and ‘loginAndEnrollAccount’ work fine. My client want without calling ‘loginAndEnrollAccount’, because some users of my app are not use Intune. Other app which my client use works without calling loginAndEnrollAccount. (I asked the app’s developer, they said nothing to do, only build the SDK into the app.)
I couldn’t find a document about this.

**Comment by sandeepbhatia4922** [comment]
@akikodx Hey, To use MAM use you must authenticate account firstly either using MSAL or ADAL. Once you received token upon auth success, you can proceed to enrolment for MAM. There is also another way of enrolment in android i.e Default Enrolment. But if your app targets to broader audience then you must use MSAL auth and then enrolment for MAM.

**Comment by akikodx** [comment]
Hi! @sandeepbhatia4922 ,  Thank you for the comment.
I understood the need for enrollment. I think even if the user already using MAM and install the app via Intune portal, still needs 'enrollment'. Is it correct?

**Comment by Kyle-Reis** [comment]
Hi @akikodx, for the scenario where the application may be used by both customers who do and don't use Intune MAM policies,  the application should call [registerAndEnrollAccount](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#apps-that-already-use-adal-or-msal) immediately after successfully authenticating the user with MSAL. registerAndEnrollAccount will attempt a silent enrollment using AAD tokens cached by MSAL from the application's authentication of the user. If the silent enrollment fails, the user should not be blocked from using the application and Intune will automatically retry the enrollment periodically in case the user's IT admin begins targeting Intune policies at any point.

**Comment by akikodx** [comment]
Hi @Kyle-Reis,  I just wanted to make sure that I had to call the enroll method(registerAndEnrollAccount / loginAndEnrollAccount). Because I heard I should only add Intune SDK, no call any method.
Thank you for your perfect explanation!
