### ISSUE TITLE
v16.0.3 Update Issue - Intune MAM SDK failed to parse the Intune MAM service's response

### ISSUE THREAD

**Issue by clcpowers** [msintuneappsdk/ms-intune-app-sdk-ios#256]
**Description:**
Recently updated to Intune v16.0.3 (from 15.2.0), and also updated MSAL to latest release v1.2.2 (from v1.1.19).

Since updating, we now receive a 206 error in the `enrollmentRequest(with status: IntuneMAMEnrollmentStatus)` callback. 
This is happening on first time launch after acquireToken interactively, successfully obtaining account, and then calling `registerAndEnrollAccount` with the obtained account from MSAL auth:
`IntuneMAMEnrollmentStatusCode.parsingFailure` - "The Intune MAM SDK failed to parse the Intune MAM service's response"

If the app is left active after the first error, repeated 206 errors are received.

Upon killing the app and restarting, we very quickly receive the successful code 100 with all the proper app protection policy information, get the "Your organization is now protecting its data in this app..." alert and the app restarts and is enforcing Intune security.

**Expected behavior:**
As with previous releases, expect to not receive the 206 error on fresh install and not have to kill/relaunch the app to have the enrollment succeed.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes, 16.0.3 (first detected issue when updated to 16.0.1)
- What platform is your app based in (native, Xamarin based, Cordova, etc)? iOS (Swift)

**Comment by ensprit** [comment]
Any update on this issue

**Comment by vigavadi** [comment]
Can you try Intune v16.0.5 and see if that fixes the issue?

**Comment by clcpowers** [comment]
v16.0.5 appears to have resolved this issue. Thank you! 🙌
