### ISSUE TITLE
client is not entitled

### ISSUE THREAD

**Issue by AceChen1** [msintuneappsdk/ms-intune-app-sdk-ios#257]
@neiljac1  hello, looks like my app still crash when upgrade the sdk verion to 16.0.5, may i know the issue had been fixed on the 16.0.5 or not. the error is:

[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
[unspecified] A NULL string is not a valid group container identifier.
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client sent invalid parameters
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: key cannot be nil'

_Originally posted by @AceChen1 in https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/220#issuecomment-1176923302_

**Comment by AceChen1** [comment]
looks like should be config issue, close it now ,Thanks.

**Comment by below** [comment]
I am seeing this issue after the update to 20.9. Is this a concern now?
