### ISSUE TITLE
Edge browser does not get invoked from deep link when opened from a managed app

### ISSUE THREAD

**Issue by persol-kumar** [msintuneappsdk/ms-intune-app-sdk-ios#259]
The app has been built using the ms-intune-app-sdk-ios version 16.0.0.
When a deep link involving Edge is clicked, it shows a dialogue box with a message “.”. However, for all other deep link such as Teams and Outlook the behavior is correct and is the app is not installed, it shows “ xxx app is not installed on the device, please install …..” Etc.
Is there anything different for deep linking Edge compared to other apps?

**Expected behavior:**
When Edge is not installed, it should show  “ xxx app is not installed on the device, please install …..” 

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 15.5

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 16.0.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Cordova
- For errors during build, does the app build without Intune SDK integration? With integration
- For errors post build, does the app launch without being Intune SDK integrated?  Yes

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**

**Comment by persol-kumar** [comment]
Any help will be greatly appreciated.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
