### ISSUE TITLE
Not able to Integrate latest Intune SDK with my Objective-C project.

### ISSUE THREAD

**Issue by SonikaPatel12** [msintuneappsdk/ms-intune-app-sdk-ios#260]
I want to integrate Intune SDK with my Objective- C project. But when I added the framework and compile the app got the multiple issues. 
I had import below framework-
IntuneMAMSwift.xcframework
IntuneMAMSwiftStub.xcframework
IntuneMAMResources.bundle

Above swift framework is not working with my  Objective-C project. So can you please suggest me what I can use this latest SDK with my Objective c project.

I have used -
 - Device: xcode simulator
 - OS: iPad (9th generation), iPad Pro (11 inch, 3rd generation)

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - Yes
- What platform is your app based in (native, Xamarin based, Cordova, etc)? - iPad OS
- For errors during build, does the app build without Intune SDK integration? - YES
- For errors post build, does the app launch without being Intune SDK integrated? - Got the error during build.

<img width="683" alt="Screenshot 2022-07-25 at 13 15 35" src="https://user-images.githubusercontent.com/106156353/180731252-d92814ef-d012-45ff-8b16-5da0fe88fb6b.png">

**Comment by darosal** [comment]
Hi @SonikaPatel12, thanks for reaching out. Can you confirm that you have added the required IntuneMAMSwift dependencies listed here: https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app?
