### ISSUE TITLE
Release the MSAL while login getting the message is "Your organization only allows you to transfer its data to other managed apps"

### ISSUE THREAD

**Issue by ensprit** [msintuneappsdk/ms-intune-app-sdk-ios#261]
**Describe the bug:**
we are facing the issue already user login to ADAL, we release the MSAL while login getting the message is "Your organization only allows you to transfer its data to other managed apps"

<img width="316" alt="image" src="https://user-images.githubusercontent.com/22345280/181205612-a740911f-b739-4368-ab15-d482c4df4108.png">

this issue does not reproduce with already login users, while after updating the latest versions of Intune(16.0.3)+MSAL(1.2.1) it is working fine.

But we observed New users login with MSAL got an error message is "Your organization only allows you to transfer its data to other managed apps"

this block our release, anyone can help us

**Intune App SDK for iOS (please complete the following information):**

iOS version : 15.6

Latest versions of
Intune(16.0.3)
MSAL(1.2.1)
Cordova 

Any Updated Is the 16.0.8 new release of the above issue ("Your organization only allows you to transfer its data to other managed apps") was fix?

**Comment by ensprit** [comment]
Can anyone reply to me on this issue?

**Comment by Kyle-Reis** [comment]
Closing out this issue as we were able to work out the configuration issues in conjunction with the MSAL team via email.
