### ISSUE TITLE
Intune iOS RemediateCompliance Error

### ISSUE THREAD

**Issue by decisionslab2** [msintuneappsdk/ms-intune-app-sdk-ios#262]
**Describe the bug:**
Can't login further even after remediating Compliance and applying the policy 

**The Flow:** 
When the App protection policy is enabled we get the following exception 

![image](https://user-images.githubusercontent.com/78529860/182564004-4095ed34-7782-4ce5-bbca-ea251af93eb9.png)

later we need to call the remediateCompliance method as given in the documentation. Once done we get the following U.I

![image](https://user-images.githubusercontent.com/78529860/182564678-393a8cee-7698-4c27-b5a2-e69878c66763.png)

![image](https://user-images.githubusercontent.com/78529860/182564718-6837b3a7-d21b-4b2c-9f4d-133740740f9b.png)

Then later after entering the PIN and try to login Again we are asked to signIn again in inTune SDK and we get stuck here 

![image](https://user-images.githubusercontent.com/78529860/182565024-a258dc4b-49b1-40e6-8fe1-3d6ca8ab5931.png)

The logs Cleary states that we are blocked by the inTune SDK application 

![image](https://user-images.githubusercontent.com/78529860/182565158-779f1bf3-e14f-4d4e-a951-eb5eca00c322.png)

**Expected behaviour:**
To login successfully after the Policy is applied and remediating Compliance is done

**Video:**
https://figg-my.sharepoint.com/:v:/g/personal/arshad_nabi_meetingdecisions_com/EXUkF73oNetBhvIv3EoG5hQBIsECo9Z6WsBhxZ-Vk47XNg?e=OjPJcU

**Smartphone (please complete the following information):**
 - Device: Any iOS Device,
 - OS: iOS Version 13.0 and Higher

- What version of the Intune SDK are you using? Are you using the latest version? Latest version 
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? App builds without error
- For errors post build, does the app launch without being Intune SDK integrated? NO 

- Do you see a trend with it only being reproduced on a specific device? NO

**Comment by decisionslab2** [comment]
Info:
We have authenticator app installed in the device and the device is registered in Azure AD as well.

**Comment by gastaffo** [comment]
@decisionslab2 What do you have in LSApplicationQueriesSchemes in your Info.plist?

**Comment by decisionslab2** [comment]
yes @gastaffo. We do have LSApplicationQueriesSchemes in our info.plist

**Comment by jasoncoolmax** [comment]
@decisionslab2 May I know which API are you calling for the following?

> Then later after entering the PIN and **try to login Again** we are asked to signIn again in inTune SDK and we get stuck here

**Comment by decisionslab2** [comment]
We are calling the MSAl login acquireToken function. 
MSALPublicClientApplication.acquireToken(with: parameters, completionBlock: completionBlock)

**Comment by jasoncoolmax** [comment]
@decisionslab2 Could you please share the following, such that i can take a deeper look.

-  Open Authenticator -> Hamburger menu on top left corner -> Send Feedback -> Having trouble? -> fill in any info needed -> Send -> give us the incident id
- Collect your app's MSAL logs (If you haven't setup the logging yet, see [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-ios?tabs=objc) for details)

**Comment by decisionslab2** [comment]
@jasoncoolmax 
Incident ID: 

![image](https://user-images.githubusercontent.com/78529860/185364257-20c1a512-dbe8-47f7-8037-116a4f19b5b0.png)

Logs:
[MSAL Logs.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/9372382/MSAL.Logs.txt)

Thank you

**Comment by decisionslab2** [comment]
The issue got resolved. The problem was with Delegated Permissions. once applied fresh it works fine. 
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional
