### ISSUE TITLE
New Quick Note entry is not hide when present a UIActivityViewController in iOS 16

### ISSUE THREAD

**Issue by PiggyChen** [msintuneappsdk/ms-intune-app-sdk-ios#264]
see the picture:
<img width="278" alt="截屏2022-08-15 11 08 51" src="https://user-images.githubusercontent.com/25243068/184571475-d96612f6-9234-48c3-b37b-71289e6faf3a.png">

**Comment by neiljac1** [comment]
Hi @PiggyChen . What type of document or object were you sharing when this happen?

Thanks,
Neil

**Comment by PiggyChen** [comment]
> 

A link, you can think it is a string.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
