### ISSUE TITLE
Open in place from OneDrive with data protection active

### ISSUE THREAD

**Issue by anmipo** [msintuneappsdk/ms-intune-app-sdk-ios#269]
My non-business app uses `UIDocumentPickerViewController` to open cloud-stored files and edit them in place. Expectedly, files picked from OneDrive for Business come out encrypted (since OD has "Send org data to other apps" set to "Policy managed apps"). To solve this, I have integrated Intune SDK to my app. Now files from OneDrive come over in plain text, all good  — but the SDK imports the file instead of opening it in place!

So, it seems I can either open the file in place (without Intune SDK) or access its contents (with Intune SDK) — but not simultaneously?

**Expected behavior:**
Files picked with `UIDocumentPickerViewController` should still open in place, with the possibility to encrypt/decrypt them in the app code directly.

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2016)
 - OS: iOS 15.6.1

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK version: 16.0.12 (latest)
- Platform: native

**Questions:**

- A similar issue was raised in April 2020 (#77). Has anything changed since then?
- What are the options to edit files in OneDrive using my Intune-enabled app? I can think only about working with OneDrive API directly, implementing my own file selection dialog — which feels like back to iOS 10… Are there any other options?

**Comment by abasore** [comment]
@anmipo It is correct that a copy of the file is made when exporting with with Intune policy restrict sharing. The SDK encrypts the data before sending outgoing data from OneDrive for managed users with outgoing sharing policy.

**Comment by anmipo** [comment]
> It is correct that a copy of the file is made when exporting with with Intune policy restrict sharing. The SDK encrypts the data before sending outgoing data from OneDrive for managed users with outgoing sharing policy.

@abasore thank you, this answers my first question. What about the second one?

> What are the options to edit files in OneDrive using my Intune-enabled app? I can think only about working with OneDrive API directly, implementing my own file selection dialog — which feels like back to iOS 10… Are there any other options?

**Comment by abasore** [comment]
@anmipo, unfortunately, I don't have resources for other support besides the OneDrive APIs.
