### ISSUE TITLE
App Freeze with white screen after entering PIN - INTUNE SDK

### ISSUE THREAD

**Issue by decisionslab2** [msintuneappsdk/ms-intune-app-sdk-ios#270]
**Describe the bug:**
After successfully applying the InTune App protection policy the App restarts and set-up pin functionality is prompted by the InTune SDK
Later once the PIN set-up is completed the App freezes with white screen.
This problem occurs after the initial PIN set-up and returning to the app after an hour and the Pin request is prompted again

Closing and launching the App again works.

No logs or reports is found during the App Freeze  

**Expected behavior:**
To open the default screen of the App after PIN Validation 

**Screenshots and logs:**

https://user-images.githubusercontent.com/78529860/188453803-f6d79cae-b7d5-4c84-b1dc-8701223c2b36.MP4

**Smartphone (please complete the following information):**

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
   yes, Latest version.
   [16.1.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases)

- What platform is your app based in (native, Xamarin based, Cordova, etc)?
 Native Login on top of Flutter Framework. 

- Do you see a trend with it only being reproduced on a specific device?
  Reproducible devices:  iPAD and Iphones

**Comment by robaburgess** [comment]
@decisionslab2 What happens if you run the app in Xcode? The white screen is LaunchImage in Assets.xcassets.

**Comment by aschemel-ZIG** [comment]
> We're are seeing a similar issue. However, instead of a white screen the app get stuck and shows a blurry screen.

Hi! We are getting a very similar issue, blurry screen when brining the app back to foreground. Were you able to solve this?

**Comment by nevertheless1975** [comment]
It still happens from time to time and I think it doesn't make a difference if the app is started from within Xcode or not. The blurry screen is of course part of the app protection policy, but for any reason it sometimes doesn't disappear on app resume. If you then wait a few seconds, the app will close and needs to be restarted manually again. No crash report received.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
