### ISSUE TITLE
Intune 15.4.0 and iOS 16

### ISSUE THREAD

**Issue by luky88** [msintuneappsdk/ms-intune-app-sdk-ios#273]
Hi @Kyle-Reis, 

looking at the release notes of the Intune SDK version [16.1.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/16.1.1), there is a note about the iOS 16 support for the apps compiled with Xcode 13.

Is this mandatory? It means that even using Xcode 13 we **must** use the version 16.1.1 to let the Intune SDK work on iOS 16?

In particular, we have bespoke apps that use Intune 15.4.0 and we need to understand if they will continue to work even if running on iOS 16.

Thanks in advance

**Comment by Kyle-Reis** [comment]
Hi @luky88 - Yes, the 16.1.1 update addresses several breaking changes introduced by iOS 16 and is required for all applications compiled with Xcode 13. Typically, for each major release of iOS, the Intune SDK team will release an update for apps that are still being compiled with the existing version of Xcode, as well as one for applications compiled with then new major release of Xcode corresponding to the iOS release.
