### ISSUE TITLE
CMARAcquireAADTokenOperation: Operation timed out.

### ISSUE THREAD

**Issue by nevertheless1975** [msintuneappsdk/ms-intune-app-sdk-ios#274]
**Describe the bug:**

We are integrating Intune SDK in our app and experiencing an issue (95% reproducible) that happens while enrolling the user following the MAM-CA remediation flow. 

After authentication via MS Authenticator, Intune starts to enrol the user. In almost all cases this takes up to 45 seconds, which is even indicated to be unusual by Intune SDK. Eventually an error state is returned mentioning that the enrolment was not successful and needs to be repeated. After restarting the app, the enrolment is tried again and this time it takes only a few seconds to complete. 

The Intune diagnostic log shows the following errors:

IntuneMAM: CMARAcquireAADTokenOperation: Operation timed out.  Time out interval is set for 30 seconds
IntuneMAM: Failed to instantiate MSALAuthority
IntuneMAM: CMARAcquireAADTokenOperation: Failed to create an AD Authentication Context instance!
IntuneMAM: CMARMAMCacheManager: Discarding un-commited changes to the cache. 
IntuneMAM: TID=1266992 MSAL 1.2.3 iOS 15.6 [2022-09-13 10:51:40] Creating Error with description: Non Microsoft authority is not supported yet in MSAL, (null), error code: 0
...
IntuneMAM: CMARConditionalAccessManager: Compliance Status Diese App konnte nicht geschützt werden, weil eine Verbindung mit dem Intune-Dienst nicht abgeschlossen wurde. Wiederholen Sie den Vorgang.

"This app could not be protected because a connection to the Intune service was not completed."

It seems like the timeout occurs for this request, that is initiated by the SDK. 

IntuneMAM: TID=1266458 MSAL 1.2.3 iOS 15.6 [2022-09-13 10:51:11 - 3EEF49D1-881F-4407-A972-78388027B5C3] [MSAL] acquireTokenSilent returning with at: 04cf16b scopes:(
    "https://msmamservice.api.application/DeviceManagementManagedApps.ReadWrite",
    "https://msmamservice.api.application/.default"
) expiration:2022-09-13 12:04:21 +0000, (null), error code: 0

**To Reproduce**

For us and happens almost every time on initial enrolment. 

**Expected behavior:**

The timeout should never occur or very seldom. 

**Screenshots and logs:**

Can be provided via DM. 

**Smartphone (please complete the following information):**

The issue can be reproduced with all iOS phones. I used the following. 

 Device: iPhone 13 Pro
 OS: 15.6

**Intune App SDK for iOS (please complete the following information):**

Intune SDK: 16.1.1
MSAL: 1.2.3
Platform: Cordova

**Comment by darosal** [comment]
Hi @nevertheless1975, thanks for reaching out! Did this issue start occurring with a specific Intune SDK version?

Can you also confirm if there is an ADALAuthority set in the IntuneMAMSettings within the Info.plist?

**Comment by nevertheless1975** [comment]
Hi @darosal, I think I found the root cause. I explicitly did a de-register and MSAL logout prior (mainly for testing purposes). The de-registration failed, probably due to MSAL logout that happened first. If I don't do the MSAL logout, the de-register goes through and the enrollment as well without showing the timeout.
