### ISSUE TITLE
intune 无法绑定/ intune Unable to bind

### ISSUE THREAD

**Issue by slzButton** [msintuneappsdk/ms-intune-app-sdk-ios#275]
iOS提示未能完成操作：
1.使用intunesdk绑定账户。
2.跳转登录的web页面
3.alert提示Domain=MSALErrorDomain Code=-50000
4.之后再操作就无法绑定成功，提示-50002
5.intunesdk 14.6.0

The iOS message failed to complete the operation:
1. Bind the account using intunesDK.
2. Switch to the web page
3. Alert indicates Domain=MSALErrorDomain Code=-50000
4. If you perform subsequent operations, the binding fails, as shown in -50002
5. Intunesdk 14.6.0

Why did you prompt us with this error and find no solution on the official website
 
-50000 log

[Intune-com.hillhouse.gyapp-0.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/9624580/Intune-com.hillhouse.gyapp-0.txt)

-50002 log

[Intune-com.hillhouse.gyapp-0.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/9624581/Intune-com.hillhouse.gyapp-0.txt)

some info
[intuneLogMessage.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/9624583/intuneLogMessage.zip)

**Comment by Kyle-Reis** [comment]
Hi @slzButton. These errors indicate an issue with MSAL integrationin the application. Have you [followed all of the steps](https://github.com/AzureAD/microsoft-authentication-library-for-objc#microsoft-authentication-library-for-ios-and-macos) for integrating MSAL into the application?

**Comment by slzButton** [comment]
> Hi @slzButton. These errors indicate an issue with MSAL integrationin the application. Have you [followed all of the steps](https://github.com/AzureAD/microsoft-authentication-library-for-objc#microsoft-authentication-library-for-ios-and-macos) for integrating MSAL into the application?

我是使用的iOS sdk，有另一个账号可以绑定成功，这个绑定不成功的是一个新加的账号

I am using the iOS SDK, and there is another account that can be successfully bound, but the unsuccessful one is a newly added account

@Kyle-Reis

**Comment by slzButton** [comment]
是我们绑定账号的问题，有一个权限控制没有开启，实在抱歉啊

It is the problem of our binding account. One permission control is not enabled. I am really sorry
