### ISSUE TITLE
UIDocumentInteractionController Done action is hidden

### ISSUE THREAD

**Issue by OmarHassan25** [msintuneappsdk/ms-intune-app-sdk-ios#276]
**Describe the bug:**
I am using intune to wrap my apps,  all my users have a complaint that when they open PDF files inside the app they are unable to see the action bar DONE button, we are using Apple UIDocumentInteractionController to open the PDF files inside the app.

However, when I asked them to uninstall their apps and use a debug version without intune on the same devices they advised that the action bar DONE button appears on the same devices.

**Smartphone**
 - Device:
 iPhone 13 Pro max
 - OS: 
15.6 and 16

**Intune App SDK for iOS :**
- What version of the Intune SDK are you using? Are you using the latest version?
16.0.1

- What platform is your app based in?
Native
- For errors during build, does the app build without Intune SDK integration?
Yes
- For errors post build, does the app launch without being Intune SDK integrated?
Yes

- Do you see a trend with it only being reproduced on a specific device?
No, all devices

**Comment by Kyle-Reis** [comment]
Hi @OmarHassan25 - Does this issue reproduce with the latest release of the Intune SDK ([version 16.1.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/16.1.1) for apps compiled with Xcode 13 and [version 17.0.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/17.0.0) for apps compiled with Xcode 14)?

**Comment by dtatcbrain** [comment]
We've run into this issue as well. We're building with Xcode 14, Intune SDK 17.0 and running on iOS/iPad OS 16.1.

We tried switching from UIDocumentInteractionController to QLPreviewController from the QuickLook framework, but we get the same behaviour there - no Done/OK button to close the preview.

Both options (UIDocumentInteractionController and QLPreviewController) work just fine with the same code in the non-Intune version of our app.

Here's the code we use for previews with UIDocumentInteractionController:
```
  UIDocumentInteractionController *previewController = [UIDocumentInteractionController interactionControllerWithURL:fileUrl];
  previewController.delegate = self;
  previewController.name = displayFileName;
  BOOL presented = [previewController presentPreviewAnimated:YES];
```

Example fileUrl: file:///var/mobile/Containers/Data/Application/5C1ECF0C-CE3F-40B3-BF74-17CE1F7BA1A4/Library/Caches/documentcache/264486/Bestillinger%20%231771%20(Departementet%20(departementet%40departementet.dk))_F2_264489_0_264486_7.pdf

**Comment by dtatcbrain** [comment]
We just tried the new 17.1.1 SDK release, but are still missing a Done or OK button when showing document previews. We tested UIDocumentInteractionController as well as QLPreviewController again.

**Comment by Kyle-Reis** [comment]
Hi @dtatcbrain and @OmarHassan25 - I was able to reproduce this issue and am investigating the root cause. No ETA yet on a fix.

**Comment by dtatcbrain** [comment]
All right, appreciate the update :)

**Comment by Kyle-Reis** [comment]
@dtatcbrain and @OmarHassan25 - I've identified the root cause of this issue and expect a fix to be available in our next minor update (17.2.0)

**Comment by dtatcbrain** [comment]
Good to hear, thank you!

**Comment by OmarHassan25** [comment]
> @dtatcbrain and @OmarHassan25 - I've identified the root cause of this issue and expect a fix to be available in our next minor update (17.2.0)

Thanks a lot for updating us, we are hoping to see the fix soon.

**Comment by dtatcbrain** [comment]
Is there an ETA on the next release?

**Comment by OmarHassan25** [comment]
> 7.2.0

Hi @Kyle-Reis  When we should expect the new release 17.2.0?, do you have any ETA for it?

**Comment by Kyle-Reis** [comment]
Hi @OmarHassan25 and @dtatcbrain, we are targeting mid-January for release.

**Comment by dtatcbrain** [comment]
It is indeed, thanks! Appreciate the other fixes to previews as well.
