### ISSUE TITLE
Failed to find missing files

### ISSUE THREAD

**Issue by VictorKimbi** [msintuneappsdk/ms-intune-app-sdk-ios#279]
I am facing issues when pushing my changes to the repo, I am using DevOps for repo and running my pipiline but the pipileline fails for iOS build with error message: There is no XCFramework found at ‘/Users/Downloads/ms-intune-app-ask-iOS-master/IntuneMAMSwift.xcframework’ 

if anyone has faced same issues please assist.

**Comment by vigavadi** [comment]
Hey @VictorKimbi, how are you adding the IntuneMAMSwift xcframework? Can you send me a screenshot of where it's added in the project?

**Comment by VictorKimbi** [comment]
I am adding the files following the guide, click on the + to add to the Frameworks, Libraries, and Embedded Content list
![Uploading Screenshot 2022-10-03 at 17.26.08.png…]()

**Comment by VictorKimbi** [comment]
This guide https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios

**Comment by VictorKimbi** [comment]
![Uploading image.jpg…]()

**Comment by VictorKimbi** [comment]
@vigavadi  I am struggling to share a screenshot, keeps on saying uploading image but never uploads anything I hope I haver provided enough details for you.

**Comment by vigavadi** [comment]
@VictorKimbi Yeah the image doesn't show up here :( Let's try this, can you create an Intune folder within your project, add IntuneMAMSwift.xcframework and IntuneMAMSwiftStub.xcframework there and then try to link those.

**Comment by VictorKimbi** [comment]
@vigavadi I have created the Intune folder and linked the files, that actually helped to fix the pipeline issue I the path was an issue. Thank you!

**Comment by vigavadi** [comment]
Glad it worked. :)
