### ISSUE TITLE
ADAL with broker in Xamarin iOS. Please suggest how to do the process in MVVM Cross

### ISSUE THREAD

**Issue by sureshbabu4** [msintuneappsdk/ms-intune-app-sdk-ios#28]
Hi Folks,

Could you please suggest to do the process of SSO with broker in Intune with Xamarin.iOS,
After integration of ADAL to Intune only one sign in. I think we need to send some token to intune api or something other procedure please help me out.Briefly explain Folks

Thanks in Advance
Suresh.

**Comment by sureshbabu4** [comment]
this is Xamarin issue not related native iOS

**Comment by prsreejith** [comment]
Hi Suresh 

Please follow the instructions shared in the below given link

https://cloudwatching.home.blog/2019/06/01/configure-xamarin-ios-app-intune-sdk-with-adal/

Thanks
