### ISSUE TITLE
MAM policy issue

### ISSUE THREAD

**Issue by VictorKimbi** [msintuneappsdk/ms-intune-app-sdk-ios#281]
Hello, I am getting this error message when calling the IntuneMAMEnrollment function "The account is licensed for Intune but is not targeted with MAM policy" can someone please help me.

**Comment by Kyle-Reis** [comment]
Hi @VictorKimbi, this status is returned to the application when the enrolling account does not have any Intune app protection policies or app configuration policies targeted to it for your application. You can follow [this guidance](https://learn.microsoft.com/mem/intune/apps/app-protection-policies) to target app protection policies to both the app and user, and you can follow [this guidance](https://learn.microsoft.com/mem/intune/apps/app-configuration-policies-managed-app) to target app configuration policies.
