### ISSUE TITLE
Copy To Actions List of Apps is not being filtered

### ISSUE THREAD

**Issue by chasemac** [msintuneappsdk/ms-intune-app-sdk-ios#282]
**Describe the bug:**
I followed all of the documentation on here:
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#copy-to-actions
However, the end result has not changed to this expected result:
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#what-the-ui-should-look-like
 
The only thing I didn’t do was  IntuneMAMConfigurator – generateOpenInIcons because it fauled with the error: “Failed to generate icons.”
 
**To Reproduce**
1. Open file with QuickLook viewer
2. Tap on share button in the bottom left
3. Shared options are not restricted to Intune applications
 
**Expected behavior:**
Only Intune applications are visible in the shared app section
 
**Screenshots and logs:**
 
![IMG_1976](https://user-images.githubusercontent.com/13863121/199635169-091d1468-36d4-4c5b-9d13-25efe84d9c09.PNG)

**Smartphone (please complete the following information):**
- Device: iPhone 14 Pro
- OS: 16.1
 
**Intune App SDK for iOS (please complete the following information):**
- Intune 17.0

**Comment by abasore** [comment]
Hi @chasemac, the SDK will filter non-Intune apps from the Share view only if data transfer policy is restrictive. Can you confirm if policy "Send Org data to other apps" for this user is set to "Policy managed apps with Open-In/Share filtering"?

**Comment by chasemac** [comment]
<img width="786" alt="image001" src="https://user-images.githubusercontent.com/13863121/202060678-a61574ef-7fb2-4c50-9adb-930d191ba324.png">

**Comment by abasore** [comment]
@chasemac in this case it would be helpful in debugging this issue to have Intune logs. Could you open a request by going to "Troubleshooting + support" -> "Help and support" -> "Intune" in Endpoint Manager? If you could collect them by calling the API mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app)

**Comment by abasore** [comment]
Closing this issue for now. Feel free to reopen if issue persists or if you are not able to upload logs with Intune Support.

**Comment by abasore** [comment]
@chasemac can you attempt confirm if you are able to repo with the latest 17.2.0 release now abvaliable?

**Comment by chasemac** [comment]
Is this something that might have been fixed in the last release? If so, I might have time to test next week.

**Comment by abasore** [comment]
Yes, we expect this issue to be resolved with 17.2.0

**Comment by chasemac** [comment]
I've update Intune to 17.2 and I'm still experiencing the same issue where the share sheet has non-Intune apps on it.

**Comment by abasore** [comment]
@chasemac, this issue is being investigated as an incident by a member of the Intune SDK team. We will be working on getting a fix ASAP

**Comment by chasemac** [comment]
It appears your team's "fix" broke another part of the app. I have a support ticket open. Case 34573019. 

I uploaded logs and shared screenshots and swift files.
