### ISSUE TITLE
Offline access to Intune enabled apps

### ISSUE THREAD

**Issue by luky88** [msintuneappsdk/ms-intune-app-sdk-ios#284]
**Describe the bug:**
Using the latest versions of the Intune SDK, at least since 16.1.1, trying to use an Intune enabled application without Internet access is not possible in most cases.

It seems to be related to a kind of Intune token that needs to be refreshed online.

**To Reproduce**
1. Launch the app and enroll the user
2. Wait at least 1 day after the first user enrollment in the app
3. Put the device in airplane mode or disable the Internet connections
4. Launch the app
5. See error

**Expected behavior:**
Possibility to always launch the app, after the first enrollment, even if the device is offline.

**Screenshots and logs:**
See attached screenshots of the Intune alerts.

![IMG_0049](https://user-images.githubusercontent.com/6715432/200788496-db8481ef-ab53-4bd4-bde9-070b187ec60c.PNG)
![IMG_0050](https://user-images.githubusercontent.com/6715432/200788505-bac50a35-6565-4b08-8071-0c0de5a42859.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone and iPad
 - OS: iOS 15.7 and 16.x

**Comment by Kyle-Reis** [comment]
Hi @luky88, what you are seeing is an intended design change in the way that the offline grace period "block access" action policy is enforced, beginning in [version 16.1.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/16.1.1) of the Intune SDK. For clarity, I'm referring to the 2nd policy setting in this list:
![image](https://user-images.githubusercontent.com/7443106/192361093-384ac81d-a137-438d-a77b-777b0644aade.png)

 
Prior to this change, policy enforcement was based solely on whether the device was internet connected, and the timer would only begin after the app was first launched while the device was not connected to the internet.
 
After the change, the "block access" policy now behaves consistently with the "wipe data" offline grace period policy:
 
When the app is brought to the foreground, the SDK checks when the last successful policy checkin occurred, and if the time elapsed exceeds the value provided for this policy setting, it will attempt a policy checkin. If that checkin fails for any reason, user is presented with options to try signing in to refresh their AAD tokens, remove the account, or to close the app.

If you think users within your organization (or your customer's organization, if the app is developed for a 3rd party) might encounter this UI too frequently, then I would recommend increasing the timeout above to a value that you/they feel is a reasonable balance between usability and security.

**Comment by lucac-apps** [comment]
> Hi @luky88, what you are seeing is an intended design change in the way that the offline grace period "block access" action policy is enforced, beginning in [version 16.1.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/16.1.1) of the Intune SDK. For clarity, I'm referring to the 2nd policy setting in this list: ![image](https://user-images.githubusercontent.com/7443106/192361093-384ac81d-a137-438d-a77b-777b0644aade.png)
> 
> Prior to this change, policy enforcement was based solely on whether the device was internet connected, and the timer would only begin after the app was first launched while the device was not connected to the internet.
> 
> After the change, the "block access" policy now behaves consistently with the "wipe data" offline grace period policy:
> 
> When the app is brought to the foreground, the SDK checks when the last successful policy checkin occurred, and if the time elapsed exceeds the value provided for this policy setting, it will attempt a policy checkin. If that checkin fails for any reason, user is presented with options to try signing in to refresh their AAD tokens, remove the account, or to close the app.
> 
> If you think users within your organization (or your customer's organization, if the app is developed for a 3rd party) might encounter this UI too frequently, then I would recommend increasing the timeout above to a value that you/they feel is a reasonable balance between usability and security.

Hi @Kyle-Reis,

is it possible to disable/neutralise all togetgher these two policy settings:
Offline grace period - Block access
Offline grace period - Wipe data

We created our own logic in the apps to remove corporate data from unused apps and devices.

**Comment by Kyle-Reis** [comment]
@lucac-apps - Both of these policy settings are required.
