### ISSUE TITLE
Building the app with Apple Silicon - The data couldn’t be read because it isn’t in the correct format. 

### ISSUE THREAD

**Issue by dragantr** [msintuneappsdk/ms-intune-app-sdk-ios#286]
**Describe the bug:**
Building the app on MacBook with Apple Silicon failed with the error "The data couldn’t be read because it isn’t in the correct format.". On Intel MacBook, everything is working properly.

**To Reproduce**
1. On MacBook with Apple Silicon chip, create a new project
2. Embed the Intune SDK following the documentation https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios
3. Build the app
4. See error log:
The data couldn’t be read because it isn’t in the correct format.

**Expected behavior:**
The app should build without any error

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
<img width="820" alt="Screen Shot 2022-11-15 at 10 14 25" src="https://user-images.githubusercontent.com/3366519/201889853-aeb9cea1-3fe1-42b9-b413-5ad496b45f29.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 13, iOS 16.1
 - MacBook: MacBook Pro (14-inch, 2021), M1 Pro

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 17.0.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? N/A

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by neiljac1** [comment]
Hi @dragantr. It looks like you are trying to build a macOS target. Make sure the Mac Catalyst option is unchecked in your target's Deployment section. Mac Catalyst is not supported.

Thank you,
Neil

**Comment by neiljac1** [comment]
Hi @dragantr. Can you provide a sample project file exhibiting this issue?

Thanks,
Neil

**Comment by dragantr** [comment]
hi @neiljac1 I attached the test project.

[Intune Test.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/10033152/Intune.Test.zip)

Thanks,
Dragan
