### ISSUE TITLE
Do Access Requirements block network traffic?

### ISSUE THREAD

**Issue by chasemac** [msintuneappsdk/ms-intune-app-sdk-ios#287]
My app is set up to require user to authenticate every 30 min. If I try to run a background task that is launched an hour after the user stops using the app, will Intune block the apps access to the internet? 

<img width="615" alt="Screenshot 2022-11-15 at 5 28 58 PM" src="https://user-images.githubusercontent.com/13863121/202060921-bd8a525d-2708-4884-8683-419dde302463.png">

Is there some sort of delegate method where I can tell if the app is waiting for the user to provide the access requirements? And can I be notified when that was completed?

Thanks!

**Comment by neiljac1** [comment]
Hi @chasemac. The Intune MAM SDK won't interfere with background tasks or any network operations. In general, the SDK doesn't have a delegate or notification letting the application know when the conditional launch UI is displayed or dismissed. However, if your application is configured as a multi-identity application and you call IntuneMAMPolicyManager setUIPolicyIdentity setting the account, there is a completion handler which will be called after the Intune UI is displayed and dismissed.

Thanks,
Neil
