### ISSUE TITLE
Is it possible to integrate flutter SDK app with Intune MAM policy?

### ISSUE THREAD

**Issue by AshrafulTuhin** [msintuneappsdk/ms-intune-app-sdk-ios#288]
We have a LOB application developed in Flutter. We need to apply Intune MAM policy for that Application but there is no official article from Microsoft for Flutter App integration with Intune. We have followed bellow URL but no luck 
•	https://learn.microsoft.com/en-us/mem/intune/developer/apps-prepare-mobile-application-management
•	https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk
•	https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin
•	https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-android 
•	https://learn.microsoft.com/en-in/mem/intune/apps/apps-supported-intune-apps
 
Is there any URL or guideline for Flutter app integration with Intune?

**Comment by neiljac1** [comment]
Hi @AshrafulTuhin. The Intune MAM SDK doesn't officially support Flutter. However you should be able to open the Runner project file to make the changes necessary to link to the Intune MAM SDK and use the Flutter documentation on how to call into native code. 

Thanks,
Neil
