### ISSUE TITLE
remediateComplianceForIdentity is not called even delegate is implemented

### ISSUE THREAD

**Issue by rjvishnu87** [msintuneappsdk/ms-intune-app-sdk-ios#290]
I have implemented the delegate in willFinishLaunchingWithOptions
I am calling             IntuneMAMComplianceManager.instance().remediateCompliance(forIdentity:username, silent: true)
after getting the error. 
But I am not getting the callback compliance request is finished or not. Because of this my login flow is broken. 

If the user swipe kill the app during the compliance process, we are not able to find the status properly on next launch.

**Comment by rjvishnu87** [comment]
any update on this?

**Comment by vigavadi** [comment]
@rjvishnu87 Are you calling the hasComplianceStatus delegate method as mentioned here: [App protection CA support](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#app-protection-ca-support-optional)

Where are you setting the delegate? Make sure you set it in the willFinishLaunchingWithOptions AppDelegate method. Also, you need to make sure you hold a strong reference to it.

**Comment by rjvishnu87** [comment]
I have implemented like this way in app delegate, 

- (BOOL)application:(UIApplication *)application willFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey,id> *)launchOptions {
    [IntuneMAMComplianceManager instance].delegate = self;
    return true;
}

Please check this and comment if anything wrong.

**Comment by rjvishnu87** [comment]
Please update us on next steps.

**Comment by vigavadi** [comment]
You need to hold a strong reference to the delegate. Try initializing it first and then set the delegate. 
Checkout this sample code for reference: [AppDelegate.m](https://github.com/msintuneappsdk/wagr/blob/main/Wagr/Application/Main/AppDelegate.m)

**Comment by rjvishnu87** [comment]
Thanks for the help. We resolved the issue by checking the enrolledaccount value.
