### ISSUE TITLE
Does the Intune SDK offer any mehtod to verify whether an app available on the company portal has been installed on the device?

### ISSUE THREAD

**Issue by lucac-apps** [msintuneappsdk/ms-intune-app-sdk-ios#293]
Does the Intune SDK offer any mehtod to verify whether an app available on the company portal has been installed on the device?

In case it does not; is there any Graph API we can query directly from our code to get this information?

**Comment by Kyle-Reis** [comment]
Hi @lucac-apps, there is no API available on the Intune MAM SDK to query for this information. I'm unsure if any such Graph API exists, but would recommend checking the [documentation](https://learn.microsoft.com/graph/).

**Comment by lucac-apps** [comment]
> Hi @lucac-apps, there is no API available on the Intune MAM SDK to query for this information. I'm unsure if any such Graph API exists, but would recommend checking the [documentation](https://learn.microsoft.com/graph/).

Hi Kyle,

following your advice (thanks again) we did find a Beta Graph Api that fits for purpose: https://learn.microsoft.com/en-us/graph/api/resources/intune-apps-mobileappinstallstatus?view=graph-rest-beta 

We configured in azure the delegated permission from this name space: DeviceManagementApps.Read.All for our users.
However we get a very strange error back when we try to use an endpoint under it:
401 Unauthorized - Error/code: UnknownError

All other graph api end points used in our app work perfectly; we double checked the azure setup n times and it seems correct and equal to what we setup for the end points that we use succesfully.

Do you have any idea on what the issue may be?
