### ISSUE TITLE
Datepicker crashes the app

### ISSUE THREAD

**Issue by VictorKimbi** [msintuneappsdk/ms-intune-app-sdk-ios#295]
Our Android application crashes when using date picker, if we use ReactActivity it works fine but if we use MAMActivity it crashes.

anyone who faced same issue?

**Comment by Kyle-Reis** [comment]
Hi @VictorKimbi, this repository is specifically for the iOS Intune MAM SDK. You might have better luck getting this issue addressed by filing an issue here: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues
