### ISSUE TITLE
Unable to share documents via local file url through UIActivityViewController.

### ISSUE THREAD

**Issue by santosh0045** [msintuneappsdk/ms-intune-app-sdk-ios#299]
**Describe the bug:**

Platform: iOS
I have set Intune policy Send org data to other apps to policy managed Apps. In my app I am trying to download the onedrive file to local storage and share the file using UIActivityViewController. Share tray opens and when I select outlook, outlook share extension opens but I don't see any attachment in the outlook share extension.  (Have added outlook and other microsoft apps as policy managed app in intune settings.)

Am I missing some intune mam settings in my app info.plist due to which I am seeing this issue.

Below are the some logs captured in xcode.

[ShareSheet] Failed to request default share mode for fileURL:file:///private/var/mobile/Containers/Data/Application/E4ECAB22-0EAA-4083-963E-9B155DDB731A/tmp/.IntuneMAM/19_01_23,%205_08%20AM%.JPEG error:Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=1538, _LSFunction=runEvaluator}

**Comment by vigavadi** [comment]
@santosh0045 Which version of the SDK are you using?

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
