### ISSUE TITLE
Unable to get token silent for the first time using ADAL

### ISSUE THREAD

**Issue by karunagarajan** [msintuneappsdk/ms-intune-app-sdk-ios#30]
When trying to loginAndEnrollAccount() SDK Prompts user login and does not sign in silently without prompt even when trying to use the ADAL Library to get token silent.

**Comment by Kyle-Reis** [comment]
Hey @karunagarajan, this is by design. loginAndEnrollAccount is intended for apps that do not already use ADAL to authenticate. You should use registerAndEnrollAccount for your scenario:

https://docs.microsoft.com/intune/app-sdk-ios#apps-that-use-adal

**Comment by karunagarajan** [comment]
When I try to use the "registerAndEnrollAccount" I am getting the following error. 
"The operation failed because the SDK could not access the user\'s AAD token.  The application should prompt the user for credentials to refresh the user\'s AAD token."
But as part of ADAL auth I already have a token.

**Comment by Kyle-Reis** [comment]
Did you configure the ADAL settings under the IntuneMAMSettings dictionary as mentioned [here](https://docs.microsoft.com/en-us/intune/app-sdk-ios#configure-adal-settings-for-the-intune-app-sdk)?

I strongly recommend reading through our entire iOS SDK guide as there is a lot of important information in the doc about properly integrating our SDK.

**Comment by karunagarajan** [comment]
Yes,  Following properties have been configured in the IntuneMAMSettings dictionary.
1) ADALAuthority
2) ADALClient
3) ADALRedirectUri
4) MainStroryBoardFile

**Comment by Kyle-Reis** [comment]
And these properties all match what your app is using? 

If so, I have a few questions for you:
Which version of ADAL are you using?
What do you have set for keychain access groups in the entitlements file of your app?
Does your app change the default token cache location used by ADAL?
Are you testing in an ADFS environment?

**Comment by karunagarajan** [comment]
Thanks a lot. registerAndEnrollAccount worked for me. just want to understand , when I try to authenticate to ADAL via broker app, for the very-first time it redirecting to broker (authenticator app), the broker prompts for login . Since my device is  already managed through company portal and is of compliance status. How can make the broker app to show my account for the very first time rather than prompting login screen.

**Comment by Kyle-Reis** [comment]
Glad to hear that it's working for you! Your question about SSO between Company Portal and Authenticator is outside the scope of mobile app management, and thus, outside the scope of my knowledge :) But I'll see if I can find the right person or place for you to ask

**Comment by Kyle-Reis** [comment]
Hey @karunagarajan, I did a little digging on your question and learned that the broker needs to authenticate users the very first time an app redirects to it. Even if the device is already managed with that user’s account.
