### ISSUE TITLE
Xcode prompts a warning while upload to appstore connect

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#301]
Warning:

The app references non-public selectors in Payload/<my app>.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift: additionalProperties, cancelAllTasks:, providerId, setPromptType:

SDK version 17.2.1

**Comment by dtatcbrain** [comment]
We got this as well when uploading with the latest SDK (17.2.1).

**Comment by rjvishnu87** [comment]
Even we got this.

**Comment by Kyle-Reis** [comment]
Hi all, thanks so much for reporting these. I just want to confirm: These are currently just warnings and not preventing you from uploading to the app store, correct?

**Comment by dtatcbrain** [comment]
Not sure - we were able to send the app out for testing but haven't tried a review for app store yet. We're holding back on that as we're waiting for another Intune bug to be solved.

**Comment by rjvishnu87** [comment]
> Hi all, thanks so much for reporting these. I just want to confirm: These are currently just warnings and not preventing you from uploading to the app store, correct?

Yes, just the warning, we are able to upload the app to appstore. 
But we need this to be fixed soon otherwise anytime near future, build can be blocked by apple. We dont know when.
