### ISSUE TITLE
App crashed and stacktrace shows cmarDeviceComplianceEnabled EXC_BAD_ACCESS (KERN_PROTECTION_FAILURE)

### ISSUE THREAD

**Issue by rjvishnu87** [msintuneappsdk/ms-intune-app-sdk-ios#304]
**Describe the bug:**
App crashed while performing search operation inside our app. In firebase it shows the below stack trace. 
**To Reproduce**

**Expected behavior:**
App should not get crashed. 
**Screenshots and logs:**
-cmarDeviceComplianceEnabled
EXC_BAD_ACCESS (KERN_PROTECTION_FAILURE)

Crashed: com.apple.main-thread
0  libsystem_pthread.dylib        0xbe4 thread_chkstk_darwin + 60
1  libsystem_pthread.dylib        0xbe4 ___chkstk_darwin + 60
2  CoreAutoLayout                 0xdaec -[NSISEngine _flushPendingRemovals] + 48
3  CoreAutoLayout                 0x7730 -[NSISEngine tryToAddConstraintWithMarker:expression:mutuallyExclusiveConstraints:] + 80
4  CoreAutoLayout                 0x75e4 -[NSLayoutConstraint _addLoweredExpression:toEngine:lastLoweredConstantWasRounded:mutuallyExclusiveConstraints:] + 236
5  CoreAutoLayout                 0x18c8 -[NSLayoutConstraint _addToEngine:mutuallyExclusiveConstraints:] + 152
6  UIKitCore                      0x5b664 -[UIView _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:] + 560
7  UIKitCore                      0x3f664 -[UIView _tryToAddConstraint:roundingAdjustment:mutuallyExclusiveConstraints:] + 160
8  UIKitCore                      0x5d5b0 -[UIView(UIConstraintBasedLayout) nsli_addConstraint:] + 76
9  UIKitCore                      0x5d450 -[UIView _updateContentSizeConstraints] + 504
10 UIKitCore                      0xf0ab0 -[UIView(AdditionalLayoutSupport) _updateSystemConstraints] + 88
11 UIKitCore                      0xfef448 -[UILabel _updateSystemConstraints] + 52
12 UIKitCore                      0xf0984 -[UIView(AdditionalLayoutSupport) _sendUpdateConstraintsIfNecessaryForSecondPass:] + 348
13 UIKitCore                      0xf071c -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 764
14 UIKitCore                      0xf0638 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 536
15 UIKitCore                      0xf0638 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 536
16 CoreAutoLayout                 0x4e90 -[NSISEngine withBehaviors:performModifications:] + 84
17 UIKitCore                      0xf0b6c -[UIView(AdditionalLayoutSupport) _recursiveUpdateConstraintsIfNeededCollectingViews:forSecondPass:] + 132
18 UIKitCore                      0xf0638 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 536
19 UIKitCore                      0xf0414 __100-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:]_block_invoke + 104
20 UIKitCore                      0x92bf0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:] + 172
21 UIKitCore                      0x927f0 -[UIView(AdditionalLayoutSupport) _updateConstraintsAtEngineLevelIfNeededWithViewForVariableChangeNotifications:] + 388
22 UIKitCore                      0x921f0 -[UIView _updateConstraintsAsNecessaryAndApplyLayoutFromEngine] + 332
23 UIKitCore                      0x5080 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2076
24 QuartzCore                     0x99ec CA::Layer::layout_if_needed(CA::Transaction*) + 500
25 UIKitCore                      0xd21dc -[UIView(Hierarchy) layoutBelowIfNeeded] + 292
26 UIKitCore                      0x31564 +[UIView(Animation) performWithoutAnimation:] + 76
27 UIKitCore                      0x14c09c -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 1688
28 UIKitCore                      0x11f844 -[UITableView _updateVisibleCellsForRanges:createIfNecessary:] + 596
29 UIKitCore                      0x59350 -[UITableView _updateVisibleCellsNow:] + 1088
30 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
31 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
32 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
33 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
34 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
35 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
36 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
37 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
38 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
39 UIKitCore                      0x59620 -[UITableView _updateVisibleCellsNow:] + 1808
40 UIKitCore                      0x58e44 -[UITableView layoutSubviews] + 148
41 UIKitCore                      0x5020 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1980
42 QuartzCore                     0x99ec CA::Layer::layout_if_needed(CA::Transaction*) + 500
43 QuartzCore                     0x1d0a0 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 148
44 QuartzCore                     0x2e5b0 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 456
45 QuartzCore                     0x635ec CA::Transaction::commit() + 652
46 QuartzCore                     0x4c8cc CA::Transaction::flush_as_runloop_observer(bool) + 88
47 CoreFoundation                 0x91d60 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
48 CoreFoundation                 0x1a2d0 __CFRunLoopDoObservers + 532
49 CoreFoundation                 0x7bc7c __CFRunLoopRun + 1048
50 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
51 GraphicsServices               0x1368 GSEventRunModal + 164
52 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
53 UIKitCore                      0x3a2034 UIApplicationMain + 340
54 IntuneMAMSwift                 0x2730b4 cmarDeviceComplianceEnabled + 2092348
55 MultiLine for Intune           0xc6a98 main + 36 (main.m:36)
56 ???                            0x1d0768960 (Missing)

**Smartphone (please complete the following information):**
 - Device
Model:iPhone 11
Orientation: Portrait
RAM free: 46.08 MB
Disk free: 2.37 GB

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- 17.2.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- iOS

- Do you see a trend with it only being reproduced on a specific device?
- No, we saw 3 users faced this issue. 

**Additional context:**

**Comment by rjvishnu87** [comment]
Can we have update on this issue ? 
Is this related to intune library or other ?

**Comment by neiljac1** [comment]
Hi @rjvishnu87. It's normal to see a call frame from Intune on the main thread below the UIApplicationMain call. Unless there are more frames higher up, then Intune code is not running which is this case. This crash isn't related to Intune.

Thanks,
Neil
