### ISSUE TITLE
Delegate methods do not fire

### ISSUE THREAD

**Issue by chrisnok** [msintuneappsdk/ms-intune-app-sdk-ios#305]
**Describe the bug:**
I'm not able to get ANY delegates to fire. Intune enrollment works fine (I'm enrolled and the app becomes secured by a PIN), but not I never get any activity in the delegate methods.

Example:
```
import IntuneMAMSwift

class AViewController: UIViewController, IntuneMAMWebViewPolicyDelegate {

  func isExternalURL(_ url: URL) -> Bool {
    print("ViewController.isExternalURL", url.absoluteString)
    DispatchQueue.main.async {
        let alert = UIAlertController(title: "PolicyDelegate", message: "isExternalURL: \(url.absoluteString)", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default))
        self.present(alert, animated: true)
    }
    return true
  }
  
  func openURL(_ url: URL) {
    let safariViewController = SFSafariViewController(url: url)
    IntuneMAMPolicyManager.instance().setWebViewPolicyDelegate(self, forWebViewer: safariViewController)
    self.present(safariViewController, animated: true)
  }
}
```

In the example, I receive no print logs or alerts. I have tested this from the debugger and from an app distributed through Company Portal. IntuneMAMDiagnosticConsole.display() works fine and show no issues.

**Versions:**
SDK: 17.2.1
iOS: 16.1.1
MSAL: 1.2.8

**Comment by gastaffo** [comment]
Can you show the code where you are calling `-[IntuneMAMPolicyManager setDelegate:]` ?

**Comment by chrisnok** [comment]
Ok, so I was able to detect that `restartApplication` is being triggered now, but not `enrolledRequestWithStatus` and `isExternalURL`. Maybe there is something I don't understand about the flow here. Here's a slimmed down version of my AppDelegate.

```
import MSAL
import IntuneMAMSwift

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate, IntuneMAMEnrollmentDelegate, IntuneMAMPolicyDelegate, IntuneMAMComplianceDelegate {

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {

    IntuneMAMEnrollmentManager.instance().delegate = self
    IntuneMAMPolicyManager.instance().delegate = self
    IntuneMAMComplianceManager.instance().delegate = self

    ...
  }

  func enrollmentRequestWithStatus(status: IntuneMAMEnrollmentStatus) {
      print("IntuneDelegate.enrollmentRequestWithStatus", status)
      
      if status.didSucceed {
          print("IntuneDelegate.enrollmentRequestWithStatus - enroll successful")
      }
      else {
          print("Enrollment result for identity \(status.identity) with status code \(status.statusCode)")
          print("Debug message: \(String(describing: status.errorString))")
      }
  }

  func restartApplication() -> Bool {
    print("IntuneDelegate.restartApplication")
    
    // Let Intune handle restart
    return false
  }
}
```

I get no printouts that the app completes the enrollment (or fails), but I do get the print "IntuneDelegate.restartApplication" and the popup "Your organization is now protecting its data in this app. You need to restart the app to continue."

And I get the following when printing out the delegate later:
```
print("IntuneMAMEnrollmentManager.instance().delegate =", IntuneMAMEnrollmentManager.instance().delegate)
print("IntuneMAMPolicyManager.instance().delegate =", IntuneMAMPolicyManager.instance().delegate)
```
->
```
IntuneMAMEnrollmentManager.instance().delegate = Optional(<App.AppDelegate: 0x2808d9c00>)
IntuneMAMPolicyManager.instance().delegate = Optional(<App.AppDelegate: 0x2808d9c00>)
```

**Comment by gastaffo** [comment]
Im guessing its from you method names as the conversion between Obj-C selectors and swift functions can be tricky. For example your `enrollmentRequestWithStatus(status: IntuneMAMEnrollmentStatus)` should be `enrollmentRequest(with status: IntuneMAMEnrollmentStatus)`.

If you don't want to manually try and figure out exact selector conversion from Obj-C to Swift you can try annotating your swift functions with `@objc(selector)`. For example `@objc(enrollmentRequestWithStatus:)  func enrollmentRequestWithStatus(status: IntuneMAMEnrollmentStatus)` should work.

**Comment by chrisnok** [comment]
You're 100% right! I tried a direct translation from IntuneMAMEnrollmentDelegate.h which did not work.

The only problem left is `IntuneMAMWebViewPolicyDelegate` and `isExternalURL`. I have tried adding `TreatAllWebViewsAsUnmanaged` to `IntuneMAMSettings` and using `setWebViewPolicy` to .unmanaged. But I can't seem to either trigger the `isExternalURL` method or prevent copy-paste (which is clearly stopped when copying something in the app and pasting it outside the app).

The `isExternalURL` method is autocompleted by xcode so I don't think that the name is wrong here.

**Comment by darosal** [comment]
Hi @chrisnok, can you confirm that the `IntuneMAMPolicyManager`'s `setWebViewPolicyDelegate:forWebViewer:` method is being used to tie the `IntuneMAMWebViewPolicyDelegate` to the webview? If the delegate is not set in this way, the `isExternalURL` method will not be called.

Also, can you expand on your app's desired behavior surrounding copy/paste and webviews?

**Comment by chrisnok** [comment]
@darosal Yes, `setWebViewPolicyDelegate:forWebViewer` is used as shown in the my first comment. 

The desired behavior is to control if the webview is managed or unmanaged to make sure copy/paste does not allow the user to leak sensitive data. The app includes corporate webviews that are sensitive and webviews that allow the user to surf unimpeded. I have not been able to make the webviews unmanaged.

**Comment by darosal** [comment]
@chrisnok, Ah sorry for missing that! That looks right to me. I started a sample project and was able to get a breakpoint hitting in isExternalURL using the following code and it looks near identical to yours.

```swift
import UIKit
import IntuneMAMSwift
import SafariServices

class ViewController: UIViewController, IntuneMAMWebViewPolicyDelegate {

    func isExternalURL(_ url: URL) -> Bool {
        return false
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }

    @IBAction func presentSFViewController(_ sender: Any) {
        let safariViewController = SFSafariViewController(url: URL(string: "https://bing.com")!)
        IntuneMAMPolicyManager.instance().setWebViewPolicyDelegate(self, forWebViewer: safariViewController)
        self.present(safariViewController, animated: false)
    }

}
```

Could you post a screenshot of the presented SFSafariViewController? The isExternalURL delegate method will only fire when an enrolled account is viewing the web view. The SFSafariViewController should have slightly different chrome around it when being used by an enrolled account vs an account with no MAM policies.

Does your app specify in the Info.plist's IntuneMAMSettings that it supports multiple identities? If so, the delegate might not be firing because the enrolled account might not be the active ui policy identity.

**Comment by chrisnok** [comment]
Here's the SFSafariViewController (with Edge requirement)
![IMG_0381](https://user-images.githubusercontent.com/83590140/219299792-2d02ed3c-422c-4488-af73-76184588705c.png)

Here's the IntuneMAMSettings
![settings](https://user-images.githubusercontent.com/83590140/219300279-ca5f704f-749b-4253-beaf-14b4ccf410eb.jpg)

I have also tried setting `TreatAllWebViewsAsUnmanaged` in the Info.plist (both in IntuneMAMSettings and outside, since the documentation didn't specify), but I still get a managed browser.

Here's a ugly printout of `appConfig.fullData` in case there is something wrong there:
```
[[
AnyHashable("com.microsoft.intune.mam.managedbrowser.AllowTransitionOnBlock"): true, 
AnyHashable("***.usemsal"): true,
AnyHashable("com.microsoft.intune.mam.managedbrowser.AppProxyRedirection"): false, 
AnyHashable("***.scopes"): openid profile email offline_access calendars.read.shared calendars.readwrite user.read user.readbasic.all], 
[AnyHashable("__IsDefault"): true, 
AnyHashable("com.microsoft.intune.mam.menufilter.action"): 0;elem;DDSearchWebAction;pair;0;elem;DDOpenURLAction;pair;0;elem;DDAddToReadingListAction;pair;0;elem;DDShowCalendarAction;pair;0;elem;DDCreateReminderAction;pair;0;elem;DDCreateEventAction;pair;0;elem;DDTrackShipmentAction;pair;0;elem;DDAddToAddressBookAction;pair;0;elem;DDFaceTimeAudioAction;pair;0;elem;DDFaceTimeAction;pair;0;elem;DDTextMessageAction;pair;0;elem;DDFlightAction;pair;0;elem;DDPersonAction;pair;0;elem;DDTimeLineAction;pair;0;elem;DDURLPreviewAction;pair;0;elem;DDFlightPreviewAction;pair;0;elem;DDMessagesCustomAction;pair;0;elem;DDGenericURLPreviewAction;pair;0;elem;DDAddEventAction;pair;0;elem;DDNewsPreviewAction;pair;0;elem;DDSendMailAction;pair;0;elem;DDAppleStorePreviewAction;pair;0;elem;DDParsecYeaAction;pair;0;elem;DDParsecNayAction;pair;0;elem;DDParsecAction;pair;0;elem;DDParsecPreviewAction;pair;0;elem;DDClientPreviewAction;pair;0;elem;DDMoneyPreviewAction;pair;1;elem;DDCallAction;pair;1;elem;DDTelephoneNumberAction;pair;1;elem;DDAssistedCallAction;pair;1;elem;DDTTYCallAction;pair;1;elem;DDRelayCallAction;pair;1;elem;DDCallKitAction;pair;1;elem;DDSingleCallKitAction;pair;1;elem;DDMoreCallActionsAction;pair;2;elem;DDOpenMapsAction;pair;2;elem;DDDirectionsAction;pair;2;elem;DDAddressAction;pair;2;elem;DDMapAction], 
[AnyHashable("com.microsoft.intune.useEdge"): true
]]
```

**Comment by darosal** [comment]
Thanks for the screenshot. That confirms that it is a managed SFSafariViewController so the IntuneMAMWebViewPolicyDelegate should be getting set correctly.

I was able to get the same behavior when "Send org data to other apps" policy for the user was set to "All apps". Does the isExternalURL delegate method fire when the user's "Send org data to other apps" policy is set to "Policy managed apps"?

**Comment by chrisnok** [comment]
Yep, you found the issue. `isExternalURL` fires when "Send org data to other apps" policy is set to "Policy managed apps". `setWebViewPolicy` also work.

It makes sense that "Restrict cut, copy, and paste between other apps" and "Send org data to other apps" are contextually connected, but it makes handling contradictory configurations (ex. restrict clipboard + allow all data transfer) somewhat tricky. I guess we just have to put this relation in our documentation so our customers don't end up with any security holes.

However, I do believe that IntuneMAMWebViewPolicyDelegate should be available with "Send org data to other apps" set to "All apps", since that would allow the app to control the security context of internal web views in all use cases.
