### ISSUE TITLE
Accessing Your Organization's Data on Second login MAM

### ISSUE THREAD

**Issue by byhkalo** [msintuneappsdk/ms-intune-app-sdk-ios#307]
Hello everyone,

**Describe the bug:**
We have a bug with the MAM authentication step.
Everything works fine when a user tries to log in the first time (or after application termination). Smooth, fast, okay.

If users log out and log in again, they can see the _Accessing Your Organization's Data_ window, and it asks to install the Microsoft Authenticator application.

**To Reproduce**
Steps to reproduce the behaviour:

---- ⏳ Preparing Conditions ----
1. Configure the [endpoint.microsoft.com](endpoint.microsoft.com)
    1.1 Create the Conditional Access rule, assign it to the User
    1.2 Set in **Grand** section: 
        1.2.1 ✅ Require the device to be marked as compliant
        1.2.2 ✅ Require app protection policy
        1.2.3 ✅ Require all the selected controls
    1.3 Set in **Conditions** -> **Client apps** section: 
        1.2.1 ❌ _Exclude_ Browser
        1.2.2 ✅ Mobile apps and desktop clients
        1.2.3 ✅ Legacy authentication clients
        1.2.4 ✅ Exchange ActiveSync clients
        1.2.5 ✅ Other clients
2. Install the **Microsoft Authenticator** on the smartphone
3. Install the **Company Portal** application
4. Enroll the device with **Company Portal** Application

---- 🐞 Reproduce the bug ----

5. Log into the Application first time
     5.1. Everything is fine on this step 👍. (MSAL, MAM, PIN code, Application restarting...)
6. (if the Application was terminated - Open It)
7. Log out from the Application (Logout MSAL, MAM)
8. Try to login again
     8.1. Login MSAL Successful 👍 
     8.1. Login MAM Successful 👍 
         8.2.1 We receive __IntuneMAMEnrollmentStatusNewPoliciesReceived__ in **enrollmentRequest(with:)**
         8.2.2 We receive __IntuneMAMEnrollmentStatusPoliciesHaveNotChanged__ in **policyRequest(with:)**
9. ❗️❌❗️❌ **Appeared the window with "Accessing Your Organization's Data" and asks to install the Authenticator. But Authenticator is already installed.**

**Expected behaviour:**
No window with "Accessing Your Organization's Data" and asks to install the Authenticator.

**Screenshots and logs:**
__Can't create screenshot, because of the protection policies__
<img src="https://user-images.githubusercontent.com/12058642/219804517-d3ae07da-8986-431f-bcce-b9b755dcca87.JPG"  width="300">

**Smartphone (please complete the following information):**
 - Device: iPhone 11, iPhone XS
 - OS: iOS 16.2

**Intune App SDK for iOS (please complete the following information):**
- __What version of the Intune SDK are you using?__ **Version 17.3.0**
- __Are you using the latest version?__ **Yes, we installed the latest**
- What platform is your app based in? **Native iOS**

- Who is the customer? *We don't have production users yet. Test Environment*
- Do you see a trend with it only being reproduced on a specific device? *Reproduced on different devices and different users. Requires "Conditional Access"*

Regards, 
Constantine

**Comment by ShruthiAchutha** [comment]
Please re-open this issue if it still impacts you.
