### ISSUE TITLE
“IntuneMAMConfigurator” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by bizlina** [msintuneappsdk/ms-intune-app-sdk-ios#308]
**Describe the bug:**
While trying to execute the IntuneMAMConfigurator to follow the steps for integrating IntuneSDK I get the following error:
![image](https://user-images.githubusercontent.com/23396884/220641155-41e75b80-efbf-49f8-ae28-0c17ea3eef67.png)

Even when trying out the workaround described here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/102 (right-clicking the IntuneMAMConfigurator executable in Finder and selecting "Open") , I get following error:

![image](https://user-images.githubusercontent.com/23396884/220641547-e4c63887-9296-401a-b553-95a4b37da9ba.png)

**To Reproduce**
1. Go to 'https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios'
2. While executing step 7 this error pops up.

**Expected behavior:**
No error pop-up opens during execution of this step.

**Smartphone (please complete the following information):**
 - Device: MacBook Pro M1 (16-inch, 2021)
 - OS: macOS 13.2 Ventura

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
--> **latest GitHub version 17.3.0** 
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
--> native

**Comment by neiljac1** [comment]
Hi @bizlina. Thanks for bring this to our attention. We'll address this in a future release. For now you can bypass this error by launching Settings -> System Prefences -> Privacy & Security(in left pane) -> Scroll down to bottom of right pane Click "Allow Anyway". Launch IntuneMAMConfiguration again and select Open in the dialog.

Thanks,
Neil

**Comment by bizlina** [comment]
Hi @neiljac1, sadly I don't have the option available you described. 

In the meanwhile I tested it with two colleagues so we had different setup tested, but with the same result as on my machine:
- MacBook Pro M1 with macOS Monterey
- MacBook Pro without M1 with macOS Ventura.

**Comment by neiljac1** [comment]
Hi @bizlina. Here are some screenshots of what I was referring to. What shows up on the Privacy & Security pane on your Mac?

Monterey:
![image](https://user-images.githubusercontent.com/25067583/222432452-3311a7ab-c04e-4234-bd73-dbe18540e6bd.png)

Ventura:
![image](https://user-images.githubusercontent.com/25067583/222432495-38bc5749-436c-4bb4-8000-7b92c4d74b1b.png)

Thanks,
Neil

**Comment by bizlina** [comment]
Hi @neiljac1, the screenshot helped a lot, thank you for this. I was in the right place already but without having tried out to execute the IntuneMAMConfigurator the Button "Open Anyway" is not visible.

Now I see it:
![image](https://user-images.githubusercontent.com/23396884/222434716-120f749c-a3c6-498c-a685-81440c5b2ae0.png)
and after clicking it, I can execute the configurator.
