### ISSUE TITLE
Call to registerAndEnrollAccount Never Results in a Response

### ISSUE THREAD

**Issue by LibertyDev18** [msintuneappsdk/ms-intune-app-sdk-ios#309]
**Describe the bug:**
An app that was previously managed "falls out" of management, making a call to registerAndEnrollAccount to get the app back under management results in no response ever being returned. Other apps on the device are still correctly under management but in this scenario this app is unable to become successfully managed again.

**To Reproduce**
1. App is successfully managed
2. Not sure what caused management to be removed but we always check on launch that management is still in effect
3. isManagementEnabled returns false
4. Make call to registerAndEnrollAccount
5. No response ever comes back and the app is never able to be placed under management

**Expected behavior:**
After falling out of management a call to registerAndEnrollAccount would result in APP being delivered and the app management is successfully restored

**Screenshots and logs:**
- Used the diagnostics console to upload logs Reference ID: 14FB73

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.3.1

**Intune App SDK for iOS (please complete the following information):**
- 17.3.0 (saw the same behavior with 17.2.4 & 17.2.1)
- Native

**Additional context:**
Looking to understand if there is any recovery path that would avoid an uninstall-reinstall of the app.

@Kyle-Reis for awareness.

**Comment by Kyle-Reis** [comment]
Hi @LibertyDev18 - I confirmed that this looks to be caused by the same issue from #300
