### ISSUE TITLE
Intune SDK for iOS support for Swift apps built with Xcode 10.2+

### ISSUE THREAD

**Issue by msintuneappsdk** [msintuneappsdk/ms-intune-app-sdk-ios#31]
The Intune SDK for iOS does not yet support Swift apps built with Xcode 10.2+. These apps use Swift libraries that are baked into the OS on iOS 12.2+. These apps use Swift libraries that are baked into the OS on iOS 12.2+. 

Obj-C apps or any app built on an older version of Xcode should continue to use the framework that is currently available.

The development team is working to release a new framework for Swift apps built with Xcode 10.2+.

**Comment by thebugcode** [comment]
Any progress on this issue?

**Comment by Kyle-Reis** [comment]
@thebugcode, yes! We're still working on updating the docs, but essentially Swift apps built with iOS 10.2+ will need to integrate  IntuneMAMSwift.framework and IntuneMAMSwiftStub.framework instead of the old framework/static lib

Apps that contain no Swift or that were built with a version of Xcode prior to 10.2 should continue to use IntuneMAM.framework

**Comment by thebugcode** [comment]
@Kyle-Reis Ah maybe then we're speaking about different things. I tried running the IntuneMAMPackager on our app and got the following error log:

Message: Application packaging in progress...

Verbose: Version of MACOSX is 10.14.4

Verbose: Version of XCode installed is Xcode 10.2.1
Build version 10E1001


Verbose: Input Parameters
 Path to input application:		/Users/danursu/Desktop/Speakap/INGBanky.ipa
 Path to output application:	/Users/danursu/Desktop/Speakap/WrappedINGBanky.ipa
 Provisioning profile:			/Users/danursu/Library/MobileDevice/Provisioning Profiles/32c8f851-7633-4453-9e9c-bfcb9dc143c1.mobileprovision
 SHA1 Hash of certificate:		b3b1dc93d3ec57e5c5f38f40720ba1b999aaf213

Verbose: Packager Version: 10.0.1, Packager Build: 190211.3, App Build: 5.28.0.99, Concatenated Build: 190226.31.1.99

Verbose: Packager Version: 10.0.1, Packager Build: 190211.3, App Build: 5.28.0.99, Concatenated Build: 190226.31.1.99

Error: Failed to inject IntuneMAM.framework into the app.

Verbose: Failed to inject IntuneMAM.framework into the app.
Cause of the error to be provided for investigation:Error Domain=Insufficient space to insert library dependency. Code=-1 "(null)"

**Comment by karunagarajan** [comment]
Can this issue be considered as closed so that I can use the new version of the SDK.

**Comment by fastharper** [comment]
Importing IntuneMAMSwift and IntuneMAMSwiftStub instead of IntuneMAM
But now all my references to IntuneMAMEnrollmentManager and other objects don't resolve

**Comment by Kyle-Reis** [comment]
Hey @fastharper, are you importing our headers through a bridging header rather than a using module import statement? This is required for now.

**Comment by andrejacobs** [comment]
Which version of the ADAL framework do I need to use to work with these new Swift frameworks?
I am using Cocoa Pods and it is using 4.0 for ADAL.
However my app is closed the moment the Intune enrollment starts.
Setting auto enroll and requires protection policy to NO in the info.plist allows the app to at least run.
Thank you.

**Comment by Kyle-Reis** [comment]
Hey @AndreJacobs, the current release does not support ADAL 4.0. Using 2.x is recommended. We’re actively working on 4.0 support and it will be available in an upcoming release.

**Comment by andrejacobs** [comment]
@Kyle-Reis Thank you for confirming. I have just rolled back to 2.7.9 and the latest 11.0.3 Intune MAM and at least the app doesn't crash now and show me the Intune enrollment / login screen.
Next is to make all this work together :-D

**Comment by Kyle-Reis** [comment]
Closing this issue out as the doc update is now live: https://docs.microsoft.com/intune/app-sdk-ios
