### ISSUE TITLE
弹框无法消失/The alert cannot disappear

### ISSUE THREAD

**Issue by slzButton** [msintuneappsdk/ms-intune-app-sdk-ios#315]
在绑定intune的时候出现了错误,并出现了一个弹框,但是出现之后就无法消失了,导致app不能再使用了,是否有拦截这个弹框的方法?

There was an error binding intune and a alert appeared, but after it appeared it would not disappear, rendering the app unusable,Is there a way to intercept this alert?

https://user-images.githubusercontent.com/13009437/226544537-292f228e-c50a-4c01-8df1-7f2afbb8b126.mov

**Comment by slzButton** [comment]
能帮忙看下么?
Can you take a look?

**Comment by slzButton** [comment]
@chadseippel 求助

please, help

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
