### ISSUE TITLE
App blocked with blank a white screen

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#319]
**Describe the bug:**
When the app tried to enroll, it launches the browser(SFViewController) and stays blank page.

**To Reproduce**
1. User had an app enrolled with a UPN
2. Then the UPN got changed (domain)
3. Trying with new UPN and the screen goes blank.
4. The same user able enrol just fine in another device.

I assume its related ADAL cache.

Note that trying to delete the session from another Intune enrolled app (OneDrive) assumed its ADAL cache issue.

**Expected behavior:**
Enrolment should happen. 

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 16.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 17.4.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer? Infor
- Do you see a trend with it only being reproduced on a specific device? - Yes

**Additional context:**
How can we delete the Cache or fix this issue for this specific user.

**Comment by darosal** [comment]
Hi @Nookaraju, thanks for reaching out! Can you clarify which version of the Intune SDK the app is being used? We haven't released a version 17.4.1 yet.

For clearing out the ADAL Cache, can you try using the Microsoft Authenticator app to do so? Here are some screenshots of the steps to take to clear the account from all apps.

![IMG_0A66388CC19A-1](https://user-images.githubusercontent.com/58273741/229175061-5a925102-6d11-4a7b-8628-d604d2dbf1ec.jpeg)
![IMG_0A66388CC19A-2](https://user-images.githubusercontent.com/58273741/229175072-d965fda1-fdf0-4884-9274-8aec6f9584b0.jpeg)
![IMG_0A66388CC19A-3](https://user-images.githubusercontent.com/58273741/229175088-837d7914-5182-4ab9-892b-c30476d9138a.jpeg)
![IMG_0A66388CC19A-4](https://user-images.githubusercontent.com/58273741/229175102-968b0a0b-a822-492b-b477-633a45d1b4f7.jpeg)

**Comment by Nookaraju** [comment]
@darosal Sorry, the Version is: 17.1.2

What if the user is not using the authenticator app?

Will it work if remove the account from the Company Portal app?

**Comment by Nookaraju** [comment]
@darosal is the user who is facing the issue of not using the authenticator app. Is there any other way to clear the session cache?
