### ISSUE TITLE
Is there any method to force programmatically the launch of an app regardless the block access policy requesting for authentication?

### ISSUE THREAD

**Issue by lucac-apps** [msintuneappsdk/ms-intune-app-sdk-ios#321]
We have an app that has to be accessed in critical situations and likely it is very rarely used.
This however implies that users do not use it often and even setting the block access policy to its maximum value we cannot guarantee the business the possibility to access the data it stores locally, if the device is off line.

Is there any method to force programmatically the app to launch regardless the block access policy requesting for authentication in case the device is not connected to any network, to guarantee the off line access to it?

**Comment by lucac-apps** [comment]
Can any one help, please!

**Comment by darosal** [comment]
Hi @lucac-apps, thanks for reaching out. Unfortunately there is no current way to disable the offline grace period policies. The blocks are in place to ensure that an app does not end up with stale policies when an admin has changed the targeting to use more restrictive policies. 

I do understand your specific use case and have passed that feedback along. For now, does the customer need this app to be targeted with MAM policies? Or would it be possible to have the users regularly launch the app on a specific cadence to reset the timer and avoid being blocked when a critical situation arises?
