### ISSUE TITLE
Unable to access camera

### ISSUE THREAD

**Issue by viwod** [msintuneappsdk/ms-intune-app-sdk-ios#323]
A user has reported being unable to access the camera because the camera is an unmanaged app. The prescribed solution has been to change the policy setting to allow data sharing from "Policy managed apps" to "All apps", but the user would not like to change this setting to "All apps" for security reasons. 

Is there a way to selectively allow access to unmanaged apps for data sharing? Or are we only able to choose between either "Policy managed apps" or "All apps"?

This is the notification that we're seeing from the SDK:
<img width="330" alt="Screen Shot 2023-03-31 at 8 40 37 AM" src="https://user-images.githubusercontent.com/38266802/229168273-8b442324-1978-448d-94ee-50e8428b3a4a.png">

**Comment by viwod** [comment]
@darosal The user is attempting to take a photo directly from within the app

**Comment by darosal** [comment]
@viwod, does the app implement a UIImagePickerController to present the camera view? If the scenario involves taking a photo and bringing that photo into the app, the user can change the "Allow users to open data from selected services" policy to include the Camera.

 
![Screen Shot 2023-03-31 at 12 46 16 PM](https://user-images.githubusercontent.com/58273741/229181427-a84bb6e1-05c8-4538-9351-ccfd13e2a567.png)

**Comment by viwod** [comment]
The user has the settings in that screenshot (Receive data from other apps set to Policy managed apps, Allow users to open data from selected services with Camera and Photo Library checked) and is still unable to access the camera

In the camera view we access the camera via `AVFoundation`

**Comment by darosal** [comment]
As part of the functionality provided in AVFoundation, is the app saving the photo using `ALAssetsLibrary` or `PHPhotoLibrary`? If that is done, the Intune SDK will prevent the action and throw the error alert unless the outgoing data policy is also set to allow saving to the "Photo Library" in the "Allow user to save copies to selected services" policy.

**Comment by viwod** [comment]
@darosal It turned out to be a setting configuration problem. I'll close out this issue, thank you for your help!
