### ISSUE TITLE
Unable to call AppDelegate methods from Unit tests post IntuneSdk integration

### ISSUE THREAD

**Issue by bharathraj45** [msintuneappsdk/ms-intune-app-sdk-ios#327]
**Describe the bug:**
Once the Intune MAM Sdk is integrated, the existing Unit tests on AppDelegate class is failing. Basically the AppDelegate didFinishLaunchingWithOptions when called from unit tests, the execution is not reaching the delegate method in AppDelegate. 

**To Reproduce**
Added the Intune MAM framework in the existing project by following the Sdk integration process steps. Post which unit tests related to AppDelegate doesn't work. Attached the sample app with the appdelegate unit test.

**Expected behavior:**
When we call AppDelegate method from unit test, the execution should reach AppDelegate didFinishLaunchingWithOptions method. Posted below sample code.

AppDelegate *appDelegate = [[AppDelegate alloc] init];
 BOOL didFinishLaunch = [appDelegate application:[UIApplication sharedApplication] didFinishLaunchingWithOptions:nil];

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 simulator
 - OS: [e.g. iOS8.1] iOS 16.2

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes, latest version - 17.4.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes

- Who is the customer? - NA
- Do you see a trend with it only being reproduced on a specific device? No
[IntuneSdkIntegration.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/11171197/IntuneSdkIntegration.zip)

**Comment by abasore** [comment]
Hi @bharathraj45, we might expect this behavior if the application is managed but the conditional launch processes are not able to complete. In order to debug more could you clarify the following:
1. Does your app support UIScenes?
2. Does this issue also repo on physical devices?
3. Can you confirm if your test app (IntuneSDKIntegration) is showing a repo of the issue for you? From testing with IntuneSDKIntegration's unit test, the project app delegate is called twice (once during launch and again after called from the test).

**Comment by bharathraj45** [comment]
Hi @abasore , thank you for the update.

1.     Does your app support UIScenes?
        Our app doesn't support scene delegate as yet. It will be enabled soon. In the test project I sent, as you know when we create the new project, scene delegate comes by default in latest version of xcode.

2.    Does this issue also repo on physical devices?
        Yes, it has been tested on physical device. The issue remains the same.

3.     Can you confirm if your test app (IntuneSDKIntegration) is showing a repo of the issue for you? From testing with IntuneSDKIntegration's unit test, the project app delegate is called twice (once during launch and again after called from the test).
        Yes, the test project which I uploaded is able to repo the issue. However, when I uploaded it didn't include the Intune framework files init. Can you add the IntuneMAMSwift.xcframework and IntuneMAMSwiftStub.xcframework file to the test project and run the test testApplicationDelegate added in IntuneSdkIntegrationTests.m class.

Please let me know if you have any questions.

Thank you,
Bharath

**Comment by abasore** [comment]
@bharathraj45 Yes, after adding the Intune SDK frameworks to the IntuenSDKIntegration test app, the issue did not repo for me using the latest SDK version and latest Xcode. Can you confirm which Xcode version you are using? Can you also confirm you are using the latest SDK (17.4.1)?

**Comment by bharathraj45** [comment]
Hi @abasore , can you confirm if you have tested on the test project which I sent. We observed if the app is created with Swift language, the appdelegate delegate methods from unit tests are working fine. The test app which I sent is based on Objective - C  and unit test is not working once we add the Intune frameworks mentioned in the previous response. Can you try checking on the test app I sent. Yes, we tried adding the latest sdk version and the issue remains the same.

**Comment by abasore** [comment]
Hi @bharathraj45, thanks for confirming. I've been able to get a local repo of this issue and am investigating a potential fix. I will update this discussion with updates as soon as possible.

**Comment by abasore** [comment]
@bharathraj45 Thank you for calling this to our attention! We've made a change that will be available in a future SDK version. It did NOT make it into our upcoming 17.5.0 release (expected by next week) but will likely in the following.

**Comment by bharathraj45** [comment]
Hi @abasore , thank you for the update. Could you provide an update on whether the fix has been pushed to latest sdk if not could you confirm the release version it will be part of.

**Comment by abasore** [comment]
This will be part of the next release, mostly likely 17.6.0. Ill update this discussion when I have an ETA

**Comment by bharathraj45** [comment]
Hi @abasore, any update of fix included in the release version?
