### ISSUE TITLE
The operation failed because the SDK could not access the user's AAD token

### ISSUE THREAD

**Issue by jay-canty-dept** [msintuneappsdk/ms-intune-app-sdk-ios#329]
**Describe the bug:**

 I believe this is more of a configuration issue than a bug. This has been reported a lot but I could not find a fix in previous issues. 

We are trying to get Intune set up for Multi-tenant MAM.  

Configuration:
- Company's AAD instance holds our AAD client id
- Intune instance (tenant) holds: AAP, ACP, user, user group, license
- Tenant's Linked AAD account contains App with API permissions - 
Microsoft Mobile Application Management (not sure this is set up correctly) 

**To Reproduce**

Client config:
- client id: Company's AAD client id
- redirectURI: uri specified in Company's AAD client id
- authority: https://login.microsoftonline.com/TenantName.onmicrosoft.com/

For our use case, we will need to use MSAL for authentication. 

Wen calling `[self.clientApplication acquireTokenWithParameters...]` the callback comes back with a token, and on app restart, calling `[self.clientApplication getCurrentAccountWithParameters....]` then `[self.clientApplication acquireTokenSilentWithParameters....]` results in a callback with token.

However, calling `[[IntuneMAMEnrollmentManager instance] registerAndEnrollAccountId:accountId];` using the `result.account.identifier` in the callback for `[self.clientApplication acquireTokenWithParameters...]` results in the `[IntuneMAMEnrollmentDelegate enrollmentRequestWithStatus]` callback error:

```
The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token.
```

**Expected behavior:**

`[IntuneMAMEnrollmentDelegate enrollmentRequestWithStatus]` is successful and kicks in the APP, ACP enrollment for the device.

**Screenshots and logs:**

Result of `[self.clientApplication acquireTokenWithParameters...]`:

<img width="878" alt="Screen Shot 2023-04-06 at 4 15 47 PM" src="https://user-images.githubusercontent.com/113119081/230913101-4b5a4b86-7aac-410b-9008-825338b881e6.png">

Logs when isolating `[self.clientApplication acquireTokenWithParameters...]`

[MSAL-logs.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/11190952/MSAL-logs.txt)

**Smartphone:**

Device: iPhone 14 (iOS 16) simulator on M1 mac 
OS: 
- OSX: 12.6
- XCODE: 14.0.1 

**Intune App SDK for iOS (please complete the following information):**
- IntuneMAM: 17.4.0
- MSAL: 1.2.10

Who is the customer?  Multi-tenant
Do you see a trend with it only being reproduced on a specific device? No

**Comment by abasore** [comment]
Hi @jay-canty-dept We would expect this error if a token is not found for the account passed into registerAndEnroll. To clarify, there are two API for registerAndEnroll:

- registerAndEnrollAccount:(NSString *)identity, which takes in the user's UPN (i.e. "user@foo.com")

- registerAndEnrollAccountId:(NSString *)accountId; which takes in the account Identifier. (i.e. 3ec2c00f-b125-4519-acf0-302ac3761822). 

**Could you try using the result.tenantProfile.identifier? That would ensure that the user from the current token request is the one being enrolled.**

Also, this example app implements MSAL might be useful for reference. The app performs an enrollment request here: https://github.com/msintuneappsdk/wagr/blob/main/Wagr/Application/Login/LoginViewController.m

**Comment by jay-canty-dept** [comment]
Hi @abasore,

We spent time getting `[[IntuneMAMEnrollmentManager instance] loginAndEnrollAccount:nil]` working (misconfigured dashboards) and switched back to 

```
NSString *accountIdentifier = result.tenantProfile.identifier;
[[IntuneMAMEnrollmentManager instance] registerAndEnrollAccountId:accountId];
```

and everything seems to be working.  Thanks, your suggestion worked!
