### ISSUE TITLE
Flashing Pin pad page error

### ISSUE THREAD

**Issue by TigerZhong** [msintuneappsdk/ms-intune-app-sdk-ios#333]
Describe the bug: 
Microsoft Intune user should be able to share files and media between Apps that support Intune

preconditions

1. User have Microsoft OneDrive and Teams installed
2. Hardware: iPhone Xs
3. Software: iOS 16.4.1
4. Intune user is logged into both OneDrive and Teams applications
5. There is a photo saved in OneDrive

To Reproduce

1. Open the saved photo in OneDrive
2. Tap on ... icon on the top right
3. Select Open in Another App
4. Tap on Teams App and share the photo

Expected behavior:
User would be required to enter a Pin before they can continue sharing in the Teams app. The Pin pad should be the first visible page shown.

Actual behaviour:
The Pin pad is currently flashing from down to up uncontrollably. Making it impossible for the user to enter the Pin. Please see the video attached for the Bug behaviour.

https://user-images.githubusercontent.com/14226394/234426118-0c6974c6-3eed-464f-bbba-cb4d30ee199b.MOV

**Comment by vigavadi** [comment]
@TigerZhong This has been fixed in v17.4.1. Teams still hasn't updates to that version.
