### ISSUE TITLE
Unable to share photos with camera

### ISSUE THREAD

**Issue by viwod** [msintuneappsdk/ms-intune-app-sdk-ios#336]
I have a customer reporting that they are unable to share photos taken with the camera, they are presented with this notification from the SDK:

<img width="199" alt="Screen Shot 2023-05-02 at 12 18 41 PM" src="https://user-images.githubusercontent.com/38266802/235764419-f674a955-e93d-4cce-80a8-2d2000bc6a22.png">

We've seen similar variations of this notification in the past (i.e. "Your organization only allows you to transfer its data to other managed apps."), but those were resolved by changing some of the app protection policies to allow the user to receive/transfer data from the Camera/Photo library.

The user's app protection policy settings have the following:

<img width="339" alt="Screen Shot 2023-05-02 at 12 22 50 PM" src="https://user-images.githubusercontent.com/38266802/235765032-855842eb-03e7-4e3a-8a2b-ff94248e13fe.png">

I am having trouble locating the specific dialogue in this notification in the documentation, what setting could be blocking camera access and causing this notification to appear?

**Comment by Kyle-Reis** [comment]
Hi @viwod - Would the customer be be able to upload diagnostic logs for your app via the [Intune diagnostic console](https://learn.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app)? To clarify, is the end user seeing this prompt when attempting to share a photo that they've successfully imported into the app? If so, would you be able to share which system API is being used by the application to share the photo?

**Comment by viwod** [comment]
Updating ticket status as this has been resolved (the customer had altered some share restriction settings in their app protection policy that disabled this feature), thanks!
