### ISSUE TITLE
App with InTune intgration crashing on cmarDeviceComplianceEnabled

### ISSUE THREAD

**Issue by mmiroslavLT** [msintuneappsdk/ms-intune-app-sdk-ios#339]
We integrate InTune SDK in our app and quickly after lunch we found a lot of crash reports from our customers that are even do not use anything from InTune SDK. I'm providing part of crash report below. Can you help us resolve this?

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000f15221b66
```

```
# Crashlytics - Stack trace
# Application: <AppBundle>
# Platform: apple
# Version: 5.8.1 (607)
# Issue: 034a72ed2a...27fc408ec
# Session: 68fd198584...3443c_DNE_0_v2
# Date: Wed May 24 2023 10:46:02 GMT+0200 (Central European Summer Time)

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x6a84 object_getIndexedIvars + 36
1  CoreData                       0xe3538 _PFObjectIDFastHash64 + 36
2  CoreFoundation                 0x21c94 __CFBasicHashRehash + 968
3  CoreFoundation                 0x6bb34 CFBasicHashRemoveValue + 2308
4  CoreFoundation                 0x92904 CFDictionaryRemoveValue + 328
5  CoreData                       0x45e4 -[NSManagedObjectContext(_NSInternalAdditions) _forgetObject:propagateToObjectStore:removeFromRegistry:] + 120
6  CoreData                       0x41b0 -[_PFManagedObjectReferenceQueue _processReferenceQueue:] + 616
7  CoreData                       0xee9dc __90-[NSManagedObjectContext(_NSInternalNotificationHandling) _registerAsyncReferenceCallback]_block_invoke + 80
8  CoreData                       0x80fb0 developerSubmittedBlockToNSManagedObjectContextPerform + 156
9  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
10 libdispatch.dylib              0x126a4 _dispatch_main_queue_drain + 928
11 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF + 44
12 CoreFoundation                 0x98d18 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
13 CoreFoundation                 0x7a650 __CFRunLoopRun + 1992
14 CoreFoundation                 0x7f4dc CFRunLoopRunSpecific + 612
15 GraphicsServices               0x135c GSEventRunModal + 164
16 UIKitCore                      0x39d37c -[UIApplication _run] + 888
17 UIKitCore                      0x39cfe0 UIApplicationMain + 340
18 IntuneMAMSwift                 0x2300b0 cmarDeviceComplianceEnabled + 2095200
19 <AppBundle>                     0x2eeae4 main + 24 (main.m:24)
20 ???                            0x1dde30dec (Missing)


com.microsoft.intune.mam.logging
0  libsystem_kernel.dylib         0x1558 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  IntuneMAMSwift                 0x214718 cmarDeviceComplianceEnabled + 1982152
3  libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
5  libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
6  libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
7  libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
8  libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
9  libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

**Smartphone:**
 - Device: iPad
 - OS: iPadOS 14, 15, 16

**Intune App SDK for iOS:**
We are using latest version of InTune SDK for iOS, and it is used only on iPad devices.
There is no errors during build.

This is not related to specific customer but mostly for users that are not using InTune at all.
Same crash happened on 8 different iPads and to hundreds of customers, but mostly on iPad Pro 12.9 4th - 6th gen.

**Comment by abasore** [comment]
@mmiroslavLT can you describe more of the repo steps before the crash? It is directly upon app launch? Can you also confirm that this crash doesn't happen when the Intune SDK is not used?

We would always expected to see the IntuneMAMSDK in the stack trace next to UIApplicationMain.

**Comment by mmiroslavLT** [comment]
@abasore crash **does** happen when the Intune SDK is not used, so users who **are not using** InTune experiencing this crash. Also it is not clear when it happened, but what I can see from logs is that sometimes just after launch, sometimes in the middle of app use.

Here are crash report proves:
<img width="429" alt="Screenshot 2023-05-31 at 19 20 40" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/76678733/d66c3df0-8759-43f5-b7e6-3022f88b835d">
<img width="516" alt="Screenshot 2023-05-31 at 19 23 33" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/76678733/231c8b7c-d672-46cc-b1e1-063ffd4a93a7">

**Comment by abasore** [comment]
@mmiroslavLT we would expect to see the reference to Intune early in the stack trace for every launch. This trace doesn't necessarily Indicate Intune is the cause of the crash.  Could you confrim if this crash is happening with the latest SDK (17.5.0)

If the crash is still consistent, it would be helpful in debugging to have a support case. Could you open a request by going to "Troubleshooting + support" -> "Help and support" -> "Intune" in Endpoint Manager? It would also be helpful to collect log by calling the API mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app)
