### ISSUE TITLE
How to use Authenticator instead of webview

### ISSUE THREAD

**Issue by OxyFlax** [msintuneappsdk/ms-intune-app-sdk-ios#34]
I wonder if it is possible to use Authenticator to enroll device and retrieve policies like when we connect with ADAL and then use register&enroll.
There is no documentation about that possibility, it would be useful for SSO.

**Comment by Kyle-Reis** [comment]
Hey @OxyFlax This scenario is supported. Once you've configured your app to sign in via the Authenticator, you should able to silently enroll via registerAndEnrollAccount, provided that you've specified the correct AAD settings under the IntuneMAMSettings dictionary as mentioned [here](https://docs.microsoft.com/intune/app-sdk-ios#configure-adal-settings-for-the-intune-app-sdk).

**Comment by OxyFlax** [comment]
To complete my question, I'm talking about the scenario where MAMPolicyRequires and AutoEnrollOnLaunch are set to YES. It directly prompts a webview and it does not seem to be possible to make it silently or use Authenticator app.

**Comment by Kyle-Reis** [comment]
Hey @OxyFlax, does your app include msauth in the LSApplicationQueriesSchemes Info.plist entry?

**Comment by OxyFlax** [comment]
Of course :/

**Comment by andrejacobs** [comment]
@Kyle-Reis I have msauth in my plist and the app works fine with Authenticator as a Broker for getting ADAL tokens. However when I run the IntuneMAMConfigurator tool, it removes msauth and replaces it with companyportal. Is this correct behaviour? Or do I need to have both in my plist. Many thanks.

**Comment by Kyle-Reis** [comment]
Hey @andrejacobs, that is a known issue in version 10.0.7 of the configurator. It should be fixed in the latest release (11.0.7).

**Comment by Kyle-Reis** [comment]
@andrejacobs, could you confirm if your configurator issue is fixed?

@OxyFlax, are you still having issues using Authenticator?

**Comment by OxyFlax** [comment]
Seems to be fixed! Thanks

**Comment by andrejacobs** [comment]
@Kyle-Reis I can confirm that 11.0.13 running the configurator tool keeps msauth in the plist. the company portal one just moved around, but nothing else was changed :-D
