### ISSUE TITLE
Unable to share files via Microsoft apps through UIActivityViewController

### ISSUE THREAD

**Issue by bbdev9805** [msintuneappsdk/ms-intune-app-sdk-ios#340]
**Describe the bug:**

I have integrated Intune SDK to my app and set Intune policy "Send org data to other apps" to "Policy managed Apps".  My app has function to receive and send files through UIActivityViewController. My app can send the file to Microsoft apps such as Teams and OneDrive  through UIActivityViewController. However, my app can't receive the file from Teams and OneDrive. Microsoft apps show Share Extension and my app is listed there. When I select my app, my app launches and shows an error dialog.
```
Action Not Allowed
Your organization only allows you to open work or school data in this app.
```
I also checked the log with reference to the following pages.
https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-log
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app
https://learn.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge#use-edge-for-ios-and-android-to-access-managed-app-logs

Both my app and Microsoft apps have the AppSharingFromLevel and AppSharingToLevel values set to 1 (Policy managed apps). So I assume sharing from the Microsoft app to my app works fine, why not?

**Smartphone:**
Device: iPad
OS: iPadOS 14/15/16

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
Yes latest Intune SDK (17.5.0)
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
native
- Do you see a trend with it only being reproduced on a specific device?
No

**Comment by gastaffo** [comment]
Howdy, could you send a screen shot of your policy configuration?

**Comment by bbdev9805** [comment]
@gastaffo 
Where exactly is the policy configuration screen?
My application is registered in Managed APPs and has the following settings.
Please let me know if the information you need is different or if there is anything else you need.
![DataProtection](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/269b0444-99b0-4513-88d4-c25f06eb8c68)

![IMG_8AF3072D76FF-1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/fe6e204a-0384-4777-97fe-d58d91960612)

![IMG_D0F9AD573932-1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/f052c1f2-010f-46b0-b75e-1939484d709c)

![IMG_DB0A8CD41198-1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/eff011a4-e779-40a1-9622-7de1a6b6f905)

![IMG_950043A51272-1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/9c65fa47-c9c9-4af8-b5a5-05bc4aeb58df)

**Comment by gastaffo** [comment]
Could you show the entire Data Protection configuration screen? What is your "Recieve Data From Other Apps" value? Do you have "Open data into Org Documents" allowed or blocked?

**Comment by bbdev9805** [comment]
"Recieve Data From Other Apps" value is "Policy managed Apps".  "Open data into Org Documents"  is allowed.

![MicrosoftTeams-image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/1ee46072-e854-41b6-b5ea-db465437d1f5)
![MicrosoftTeams-image (1)](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/f01fc4bd-9a5d-4671-87ce-4bd2c231299b)

**Comment by gastaffo** [comment]
Ok thanks, I'll try to reproduce locally. Just to confirm, the scenario is a MSFT app sending your app a file? Are the MSFT apps you are sharing from also targeted with policy?

**Comment by bbdev9805** [comment]
> the scenario is a MSFT app sending your app a file?

Yes.

>  Are the MSFT apps you are sharing from also targeted with policy?

Yes. MSFT apps (Teams and OneDrive) are targeted with policy.

**Comment by gastaffo** [comment]
Sorry for the long delay. You say the app opens, does the share extension just open the app passing in the URL/file being shared?

**Comment by gastaffo** [comment]
Also would you be willing to share logs with a repro?

**Comment by gastaffo** [comment]
Also are the identities the same between the apps that are sharing?

**Comment by bbdev9805** [comment]
> You say the app opens, does the share extension just open the app passing in the URL/file being shared?

Yes. My app is opened by just passing the file in action Extension. 

![IMG_0033 2](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/bb20902e-0957-484f-94ed-c2cd0dccd666)
![IMG_0BD27B5E61CE-1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/5208a93e-327c-492b-a5a9-1b2b2b2b347d)

>Also would you be willing to share logs with a repro?

What logs and how should I share them?

> Also are the identities the same between the apps that are sharing?

Yes.

**Comment by gastaffo** [comment]
If you display the intune mam diagnostic console there will be a "Get Started" button for "Collect Intune DIagnostics". From there you'll be able to share logs as a file and post them here, or use "Send to Microsoft" if it exists and post the reference ID here.

**Comment by gastaffo** [comment]
Also while I am investigating on my side trying to repro. Can you double check that your action/copy to extension is configured correctly as described in https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#share-data-via-uiactivityviewcontroller?

**Comment by bbdev9805** [comment]
I have shared the log by "Send to Microsoft".  Reference ID is "038F79". However, the log is cleared like in the attached file after my app is opened by action extension. Is there something wrong?
[IntuneMAMDiagnosticFiles.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/11912575/IntuneMAMDiagnosticFiles.txt)

**Comment by bbdev9805** [comment]
I checked the description again and confirmed that there would be no problem.

**Comment by gastaffo** [comment]
Hmm something seems off, the alert isn't in the logs which does make it seem like the log file is getting cleared out somehow. Are you using a debugger? Is it possible the app is being reinstalled between launched?

**Comment by bbdev9805** [comment]
I wasn't using the debugger when I sent the logs. It will not be reinstalled between launched.

**Comment by gastaffo** [comment]
Odd. Could you try repro'ing and sending logs again real quick? Not sure why it cleared itself

**Comment by gastaffo** [comment]
Also would you be willing to share your Extensions info.plist?

**Comment by bbdev9805** [comment]
I tried again, but the log was cleared, and I got an error like the attachment when I sent it.

![IMG_8BA1A9A620F8-1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/135770768/1eebf499-d11b-49d5-8144-cf07e489be95)

**Comment by bbdev9805** [comment]
Here is Extensions info.plist.


```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>IntuneMAMSettings</key>
        <dict>
            <key>AppGroupIdentifiers</key>
            <array>
                <string>group.com.MY_APP_GROUP_IDENTIFIER</string>
            </array>
            <key>OpenInActionExtension</key>
            <true/>
        </dict>
        <key>NSExtension</key>
        <dict>
            <key>NSExtensionAttributes</key>
            <dict>
                <key>NSExtensionActivationRule</key>
                <string>
                    SUBQUERY (
                        extensionItems,
                        $extensionItem,
                        SUBQUERY (
                            $extensionItem.attachments,
                            $attachment,
                            ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.adobe.pdf"
                            || ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image"
                            || ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.com.adobe.pdf"
                            || ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.public.image"
                        ).@count == $extensionItem.attachments.@count
                    ).@count == 1
                </string>
                ...
```

**Comment by bbdev9805** [comment]
This issue is probably resolved.

I added the Intune SDK to the extension's 'Frameworks and Libraries' and the file sharing worked fine.　Sorry, I didn't realize I needed to add the SDK to the extension's framework as well.

**Comment by gastaffo** [comment]
No problem. Not sure what the deal with the logs issue but hopefully it just something weird with your device. Looking at our code for the flow we ended up logging the error but considering the logs can't be uploaded in a bit of a hole lol. I'll check our telemetry to see if I can see anything there about the logging issue. Do you have any other issues? Can I close this thread?

**Comment by bbdev9805** [comment]
I don't have anything els. I will close this issue. Thank you for your help.
