### ISSUE TITLE
Customer is unable to sign in on initial app launch when APP is applied

### ISSUE THREAD

**Issue by viwod** [msintuneappsdk/ms-intune-app-sdk-ios#341]
**Describe the bug:**
We have a customer that is facing an issue where they are unable to sign in on the first time the app is launched when their app protection policy is applied.

**To Reproduce**
Users receive this prompt (prompt 1 image) when they first launch the app and the Intune App Protection Policy is applied. If the user dismisses this prompt and attempt to sign in, they see a second prompt (prompt 2 image). The only solution is to force quit the app and start again, where the APP has applied and sign in is allowed.

**Expected behavior:**
Should we be expecting a prompt says that your organization is now protecting the app and it will restart automatically to enforce the APP?

**Screenshots and logs:**
Prompt 1 Image | Prompt 2 Image
:-------------------------:|:-------------------------:
![prompt-1](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/38266802/2d3d2fe8-d239-4f55-a521-5d73060e3740) | ![prompt-2](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/38266802/cf5daf79-efd0-4a13-b0eb-5f102054c459)

**Smartphone (please complete the following information):**
 iOS Device, iOS 16

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
17.4.0

- Do you see a trend with it only being reproduced on a specific device?
Happens to all users on managed devices

**Additional context:**
The customer's MAM enrolled account does not match the app account in this case. The user principal name is used as the Intune-enrolled account identifier and a different primary SMTP address is used as the app login. For example, the UPN would be customer.account@testdomain.com, but the primary SMTP is customer@testdomain.com. The Intune app is configured with the IntuneMAMUPN key to associate with {{userprincipalname}} to make the app associate itself with the App Protection Policy that is deployed only to managed devices.

Note on that^, the customer has noted that this mismatch in our app deployment on their account has existed for years, and they have only recently run into this issue

**Comment by gastaffo** [comment]
To clarify, this is occuring on MDM managed devices and for APP deployed for managed devices?

Does the user sign in with the two different UPNs? Also do the different UPNs map to the same Azure identity?

What auth library is the app using?

**Comment by gastaffo** [comment]
Are they signing in with the same UPN they are enrolled with via the CP? Also is the app deployed via the company portal?

**Comment by viwod** [comment]
Hi Gastaffo yes, they are signing in with the same UPN as the UPN that they have enrolled in company portal

**Comment by viwod** [comment]
To iterate again on the point in the description, the user receives the blocking prompt the first time the app is opened but the APP seems to be successfully applied when the app is force quit and restarts (the user does not receive the error in ^prompt #2 when the app is force quit and restarts), what might be causing this behavior?

**Comment by gastaffo** [comment]
Are you able to produce and share logs of a reproduction? You can do this by reproducing the issue and then launching the app and calling `[IntuneMAMDiagnosticConsole displayDiagnosticConsole]` and then doing "Collect Intune Diagnostics"

**Comment by viwod** [comment]
Sure, here are those logs from the customer:
[IntuneMAMDiagnosticFiles.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12176196/IntuneMAMDiagnosticFiles.txt)

**Comment by gastaffo** [comment]
Looking through the logs it looks like the login succeeds but still returns an error. Upon second launch, we see that the user is logged in and able to apply policy. Investigating further to see why the login is thinking it failed when it didn't.

**Comment by gastaffo** [comment]
I see the device is MDM enrolled, is the user signing in with the same user that is enrolled via MDM.
This is causing the login to file
2023-07-21T16:44:38.721Z	ERRO	com.cisco.squared.intune	tid=17      id=,ui=,io=                  	 IntuneMAM: Auto-enroll: username has been changed.

If there isn't policy to enforce that its the MDM user then it could be possible to have this flow and we would need to fix some checks.

Also is it possible the user has the same UPN but multiple OIDs like via a guest account?

**Comment by gastaffo** [comment]
Also seeing this which could cause issues
2023-07-21T16:44:38.684Z	INFO	com.cisco.squared.intune	tid=15      id=,ui=,io=                  	 IntuneMAM: Could not fetch EMM OID from EMM UPN CMARScrubbedIdentity:e645d430844f8d6624c1556e260a94f20536f9efb9f1d7c3f8c2d9496eced7fb

**Comment by gastaffo** [comment]
Hey I think I found the solution.

Y'all shoud set
IntuneMAMOID = "{{userid}}"

In the managed device config.

**Comment by viwod** [comment]
Hi @gastaffo thanks for taking a look, I'll recommend that the customer tries this

If there is a mismatch between the IntuneMAMOID and UPN, will this still work?

**Comment by gastaffo** [comment]
I think so. We should get the correct one from AAD whenever we log in and save it.

**Comment by gastaffo** [comment]
Missed your last question. The different configuration settings tell us from where to get the different values for MDM. Without them we don't check MDM as it may be unrelated to the app.
