### ISSUE TITLE
Intune Console does not show anymore the Intune SDK version

### ISSUE THREAD

**Issue by luky88** [msintuneappsdk/ms-intune-app-sdk-ios#347]
Starting from Intune SDK v. 17.5.0 opening the Intune Console, it's not possibile anymore to find the Intune SDK version included in the app.

Attached a screenshot of the previous version of the console (v. 17.4.2 and before)
![console_previous_version](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/6715432/6cbdd8d8-e917-42a6-8cf1-bdc38214e4d8)

Here the newer Intune Console, without the SDK version in it:
![console_current_version](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/6715432/8d1e7de7-ad60-42ee-8a4e-3fb212ec0af0)

**Comment by Kyle-Reis** [comment]
Thanks for reporting this @luky88! We're working on adding that info back to the console along with app version.

**Comment by lucac-apps** [comment]
> Thanks for reporting this @luky88! We're working on adding that info back to the console along with app version.

Will it be a change via telemetry with the current SDKs or will you issue a new SDK to put this functionality back?

**Comment by Kyle-Reis** [comment]
@lucac-apps - This will be a client-side fix that will roll out in a new SDK release.

**Comment by lucac-apps** [comment]
@Kyle-Reis Thanks

**Comment by Kyle-Reis** [comment]
@luky88, @lucac-apps - This issue was addressed in version 17.7.0 of the SDK.
