### ISSUE TITLE
Intune protected App Not appearing in Outlook - 'Share File via'

### ISSUE THREAD

**Issue by eg-aseem** [msintuneappsdk/ms-intune-app-sdk-ios#348]
Hello,

I am working to make my Intune protected app in the UIActivityViewController list (Horizontal View) when I use the 'Share File via' option in Outlook which I downloaded from the company portal. Below are my configurations in the App protection policy.

Send org data to other apps:
Policy managed apps with Open-In/Share filtering

Receive data from other apps:
Policy managed apps

I also followed the instructions mentioned at [Share Data via UIActivityViewController](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#share-data-via-uiactivityviewcontroller) by adding non-UI Action extension to my app. I am not sure if there are any other settings that are required to be done!

Can you please confirm if these steps are also valid for Outlook - 'share file via' scenario or there are other settings that I need to do?

**Comment by eg-aseem** [comment]
@Kyle-Reis any thoughts on this?

**Comment by neiljac1** [comment]
Hi @eg-aseem. Can you post the NSExtensionActivationRule for your action extension? You can email it to neiljac@microsoft.com if you like.

Thanks,
Neil

**Comment by eg-aseem** [comment]
Thanks @neiljac1 I have mailed you. Please check if you have received!
