### ISSUE TITLE
App crashing on loginAndEnrollAccount call

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#350]
**Describe the bug:**
The app is crashing on loginAndEnrollAccount 

**To Reproduce**
We are building our Internal framework that includes the Intune integration.  When we run the app that links our internal framework and triggers the loginAndEnrollAccount then the app crashes.

I don't think Intune uses the main bundle for its resources(nibs). We also tried to link the IntuneMAMSwift.xcframework & IntuneMAMSwiftStub.xcframework for both our framework target and app target that uses our framework. Still crashing at same point.

**Expected behavior:**
App should not crash even the framework referred from another framework.

**Screenshots and logs:**
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/<>Library/Developer/CoreSimulator/Devices/C12954FF-809E-4931-9F46-D28AE1166868/data/Containers/Bundle/Application/50940FE0-4C6C-434E-9678-CBF88738CA2F/InforGoCoreApp.app> (loaded)' with name 'PolicyViewController_iPhone''

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] -iPhone 14 simulator 
 - OS: [e.g. iOS8.1] -iOS 16.4

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? -17.5.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? -native
- For errors during build, does the app build without Intune SDK integration? -No
- For errors post build, does the app launch without being Intune SDK integrated? -Yes

- Who is the customer? Infor
- Do you see a trend with it only being reproduced on a specific device? -No

**Additional context:**

**Comment by Nookaraju** [comment]
@Kyle-Reis any thoughts on this issue?

**Comment by Nookaraju** [comment]
@Kyle-Reis any help would be appreciated.

**Comment by Nookaraju** [comment]
@abasore any help on this?

**Comment by Nookaraju** [comment]
@Kyle-Reis @msintuneappsdk any suggestions?

**Comment by abasore** [comment]
@Nookaraju Thank you for reporting. Could confirm if this issue still reproduces with the latest SDK: 17.7.0?

**Comment by Nookaraju** [comment]
@abasore Yes, It crashes with the crash log when we use the latest SDK 17.7.0

Please note that SDK is included in our internal framework project and using that framework to build an app.

**Comment by Nagarjun30** [comment]
<img width="960" alt="Screenshot 2023-08-18 at 5 26 11 PM" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/9572665/11ac833b-f29c-4f41-979e-2accb1b93e82">

Include the frameworks (IntuneMAMSwift.xcframework and IntuneMAMSwiftStub.xcframework) by placing them in the **Build Phase**. Create a **New Copy Files Phase**, choose "Frameworks" as the destination, and add both of these frameworks to the phase.

**Comment by Nookaraju** [comment]
@Nagarjun30 Thanks for your reply.

It worked after creating Copy Files Phase and adding both the frameworks for the App target. 

Really appriciate your help.

**Comment by mahavrani** [comment]
Im using Option 2 Approach.Still im facing crash on calling loginAndEnrollAccount after following the above suggested steps.
<img width="1116" alt="Screenshot 2024-04-27 at 8 29 51 PM" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/18703776/8cb040c5-9558-42a2-a4f2-bb8037f27dbe">
<img width="1123" alt="Screenshot 2024-04-27 at 8 29 58 PM" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/18703776/a902cbcd-0da8-45fb-bfd9-e6bfe8a4f43c">
