### ISSUE TITLE
Crash on start on iOS 15.2

### ISSUE THREAD

**Issue by sergiva-mp** [msintuneappsdk/ms-intune-app-sdk-ios#351]
Our app is compiled with Intune SDK 17.6.1 and it runs fine on iOS 16.5. We received a report that it will reliably crash on start on iOS 15.2 device (iPad 5th gen).

The symptom is identical to this issue previously reported:

https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/137
@Kyle-Reis Do you remember what the root cause was?

App log contains the following line:

Line  453: Jul 18 14:12:54 xxxxx-iPad runningboardd(RunningBoard)[60] <Notice>: [application<com.xxxxx.intune>:8873] termination reported by launchd (2, 10, 10)

I could not repro this in iOS Simulator configured for iPad 5th gen and iOS 15.2. However, it fails as above on actual devices running iOS 15.2.

**Comment by sergiva-mp** [comment]
Thank you for the quick response! Yes, I do have crash log and I'll be sending it to you shortly.

**Comment by sergiva-mp** [comment]
Hi there, just checking back on this. I sent the crash log in the email, were you able to pick up any clues from that?

**Comment by kariohlsen** [comment]
I'm seeing a similar crash in background/idle using Intune 18.0.0.  Crash is in NSURLSession-work queue and is in libsqlite.dylib.  @darosal should I email crash log you?

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
