### ISSUE TITLE
Customise the Intune MAM login prompts to a section of group for enterprise apps

### ISSUE THREAD

**Issue by bharathraj45** [msintuneappsdk/ms-intune-app-sdk-ios#352]
Hi Team,

We have integrated Intune MAM SDK for our iOS app. The app is for B2B category. In the app, we have our custom library for authentication and don't use ADAL or MSAL for authentication. We are looking to enroll user into Intune MAM policy post our app authentication by calling the iOS **loginAndEnrollAccount** api provided by Intune iOS SDK. However, as you know this will show the Microsoft login prompt for all the users across the customers we have. Now some of the customers might not possess the Intune MAM license/subscription.

We have gone through the Intune iOS Sdk documentation and couldn't find an a way to customise/display the login prompt for specific users and avoid for others. Could you let us know if there an mechanism to display the Intune MAM login prompt for users who have intune license/subscription and avoid for the others who don't have it.

Please let us know if you have any questions.

Thank you,
Bharath

**Comment by Mughundhan-Citrix** [comment]
@darosal , We are stuck on this development effort. It would be helpful if you could provide your inputs

**Comment by darosal** [comment]
Unfortunately there is no simple answer here. There isn’t really a solution from the Intune MAM SDK side, as we don’t know if a user is MAM enabled until after they have been authenticated through ADAL/MSAL.

Other developers have solved this by including a setting within their app’s own service-end that an admin can toggle to specify if their tenant uses Intune. The app can then check their own service for this toggle and display the Intune flow. 

Please reopen this issue if you have any further questions.
