### ISSUE TITLE
My app isn't recognized for "Require app protection policy"

### ISSUE THREAD

**Issue by sergiva-mp** [msintuneappsdk/ms-intune-app-sdk-ios#353]
Hi foks, we have an app that fully integrates Intune SDK and thus does support App Protection. In fact, in my test deployment an app protection policy is configured and is active.

However, when I enabled Conditional Access with the Grant Access condition of "Require app protection policy", I start getting the following error in the app:

You can't get there from here
It looks like you're trying to open this resource with a client app that is not available for use with app protection policies. Ask your IT department or see a list of applications that are protected here.

Does our app need to be added to some kind of whitelist? Or did I miss some configuration to designate my app as supporting app protection policies? To clarify, this isn't one of the apps on the published list, it's an app we have built and are providing to our customers. I am reproducing an issue that our customer has encountered when they enabled Conditional Access in their deployment.

Thanks!

**Comment by neiljac1** [comment]
Hi @sergiva-mp,

Your application will need to specify the 'protapp' capability in the MSALPublicClientApplicationConfig configuration. See the documentation [here](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#msaladal).

Thanks,
Neil

**Comment by sergiva-mp** [comment]
Thank you! I implemented this and had good success on one of my test devices. On the other device (which I have been using for a long time for development -- so it has multiple successive versions of the app installed on it), the app got into a state where on startup there is the following error:

The operation couldn’t be completed. MSALErrorDomain error -50004

And then the app closes. Any suggestion how to troubleshoot this type of MSAL error? (short of resetting the device)

Uninstalling/reinstalling the app, and unenrolling/re-enrolling the device using Comp Portal (and even uninstalling/re-installing Comp Portal) makes no difference -- the same error occurs every time no matter what I do with that device.

**Comment by neiljac1** [comment]
Hi @sergiva-mp,

The -50004 error corresponds to MSALErrorServerProtectionPoliciesRequired. When you receive this, your application should call IntuneMAMComplianceManager remediateComplianceForIdentity or remediateComplianceForAccountId.

Thanks,
Neil

**Comment by KrystofMacek** [comment]
I had the same issue getting -50004 error, I have the 'protapp' capability set, however the remediateComplianceForIdentity does not have effect even when it returns with "compliant" status. So Device is managed, and app compliant as per result from the remediate but signIn still returns application needs to enforce intune protection policies

**Comment by msft-neiljac** [comment]
Hi @KrystofMacek. Can you send a screenshot of the interactive authentication failure after clicking the 'More details' link?

Thanks,
Neil

**Comment by KrystofMacek** [comment]
@msft-neiljac 
First i authenticate user requesting only User.Read scope which works fine, then i need access to OneDrive call acquire token again with appropriate scopes. Then depending on if i use Company Portal or not I get these two screens:

When i use Company Portal to first register the device and install the certifikate I get the one that says compliant. If I do not use Company portal and only MS Authenticator (broker) then its unregistered. 


![IMG_2763](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/40734895/ac559834-85e8-4719-b2ba-5af16146062f)
![IMG_2762](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/40734895/1532ead3-a100-4256-a41e-a19a8199aca2)

**Comment by KrystofMacek** [comment]
Sure, its implemented as a handler since I had to make it as a plugin for flutter/dart but here it is:
Im calling the functions from FlutterFramework so the implementation is little different, but for sign in the "call.method = MSALSignIn" which is the first switch case

I am calling   config.clientApplicationCapabilities = ["ProtApp"] for any 

when i add         `config.clientApplicationCapabilities = ["ProtApp"]` It no longer shows the dialog to sign in but, the error i get in completionBlock is:
`"AADSTS53005: Application needs to enforce Intune protection policies. Trace ID: beacc4a7-8a7b-43d0-939b-f25dcdd64a00 Correlation ID: 995e254b-2935-4426-af12-b3e465ac0d6a Timestamp: 2023-12-11 17:56:07Z"	`

```
 func handleMSAL(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        if ( call.method ==  "MSALSetup"){
            let args = call.arguments as? Dictionary<String, Any>
            authority = try? MSALAADAuthority(url: URL(string:  args?["authority"] as? String ?? "https://login.microsoftonline.com/common")!)
            clientId = args?["clientId"] as? String
            if (clientId == nil) {
                result(false)
                return
            }
            redirectUri = args?["redirectUri"] as? String
            scopes = args?["scopes"] as? Array<String> ?? []
            extraScopes = args?["extraScopes"] as? Array<String> ?? []
            selectAccount = args?["selectAccount"] as? Bool ?? true
            result(true)
            return
        }
        
        let config = MSALPublicClientApplicationConfig(clientId:  clientId ?? "",
                                                       redirectUri: redirectUri,
                                                       authority:authority)
        
        config.clientApplicationCapabilities = ["ProtApp"]
        
        guard let application = try? MSALPublicClientApplication.init(configuration: config)  else {
            result(FlutterError(code: "error", message: "Unable to find MSALPublicClientApplication", details: nil))
            return
        }
        
        switch call.method {
        case "MSALSignIn":
            let msalParameters = MSALParameters()
            msalParameters.completionBlockQueue = DispatchQueue.main
            let viewController = UIApplication.shared.windows.first!.rootViewController
            
            let interactiveParameters = MSALInteractiveTokenParameters(scopes: scopes, webviewParameters: MSALWebviewParameters(authPresentationViewController: viewController!))
            interactiveParameters.promptType = MSALPromptType.selectAccount
            interactiveParameters.extraScopesToConsent = extraScopes
            if (selectAccount == false) {
                if let accounts = try? application.allAccounts(), !accounts.isEmpty {
                    let id = accounts[0].identifier
                    guard let account = try? application.account(forIdentifier: id ?? "") else { return }
                    interactiveParameters.account = account
                }
            }
            application.acquireToken(with: interactiveParameters, completionBlock: { (res, error) in
                guard let authResult = res, error == nil else {
                    if let error = error as NSError?, let errorDescription = error.userInfo[MSALErrorDescriptionKey] as? String{
                        if errorDescription.lowercased().contains("user cancelled authentication") {
                            result(["error" : "user canceled"])
                        }
                        result(["error" : error.localizedDescription, "description" : errorDescription])
                    }
                    
                    result(["error" : error!.localizedDescription])
                    return
                }
                result(["accessToken" : authResult.accessToken,
                        "idToken" : authResult.idToken ?? "",
                        "objectId": authResult.account.accountClaims?["oid"] ?? ""
                       ])
            })
        case "MSALSignInSilently":
            if let accounts = try? application.allAccounts(), !accounts.isEmpty {
                let id = accounts[0].identifier
                guard let account = try? application.account(forIdentifier: id ?? "") else { return }
                let silentParameters = MSALSilentTokenParameters(scopes: scopes + extraScopes, account: account)
                application.acquireTokenSilent(with: silentParameters) { (res, error) in
                    guard let authResult = res, error == nil else {
                       
                        let nsError = error! as NSError
                        
                        if (nsError.domain == MSALErrorDomain &&
                            nsError.code == MSALError.interactionRequired.rawValue) {                            
                            result(["error" : "Interaction required"])
                            return
                        }
                     
                        result(["error" : error!.localizedDescription])
                        return
                    }
                    result(["accessToken" : authResult.accessToken,
                            "idToken" : authResult.idToken ?? "",
                            "objectId": authResult.account.accountClaims?["oid"] ?? ""
                           ])
                }
            } else {
                result(["error" : "no account"])
            }
        case "MSALSignOut":
            let params = MSALSignoutParameters();
            params.wipeAccount = true
            params.wipeCacheForAllAccounts = true
            if let accounts = try? application.allAccounts(), !accounts.isEmpty {
                application.signout(with: accounts[0], signoutParameters: params, completionBlock: { success, error in
                    result(["success" : success, "msg" : error?.localizedDescription ?? ""] as [String : Any])
                })
            } else {
                result(["success" : true, "msg" : "Already signed out"] as [String : Any]);
            }
        case "MSALGetIdentity":
            if let accounts = try? application.allAccounts(), !accounts.isEmpty {
                result(["identity" : accounts[0].username,
                        "id" : accounts[0].identifier ?? "",
                        // "authority" : accounts[0].environment,
                        //"tenantId" : accounts[0].tenantProfiles?[0].tenantId,
                       ])
            } else {
                result(["identity":nil] as [String : Any?])
            }
        default:
            result(FlutterMethodNotImplemented)
        }
    }
```

**Comment by msft-neiljac** [comment]
Hi @KrystofMacek. Does your application call remediateComplianceForIdentity after you get the "Application needs to enforce Intune protection policies." error? It's not shown in the example above. If it does, do you call MSALSignInSilently again after the remediateComplianceForIdentity completion block returns 'compliant'?

Thanks,
Neil

**Comment by KrystofMacek** [comment]
hi @msft-neiljac, this is my implementation of remediate. There is no completion block for remediateComplience. But after calling remediateCompliance I do get "compliant" status in the implementation of IntuneMAMComplianceDelegate. However after that the sign in results in same error.

```
 let args = call.arguments as? Dictionary<String, Any>
            let identity = args?["identity"] as? String
            let accountId = args?["accountId"] as? String
            let silently = args?["silently"] as? Bool ?? false
            if (identity != nil) {
                complianceManager.remediateCompliance(forIdentity: identity!, silent: silently)
                result(nil)
            } else if (accountId != nil){
                complianceManager.remediateCompliance(forAccountId: accountId!, silent: silently)
                result(nil)
            } else {
                result(FlutterMethodNotImplemented)
            }
```

**Comment by msft-neiljac** [comment]
Hi @KrystofMacek. What scopes and extraScopes are you passing into MSAL? Can you also upload Intune logs for your app using [IntuneMAMDiagnosticConsole displayDiagnosticConsole] and post the reference id?

Thanks,
Neil
