### ISSUE TITLE
IntuneMAMFrameworkPatcher?

### ISSUE THREAD

**Issue by chasemac** [msintuneappsdk/ms-intune-app-sdk-ios#355]
What is the IntuneMAMFrameworkPatcher? It was part of the latest release, and I don’t see any documentation for it.

**Comment by vigavadi** [comment]
@chasemac We are already working on adding documentation for it.

**Comment by chasemac** [comment]
@vigavadi do you have any more info on what the patcher is doing?

Is it important to implement 17.6.3 before iOS 17 is released?

**Comment by CraigST123** [comment]
Yes, if this is patching the underlying iOS frameworks, it's important for us to understand what changes it's making. This is important for security, QA, and just debugging.

**Comment by neiljac1** [comment]
It is important to integrate IntuneMAMFrameworkPatcher into your build before the iOS 17 release. The tool modifies application binaries, not iOS frameworks, allowing the Intune SDK API interception used to apply APP policies to continue working as it did in previous iOS releases.
