### ISSUE TITLE
Documentation link in 17.7.0 release notes requires login

### ISSUE THREAD

**Issue by roanutil** [msintuneappsdk/ms-intune-app-sdk-ios#358]
**Describe the bug:**
In the release notes for 17.7.0, there is a link to documentation for the new IntuneMAMFrameworkPatcher. The link is `https://review.learn.....` which requires signing in. It seems that the link should be `https://learn.....`. The release notes and the incorrect link are below.

https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/17.7.0
https://review.learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios?branch=main&branchFallbackFrom=pr-en-us-11521#post-build-script

**Comment by vigavadi** [comment]
@roanutil Thanks for reporting this. The link has been updated now.
