### ISSUE TITLE
Permission denied for IntuneMAMFrameworkPatcher

### ISSUE THREAD

**Issue by jdanthinne** [msintuneappsdk/ms-intune-app-sdk-ios#359]
**Describe the bug:**
IntuneMAMFrameworkPatcher step fails to run with permission denied error.

**To Reproduce**
1. Add IntuneMAMFrameworkPatcher as a build step  `"${SRCROOT}/Intune/IntuneMAMFrameworkPatcher" -i $BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH -resign -verbose`
2. Build the project
3. See build error

**Expected behavior:**
The project builds.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes, 17.7.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes

**Comment by neiljac1** [comment]
Hi @jdanthinne. Can you try running 'chmod +x' on the IntuneMAMFrameworkPatcher binary to see if this fixes the permission denied error?

Thanks,
Neil

**Comment by jdanthinne** [comment]
That does work, thanks.
