### ISSUE TITLE
IntuneMAMFrameworkPatcher `Wrong configuration` pops up even after applying build-step

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#361]
**Describe the bug:**
I installed the newest 17.7.0 and run the `IntuneMAMFrameworkPatcher` inside my build steps. On development this works, but on release it breaks and I get a popup that we didn't run the tool.

**To Reproduce**
- `Edit Scheme...` inside Xcode
- Added a Build Post-action: `${PROJECT_DIR}/IntuneMAMFrameworkPatcher -i "$TARGET_BUILD_DIR/$WRAPPER_NAME" -resign -verbose`
![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/1229109/fe4e85b9-3104-492d-940d-a6ebe1396cb5)
- Also runs in every build successfully.
- Upload & release to TestFlight/AppStore
- App on iOS17 crashes and shows this alert after restart: "Please run IntuneMAMFrameworkPatcher during the build process. See the integration guide for more details."
Sorry it is in German (and seems intended of Intune if the app does not support en, as the system is):
<img width="330" alt="Screenshot 2023-08-17 at 08 25 15" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/1229109/7f2eb410-e1c3-4a1d-b1d1-d83a310f9009">

**Expected behavior:**
No alert to appear.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
Build log shows script which in verbose also produces multiple entries of:
2023-08-17 08:29:01.341 IntuneMAMFrameworkPatcher[3662:33921] Resigning ../*.framework

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: iOS17 Beta 6

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?: 17.7.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?: native
- For errors during build, does the app build without Intune SDK integration?: yes
- For errors post build, does the app launch without being Intune SDK integrated?: yes

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**
Also there is really not a lot of documentation about the `IntuneMAMFrameworkPatcher` nor why it is required. We also use other build steps afterwards that include RASP and obfuscation. This always worked in previous releases, but may also result in showing the alert?

**Comment by vigavadi** [comment]
The requirement to run IntuneMAMFrameworkPatcher has been removed with the latest version 17.7.1. Please give that a try.

**Comment by vigavadi** [comment]
@ryanbland Correct. This is only needed if you are using 17.7.0. We'll be updating the docs soon.
