### ISSUE TITLE
Enrollment fails

### ISSUE THREAD

**Issue by roanutil** [msintuneappsdk/ms-intune-app-sdk-ios#365]
I've made progress so that the problem has changed. This issue has been updated to reflect that.

**Describe the bug:**
Enrollment immediately fails with an error: `Unexpected failure. Contact your organization's support team for help.`

**Screenshots and logs:**
[Intune-com.mfbtech.align.intune.qa-0.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12381708/Intune-com.mfbtech.align.intune.qa-0.txt)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9" 4th generation
 - OS: iPadOS 16.6

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 17.7.1, no
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native

- Who is the customer? MFB Technologies, Inc
- Do you see a trend with it only being reproduced on a specific device? no

**Additional context:**
- Both `IntuneMAMSwift.xcframework` and `IntuneMAMSwiftStub.xcframework` are set to `Embed & Sign` for the project.
- Occurs for both debug and release builds
- The device I'm testing on is enrolled with Intune MDM. Also tested on non-enrolled devices.
- Relevant parts of Info.plist
  - [partial.plist.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12373949/partial.plist.zip)
- URL Types (shows in separate section of Info.plist view)
  - msauth.com.microsoft.intunemam

**Comment by roanutil** [comment]
After adding `msauth.$(PRODUCT_BUNDLE_IDENTIFIER)` and `msauth.$(PRODUCT_BUNDLE_IDENTIFIER)-intunemam` as additional URL Types MSAL now fails with -50000 error code.
[Intune-com.mfbtech.align.intune.qa-0.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12381771/Intune-com.mfbtech.align.intune.qa-0.txt)

**Comment by roanutil** [comment]
After changing the App Registration to Multitenant, it change slightly.
[Intune-com.mfbtech.align.intune.qa-0.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12381820/Intune-com.mfbtech.align.intune.qa-0.txt)

**Comment by roanutil** [comment]
And a diagnostic file that includes the `IntuneMAMDiagnosticInfo.txt` at the end.

[IntuneMAMDiagnosticFiles.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12410786/IntuneMAMDiagnosticFiles.txt)

**Comment by roanutil** [comment]
When trying to enroll after authenticating via MSAL and using the UPN to call `IntuneMAMEnrollmentManager.instance().registerAndEnrollAccount`:

[2023-08-22_15-38-02_MSAL_First.log](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12412938/2023-08-22_15-38-02_MSAL_First.log)
[IntuneMAMDiagnosticFiles_MSAL_First.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12412939/IntuneMAMDiagnosticFiles_MSAL_First.txt)

**Comment by roanutil** [comment]
One small note: the logs typically say that MSAL version 1.2.13 is being used. But 1.2.15 is the actual version used and linked.

**Comment by roanutil** [comment]
@darosal is this being looked at yet?

**Comment by roanutil** [comment]
My colleague @raj3m8 figured out what the problem was. We needed to add another permission to the app registration.

 https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional

**Comment by faisalike** [comment]
@roanutil what permission?
I'm facing the same problem.

**Comment by thuongtv-vn** [comment]
Look like we must define this url scheme in app right?
msauth.com.microsoft.intunemam

i don't see any official documentation about this value.
