### ISSUE TITLE
SceneDelegate methods are not called when integrating the Intune SDK

### ISSUE THREAD

**Issue by bbdev9805** [msintuneappsdk/ms-intune-app-sdk-ios#366]
**Describe the bug:**

SceneDelegate methods, such as following, are not called when integrating the Intune SDK.

- [func scene(UIScene, willConnectTo: UISceneSession, options: UIScene.ConnectionOptions)](https://developer.apple.com/documentation/uikit/uiscenedelegate/3197914-scene)
- [func scene(UIScene, openURLContexts: Set<UIOpenURLContext>)](https://developer.apple.com/documentation/uikit/uiscenedelegate/3238059-scene)

Everything was working fine until a few days ago, but suddenly this issue started occurring from yesterday. This happens despite no changes in the version of the SDK and OS. Also, when SDK is not integrated, this issue does not arise.

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iPadOS 15.5/16.5.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
Intune SDK (17.5.0). I tried with the latest version (17.7.0) and it was the same.
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
native
- Do you see a trend with it only being reproduced on a specific device?
no

**Comment by bbdev9805** [comment]
I have discovered something new. When the following code is integrated into AppDelegate using the Facebook iOS SDK, SceneDelegate methods will no longer be called. 
```
        ApplicationDelegate.shared.application(
            application,
            didFinishLaunchingWithOptions: launchOptions
        )
```
This issue seems to occur only when the above code and IntuneSDK are integrated.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
