### ISSUE TITLE
Application Misconfiguration Error after updating to new version 17.7.0

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#367]
**Describe the bug:**
Application Misconfiguration prompt is showing after updating to new version 17.7.0

**To Reproduce**
1. Updated from Intune version 17.6.3 to 17.7.0
2. Installed the app on the device.

**Expected behavior:**
There shouldn't be unwanted prompts

**Screenshots and logs:**
![MicrosoftTeams-image (18)](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/2161122/8d0e7a97-fceb-462a-a482-bb722d40aab9)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16.0

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? latest 17.7.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? NATIVE
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device? No, h

**Additional context:**
Its not happening If I revert the SDK version back to 17.6.3 and run the app.
We don't see this issue in simulators.

**Comment by vigavadi** [comment]
This alert is expected because running IntuneMAMFrameworkPatcher is a required step for 17.7.0. However, this requirement has been removed with the latest version 17.7.1. Please give that a try.
