### ISSUE TITLE
Deeplink doesn't work on in-app Edge managed by MAM

### ISSUE THREAD

**Issue by Regi2na** [msintuneappsdk/ms-intune-app-sdk-ios#371]
**Describe the bug:**
Our mobile app is facing an issue where deeplink doesn't work after we migrate from webview to in-app browser.
Our app is using Intune MAM with Edge as the default browser.

Need the resolution on how to make the deeplink works on in-app Edge browser managed by MAM.
We have logged this issue under company ticket TrackingID#2308110060000563 (please refer to this ticket for the detail) 
We have tried to change some MAM settings as guided by Microsoft engineer, but still not able to get any solution or conclusion for 3 weeks.

Let us know if anything you need from us.

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by abasore** [comment]
Closing this since it is being tracked with support. Updates from the ICM will be the most up to date.
