### ISSUE TITLE
App crashes with EXC_BAD_ACCESS while playing audio in background

### ISSUE THREAD

**Issue by phani9205** [msintuneappsdk/ms-intune-app-sdk-ios#372]
**Describe the bug:**
I have a capacitor application that uses ms-intune-app-sdk-ios. There is a specific use case where I need to play an audio in an iframe in my app. The expectation of this audio is that it should be playing in the background when the capacitor app is pushed to the background. But when I push the app to the background and lock the phone, the app seems to play the audio for few minute(s) and crashes in the background with the below error. 

Date/Time:           2023-08-31 15:30:56.3626 -0400
Launch Time:         2023-08-31 15:29:17.8574 -0400
OS Version:          iPhone OS 15.3.1 (19D52)
Release Type:        User
Baseband Version:    4.02.02
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype:  FS pagein error: 1 Operation not permitted
Exception Codes: 0x000000000000000a, 0x0000000103cac000
VM Region Info: 0x103cac000 is in 0x103cac000-0x103cb4000;  bytes after start: 0  bytes before end: 32767
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_LARGE             103ca0000-103cac000 [   48K] rw-/rwx SM=PRV  
--->  mapped file              103cac000-103cb4000 [   32K] rw-/rw- SM=PRV  ...t_id=71248b31
      GAP OF 0x18000 BYTES
      SQLite page cache        103ccc000-103cdc000 [   64K] rw-/rwx SM=PRV  
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 10 Bus error: 10
Terminating Process: exc handler [646]

The reason that I am posting it in this forum is because, I have tried the similar use case of playing an iframe audio/video in app that is not plugged in with this Intune SDK and the app seems to be working fine. Only when I add this SDK, app seems to be crashing. Any help is much appreciated. 

**To Reproduce**
1. Create a sample capacitor angular app with NX ([link](https://nxext.dev/docs/ionic-angular/getting-started.html)). 
2. Embed a sample iframe to your app. (below is the sample iframe with audio/video. Error can be replicated when we play the vimeo video in the app, play the video in picture-in-picture mode) 
` <iframe
src="[https://player.vimeo.com/video/714042444?h=07887a16c1"](https://player.vimeo.com/video/714042444?h=07887a16c1%22)
frameborder="0"
allow="autoplay; fullscreen; picture-in-picture"
allowfullscreen></iframe>`

3. Add intune sdk to a above sample capacitor application. 
3. Build and deploy the iOS application using capacitor and XCode either in simulator or hard deploy to iPhone. 
4. Open the app, play the audio/video in the iframe and move the video into picture-in-picture mode. 
5. Push the app to the background and lock the phone. 
6. App should crash with above mentioned error code (EXC_BAD_ACCESS) after few minutes (1 - 5 min). This error is shown the app crash log.  
 
**Expected behavior:**
When I push the app to the background and lock the phone, the app should keep playing the audio in the background and should not crash. 

**Screenshots and logs:**
Incident Identifier: 246FFF9A-A1EF-400C-BC5F-2DA2315C69F2 CrashReporter Key:   0b01e1ea3d579f1c464060a80913911084d693d1 Hardware Model:      iPad11,7 Process:             App [646] Path:                Identifier:           Version:             5.0.0 (5.0.0) Code Type:           ARM-64 (Native) Role:                Non UI Parent Process:      launchd [1] Coalition:          
 
Date/Time:           2023-08-31 15:30:56.3626 -0400 Launch Time:         2023-08-31 15:29:17.8574 -0400 OS Version:          iPhone OS 15.3.1 (19D52) Release Type:        User Baseband Version:    4.02.02 Report Version:      104
 
Exception Type:  EXC_BAD_ACCESS (SIGBUS) Exception Subtype:  FS pagein error: 1 Operation not permitted Exception Codes: 0x000000000000000a, 0x0000000103cac000 VM Region Info: 0x103cac000 is in 0x103cac000-0x103cb4000;  bytes after start: 0  bytes before end: 32767       REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL       MALLOC_LARGE             103ca0000-103cac000 [   48K] rw-/rwx SM=PRV   --->  mapped file              103cac000-103cb4000 [   32K] rw-/rw- SM=PRV  ...t_id=71248b31       GAP OF 0x18000 BYTES       SQLite page cache        103ccc000-103cdc000 [   64K] rw-/rwx SM=PRV   Exception Note:  EXC_CORPSE_NOTIFY Termination Reason: SIGNAL 10 Bus error: 10 Terminating Process: exc handler [646]
 
Triggered by Thread:  9
 
Kernel Triage: VM - Filesystem pagein returned an error in vnode_pagein VM - Page has error bit set VM - Filesystem pagein returned an error in vnode_pagein VM - Page has error bit set
 
 
Thread 0 name:   Dispatch queue: com.apple.main-thread Thread 0: 0   libsystem_kernel.dylib                   0x1b7756504 mach_msg_trap + 8 1   libsystem_kernel.dylib                   0x1b7756b9c mach_msg + 76 2   CoreFoundation                           0x180d70738 __CFRunLoopServiceMachPort + 372 3   CoreFoundation                           0x180d74a2c __CFRunLoopRun + 1212 4   CoreFoundation                           0x180d88468 CFRunLoopRunSpecific + 600 5   GraphicsServices                         0x19c92c38c GSEventRunModal + 164 6   UIKitCore                                0x18372b5d0 -[UIApplication _run] + 1100 7   UIKitCore                                0x1834a9f74 UIApplicationMain + 364 8   IntuneMAMSwift                           0x10431d6c8 0x10404c000 + 2954952 9   App                                      0x102fcbb5c main + 64 10  dyld                                     0x1031d9aa4 start + 520
 
Thread 1 name:   Dispatch queue: com.microsoft.intune.mam.logging Thread 1: 0   libsystem_kernel.dylib                   0x1b7756f90 __psynch_cvwait + 8 1   libsystem_pthread.dylib                  0x1f0696254 _pthread_cond_wait + 1228 2   IntuneMAMSwift                           0x1042fcd24 0x10404c000 + 2821412 3   libdispatch.dylib                        0x180a72924 _dispatch_call_block_and_release + 32 4   libdispatch.dylib                        0x180a74670 _dispatch_client_callout + 20 5   libdispatch.dylib                        0x180a7bdf4 _dispatch_lane_serial_drain + 672 6   libdispatch.dylib                        0x180a7c968 _dispatch_lane_invoke + 392 7   libdispatch.dylib                        0x180a871b8 _dispatch_workloop_worker_thread + 656 8   libsystem_pthread.dylib                  0x1f068f0f4 _pthread_wqthread + 288 9   libsystem_pthread.dylib                  0x1f068ee94 start_wqthread + 8
 
Thread 2 name:  JavaScriptCore bmalloc scavenger Thread 2: 0   libsystem_kernel.dylib                   0x1b7756f90 __psynch_cvwait + 8 1   libsystem_pthread.dylib                  0x1f0696254 _pthread_cond_wait + 1228 2   libc++.1.dylib                           0x1996ecddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 3   JavaScriptCore                           0x18cf66174 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 108 4   JavaScriptCore                           0x18cf6a944 bmalloc::Scavenger::threadRunLoop() + 340 5   JavaScriptCore                           0x18cf6a4e4 bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 16 6   JavaScriptCore                           0x18cf6b9a0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 48 7   libsystem_pthread.dylib                  0x1f068f9a4 _pthread_start + 148 8   libsystem_pthread.dylib                  0x1f068eea0 thread_start + 8
 
Thread 3 name:  WebThread Thread 3: 0   libsystem_kernel.dylib                   0x1b7756504 mach_msg_trap + 8 1   libsystem_kernel.dylib                   0x1b7756b9c mach_msg + 76 2   CoreFoundation                           0x180d70738 __CFRunLoopServiceMachPort + 372 3   CoreFoundation                           0x180d74a2c __CFRunLoopRun + 1212 4   CoreFoundation                           0x180d88468 CFRunLoopRunSpecific + 600 5   WebCore                                  0x190b73964 RunWebThread(void*) + 756 6   libsystem_pthread.dylib                  0x1f068f9a4 _pthread_start + 148 7   libsystem_pthread.dylib                  0x1f068eea0 thread_start + 8
 
Thread 4 name:  com.apple.uikit.eventfetch-thread Thread 4: 0   libsystem_kernel.dylib                   0x1b7756504 mach_msg_trap + 8 1   libsystem_kernel.dylib                   0x1b7756b9c mach_msg + 76 2   CoreFoundation                           0x180d70738 __CFRunLoopServiceMachPort + 372 3   CoreFoundation                           0x180d74a2c __CFRunLoopRun + 1212 4   CoreFoundation                           0x180d88468 CFRunLoopRunSpecific + 600 5   Foundation                               0x1825a6c84 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 6   Foundation                               0x1825e7db8 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92 7   UIKitCore                                0x1836a474c -[UIEventFetcher threadMain] + 524 8   Foundation                               0x1825f63fc __NSThread__start__ + 808 9   libsystem_pthread.dylib                  0x1f068f9a4 _pthread_start + 148 10  libsystem_pthread.dylib                  0x1f068eea0 thread_start + 8
 
Thread 5: 0   libsystem_pthread.dylib                  0x1f068ee8c start_wqthread + 0
 
Thread 6 name:  com.google.firebase.crashlytics.MachExceptionServer Thread 6: 0   libsystem_kernel.dylib                   0x1b7756504 mach_msg_trap + 8 1   libsystem_kernel.dylib                   0x1b7756b9c mach_msg + 76 2   FirebaseCrashlytics                      0x103919870 FIRCLSMachExceptionReadMessage + 80 3   FirebaseCrashlytics                      0x1039197a8 FIRCLSMachExceptionServer + 52 4   libsystem_pthread.dylib                  0x1f068f9a4 _pthread_start + 148 5   libsystem_pthread.dylib                  0x1f068eea0 thread_start + 8
 
Thread 7: 0   libsystem_kernel.dylib                   0x1b7756558 semaphore_timedwait_trap + 8 1   libdispatch.dylib                        0x180a74c7c _dispatch_sema4_timedwait + 64 2   libdispatch.dylib                        0x180a75280 _dispatch_semaphore_wait_slow + 76 3   IntuneMAMSwift                           0x1040d1888 0x10404c000 + 546952 4   IntuneMAMSwift                           0x1041ee64c 0x10404c000 + 1713740 5   libdispatch.dylib                        0x180a72924 _dispatch_call_block_and_release + 32 6   libdispatch.dylib                        0x180a74670 _dispatch_client_callout + 20 7   libdispatch.dylib                        0x180a7bdf4 _dispatch_lane_serial_drain + 672 8   libdispatch.dylib                        0x180a7c968 _dispatch_lane_invoke + 392 9   libdispatch.dylib                        0x180a871b8 _dispatch_workloop_worker_thread + 656 10  libsystem_pthread.dylib                  0x1f068f0f4 _pthread_wqthread + 288 11  libsystem_pthread.dylib                  0x1f068ee94 start_wqthread + 8
 
Thread 8 name:  AVAudioSession Notify Thread Thread 8: 0   libsystem_kernel.dylib                   0x1b7756504 mach_msg_trap + 8 1   libsystem_kernel.dylib                   0x1b7756b9c mach_msg + 76 2   CoreFoundation                           0x180d70738 __CFRunLoopServiceMachPort + 372 3   CoreFoundation                           0x180d74a2c __CFRunLoopRun + 1212 4   CoreFoundation                           0x180d88468 CFRunLoopRunSpecific + 600 5   AudioSession                             0x18a1a3308 CADeprecated::GenericRunLoopThread::Entry(void*) + 164 6   AudioSession                             0x18a1acd64 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92 7   libsystem_pthread.dylib                  0x1f068f9a4 _pthread_start + 148 8   libsystem_pthread.dylib                  0x1f068eea0 thread_start + 8
 
Thread 9 name:   Dispatch queue: com.apple.NSURLSession-work Thread 9 Crashed: 0   libsqlite3.dylib                         0x19f669cb8 0x19f641000 + 167096 1   libsqlite3.dylib                         0x19f6680dc 0x19f641000 + 159964 2   libsqlite3.dylib                         0x19f6680dc 0x19f641000 + 159964 3   libsqlite3.dylib                         0x19f66790c 0x19f641000 + 157964 4   libsqlite3.dylib                         0x19f665e08 0x19f641000 + 151048 5   libsqlite3.dylib                         0x19f665750 0x19f641000 + 149328 6   libsqlite3.dylib                         0x19f6851a4 0x19f641000 + 278948 7   libsqlite3.dylib                         0x19f683594 sqlite3_step + 308 8   CFNetwork                                0x1815a78a4 0x181584000 + 145572 9   CFNetwork                                0x1815b32c8 0x181584000 + 193224 10  CFNetwork                                0x1815f048c 0x181584000 + 443532 11  CFNetwork                                0x1815b9094 0x181584000 + 217236 12  CFNetwork                                0x1815ede18 0x181584000 + 433688 13  CFNetwork                                0x1815ae8bc 0x181584000 + 174268 14  CFNetwork                                0x1815d0c8c 0x181584000 + 314508 15  CFNetwork                                0x18158dae4 0x181584000 + 39652 16  CFNetwork                                0x1815a2b8c 0x181584000 + 125836 17  libdispatch.dylib                        0x180a83454 _dispatch_block_async_invoke2 + 148 18  libdispatch.dylib                        0x180a74670 _dispatch_client_callout + 20 19  libdispatch.dylib                        0x180a7bdf4 _dispatch_lane_serial_drain + 672 20  libdispatch.dylib                        0x180a7c99c _dispatch_lane_invoke + 444 21  libdispatch.dylib                        0x180a871b8 _dispatch_workloop_worker_thread + 656 22  libsystem_pthread.dylib                  0x1f068f0f4 _pthread_wqthread + 288 23  libsystem_pthread.dylib                  0x1f068ee94 start_wqthread + 8
 
Thread 10: 0   libsystem_pthread.dylib                  0x1f068ee8c start_wqthread + 0
 
 
Thread 9 crashed with ARM Thread State (64-bit):     x0: 0x0000000105044ba8   x1: 0x000000016d2ddd34   x2: 0x0000000000000000   x3: 0x0000000000000001     x4: 0x0000000000000000   x5: 0x0000000000000001   x6: 0x0000000000000000   x7: 0x0000000000000000     x8: 0x0000000000000000   x9: 0x0000000103f3fa30  x10: 0x0000000000000005  x11: 0x0000000000000000    x12: 0x000000050000078c  x13: 0x00000001da24a000  x14: 0x00000001810391d2  x15: 0x00000001da1cc410    x16: 0x000000019f648a24  x17: 0x000000019f684824  x18: 0x0000000000000000  x19: 0x0000000104929170    x20: 0x000000016d2ddd34  x21: 0x0000000103cac000  x22: 0x0000000000000001  x23: 0x0000000000000000    x24: 0x0000000000000000  x25: 0x0000000103ca79e0  x26: 0x000000016d2ddd34  x27: 0x00000001da24c000    x28: 0x0000000103ca7e90   fp: 0x000000016d2ddb00   lr: 0xe35aa3819f6680dc     sp: 0x000000016d2dda70   pc: 0x000000019f669cb8 cpsr: 0x80000000    far: 0x0000000103cac000  esr: 0x92000007 (Data Abort) byte read Translation fault
 
Binary Images:        0x1b7755000 -        0x1b7788fff libsystem_kernel.dylib arm64e  <ff3ee512a0bc3123b983d365a71fb06a> /usr/lib/system/libsystem_kernel.dylib        0x180d69000 -        0x1811bcfff CoreFoundation arm64e  <e2f84645290531ef8ec73cc19c3cddb3> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation        0x19c92b000 -        0x19c933fff GraphicsServices arm64e  <b40e3b1790c73ebcb6bc8c7b605f47a9> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices        0x183212000 -        0x184a9dfff UIKitCore arm64e  <920a0ee6d2663058814427a27b23ad62> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore        0x10404c000 -        0x10444bfff IntuneMAMSwift arm64  <4d8b7b4b166d3ea283dbef2860b273dd> /private/var/containers/Bundle/Application/D778C48E-4016-44F7-8C4D-BA483907686F/App.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift        0x102fc4000 -        0x102fcffff App arm64  <5d045126673537ac855f203d0d2f3f72> /private/var/containers/Bundle/Application/D778C48E-4016-44F7-8C4D-BA483907686F/App.app/App        0x1031c0000 -        0x103217fff dyld arm64e  <780553c7d39f322a8cb9f4f6de52610d> /usr/lib/dyld        0x1f068e000 -        0x1f0699fff libsystem_pthread.dylib arm64e  <a17d07cfe86a392387c4921045898a8a> /usr/lib/system/libsystem_pthread.dylib        0x180a70000 -        0x180ab6fff libdispatch.dylib arm64e  <bd02a62584753fd68dc38aed25d1573b> /usr/lib/system/libdispatch.dylib        0x1996e3000 -        0x199746fff libc++.1.dylib arm64e  <346a1fc1f0b337dbb10209951bb9aa78> /usr/lib/libc++.1.dylib        0x18bd85000 -        0x18d075fff JavaScriptCore arm64e  <8882e299ecd236a1839b41ee2ca83aa6> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore        0x18ff91000 -        0x192537fff WebCore arm64e  <3703d6463b8237d99d4635ab8fc2bc6e> /System/Library/PrivateFrameworks/WebCore.framework/WebCore        0x18258e000 -        0x182894fff Foundation arm64e  <925a43cdeaf2316193783ed87468301d> /System/Library/Frameworks/Foundation.framework/Foundation        0x1038f4000 -        0x103953fff FirebaseCrashlytics arm64  <9bb593edb5d6307a834f3d8c5c697af7> /private/var/containers/Bundle/Application/D778C48E-4016-44F7-8C4D-BA483907686F/App.app/Frameworks/FirebaseCrashlytics.framework/FirebaseCrashlytics        0x18a19d000 -        0x18a1c6fff AudioSession arm64e  <cfe93669499d3d2b972b0f516064a8a6> /System/Library/PrivateFrameworks/AudioSession.framework/AudioSession        0x19f641000 -        0x19f7d3fff libsqlite3.dylib arm64e  <bdddcea91a8f3a4f854a94b2d2e75cff> /usr/lib/libsqlite3.dylib        0x181584000 -        0x181a48fff CFNetwork arm64e  <23a465f1e97c36c5a30fcefec059f79f> /System/Library/Frameworks/CFNetwork.framework/CFNetwork                0x0 - 0xffffffffffffffff ??? unknown-arch  <00000000000000000000000000000000> ???
 
EOF

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? **16.1.1**
- What platform is your app based in (native, Xamarin based, Cordova, etc)? **Capacitor/Angular**
- For errors during build, does the app build without Intune SDK integration? **Issue is not replicable without IntuneSDK**
- For errors post build, does the app launch without being Intune SDK integrated? **Yes**

**Comment by vigavadi** [comment]
@phani9205 You need to set MaxFileProtectionLevel to NSFileProtectionCompleteUntilFirstUserAuthentication under IntuneMAMSettings in the Info.plist file. You can find the details for the setting here: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk

**Comment by chasemac** [comment]
You're so lucky I ran into this issue a few months ago. It took support about a month to figure it out.

**Comment by phani9205** [comment]
@vigavadi Thank you very much! That worked.
