### ISSUE TITLE
iOS 17 Issue 'This app could not be protected due to a network issue'

### ISSUE THREAD

**Issue by arsalangolestanekh** [msintuneappsdk/ms-intune-app-sdk-ios#373]
Hello, we are using Intune SDK and we found an issue,
For some accounts, when starting the app on iOS 17, during the login process we receive an error.
![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/61407619/94b5f8eb-db25-4782-8364-93d0428addb6)
This error was observed on Intune SDK 17.5.0, once we upgraded the SDK to 17.7.1 issue disappeared if user fresh install the app, but if user updates from 17.5.0 to 17.7.1 issue is still exist.

Is there anything that we should do on our side?

Please, tell me if anything else is needed.
Thank you,
Best regards,

**Comment by vigavadi** [comment]
@arsalangolestanekh Can you send logs to vigavadi@microsoft.com? Here's details on how to get logs for your app: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app

**Comment by arsalangolestanekh** [comment]
@vigavadi thank you,
Logs have been sent

**Comment by vigavadi** [comment]
@arsalangolestanekh The logs show an older SDK version. 

IntuneMAM: (2023-09-07T22:01:40.603Z) SDK version: 16.0.12

**Comment by arsalangolestanekh** [comment]
Issue was fixed with 17.7.1
