### ISSUE TITLE
Intune SDK causing the application to crash when we delete keychain item through one of our SDK

### ISSUE THREAD

**Issue by gowthamrajc** [msintuneappsdk/ms-intune-app-sdk-ios#374]
**Describe the bug:**
Latest versions of Intune SDK is causing our application to crash when one of the dependency SDK (dynamic framework) tries to delete the value from Keychain using SecItemDelete API. The same crash is not happening when we remove Intune SDK from our application project and try to follow the same flow. 

Additional Note: The dependency SDK project is obfuscated using Guardsquare.

Also we found the similar kind of crash reported in https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/167 and came to know through release notes it has been fixed in Intune SDK 14.5.0.
We tried integrating that older Intune SDK 14.5.0 in our application and found that the SecItemDelete crash is NOT occurring.

**Expected behavior:**
Intune latest SDK should not cause the application to Crash when we delete Keychain item using SecItemDelete API through our obfuscated SDK. 

**Smartphone (please complete the following information):**
 - Device: All Models
 - OS: All versions

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
   We used Intune SDK 17.6.3
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
   Native (iOS)
- Who is the customer?
   Whoever is using Intune SDK in their application
- Do you see a trend with it only being reproduced on a specific device?
   Happening in all device

**Comment by vigavadi** [comment]
@gowthamrajc Can you try v17.7.2?

**Comment by gowthamrajc** [comment]
Yes tried the latest v17.7.1, still getting the crash

**Comment by vigavadi** [comment]
@gowthamrajc Thanks for confirming. Can you send logs and the crash report on vigavadi@microsoft.com?

**Comment by gowthamrajc** [comment]
@vigavadi We have sent the logs and crash report to the above email.

**Comment by gowthamrajc** [comment]
@vigavadi We tried with static library (**Option 2** as per Microsoft Intune App SDK for iOS developer guide) with the latest version **18.0.1**, there is no crash observed. But with with **Option 1** dynamic framework approach we are getting the crash.

**Comment by gowthamrajc** [comment]
@vigavadi Yes the crash is not originating in Intune SDK, As mentioned earlier we are using obfuscated dynamic library (source code protected using Guardsquare's iXGuard) in the app. This works perfectly fine without Intune SDK. But when Intune SDK is also present in the application, this leads to crash.
We are clueless about why the Intune SDK is conflicting with our Guardsquare's iXGuard protected dynamic library SDK.

Is there something that we have to do from our end to avoid this conflict?

**Comment by vigavadi** [comment]
@gowthamrajc It would be hard to determine what's causing the crash without getting a fully symbolicated crash report from that obfuscated library. There isn't a way you can exclude the SDK for your dependencies.
