### ISSUE TITLE
Text missing from Intune dialogs after upgrade to 17.7.1

### ISSUE THREAD

**Issue by dtatcbrain** [msintuneappsdk/ms-intune-app-sdk-ios#375]
**Describe the bug:**
After upgradring our app with the latest Intune SDK (17.7.1), Intune's dialogs have no text.

**To Reproduce**
1. Integrate Intune 17.7.1 into app
2. Trigger an Intune dialog, for example by logging in to the app with two different accounts.
3. See a dialog appear with no text.

**Expected behavior:**
Text should be shown in the dialogs.

**Screenshots and logs:**
![IMG_0012](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/92786379/c3fdbb9c-0d81-477b-8a31-286d30ed013e)
![IMG_0013](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/92786379/7707e7f5-4b5a-4c2f-83a0-3a585e857d7b)

**Smartphone (please complete the following information):**
 - iPhone XR, also reproduced with iPhone 14 simulator
 - Happens on both iOS 16.4 and iOS 17 beta

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
17.7.1

- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native

- For errors post build, does the app launch without being Intune SDK integrated?
Yes all good, just Intune causing trouble.

- Who is the customer?
Municipalicty of Copenhagen and Danish ministry of taxation

- Do you see a trend with it only being reproduced on a specific device?
No

**Comment by vigavadi** [comment]
@dtatcbrain Can you try v17.7.2?

**Comment by dtatcbrain** [comment]
That version hasn't been released yet?

**Comment by vigavadi** [comment]
@dtatcbrain Sorry, 17.7.1 is the latest. Which version of the SDK did you use before this? Did you update the IntuneMAMResources.bundle as well?

**Comment by dtatcbrain** [comment]
That bundle is only needed for the static library, right? We're embedding the framework (IntuneMAMSwift.xcframework). We upgraded from version 17.4.0.

**Comment by vigavadi** [comment]
@dtatcbrain Thanks for confirming. Can you try out 17.7.2? It should be available now.

**Comment by dtatcbrain** [comment]
Seems to be fixed in 17.7.2, thanks

**Comment by vigavadi** [comment]
Thanks for confirming!
