### ISSUE TITLE
UIActivitiyViewController becomes unresponsive with certain Send Org Data settings with latest SDKs

### ISSUE THREAD

**Issue by ryanbland** [msintuneappsdk/ms-intune-app-sdk-ios#376]
**Describe the bug:**
When using an item from a FileProviderExtension the UIActivityViewController opens up but when you press on the app you want to send to nothing happens. This happens when the app is MAM or MDM with Send org data to other apps set to Policy Managed, when on MDM with Policy Managed with OS Sharing the issue does not occur and the file opens in the intended app. 

This issue did not happen in our prior release that used SDK version 17.4.2, however on both 17.7.1 (Which we released last week in anticipation of iOS 17) and the newly released 17.7.2 this issue occurs. 

**To Reproduce**
1. use a file extension provider to create a url to share out of the app
2. use that url with the UIActivityViewController
3. Notice on MAM apps this opens the controller but nothing happens when you try to select any of the apps present, notice this also happens on MDM devices when Send Org Data is set to Policy Managed but not when its set to Policy Managed with OS Sharing.

**Expected behavior:**
When an app is selected in the UIActivityViewController, that app will open the URL

**Smartphone (please complete the following information):**
 - Device: iPhone/iPad
 - OS: 16.6, 16.6.1, iOS 17 beta

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? It works in 17.4.2 and is broken in 17.7.1 & 17.7.2
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native swift

**Comment by gastaffo** [comment]
Which FileProviderExtension are you using? Does it also integrate the MAM SDK?

**Comment by ryanbland** [comment]
We have the NSFileProviderExtension, we have the IntuneMAMSettings setup in the info.plist and it integrates with the sdk.

**Comment by gastaffo** [comment]
use a file extension provider to create a url to share out of the app
use that url with the UIActivityViewController

What exactly do you mean by this?

**Comment by ryanbland** [comment]
Well if you use the fileproviderextension to get a url using the file providers method providePlaceholder, this gives a url that when an item is copied to can be used to do edits to a document without first having to save to the receiving app (assuming the receiving  work with the apple open in place logic). We give that url to the UIActivityViewController like we would any url in our system and the user can choose where to send it.

**Comment by gastaffo** [comment]
Could you provide logs from a device that has the issue? This can be done reproducing the issue and then opening the `IntuneMAMDiagnosticConsole` by calling the `+[IntuneMAMDiagnosticConsole displayDiagnosticConsole]` API.

**Comment by gastaffo** [comment]
Everything appears to be working on that end. Could you also collect diagnostics for Outlook? This can be done by installing Edge and going to about:intunehelp, with those logs we could see what causing the Outlook share extension to not appear

**Comment by ryanbland** [comment]
The options to send are appearing its just that the UIActivityViewController does nothing when we hit them. So for example i see the word app in the list of options to send to but when i touch the word app in the list nothing happens.

**Comment by ryanbland** [comment]
Is there any update on this. Is the outlook log needed, we arnt trying to share to outlook but rather word which is showing up its just that nothing happens when you touch any of the apps (word included) from the UIActivityViewController when the app policy is set to policy managed apps.

**Comment by gastaffo** [comment]
The outlook or word logs would be helpful as we could see why the share extension isn't appearing. They can be collected in the same way through edge.

**Comment by ryanbland** [comment]
[IntuneMAMDiagnosticFiles.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12754149/IntuneMAMDiagnosticFiles.txt)

**Comment by ryanbland** [comment]
also i noticed this behavior not sure if its related but when i had the UIActivityViewController open in my app and in the about :intunehelp and swiped away then came back the UIActivityViewController was missing apps that were their before I swiped to another app. I had to close the controller and reopen to see options to send to again.

**Comment by gastaffo** [comment]
Could you give a description of how you are passing the fileprovider URL into the Activity View Controller? I am not aware of a programmatic interface to get a URL from a file provider in the main app and then to be able to give that to an UIActivityViewController. We do perform some copying and encrypting with share extensions so its possible if the share extension is expecting to be open in place or if the URL becomes broken when copied out of the file provider it could cause issues.

**Comment by ryanbland** [comment]
The AppDelegate can access a sharedProvider created in the fileProviderExtension, from there we can make calls to the fileprovider to get a url using the method urlForItem(withPersistentIdentifier), that URL is used in providePlacholder(at url) to write the placeholderURL, at this point we have that url and can copy data to it then send to a UIActivityViewController.

**Comment by gastaffo** [comment]
I don't see anything obvious in the logs yet. Though the extension could be crashing hence why it's not showing up. If you look at the crash logs for the device do you see any for the outlook or word share extensions?

**Comment by kariohlsen** [comment]
I am seeing something similar in iOS 17 Open In Action Extensions.  Both with my own app and with native MS Apps the Open In is failing.  For example open a document in Word, Send a copy and select Import to Microsoft 365. The dialog is dismissed and the device remains in Word rather than Microsoft 365.   The same thing happens for my own apps Open In Action extension.  I have updated my app to Intune 18.1.1 and am running on an iPhone Pro Max 13 running iOS 17.0.2.  This does not happen on an iOS 16 device.

**Comment by gastaffo** [comment]
@kariohlsen Could you provide Intune, app and crash logs as described above?

**Comment by kariohlsen** [comment]
I uploaded the logs  reference ID: E5FF2C

**Comment by gastaffo** [comment]
@kariohlsen I am seeing "ActivityViewController error loading open-in data: Error Domain=NSItemProviderErrorDomain Code=-1200 "(null)" UserInfo={CMARScrubbedUserInfo=5d116f527b0df75789b9a7093254d7fb657ac153e2cb29854a984db14178a274}" when trying to prepare sending to com.blackberry.intune.bridge.OpenInAction from Word. 

There is a known issue in iOS 17 where an incorrect coercion failure occurs when loading a NSDictionary that we have a workaround in 17.7.2 but it looks like your version of Word is still on 17.7.1. I am not sure when Word will be releasing with a newer SDK but I will update the thread when I can find out.

For the word open in extension I am seeing "Handling OpenIn operation" which shows that it is attempting, however I am seeing no other log statements for that flow which is odd since that particular function has log statement before each return. My best guess is that extension is crashing somewhere in that function before returning, so would you be able to get crash logs for the device you reproed on for com.microsoft.officemobile.actionextension? They should be available in the Devices window of xcode.

**Comment by kariohlsen** [comment]
Yes indeed Word is crashing. I can't find crash logs on Xcode 15/iOS 17 device. Here is console log for Word.
[WordCrashConsole100523.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12823399/WordCrashConsole100523.txt)

**Comment by iambland1990** [comment]
@gastaffo we now have a third customer who this is affecting. What changes were made to how the sdk handles the UIActivityViewController between the 17.4.2 SDK where this continues to work and the newer SDKs? The extension is not crashing as far as I can tell.

**Comment by gastaffo** [comment]
Ok I think I found a change that occured that could be related, although this changes seems to be attempting to fix the problem y'all are having but maybe it didn't work in all cases.

Do your apps have LSSupportsOpeningDocumentsInPlace and UIFileSharingEnabled set to YES?

**Comment by kariohlsen** [comment]
For our app we do not have LSSupportsOpeningDocumentsInPlace or UIFileSharingEnabled set to YES

HOWEVER for us, the recent update to Word and MS 365 that was available on iOS App Store on 10/9/23  v 2.78 (23100104) which included Intune update resolved the issue

**Comment by gastaffo** [comment]
Interesting, word was on an earlier version of the SDK, I think 17.4.2, until the recent update. @iambland1990 @ryanbland  does the issue this still repro for y'all if you update Word? I wonder if there is break where <=17.4.2 can't receive files from >17.4.2

**Comment by gastaffo** [comment]
@ryanbland Could you submit a support ticket through https://learn.microsoft.com/en-us/mem/get-support?toc=%2Fmem%2Fintune%2Ftoc.json&bc=%2Fmem%2Fintune%2Fbreadcrumb%2Ftoc.json 

That way we could maybe do some more code sharing or example sharing so we can try and get a repro on our end

**Comment by gastaffo** [comment]
@ryanbland Does the file URL you are passing to the ActivityViewController already downloaded and exists on the device when you get it from the file provider?

**Comment by ryanbland** [comment]
@gastaffo yes it does. It works perfectly when the setting for Send Org data is set to Policy Managed with OS Sharing but becomes unresponsive if i instead put just Policy Managed, so its something with the sdk since its all the same code on our side

**Comment by gastaffo** [comment]
@ryanbland Is there a possibility we could get a test build or test account that reproduces? Then we could build outlook and step through the compose extension to see why it isn't showing up

**Comment by ryanbland** [comment]
@gastaffo We cannot give that info out on github. I did get a ticket created with support its #2310190040013878. There are inaccuracies in the ticket as it was created over the phone and Im not sure how to go about changing it yet

**Comment by gastaffo** [comment]
@ryanbland Sounds good. Im not exactly sure how to change those on my end. But you can tell them they can transfer to the MAM SDK as we were already discussing on github

**Comment by gastaffo** [comment]
@ryanbland Have you had any luck getting that IcM created?

**Comment by ryanbland** [comment]
@gastaffo Im trying to get that ticket transferred to you but support is saying there isnt a mechanism to do so.

**Comment by gastaffo** [comment]
@ryanbland Thats very odd. Do you have the number? I could try pushing on my end to let them know to send it to my team.

**Comment by ryanbland** [comment]
@gastaffo the only number we have is the #2310190040013878.

**Comment by gastaffo** [comment]
@ryanbland Have you had any luck with support or this issue?
