### ISSUE TITLE
UIContextMenuConfiguration duplicates 

### ISSUE THREAD

**Issue by arsalangolestanekh** [msintuneappsdk/ms-intune-app-sdk-ios#377]
Is there any change related to UIContextMenuConfiguration?

With new Intune SDK 17.7.1+ when I long press on collection cell and create UIContextMenuConfiguration, it calls couple times, this behaviour appears after Intune SDK update. Before it was called 1 time only.

` override func collectionView(_ collectionView: UICollectionView, contextMenuConfigurationForItemAt indexPath: IndexPath, point: CGPoint) `

**Comment by arsalangolestanekh** [comment]
There are some strange logs that I see from Intune:

INFO IntuneManager+Logger.log():20 - [log] IntuneMAM: (2023-09-12T03:13:47.611Z) ActivityItemsConfigurationHooks: Hooking _UIContextMenuActionsOnlyViewController
NFO IntuneManager+Logger.log():20 - [log] IntuneMAM: (2023-09-12T03:13:47.641Z) ActivityItemsConfigurationHooks: Hooking UIInputWindowController
INFO IntuneManager+Logger.log():20 - [log] IntuneMAM: (2023-09-12T03:13:47.643Z) ActivityItemsConfigurationHooks: Hooking UIEditingOverlayViewController

**Comment by neiljac1** [comment]
Hi @arsalangolestanekh. Are you referring to the UIContextMenuActionProvider block being called twice? What side effect is this having on your application?

Thanks,
Neil

**Comment by arsalangolestanekh** [comment]
We have a func to display options when user long press on message

this is example of the result (You can see that options are duplicated: 

![2f7f9093-b62b-4705-83f0-a11efd3119d2](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/61407619/524bbb12-e003-4f24-b0d1-65c857ecbb42)

With new Intune SDK it duplicates options that we have

`let context = UIContextMenuConfiguration(identifier: nil, previewProvider: nil) {
//here code called twice
}`

**Comment by gastaffo** [comment]
Is it called with different suggested options between calls? Is one of the calls made with an empty list?

**Comment by arsalangolestanekh** [comment]
Hello, code inside the UIContextMenuConfiguration closure called twice, 
Inside the closure I have a an array of options to display values for Menu, and looks like Intune SDK calls it second time and it duplicates.
Looks like something calls this closure second time. It worked fine with previous Intune SDK 17.5

**Comment by gastaffo** [comment]
I found the source of the double call. Working on a fix

**Comment by gastaffo** [comment]
We have a fix for this issue. It should be in an upcoming SDK

**Comment by gastaffo** [comment]
The fix has been released in the most recent SDK.
