### ISSUE TITLE
Access Requirements for Pin when Device Pin is set is ignored in latest SDK

### ISSUE THREAD

**Issue by ryanbland** [msintuneappsdk/ms-intune-app-sdk-ios#380]
**Describe the bug:**
When the admin has the Pin for access set to require but App Pin when Device Pin is set set to Not Required, Device pin setting is ignored and the user must still use a pin. This was not an issue with SDK 17.4.2 but on the latest sdks, 17.7.x, 18.0.1, the user is prompted to enter a pin even when IntuneMAMUPN is set in the config and the setting for App pin when device pin is set is set to not required.

**To Reproduce**
1. Have Access Requirements set to Require for "Pin Access" and Not Required for "App Pin when device pin is set" on a managed device with IntuneMAMUPN set in the app config
2. Open the app and notice that on the latest sdks you are still prompted for a pin

**Expected behavior:**
On a device with IntuneMAMUPN setup in the config and the setting for Pin when device pin is set set to Not Required I expect that a user would not be prompted for a pin if the device has a pin

**Smartphone (please complete the following information):**
 - Device: iPhone/iPad running iOS 17

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? works on 17.4.2 and doesnt on 18.0.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native

[Intune-com.imanage.work3intune-0[32].txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12689872/Intune-com.imanage.work3intune-0.32.txt)
[IntuneMAMDiagnosticInfo[5].txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/12689873/IntuneMAMDiagnosticInfo.5.txt)

**Comment by ryanbland** [comment]
We have a customer who is saying this is a blocking issue as the sdk is not respecting their security settings.

**Comment by ryanbland** [comment]
is there anything needed from my side for this to progress?

**Comment by tgrabowski2** [comment]
Hey Ryan, sorry for the delayed response. We have addressed this issue, and the fix will be included in our 18.2.0 release later this month.

**Comment by ryanbland** [comment]
@tgrabowski2 thank you for the update.
