### ISSUE TITLE
In iOS 17, a gray bar appears at the top of the CNContactViewController.

### ISSUE THREAD

**Issue by buginux** [msintuneappsdk/ms-intune-app-sdk-ios#382]
**Describe the bug:**
In the iOS 17 app that has integrated the Intune SDK, we observed a gray bar at the top of the CNContactViewController. However, in the app that does not have the Intune SDK integrated, this page appears normal. Please assist in confirming whether this issue is caused by Intune.

Apart from integrating Intune, the code on our end is identical.

**To Reproduce**
1. Go to CNContactViewController
2. Check the top bar

**Expected behavior:**
There is no grey bar at the top for the iOS 17 app that integrates the Intune SDK

**Screenshots and logs:**
![grey_bar](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/8925205/bec40e1c-f21f-4331-a7e6-32b7d96d555d)

Below is the normal behavior:
![normal](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/8925205/33370b6b-40d8-4aa5-90e4-2f79262f3cad)

**Smartphone (please complete the following information):**
 - Device: iPad mini 6th generation
 - OS: iOS 17

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK version: 17.6.1
- Platform: Native
- For building without Intune SDK, this page appears normally

- Who is the customer?
- On All iOS 17 devices for our App

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
