### ISSUE TITLE
App enrolment failing

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#383]
**Describe the bug:**
One specific user is unable to enroll in the app.

**To Reproduce**
On loginAndEnrollAccount there is an error prompted directly "Account Not Set Up" while other user were able to complete the app enrolement

**Expected behavior:**
Account Not Set Up should not displayed if the user account is configured with Intune and assigned a valid policy. 

**Screenshots and logs:**
First error:
![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/2161122/386ac333-147d-4f07-9b41-f57961b734de)

If we click on OK on the previous alert, then the below alert is prompted.
![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/2161122/79f106f4-7a80-40e7-989b-5eac840da9f1)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOs 17.0

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 18.0.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? No
- For errors post build, does the app launch without being Intune SDK integrated? yes.

- Who is the customer? GP
- Do you see a trend with it only being reproduced on a specific device? Yes, this is specific to one user.

**Additional context:**

**Comment by vigavadi** [comment]
Can you share the incidentId from the logs? Here are the steps to get the diagnostic console for sharing logs: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app.

Once that's displayed, Get Started -> Send logs to Microsoft -> Share the ReferenceId

**Comment by Nookaraju** [comment]
@vigavadi this is still happening for 2 more users. We cannot reproduce to share the logs. Is there way to the customer to be able to share the logs?
