### ISSUE TITLE
During login, see error message "unexpected failure. Contact your organization's support team for help"

### ISSUE THREAD

**Issue by tqvcd** [msintuneappsdk/ms-intune-app-sdk-ios#386]
**Describe the bug:**
When launching the app, we keep getting the error message "unexpected failure. Contact your organization's support team for help" as soon as the Intune MAM login screen appears and we can do nothing but quit the app. This happens before displaying the Microsoft login screen.

**To Reproduce**
1. We have an existing app and integrate it with intune SDK 17.7. 
2. We updated the app info list and URL Types based on the tutorial https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#configure-settings-for-the-intune-app-sdk
3. Add IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil) in appDelegate to login the user through the Intune sign in flow
4. See the error message "unexpected failure. Contact your organization's support team for help" in the popup window. Could not dismiss the popup window and do not see any error output in the Xcode console.

**Expected behavior:**
Display Microsoft login screen, like the attached expected login screen screenshot.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? N/A
- If your app is experiencing an issue post build, do you have app logs for the crash itself? N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro, iPad
 - OS: iOS 16.4, 16.6

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Intune 17.7
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native iOS
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A

- Who is the customer? Internal users
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**

**Comment by gastaffo** [comment]
@tqvcd Can you attach a screenshot of y'alls IntuneMAMSettings in the info.plist? Also could y'all attach the MAM logs for the app? THey can be collected by usint `IntuneMAMDiagnosticConsole` API.

**Comment by tqvcd** [comment]
Hi, @gastaffo,
The IntuneMAMSettings are listed below:
<dict>
	<key>AutoEnrollOnLaunch</key>
	<false/>
	<key>ADALAuthority</key>
	<string>https://login.microsoftonline.com/</string>
	<key>ADALClientId</key>
	<string>9fd170b0-26fa-4848-a671-73df29396d83</string>
	<key>MAMPolicyWarnAbsent</key>
	<false/>
	<key>VerboseLoggingEnabled</key>
	<true/>
</dict>

For MAM logs, since my device is a managed device, so I could not share it.

**Comment by gastaffo** [comment]
@tqvcd It appears y'all are missing ADALRedirectURI which is a required setting. You should be able to find that value inside the app registration. 

Also you should update ADALAuthority to be https://login.microsoftonline.com/common or https://login.microsoftonline.com/<tenant-id> if the app is for a single tenant.

**Comment by tqvcd** [comment]
Hi, @gastaffo, I added ADALRedirectURI(msauth.com.ios.mpoc.master://auth) to info list and changed ADALAuthority to https://login.microsoftonline.com/common, then tested in my local, but still get the same error message

**Comment by gastaffo** [comment]
@tqvcd Would you be willing to send us your info.plist? Have you added the msauth.com.ios.mpoc.master to you CFBundleURLTypes?
Also would you be willing to collect logs via Authenticator and the IntuneMAMDiagnosticConsole?

**Comment by gastaffo** [comment]
@tqvcd Are you still having trouble with this issue?

**Comment by ganeshsmnt** [comment]
@gastaffo I’m getting the error: “Unexpected failure. Contact your organization’s support team for help.”
Here are my IntuneMAMSettings:

![Image](https://github.com/user-attachments/assets/9cf8690c-bf00-4f35-978e-3a25cdf232a9)
