### ISSUE TITLE
Intune SDK does not fetch the tokens saved after authenticating through ADAL

### ISSUE THREAD

**Issue by sidgami** [msintuneappsdk/ms-intune-app-sdk-ios#39]
- I am using the Intune SDK for app protection.
- Our app uses ADAL 2.x for authentication. The authentication works properly and we have been working with it since some time now, no issues whatsoever. 
- Recently, I added the Intune SDK by following the guidelines mentioned here - https://docs.microsoft.com/en-us/intune/app-sdk-ios#configure-settings-for-the-intune-app-sdk
- We are facing issues on iOS, where the intune SDK does not seem to be able to fetch the tokens saved by ADAL.
- I have set up the IntuneMAMSettings dictionary in the Info.plist with the ADALClientId, ADALRedirectUri, ADALAuthority as mentioned in the document. 
- We have checked the keychain sharing capabilities and it all seems to be done properly. 
- The api `registerAndEnrollAccount(..)` fails with a `The operation failed because the SDK could not access the user\'s AAD token.  The application should prompt the user for credentials to refresh the user\'s AAD token.`
- When we use `loginAndEnrollAccount`, everything seems to work fine. (We would want to avoid this because of the double prompting)

- We tried the same thing by cloning and modifying the sample intune app by adding capabilities to authenticate via ADAL before registering with intune - https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App 
and we see the same issue.

Any ideas on why we are seeing this behavior? Is there a workaround for this issue?

Any help would be much appreciated. Thanks!

**Comment by Kyle-Reis** [comment]
Hey @sidgami, a few questions:

1.) Are the values you're setting in IntuneMAMSettings for ADALClientId, ADALRedirectUri, and ADALAuthority the same as the corresponding values used when acquiring a token via ADAL?

2.) Did you follow these steps to give your app access to the Intune App Protection Service: https://docs.microsoft.com/intune/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional

3.) Are you supplying the UPN of the same user you acquired a token for to registerAndEnrollAccount?

**Comment by sidgami** [comment]
@Kyle-Reis : Thank you for your response and sorry for reverting a little late. The problem in my implementation was with point 2. The permissions were not properly granted to my app. I fixed it and now it works fine. 

I will close this issue now. Thank you for your help.
