### ISSUE TITLE
Text missing (again) from Intune dialogs after upgrade to 18.2.0

### ISSUE THREAD

**Issue by dtatcbrain** [msintuneappsdk/ms-intune-app-sdk-ios#390]
**Describe the bug:**
After upgradring our app with the latest Intune SDK (18.2.0), Intune's dialogs have no text.

Intune 17.7.1 had this exact issue, but it's back now. [Previous issue here](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/375).

We upgraded from Intune 17.7.2, so I'm not sure which release the bug reappeared in.

**To Reproduce**
1. Integrate Intune 18.2.0 into app
2. Trigger an Intune dialog, for example by enrolling for the first time.
3. See a dialog appear with no text.

**Expected behavior:**
Text should be shown in the dialogs.

**Screenshots and logs:**
![Screenshot 2023-11-30 at 10 29 32](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/92786379/8b55ed22-a9d0-41b4-8573-1c0f39ad0597)

**Smartphone (please complete the following information):**
Tested on iPhone and iPad, iOS 17

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
18.2.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native
- For errors post build, does the app launch without being Intune SDK integrated?
Yes

- Who is the customer?
Municipality of Copenhagen and Danish Ministry of Taxation
- Do you see a trend with it only being reproduced on a specific device?
No

**Comment by dtatcbrain** [comment]
My bad, that actually helped - seems some files were missing after unpacking the archive. We'd like to use a package manager for Intune to avoid this sort of thing, but couldn't find anything in the documentation about which ones you support?

**Comment by msft-neiljac** [comment]
Glad you were able to fix the issue. We don't support any package managers at this time.

Thanks,
Neil
