### ISSUE TITLE
Intune SDK on macOS M chip

### ISSUE THREAD

**Issue by ArsalanG99** [msintuneappsdk/ms-intune-app-sdk-ios#396]
**Describe the bug:**
I was able to build an app on macOS. 
But on launch I receive this error:
IntuneMAM: (___) MAM_CHECKPOINT: Alert - To access your data associated with account CMARScrubbedIdentity:___, your organization requires this app to run on an iOS model allowed by your organization's support team.
And it doesn't allow me to use the app.
on iPhone all works fine.

**Smartphone (please complete the following information):**
 - Device: macOS
 - OS: 13.5.2

**Intune App SDK for iOS (please complete the following information):**
Intune SDK: 17.7.2
MSAL 1.2.16

**Comment by Kyle-Reis** [comment]
Hi @ArsalanG99 - macOS is not currently supported. The Intune app SDK currently supports iOS and iPadOS.
