### ISSUE TITLE
Intune SSO Login for iOS

### ISSUE THREAD

**Issue by sin713** [msintuneappsdk/ms-intune-app-sdk-ios#40]
Intune integrated app is downloaded from the Intune company portal. Intune Company Portal requires Microsoft account to login. After Intune integrated app is downloaded, on launch app asks the user to login using Microsoft account.

Expected behaviour: Application should use Intune Company Portal username and password, should not prompt for login again.

Actual behaviour: Application is asking for microsoft username and password again.
How to configure the native application to make it work with single -sign on using Intunes SDK And ADAL Library?
Below link is used for Integration of SSO https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v1-enable-sso-ios

**Comment by Kyle-Reis** [comment]
Hey @sin713, by default cross-app SSO is only possible between apps from the same publisher, this is a limitation of the OS, as only apps from the same publisher can share a keychain group. Therefore, SSO between Company Portal and your app is not possible. However, SSO between Company Portal and other MSFT apps does work.

That being said, it is possible to enable cross-app SSO via the Authenticator app. You would need to configure your app to work with the Authenticator (as detailed in the link you shared), and then [override the default Intune AAD settings](https://docs.microsoft.com/intune/app-sdk-ios#configure-adal-settings-for-the-intune-app-sdk).

If you don't want to go through the trouble getting your app to work with the Authenticator, you can at least  get your app to pre-populate the authentication prompt with the UPN of the device-enrolled user. For this to work, you must [configure the required IntuneMAMUPN setting](https://docs.microsoft.com/en-us/intune/data-transfer-between-apps-manage-ios#configure-user-upn-setting-for-microsoft-intune-or-third-party-emm).
