### ISSUE TITLE
NIl Account error - 207 code received

### ISSUE THREAD

**Issue by byhkalo** [msintuneappsdk/ms-intune-app-sdk-ios#401]
**Describe the bug:**
We successfully integrated Intune into the project. Recently one of our customer got the error during the login process with IntuneMAM.

in the method `func enrollmentRequest(with status: IntuneMAMEnrollmentStatus)` we receive error
`IntuneMAMEnrollmentStatusNilAccount = 207, // Nil identity was passed to SDK`

All the code reviewed and we didn't pass Nil any where in login, register or remediation methods

Biggest issue, we can't reproduce it on our side and there is no info what is causing it.

**To Reproduce**
Reproducible on customer side.

**Expected behavior:**
Successfull login flow

**Screenshots and logs:**
![Capture](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/12058642/fa60db40-1a7c-4105-96c1-3018721e8758)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.2.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using?
    - 19.0.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
    - Native iOS

- Do you see a trend with it only being reproduced on a specific device?
   - It reproducible on multiple devices

**Comment by gastaffo** [comment]
@byhkalo Could you collect logs for the affected devices? This can be done using the `+[IntuneMAMDiagnosticConsole displayDiagnosticConsole]` API

**Comment by wangxiaoms** [comment]
Thanks @byhkalo for sharing the information, glad it is working for you now, I'm closing this issue.

**Comment by alanf** [comment]
We have seen this with some of our customers as well, and we have diagnostic logs, but can't share them publicly. Is there someone I could chat with about this issue more? Here are some things we saw in the diagnostic log that looked unusual:

* IntuneMAM: CMARUPNUtils: Failed to get AAD cloud instance name for user, will return default public cloud instance:(nil).
*  IntuneMAM: IntuneMAMEnrollmentManager : Invalid identity. Could not find AAD object id for account: CMARScrubbedIdentity:<redacted>
* IntuneMAM: MAMError: "MAMSharedCache: MAM611 No Device Primary User found in keychain: 1"
