### ISSUE TITLE
The app gets stuck on launch after the SDK integration

### ISSUE THREAD

**Issue by yogendrajs** [msintuneappsdk/ms-intune-app-sdk-ios#402]
**Describe the issue:**
I've integrated the Intune iOS SDK with MSAL in my React-Native app (however, integrating on the native side). On launch, it asks for the credentials like password and PIN (as per the App protection policy), once the correct PIN is entered, the app gets stuck there and does not go forward.

**To Reproduce**
Integrate the MSAL and iOS SDK as defined in the docs and set both `AutoEnrollOnLaunch` and `MAMPolicyRequired` to `true` in the `Info.plist` file and then build and launch the app. After the correct credentials and the PIN is entered, the app gets stuck on the PIN screen. Sometimes, it also gets stuck on the screen where it says: `Checking your organization's data access requirements for this app.`

**Expected behavior:**
The app should have NOT been stuck on the PIN screen and have redirected to the actual app screen.

**Screenshots and logs:**
Seems like `AutoEnrollOnLaunch` is working as I could see this log: ` WARN  Sending EnrollmentStatus with no listeners registered.`. The problem arises when `MAMPolicyRequired` is also `true`.

The logs I could see in the XCode are:

![Screenshot 2024-02-07 at 6 17 11 PM](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/43265032/0237cdb6-67fb-45ef-b86b-c605606a4ed9)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 and 15 Pro (Simulator)
 - OS: iOS 17.0 / 17.2

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes, latest
- What platform is your app based in (native, Xamarin based, Cordova, etc)? React-Native, but implementing on the native side.
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes

**Comment by gastaffo** [comment]
@yogendrajs We have seen some odd side effects with React-Native that can be hard to debug without code. Would you be willing to share a minimal example app that reproduces the error so we could debug on our side? Also could you collect MAM logs for the device? You can start collection by using the `+[IntuneMAMDiagnosticConsole displayDiagnosticConsole]` API on launch

**Comment by yogendrajs** [comment]
@gastaffo I've successfully added Intune SDK for the Android RN app without even integrating MSAL. But, the iOS SDK is causing issues.

I've already added the `[IntuneMAMDiagnosticConsole displayDiagnosticConsole]` API in the `AppDelegate.mm` within the `didFinishLaunchingWithOptions` func, which should work on the launch of the application.

**Comment by yogendrajs** [comment]
@gastaffo any update on this?

**Comment by gastaffo** [comment]
@yogendrajs  Sorry for the delay has been a very busy two weeks. I will take a look at the logs today. I will mention that we don't officially support React Native apps.

**Comment by yogendrajs** [comment]
@gastaffo I understand, but I'm integrating it on the native side of RN (and I successfully did that for Android). It would be helpful if you could please check the logs and get an update on this. Thanks!

**Comment by wangxiaoms** [comment]
@yogendrajs From logs it isn't clear why the app is hanging.  Can you share a minimal example app that reproduces the error then I can test and debug? You may share it via a GitHub repo.

**Comment by yogendrajs** [comment]
@wangxiaoms Yeah, I'll be trying to debug as you suggested. 
Can you also let me know if it is necessary to integrate MSAL for this to be working? It is confusing because, in the Android SDK docs, there's [a section](https://learn.microsoft.com/en-gb/mem/intune/developer/app-sdk-android-phase1#should-my-application-integrate-the-microsoft-authentication-library-msal) which describes when can it be skipped, but for iOS docs, there's no such thing written.

**Comment by wangxiaoms** [comment]
@yogendrajs MSAL is needed, you can follow below procedure to integrate latest MSAL (and latest Intune SDK).
https://learn.microsoft.com/en-gb/mem/intune/developer/app-sdk-ios-phase2

**Comment by yogendrajs** [comment]
@wangxiaoms I didn't quite get why it is mandatory to integrate MSAL for iOS and not for Android. 

Also, had one more question:
Why is it mandatory for Android to install the Company Portal app to get the App Protection policy enforced, and not for iOS, I was able to sign in without it.

**Comment by wangxiaoms** [comment]
iOS and Andriod Intune SDKs have different designs. The Intune App SDK for Android relies on the presence of the Company Portal app on the device to enable app protection policies. The Company Portal retrieves app protection policies from the Intune service. This Company Portal functionality for app protection policy is specific to Android.
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase1#why-is-the-company-portal-app-required-for-application-protection-policies-on-android

**Comment by yogendrajs** [comment]
@wangxiaoms thank you and team for all the information.
I had an issue with my RN dependencies being outdated which was causing issues with the launch. This issue has been fixed, closing this for now.
