### ISSUE TITLE
Intune SDK hangs app on next start after first enrolment happens on iOS 10 devices

### ISSUE THREAD

**Issue by idcuesta** [msintuneappsdk/ms-intune-app-sdk-ios#41]
**Describe the bug:**
Intune SDK hangs app on next start after first enrolment happens on iOS 10 devices.

**To Reproduce**
1. App is opened for the first time
2. User logs into the app using an Azure SSO account (app is using ADAL library for authentication, so when enrolling the user into IntuneSDK there is no double authentication request)
3. After successful login, user is automatically enrolled into IntuneSDK (enrolment returns 100 OK status code), and IntuneSDK present an alert to the user `... You need to restart the app`
4. User press `OK` button and restart the app
5. App opens, but it hangs immediately after opening, showing a 98% CPU consumption on the main thread that never ends.

**Expected behavior:**
In step 5, app should open normally and don't hang.

**Screenshots and logs:**
![intune-ios10-hang-issue-instruments](https://user-images.githubusercontent.com/2726409/62629921-58258980-b92e-11e9-84c5-d4f635473b04.gif)

**Smartphone (please complete the following information):**
 - Device: Tested and reproduced on iPhone5S and Simulator
 - OS: iOS10.3.1 and iOS 10.3.2

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? **11.0.13** Are you using the latest version? **Yes**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? **Objective-C**
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated? **Yes, if the user is not enrolled into IntuneSDK, app works fine**
- Who is the customer? **CipherHealth**
- Do you see a trend with it only being reproduced on a specific device? **On any iOS 10 device we could test**

**Additional context:**
As shown in the instruments .gif file, it looks IntuneSDK is hanging the app when executing `[NSOutputStream(CMARHookedOutputStream) load]`.

**Comment by Kyle-Reis** [comment]
Hey @idcuesta, thanks for reporting this issue and for all the really helpful analysis! We're investigating this and I'll give an update as soon as I have one

**Comment by Kyle-Reis** [comment]
@idcuesta, this issue is now understood and a fix is in code review

**Comment by idcuesta** [comment]
Thank you very much for your prompt action on this bug @Kyle-Reis, impressive response time 💯

**Comment by idcuesta** [comment]
Hi @Kyle-Reis , any ETA for a new version of the SDK with this issue solved?

**Comment by Kyle-Reis** [comment]
Hey @idcuesta, we're targeting end of this week to have the fix available.

**Comment by Kyle-Reis** [comment]
Hey @idcuesta, by end of this week, I meant today :) The fix is now available in our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (11.1.2)
