### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by caspernot** [msintuneappsdk/ms-intune-app-sdk-ios#413]
# Microsoft Intune App SDK for MAUI.iOS Issue

## Summary
**Describe the bug:**

**To Reproduce**

**Expected behavior:**

**Intune App SDK for iOS (please complete the following information):**
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

## Details

- Device: [e.g. iPhone 14]
- iOS Version: [e.g. iOS 16.6.1]
- `Microsoft.Intune.Maui.Essentials.iOS` Version:
- Build Operating System (Mac, Windows) and Version:
- Visual Studio Version:

## Screenshots and logs

- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

## Questions to Ask Before Submission

1. Does the app build and launch without including the `Microsoft.Intune.Maui.Essentials.iOS` package?
2. Does the issue reproduce if you rebuild after deleting the `bin` and `obj` output folders?
3. Have you checked the [.NET MAUI repository](https://github.com/dotnet/maui/issues) for similar issues? If so, please follow the guidance there or add that information to this issue.
4. Are you using the latest `Microsoft.Intune.Maui.Essentials.iOS` NuGet package version?

**Comment by wangxiaoms** [comment]
This does not include any real issue description or repo procedure, close it.
