### ISSUE TITLE
sqlite3_finalize app crash

### ISSUE THREAD

**Issue by lastsemler** [msintuneappsdk/ms-intune-app-sdk-ios#415]
**Describe the bug:**
We use the Intune App SDK in more than 10 of our company apps and we see a lot of random app crashes related to sqlite3_finalize. It happens both when the apps are used and when they are running in the background.

**To Reproduce**
We use Intune App SDK with MSAL and detect the crashes in Visual Studio App Center.

**Expected behavior:**
We expect that the apps do not crash because of the Intune App SDK

**Screenshots and logs:**
[report-2516913766030009999-0b08e240-0697-499b-b5e1-5b26c51cbc05.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/14663858/report-2516913766030009999-0b08e240-0697-499b-b5e1-5b26c51cbc05.txt)

**Smartphone (please complete the following information):**
The crash happens across all of our iOS devices running iOS version 15-17.

**Intune App SDK for iOS (please complete the following information):**
We use Intune App SDK for iOS version 19.2.0 and MSAL version 1.3.0 but we have experienced the same issue in earlier versions as well.

**Additional context:**
None

**Comment by ChismanRaheem** [comment]
Hi @lastsemler working with my team it's been confirmed that applications which can access files in the background while the device is locked must set the MaxFileProtectionLevel value under the IntuneMAMSettings dictionary in the application's Info.plist This should be set to "NSFileProtectionCompleteUntilFirstUserAuthentication". If this is not set, files will not be accessible while the device is locked. This will cause a crash in sqlite.

**Comment by ChismanRaheem** [comment]
ref : https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3
![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/159470974/8fddc124-3a8e-4d3a-9d11-0aebc4b2af3a)

**Comment by lastsemler** [comment]
Thanks a lot @ChismanRaheem! I can confirm, that the suggested solution has solved the problem in our apps.
