### ISSUE TITLE
Static library can't be used

### ISSUE THREAD

**Issue by arnauZurich** [msintuneappsdk/ms-intune-app-sdk-ios#416]
**Describe the bug:**
I'm trying to use the static library ([Option 2](https://learn.microsoft.com/en-gb/mem/intune/developer/app-sdk-ios-phase3#build-the-sdk-into-your-mobile-app)) but the expected classes cannot be found.

This problem doesn't occurs with the dynamic library (option 1).

I have exactly the same issue reported here #326, but the workarounds exposed there are not working for me. I put comments on that thread 3 weeks ago, but nobody answered.

**To Reproduce**
1. Download the Intune sample app ([Chatr](https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App))
2. Try to use the static library instead.
3. The classes cannot be found.

**Comment by wangxiaoms** [comment]
@arnauZurich We are looking into this.

**Comment by wangxiaoms** [comment]
Hi @arnauZurich as checked the following procedure works for me to get Chatr sample build successful with Intune SDK as Static Library:

1. Set the 'Header Search Paths' and 'Library Search Paths' in Xcode - Build Settings
2. Add the Bridging header (import IntuneMAM.h in it), set 'Objective-C Bridging Header' in Xcode - Build Settings
3. Add framework MetricKit.framework, this is mentioned in [public doc](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#build-the-sdk-into-your-mobile-app:~:text=WebKit.framework-,MetricKit.framework,-Enable%20keychain%20sharing) but it is not in the app.

Let me know how you go.

**Comment by arnauZurich** [comment]
Hi @wangxiaoms, your procedure has finally worked for me. Thank you so much for your time 😄
