### ISSUE TITLE
New entitlement required - NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by oreporan** [msintuneappsdk/ms-intune-app-sdk-ios#420]
**Describe the bug:**
I've started compiling my app with the latest xcode and ios version (ios 17)
After doing so, my app started getting rejected on Testflight on the missing entitlement - [NSPhotoLibraryUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsphotolibraryusagedescription)

> ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Client.app” bundle should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data.

I can pinpoint it to intune because if I remove the xcframework this entitlement is no longer required

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? YES
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native

**Comment by ChismanRaheem** [comment]
@oreporan Please try adding the keypair string to your info.plist
`<key>NSPhotoLibraryUsageDescription</key>
<string>Photo Library Access Warning</string>`

**Comment by oreporan** [comment]
Thanks @ChismanRaheem 
I'm aware of the option of adding that entitlement, my question is where is this coming from? For my app, its impossible to add this entitlement as it clashes with another one I have, and apple is rejecting me for that

I'm wondering when/how this new entitlement came to be required in my app with intune? and how can I get rid of it?

**Comment by ChismanRaheem** [comment]
Hi @oreporan !
Understanding your application and its complete setup is crucial for a thorough root cause analysis (RCA). From the snippet you’ve shared, it appears that your code might be utilizing an API with access to sensitive data. Notably, the Intune SDK does not directly depend on this specific property list key. To assist you better, please provide additional details such as logs and information about how the app is configured.

**Comment by oreporan** [comment]
Hey
thanks for getting back to me

Turns out intune requires this entitlement when your app also needs [Jitsi Meet SDK](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/)

Currently we are forced to remove Jitsi in order to make intune work
