### ISSUE TITLE
iOS 16 Siri AppIntents Guidance

### ISSUE THREAD

**Issue by jeff-dialpad** [msintuneappsdk/ms-intune-app-sdk-ios#428]
**Describe the bug:**

**For custom AppIntents, is it possible to block Siri from recognizing registered shortcut phrases?**

We have some Siri functionality implemented with the iOS 16-style custom AppIntents. In the app participation features documentation [here](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase4) it is noted that:

> In iOS 16 and above, a new App Intents system framework is available for creating Swift App Intents. Apps that implement an App Intent should first check the areSiriIntentsAllowed property on the IntuneMAMPolicy object for the user.

Is there is any documentation or advice available on how to accomplish this? The issue is that the shortcut phrases are declared statically in a `@AppShortcutBuilder`, which does not allow us to run any dynamic checks, so the shortcut phrases are always registered with the system. Similarly any parameters to for the intent are defined using IntentParameter `@Parameter` property wrappers, requiring us to statically hook up those parameters.

Our first chance to check areSiriIntentsAllowed appears to be in the `perform()` function of the AppIntent. We can manually block the action from executing at this stage if needed.

Therefore we can block the action and provide an error communication only _after_ iOS has reacted to a user invoking a shortcut phrase and gathered any parameters from the user. In the iOS-controlled parameter gathering phase, there is no indication that we will be blocking their action.

**To Reproduce**
Define a custom AppIntent, with a parameter, and register its shortcut phrases with an @AppShortcutBuilder.
Enrol a user whose policy disallows Siri Intents.
Invoke the Siri shortcut phrase.
Observe that Siri recognizes your request and will automatically ask the user for input for any parameters.

**Expected behavior:**
Is it possible to block a custom AppIntent from being invoked by its shortcut phrase?
Ideally we would like to have Siri fail to recognize the shortcut phrase, so the system will not ask the user to provide a paremter.

**Smartphone (please complete the following information):**
 - Device: iPhone, and others
 - OS: iOS 17.3.1, iOS 16, 

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Latest, 19.3.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native iOS
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A
- Do you see a trend with it only being reproduced on a specific device? No

**Comment by wangxiaoms** [comment]
Use main issue of #427
