### ISSUE TITLE
IntuneMAMSettings.h missing from headers folder in v11.1.2

### ISSUE THREAD

**Issue by idcuesta** [msintuneappsdk/ms-intune-app-sdk-ios#43]
**Describe the bug:**

When updating version of Intune SDK to version 11.1.2, App doesn't compile because of missing header `IntuneMAMSettings.h`.

This happens because library is added to the project without using the Framework, but using `libIntuneMAM.a` and headers are added from your `Headers` folder.

Problem is that `IntuneMAMSettings.h` is missing in `Headers` folder.

**Workaround**

Copying `IntuneMAMSettings.h` from Framework headers works.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? **11.1.2** Are you using the latest version? **Yes**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? **Objective-C**
- For errors during build, does the app build without Intune SDK integration? **Yes**
- Who is the customer? **CipherHealth**

**Comment by Kyle-Reis** [comment]
Hey @idcuesta, thanks for reporting this. We’ll get it addressed ASAP.

**Comment by Kyle-Reis** [comment]
This is now fixed.
