### ISSUE TITLE
The configured universal link doesn't open the app

### ISSUE THREAD

**Issue by yogendrajs** [msintuneappsdk/ms-intune-app-sdk-ios#436]
**Describe the issue:**
We integrated the Intune SDK into our iOS app. But the universal link doesn't reopen the app after successful SSO sign-in using a managed browser (Edge). The user sees the following dialog box when clicking a button that contains the universal link.

![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/43265032/89e6c77b-b47a-4f10-9a6f-e902db3fd183)

**App Protection policy settings**
We've created one App protection policy for the app for which the 'Restrict web content transfer with other apps' setting is set to 'Microsoft Edge'. Other settings are default. The device is managed. However, I've NOT created any APP for 'Edge'.

I've also briefly learned about 'Select universal links to exempt' and 'Select managed universal links' settings but didn't modify them as the app reopens correctly on my device, but others. Please let me know if anything else needs to be configured in the APP to make it work.

**Expected behavior:**
The app should've been opened when the button was clicked with the universal link.

**Smartphone:**
 - Device: iPhone13
 - OS: iOS17.4.1

**Comment by wangxiaoms** [comment]
Hi @yogendrajs would you provide more details, is the button in your app, or somewhere else? What is the universal link content? Is the link supposed to open your app? Were you able to login to your app and get enrolled?

**Comment by yogendrajs** [comment]
Hi @wangxiaoms , the button is on a website which contains the app's universal link. It is something like `appname://content`. Yes, this link is supposed to open the app when clicked. Yes, the Intune login was successful and the app was able to enroll on the first startup as I use `AutoEnrollOnLaunch` and `MAMPolicyRequired` options as `true` in the app's `Info.plist` file.

**Comment by wangxiaoms** [comment]
Hi could you confirm, if without MAM policy, e.g. remove AutoEnrollOnLaunch and MAMPolicyRequired, is the URL scheme link working fine?

**Comment by yogendrajs** [comment]
@wangxiaoms it is working fine when the browser is not managed, so I don't see any concerns with the above values

**Comment by wangxiaoms** [comment]
@yogendrajs can you follow step number 7 (IntuneMAMConfigurator) here: https://learn.microsoft.com/mem/intune/developer/app-sdk-ios-phase3#build-the-sdk-into-your-mobile-app
Among other things, the IntuneMAMConfigurator tool will add URL schemes to the existing list declared in the app's Info.plist so that it can receive openURL requests from other Intune-managed applications. If still not working can you share a copy of the app's Info.plist.

**Comment by yogendrajs** [comment]
@wangxiaoms I already followed this step by using the IntuneMAMConfigurator tool and it also added the needed URL schemes to the list.

As I suspected, turns out I needed to add our app's URL scheme to the excluded list within the App protection policy for the Edge browser. Closing this for now. Thank you!
