### ISSUE TITLE
Microsoft Intune SDK | Native Script plugins availability for iOS

### ISSUE THREAD

**Issue by virinchypanangipalli** [msintuneappsdk/ms-intune-app-sdk-ios#439]
I would like to integrate the Microsoft Intune SDK into my application using NativeScript plugins. Are there any existing NativeScript plugins available for incorporating the Intune SDK on iOS devices or whats the recommendation / guidance in this scenario?

**Comment by ChismanRaheem** [comment]
Hi @virinchypanangipalli I have validated there are no existing NativeScript plugin available for our Intune SDK and though we have reports of customer with successfully integration it is not officially supported and currently Microsoft does not provide guidance or plugins outside the supported platforms. I will be closing this incident and report this as an enhancement requested.
 
 
 Recommendation:
 App wrapping tool https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios
