### ISSUE TITLE
Trying to change the Intune PIN fails

### ISSUE THREAD

**Issue by sidgami** [msintuneappsdk/ms-intune-app-sdk-ios#44]
@Kyle-Reis : 

- My app has the intune SDK integrated. We are sharing ADAL between exchange and Intune login. It works perfectly without the app double prompting for Intune. 
- I followed the documentation and setup the IntuneMAM Settings with the correct ADALAuthority, ADALClientId and ADALRedirectUri. 

- **Issue I am facing**

<img width="349" alt="Screen Shot 2019-08-22 at 6 39 45 PM" src="https://user-images.githubusercontent.com/1117834/63517406-92854e00-c50c-11e9-831b-4c580f846549.png">

- In the screenshot above, when I try to reset the pin by tapping on `Forgot your pin, or need to change it?` , it prompts me for my work account credentials. As soon as I input my work credentials, it fails with the following:

- AADSTS650057: Invalid resource. 
The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. 
Client app ID: `<client app id>`
`Resource value from request: https://intunemam.microsoftonline.com`
`Resource app id: b642c013-22f8-419d-af11-8f0e05b795e6`
List of valid resources from app registration: `<list of resource app ids, that does not have the above resource id>`
`Trace id: 73b08a1f-80da-4d1f-891a-86716a904a00`
`Correlation ID: 00abea30-10ca-486b-85ef-8948038e59e1`
`Timestamp: 2019-08-22 13:22:30Z`

- I understand that my app is trying to access a resource that it does not have permissions for. But, I wanted to understand which permissions am I missing here? Also, if I use **default ADAL values for Intune SDK**, it allows me to reset the PIN. 

- Could you please point me towards the right permissions set so that I can reset the pin properly? We are nearing a release and are blocked on this issue since the past 2 days. 

- Here are the permissions that my app currently has: 

![Screen Shot 2019-08-22 at 7 04 11 PM](https://user-images.githubusercontent.com/1117834/63519021-d4fc5a00-c50f-11e9-9866-059ec9c4b872.png)

- Thanks once again, as I hope for a solution to this issue.

**Comment by msintuneappsdk** [comment]
Hi  - could you send us your AAD client ID to msintuneappsdk@microsoft.com and we'll get your app approved for access.

**Comment by sidgami** [comment]
@msintuneappsdk : Just send the AAD Client Id. Let me know once my app is approved for access. 

Thanks for the quick revert 👍

**Comment by sidgami** [comment]
Thanks a lot @msintuneappsdk and @Kyle-Reis. It works now. I will close this issue. 

I really appreciate the quick turnaround time. Really impressive 💯

**Comment by sidgami** [comment]
@Kyle-Reis @msintuneappsdk : Need help with approving app access that we are going to use for the iOS app rollout to our customers.

I have already sent an email to  msintuneappsdk@microsoft.com with the **client id**. Could you please approve my app for access, so that the app properly access the Intune resources?

Thanks once again!

**Comment by msintuneappsdk** [comment]
Done.

**Comment by idcuesta** [comment]
Hi there, 

We are experiencing exactly the same issue that is described in here. What is the fix for this ? 

We have a multi-tenant app and we are currently using 6 different client ids (we have 3 environments and different apps for Android and iOS).

Regards

**Comment by msintuneappsdk** [comment]
Hi @idcuesta, if you or anyone else using the Intune SDK is hitting the following error, please email msintuneappsdk with a list of Client IDs that your app is using:

```
<client app id>
Resource value from request: https://intunemam.microsoftonline.com
Resource app id: b642c013-22f8-419d-af11-8f0e05b795e6
```

**Comment by idcuesta** [comment]
Thank you for quick answer, I have already sent an email 👍

**Comment by lucac-apps** [comment]
This morning we sent the same request:
Resource value from request: https://intunemam.microsoftonline.com
Resource app id: b642c013-22f8-419d-af11-8f0e05b795e6

I am looking forward to receiving your answer!

**Comment by viveknegi51288** [comment]
@msintuneappsdk i have sent a mail, can u please check and approve the access please

**Comment by viveknegi51288** [comment]
@msintuneappsdk  please approve the access

**Comment by Kyle-Reis** [comment]
Hi @viveknegi51288, access should be granted now.

**Comment by viveknegi51288** [comment]
yes thanks @Kyle-Reis and @jamie

**Comment by lucac-apps** [comment]
I sent the same request below for two apps:
Resource value from request: https://intunemam.microsoftonline.com
Resource app id: b642c013-22f8-419d-af11-8f0e05b795e6

I am looking forward to receiving your answer!

**Comment by lucac-apps** [comment]
@msintuneappsdk Can you please grant the requested access? 

We are stuck.

**Comment by lucac-apps** [comment]
@msintuneappsdk Any chance to grant the requested access? 
I sent the request on 18.9.2020.

**Comment by Kyle-Reis** [comment]
Hi @lucac-apps, Sorry for the delay here. Was your app granted access? In the future, if replying to a closed issue doesn't seem to yield a response, opening a new one should :)

**Comment by lucac-apps** [comment]
> Hi @lucac-apps, Sorry for the delay here. Was your app granted access? In the future, if replying to a closed issue doesn't seem to yield a response, opening a new one should :)

Well, a few weeks after my request and several escalations within Microsoft. 
Ignite time is definitely not a good one to ask Microsoft to fulfill a request.

Is there any possibility to empower developers/customers to grant this access to their apps autonomously?

**Comment by Kyle-Reis** [comment]
@lucac-apps, actually with the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the SDK, you should no longer need to request this :). However, if you're using the same client ID on Android, you may still need the approval.

**Comment by lucac-apps** [comment]
> @lucac-apps, actually with the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the SDK, you should no longer need to request this :). However, if you're using the same client ID on Android, you may still need the approval.

Thanks; this is good news.

Forgive my simple mind... does "if you're using the same client ID on Android, you may still need the approval"== you still have to request it ?

**Comment by Kyle-Reis** [comment]
If you've already sent a mail with the client ID(s) you need approved I can check on it. Is the same client ID also used on Android?

**Comment by Kyle-Reis** [comment]
But yes, for any future client IDs used on Android, you still need to request approval :)

**Comment by lucac-apps** [comment]
Ok, thanks for helping me out. :-)
