### ISSUE TITLE
iOS 13 - Apps using intune is crashing while trying to open a file into other apps

### ISSUE THREAD

**Issue by JBenny25** [msintuneappsdk/ms-intune-app-sdk-ios#45]
**Describe the bug:**
Tested with word app 2.28
Device - iPhone X - iOS13 beta 7

- Open word. Login with an intune enabled user.
- Open a file and share a copy to another app via "Send with Another App" option
- The app crashes

**NOTE:**
-  If the app is logged in with a non-intune user, the app doesn't crash and open in is successfully carried out
- Similar issue is found with apps integrating with intune SDK in iOS 13

**Expected behavior:**
The app should not crash while trying to openIn a file to a different app.

**Crash logs**
[Word  26-08-19, 2-25 PM.crash.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/3540451/Word.26-08-19.2-25.PM.crash.zip)

**Comment by JBenny25** [comment]
@Kyle-Reis is this a known issue?

**Comment by gaurav17281** [comment]
@Kyle-Reis - Is this something a known issue? This is causing our application crash every time and would like to see if there's a work around.

**Comment by Kyle-Reis** [comment]
Hey @JBenny25 and @gaurav17281, we were able to reproduce this issue and will have a fix available soon.

**Comment by gaurav17281** [comment]
Thanks for acknowledgement @Kyle-Reis.

**Comment by JBenny25** [comment]
Thanks for the acknowledgment @Kyle-Reis

**Comment by Kyle-Reis** [comment]
We are working on making the fix available this week.

**Comment by gaurav17281** [comment]
Great. thanks for update @Kyle-Reis

**Comment by Kyle-Reis** [comment]
This issue should be fixed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases) (11.2.0)

**Comment by JBenny25** [comment]
It works now. Thanks @Kyle-Reis
