### ISSUE TITLE
iOS 13 dyld: Symbol not found: OBJC_CLASS$__TtCs12_SwiftObject

### ISSUE THREAD

**Issue by slnali** [msintuneappsdk/ms-intune-app-sdk-ios#49]
name: Bug report
about: Create a report to help us improve
title: ''dyld: Symbol not found: OBJC_CLASS$__TtCs12_SwiftObject
labels: ''
assignees: ''

---

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**
dyld: Symbol not found: OBJC_CLASS$__TtCs12_SwiftObject
Referenced from: /Users//Library/Developer/CoreSimulator/Devices/18FE6DA6-C140-41AB-8B8F-E4CB9CB8A648/data/Containers/Bundle/Application/5C108836-4EF8-4EA7-8AC3-48C315D06069/chatr.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift
Expected in: /Users//Library/Developer/Toolchains/swift-5.0-RELEASE.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib

in /Users/_/Library/Developer/CoreSimulator/Devices/18FE6DA6-C140-41AB-8B8F-E4CB9CB8A648/data/Containers/Bundle/Application/5C108836-4EF8-4EA7-8AC3-48C315D06069/chatr.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift
I get a successful build of the project but as the simulator starts to run the app I get above error. iOS 13, Intune (11.2.0).

**Expected behavior:**
Chatr App should run and connect to Intune services.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
<<<<<<< HEAD
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
=======
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3

**Smartphone (please complete the following information):**

<<<<<<< HEAD
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 11.2.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? iOS native
- For errors during build, does the app build without Intune SDK integration?  does not fail at build
- For errors post build, does the app launch without being Intune SDK integrated?
=======
**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hey @slnali, could you try the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (12.0.12)? This version has support for Xcode 11.

**Comment by Kyle-Reis** [comment]
Hey @slnali, just checking in again to verify that this issue is resolved with 12.0.12 before closing out this issue.

**Comment by slnali** [comment]
Hey Kyle, yep tested it on 12.0.12.. all good. Thanks for letting me know.
