### ISSUE TITLE
Intune PIN Controller Presentation style in iOS 13

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#50]
name: Bug report
about: Create a report to help us improve
title: Intune PIN View Controller Presentation style in iOS 13
labels: ''
assignees: ''

**Describe the bug:**
When App is built using Xcode 11 and running in iOS 13, all the model presentations should be in full screen. 

Currently, When PIN view is presented, user is able to dismiss PIN screen by swiping down which we shouldn't allow.

**To Reproduce**
1. Run app in iOS 13 which is built from Xcode 11.
2. PIN view is dismissing on new iOS 11 swipe gesture.

**Expected behavior:**
User should not able to dismiss the PIN screen without providing PIN input.

**Screenshots and logs:**
Attached Screenshot.
![PIN VC](https://user-images.githubusercontent.com/2161122/65873751-8c9f4a00-e3a1-11e9-8735-810d57c67344.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.0

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - 11.2.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Xcode native
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer? Infor
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, Xcode 11 isn't officially supported just yet, but we're working on getting a release out ASAP which suports building with Xcode 11.

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, this issue is now fixed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (12.0.12)
