### ISSUE TITLE
Conditional Access with Intune

### ISSUE THREAD

**Issue by sidgami** [msintuneappsdk/ms-intune-app-sdk-ios#51]
@Kyle-Reis @msintuneappsdk :

We deployed our iOS app with the Intune SDK recently. At this point, the user is blocked by Conditional Access when he/she tries to login. 

We figured out the conditional access policy that is blocking us and it is the `Require Approved Client App`.

<img width="1216" alt="Screen Shot 2019-10-01 at 12 14 52 AM" src="https://user-images.githubusercontent.com/1117834/65906625-867c8e00-e3e0-11e9-94a7-0507ffb010d5.png">

 We see the list of all the approved client apps and they are all **Microsoft apps**. How do we then, **_add our iOS app to the list of approved client apps_**? Please let us know. 

We need a solution urgently as this is stopping our customers from using the app in a productive manner

**Comment by msintuneappsdk** [comment]
Can you reach out to me directly for more information on this – jamiesil@microsoft.com<mailto:jamiesil@microsoft.com>

**Comment by sidgami** [comment]
Hi @msintuneappsdk - I replied to `jamiesil@microsoft.com` from my work email `siddharth.gami@tact.ai`.

Waiting for any further action items. Thanks!

**Comment by sidgami** [comment]
Hi @aanavath @Kyle-Reis @msintuneappsdk  - We needed to support Conditional Access in our app. I made the code changes to enable brokered authentication for the app, as mentioned by `jamiesil@microsoft.com`. 

This is how I have set up Conditional Access - 

<img width="1213" alt="Screen Shot 2019-10-10 at 11 31 54 AM" src="https://user-images.githubusercontent.com/1117834/66543007-c74b7400-eb51-11e9-980c-9a712cc104f2.png">


Based on the **remediation flow** mentioned in the doc shared by Jamie, I am **not** getting the error **ERROR_SERVER_PROTECTION_POLICY_REQUIRED** from the Microsoft Authenticator app. Infact, I am stuck on the Microsoft Authenticator app with the following message. **We never receive a callback to our app** 

![image](https://user-images.githubusercontent.com/1117834/66543470-16de6f80-eb53-11e9-8ce0-f0254bc0383d.png)

I need the callback to our app with the error message to begin the remediation flow. Are we missing something in terms of configuration?

Library versions used:
Intune (12.0.12)
ADAL (4.0.2)
Microsoft Authenticator (6.3.22)

Please let us know. Thanks.

**Comment by tritter** [comment]
Hi @sidgami 
I’m in the exact same boat. How did you fix it; what was your workaround? 
Thanks Thom

**Comment by sidgami** [comment]
> Hi @sidgami
> I’m in the exact same boat. How did you fix it; what was your workaround?
> Thanks Thom

Hi @tritter - I reached out to @msintuneappsdk regarding this. Jamie Silvestri `jamiesil@microsoft.com` was very helpful and guided me through the remediation flow. They will need to whitelist your App Id, for you to proceed further. 

So, please reach out to them. 

Let me know if you need any more help :)
