### ISSUE TITLE
IntuneMAMSwift.framework missing in version 12.0.12

### ISSUE THREAD

**Issue by sidgami** [msintuneappsdk/ms-intune-app-sdk-ios#52]
@msintuneappsdk @aanavath @Kyle-Reis : 

Cant find `IntuneMAMSwift.framework` in the latest version - 12.0.12

Has something changed? Are there any changes with the integration of the latest version of the SDK?

**Comment by msintuneappsdk** [comment]
@sidgami Good catch, this was an error with the upload. Fixing it shortly.
