### ISSUE TITLE
I can not set IntuneMAM.framework using MSAL.framework as default authentication.

### ISSUE THREAD

**Issue by 84798012** [msintuneappsdk/ms-intune-app-sdk-ios#53]
I want using MSAL.framework as default authentication. But it can not go to there. The offical demo app "Wagr" is using libADAL.a. I have test using libADAL.a, it can work. But when I want switch to using MSAL.framework, it never run to MSAL.framework. I have follow the offical document do : set ADALClientId, ADALRedirectUri; set NSUserDefaults. IntuneMAMUseMSALOnNextLaunch= yes. But it does not seems to run into MSAL.framework.
And more from the Wagr demo,  IntuneMAM.framework can show logs. But using new IntuneMAM.framework replace, there is no log show, I can not debug or analysis. It's too difficult for me to using it. Anyone can help who knows about this logic, many thanks!!

**Comment by 84798012** [comment]
by the way, I'm using intuneMAM.framework 11.1.2, MSAL.framework 0.5. the enrollmentRequestWithStatus always got 201 error, internal error. just seems like can not find MSAL. So what's the key step to make sure intuneMAM can find MSAL?

**Comment by Kyle-Reis** [comment]
Hey @84798012, you shouldn't need to set the NSUserDefaults key if the app is only linking against MSAL.  Is the device you are testing with connected to the internet? Which enrollment method are you calling? loginAndEnrollAccount or registerAndEnrollAccount? Also, if you are building with Xcode 11 you should upgrade Intune to 12.0.12 and MSAL to 0.6.0. We are adding support for 0.7.0+ now

**Comment by 84798012** [comment]
One more qustion need your help. 
We have one project that using below:
1. OnedriveSDK + libADALiOS.a 
2. Office365 calendar + MSAL.framework (0.8)
Now we're going to add Intune MAM. You said I should using Intune12.0.12 + MSAL 0.6.0.
Could you give me a suggestion, we choose to use ADAL or MSAL, which one is better? And whether we need to upgrade OnedriveSDK to use MSAL? We are bussiness app, needs stable first.

**Comment by 84798012** [comment]
> Hey @84798012, you shouldn't need to set the NSUserDefaults key if the app is only linking against MSAL. Is the device you are testing with connected to the internet? Which enrollment method are you calling? loginAndEnrollAccount or registerAndEnrollAccount? Also, if you are building with Xcode 11 you should upgrade Intune to 12.0.12 and MSAL to 0.6.0. We are adding support for 0.7.0+ now

One more qustion need your help. 
We have one project that using below:
1. OnedriveSDK + libADALiOS.a 
2. Office365 calendar + MSAL.framework (0.8)
Now we're going to add Intune MAM. You said I should using Intune12.0.12 + MSAL 0.6.0.
Could you give me a suggestion, we choose to use ADAL or MSAL, which one is better? And whether we need to upgrade OnedriveSDK to use MSAL? We are bussiness app, needs stable first.

**Comment by 84798012** [comment]
> Hey @84798012, you shouldn't need to set the NSUserDefaults key if the app is only linking against MSAL. Is the device you are testing with connected to the internet? Which enrollment method are you calling? loginAndEnrollAccount or registerAndEnrollAccount? Also, if you are building with Xcode 11 you should upgrade Intune to 12.0.12 and MSAL to 0.6.0. We are adding support for 0.7.0+ now

Could you tell me when will Intune12.0.12 support MSAL.framework 0.8 and 1.0 ? Thanks.

**Comment by 84798012** [comment]
@Kyle-Reis , 
I'm using xcode11.1 + Intune12.0.12 + MSAL.framework0.6. But it still can not work. (I've tried MSAL v0.5-1.0, none can work)
When using registerAndEnrollAccount, it will return status from enrollmentRequestWithStatus: 
201 Error. There was an internal error in the Intune MAM SDK.  Please see the NSError object for more details.
When using loginAndEnrollAccount, it will show "Unexpected failure. Contatct your IT administrator for help" in the Application Logon page.
I can not figure out what's wrong with it, because there no usefull information I can find.
I can make sure Intune have called MSAL, it runs to MSALPublicClientApplication.m -> load, init.
Could you help on this issue? Or it is not a good solution to using MSAL.framework in Intune ?
Thanks!

**Comment by Kyle-Reis** [comment]
Hey @84798012, in the registerAndEnrollAccount case, were you able to successfully authenticate the user using MSAL directly before calling registerAndEnrollAccount?

We are targeting end-of-month for support of MSAL 0.7 and beyond. The changes are currently in review.

For your 1st question, I just want to make sure I understand fully. You have a single project that contains both MSAL and ADAL?

**Comment by 84798012** [comment]
@Kyle-Reis , Thanks for your reply. 
Do you means if using Intune -> registerAndEnrollAccount, I must invoke MSAL API acquireTokenWithParameters first, and then invoke  Intune -> registerAndEnrollAccount ? 

And how about the loginAndEnrollAccount case ? I think it should auto invoke MSAL authenticate flow, isn't it ?

For my 1st question, we do have a single project contains both MSAL and ADAL. (Now using MSAL v0.8 + ADAL.a v1.0.2)

**Comment by Kyle-Reis** [comment]
@84798012, yes, registerAndEnrollAccount is meant to silently enroll the user after the application has already authenticated using ADAL/MSAL. Please see the following: https://docs.microsoft.com/intune/developer/app-sdk-ios#receive-app-protection-policy. If no cached token can be found, this method will fail.

loginAndEnrollAccount should prompt the user for credentials. Are you providing a valid UPN to this method or nil? There is a known issue with passing in the current release which will be addressed in the next release that will cause loginAndEnrollAccount(nil) to fail when using MSAL.

ADAL version 1.0.2 is quite old, and not supported by our SDK. Is there a particular reason you're using such an old version? It will likely have issues running on current versions of iOS.

**Comment by 84798012** [comment]
@Kyle-Reis , Thanks very much.
1. I did a test using MSAL authenticated, then intune registerAndEnrollAccount, but still have issue. it seems that intune can not found token cached. I'll do more test to verify.

2. I'm using loginAndEnrollAccount(nil), you said there is known issue, so I can only use it like this "loginAndEnrollAccount(UPN)"?

3. ADAL v1.0.2 used by Onedrive and is imported to our project before, and did not update for times. We can do upgade for new version Onedrive + ADAL. 
But I am not sure new added Intune should use ADAL or MSAL, which one is better and stable, could you give suggestion? 
From the offical document, it said better to use MSAL. So I have spend several days try to use MSAL, but I have never success to run one Intune + MSAL.  And Intune + ADAL seems no issue.

**Comment by 84798012** [comment]
@Kyle-Reis , is there a demo project link about how to use Intune + MSAL? I really don't know why it can not work well, and I have spend several days try to find the root cause. appreciate for your help.

**Comment by 84798012** [comment]
@Kyle-Reis , I have do more test today.
step1: Config the Info.plist file.
1. LSApplicationQueriesSchemes
2. URL types-> URL Schemes
3. IntuneMAMSettings -> ADALClientId, ADALAuthority, ADALRedirectUri
step2: 
1. Using MSAL acquireTokenWithParameters login first.
2. Then if using registerAndEnrollAccount:UPN, there is not any response.
3. If using loginAndEnrollAccount:UPN, in enrollmentRequestWithStatus return 201, There was an internal error in the Intune MAM SDK.  Please see the NSError object for more details.

It seems the Intune can not get the right MAM user tokens or any other problems happens.

**Comment by Kyle-Reis** [comment]
Hey @84798012, what value are you providing for UPN? Is it a valid AAD account UPN?

For the registerAndEnrollAccount test, is the MSAL error you provided from your app's call to acquireTokenWithParameters? It seems like it, as it looks like the app is trying to access some test resource named "jeff_test_msal". It seems like you're trying to access this resource silently, but the user hasn't performed any sort of authentication yet so you should do an interactive call to acquireTokenWithParameters so the user gets prompted for creds

**Comment by 84798012** [comment]
@Kyle-Reis 
Yes, I'm using an valid AAD account UPN. I can login with this account to portal.azure.com, manage all things.

What do you means I should do an interactive call to acquireTokenWithParameters? I have called MSAL -> acquireTokenWithParameters before call Intune -> registerAndEnrollAccount.

**Comment by Kyle-Reis** [comment]
Is the acquireTokenWithParameters call prompting the user for credentials?

**Comment by 84798012** [comment]
> Is the acquireTokenWithParameters call prompting the user for credentials?

@Kyle-Reis 
yes, call acquireTokenWithParameters  it pop up web, and I have input username and password, success.
And later I call Intune -> registerAndEnrollAccount. Then shows the error log as that.

**Comment by Kyle-Reis** [comment]
Hey @84798012, have you followed these steps to grant the app access to the Intune app protection service: https://docs.microsoft.com/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional

**Comment by 84798012** [comment]
@Kyle-Reis 
Thanks for your help, finally I success for this case: Using MSAL acquireTokenWithParameters login first, then using registerAndEnrollAccount:UPN.

But if user have never used MSAL acquireTokenWithParameters login before, he directly invoke LoginAndEnrollAccount:nil or LoginAndEnrollAccount:UPN, both will return below:

Printing description of msalError:
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Account parameter cannot be nil, MSALInternalErrorCodeKey=-42106, MSALCorrelationIDKey=26A7A0A7-891F-4B7C-A65B-E49B110F7377}
Printing description of status:
<IntuneMAMEnrollmentStatus: 0x283fd1470>
----enrollmentRequestWithStatus
2019-11-07 10:03:21.855299+0800 TestIntuneMSAL[1336:203319] ----217
2019-11-07 10:03:21.855702+0800 TestIntuneMSAL[1336:203319] ----The operation failed because the SDK encountered an internal error in ADAL when attempting to acquire the user's MAM token.

**Comment by Kyle-Reis** [comment]
Hey @84798012, that's great that you got the registerAndEnrollAccount scenario working! Are you still having trouble with loginAndEnrollAccount? If so could you clarify which version of MSAL you're using when you hit this error?

**Comment by Kyle-Reis** [comment]
@84798012, just checking in again to see if you still need help using MSAL with Intune.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. If you are still having issues with the loginAndEnrollAccount scenario, please let us know!

**Comment by viveknegi51288** [comment]
@84798012 Could you please share your code. I have also created an xamarin forms application and able to get access token using MSAL, now i need to integrate intunes, could u tell me how to configure it please . @Kyle-Reis  If you can also help
