### ISSUE TITLE
Version 12.0.12 not compatible with xcode 11.2

### ISSUE THREAD

**Issue by ryanbland** [msintuneappsdk/ms-intune-app-sdk-ios#54]
Version 12.0.12 is not compatalbe with xcode 11.2, we are seeing the following error when trying to import IntuneMAMSwift

Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: ...

It looks like xcode 11.2 may have a known issue that could be a cause:https://developer.apple.com/documentation/xcode_release_notes/xcode_11_2_release_notes

It states:
If a module is built with BUILD_LIBRARIES_FOR_DISTRIBUTION and contains a public type with the same name as the module itself, clients will fail to import the module. (19481048) (FB5863238)

Workaround:
Rename either the type or the module to remove the conflict.
Stackoverflow shows a possible fix if its not related to the below known issue with xcode11.2

Info on what could be causeing this was found in: 
https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

**Comment by Kyle-Reis** [comment]
Hey @ryanbland, we are aware of this issue and already have a fix for it. We'll be releasing an update with the fix soon.

**Comment by ryanbland** [comment]
Thanks for the update

**Comment by nickwbaker** [comment]
Our team is also needing this update, any ETA on the update?

**Comment by ryanbland** [comment]
What is the status of this fix?

**Comment by Kyle-Reis** [comment]
Hey @ryanbland and @nickwbaker, we should have the fix out within the week.

**Comment by Kyle-Reis** [comment]
Hey @ryanbland and @nickwbaker, this should he fixed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest)(12.0.18)
