### ISSUE TITLE
Could not find or use auto-linked framework

### ISSUE THREAD

**Issue by Keuha** [msintuneappsdk/ms-intune-app-sdk-ios#55]
<<<<<<< HEAD
=======
---
name:Could not find or use auto-linked framework
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**
if building with the framework, everything is fine, if I'm using `IntuneMAMEnrollmentManager.instance().enrolledAccount()` I get the following error

`ld: warning: Could not find or use auto-linked framework 'IntuneMAMSwift'
ld: warning: Could not find or use auto-linked framework 'IntuneMAMSwiftStub'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IntuneMAMEnrollmentManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**To Reproduce**
1 follow tutorial step until framework import
2  import IntuneMAMSwift in a file
3 try calling `IntuneMAMEnrollmentManager.instance().enrolledAccount()`

**Expected behavior:**
project should build

<<<<<<< HEAD
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
`ld: warning: Could not find or use auto-linked framework 'IntuneMAMSwift'
ld: warning: Could not find or use auto-linked framework 'IntuneMAMSwiftStub'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IntuneMAMEnrollmentManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not find or use auto-linked framework 'IntuneMAMSwift'

Could not find or use auto-linked framework 'IntuneMAMSwiftStub'
`

- If your app is experiencing an issue post build, do you have app logs for the crash itself?
=======
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3

**Smartphone (please complete the following information):**

<<<<<<< HEAD
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?
=======
**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hey @Keuha, which version of Xcode are you using? Does your target have Bitcode enabled?

**Comment by Keuha** [comment]
Hey @Kyle-Reis I am using Xcode11.0 
And yes Bitcode is enabled

**Comment by Kyle-Reis** [comment]
@Keuha, Bitcode is not supported by our SDK. Could you try disabling it?

**Comment by Keuha** [comment]
@Kyle-Reis Thank you so much. this is working perfectly now.
