### ISSUE TITLE
Set PIN screen is broken in iOS 13.2 

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#57]
**Describe the bug:**
Set PIN screen is broken in iOS 13.2  

**To Reproduce**
1. Completed enrolment with app
2. Now removed policy and update PIN policy(8 digit PIN)  from Azure portal
3. Launched app, app prompted to enter last PIN.
4. Once we enter pin then it show alert saying PIN policy changed you must set new PIN with New Screen to Set PIN.
5. This Set PIN screen is not responding(Unable to see anything on typing from keyboard. keyboard is not hiding) and once its gets there. User cannot go any further.

**Expected behavior:**
User should be able to set New PIN on PIN policy change and continue to app.

**Screenshots and logs:**
![IMG-0869](https://user-images.githubusercontent.com/2161122/68855949-62151080-0705-11ea-8102-bc3c3efff8c6.PNG)

**Smartphone (please complete the following information):**
 - Device: iPad / iPhone
 - OS: iOS (>= iOS 13.0)

<<<<<<< HEAD
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? **Latest 12.0.12**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? **Xcode**
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer? Infor
- Do you see a trend with it only being reproduced on a specific device? Not sure.

**Additional context:**

**Comment by Nookaraju** [comment]
@Kyle-Reis this show blocker for our app can you please check this.

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, does the app crash when this happens, or does it remain in an unresponsive state indefinitely?

**Comment by Nookaraju** [comment]
@Kyle-Reis It doesn't crash crash, but it remains unresponsive. I can tap on keyboard and see keyboard key selection but nothing gets updated in pin textfield.

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, could you try the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (12.0.18)?

**Comment by Nookaraju** [comment]
@Kyle-Reis Updated to 12.0.18 but still issue is not fixed. Actually, we didn't even set 8 digit pin in policy also.

Settings are:
PIN - Not Required
digits - 4
type - numeric

Scenario is:

App have enrolled and policies applies on app, now deleted policy and created new policy and assigned to app & app user.

Screen recording issue here:
https://www.dropbox.com/s/ex7bm0y00g8o0br/Intune%20SDk%20issue.mp4?dl=0

**Comment by Kyle-Reis** [comment]
@Nookaraju, I am able to reproduce this and will investigate. FYI: While it does look like input is not being registered, if user types a valid pin sequence and hits Enter they are presented with a confirmation screen that behaves similarly. After confirming, user is met with same message that PIN requirements have changed, and is asked to set a pin a 2nd time. Everything works as expected the 2nd time. Not ideal, but at least users aren't completely blocked from using the app here. We'll investigate and get a fix out for this ASAP.

**Comment by sidgami** [comment]
@Kyle-Reis : Any updates regarding this issue?

**Comment by Kyle-Reis** [comment]
Hey @sidgami, I’m currently investigating this issue and expect to have a fix for it in review sometime next week.

**Comment by Nookaraju** [comment]
@Kyle-Reis issue got fixed in 12.2.0.

Minor input: When PIN type set to "Numeric", the keyboard should be numeric or shouldn't accept the non-numeric characters.
