### ISSUE TITLE
Cut Copy Paste integration with outlook?

### ISSUE THREAD

**Issue by ryanbland** [msintuneappsdk/ms-intune-app-sdk-ios#58]
let me preface by saying Im not sure if this is a bug or not or even if this relates to intune or outlook specifically. 

If you are using outlook with multiple identities 1 corp account 1 personal (gmail) AND you restrict cut/copy/paste to Policy managed apps with paste in you can copy into a personal email and send that out. Based on how all the other policies work with the multi identity support i would assume that you cannot paste into an email if you are sending it from my personal account.
Is my assumption correct or are you allowed to paste into the app? If this isnt the right space for this where would I raise this issue?

I did check and it does prevent you from pasting into an app like notes thats not managed.

**Comment by Kyle-Reis** [comment]
@ryanbland, thanks for reporting this. We're investigating and will work with the Outlook team to address this.

**Comment by Kyle-Reis** [comment]
@ryanbland, this issue should be fixed in the latest release of Outlook (4.19.0). Thanks again for reporting it.
