### ISSUE TITLE
Can't register after MSAL token has been obtained

### ISSUE THREAD

**Issue by Keuha** [msintuneappsdk/ms-intune-app-sdk-ios#59]
I am using MSAL to get information thanks to authenticator. first time the user launch the app, the authenticator opens, then go back to my app. it's working perfectly.
all the other time I can perform silent token acquisition. 
for the result of token acquisition, I am using `result.account.username` to perform ` IntuneMAMEnrollmentManager.instance().registerAndEnrollAccount`
at this moment, all the following method returns null (as expected, since no one is enrolled yet)
` IntuneMAMEnrollmentManager.instance().allowedAccounts())`
`IntuneMAMEnrollmentManager.instance().enrolledAccount())`
`IntuneMAMEnrollmentManager.instance().mdmEnrolledAccount()`
`IntuneMAMEnrollmentManager.instance().registeredAccounts()`

I did implement  `IntuneMAMEnrollmentManager` delegate's to catch the reply from the enrollement request.

as a result I get this 
`"The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token."`
NSError is : 
`Error Domain=MSALErrorDomain Code=-50002 "(null)" 
UserInfo={MSALErrorDescriptionKey=No account provided for the silent request. Please call interactive acquireToken request to get an account identifier before calling acquireTokenSilent.}`

note that `registerAndEnrollAccount` is called only after `acquireTokenSilent` and if `acquireTokenSilent` fails, it will be called after `acquireToken`

any Idea why it tells me to call this method again ? 

EDIT : 
I am using Xcode 11.2.1, latest MSAL pod, my device is on iOS 13.1.2 and I am using the latest version of the IntuneFramework availabe on Master

**Comment by Kyle-Reis** [comment]
Hey @Keuha, a few comments/questions:

1.) Current version of the Intune MAM SDK only supports up to MSAL version 0.6.0. Support for 0.7.0+ will become available in the next update (assuming we don't make any hotfixes for critical issues)

2.)  Have you verified that result.account.username evaluates to the user's UPN?

3.) Have you configured the ADALClientId, ADALRedirectUri, and ADALAuthority settings to match those used by your app as mentioned here: https://docs.microsoft.com/intune/developer/app-sdk-ios#configure-adalmsal-settings-for-the-intune-app-sdk

4.) Have you followed [these steps](https://docs.microsoft.com/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional) to give your app access to the Intune app protection service?

**Comment by Keuha** [comment]
> 1.) Current version of the Intune MAM SDK only supports up to MSAL version 0.6.0. Support for 0.7.0+ will become available in the next update (assuming we don't make any hotfixes for critical issues)

I did miss this information, did modify the pod version now, thanks.

> 2.) Have you verified that result.account.username evaluates to the user's UPN?
> 
> 3.) Have you configured the ADALClientId, ADALRedirectUri, and ADALAuthority settings to match those used by your app as mentioned here: https://docs.microsoft.com/intune/developer/app-sdk-ios#configure-adalmsal-settings-for-the-intune-app-sdk
> 
> 4.) Have you followed these steps to give your app access to the Intune app protection service?

all those step has been configure fine. The value I am using does correspond to the UPN.

I now face this problem : 

`Optional("The operation failed because the SDK encountered an internal error in ADAL when attempting to acquire the user\'s MAM token.")`
with the following Error
`Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Account parameter cannot be nil, MSALInternalErrorCodeKey=-42106, MSALCorrelationIDKey=AA2CFC22-6091-4063-95CD-E4699488C5B2}`

still working on it

**Comment by Keuha** [comment]
after further research, turns out that `MSIDSilentTokenRequest.executeRequestWithCompletion` is a success when it come to fetch the token in a silent or non silent mode. 
However, when called from a `RegisterAndEnrollAccount`, `self.requestParameters.accountIdentifier` seems to be nil for some reasons.

any idea

**Comment by Keuha** [comment]
every thing is working fine, some information on backend was missing. thanks for the support.

**Comment by ws752958369** [comment]
@keuha i  have meet the same question,could you help me?

**Comment by Keuha** [comment]
Hi @ws752958369
As mentioned in my last comment, if you follow the doc, you should not face any major issue. Actualy, all of my problems was actually because of some backend issue :)
