### ISSUE TITLE
Debug version of `libIntuneMAM.a` not present in SDK, is debug version still supported?

### ISSUE THREAD

**Issue by Utsira** [msintuneappsdk/ms-intune-app-sdk-ios#6]
In the [documentation](https://docs.microsoft.com/en-us/intune/develop/intune-app-sdk-ios) it states:

> If you plan to release your app to the App Store, please use the version of libIntuneMAM.a that is built for release and not the debug version. The release version will be in the release folder. The debug version has verbose output that helps troubleshoot problems with the Intune App SDK.

7.0.1 does not contain a debug version of `libIntuneMAM.a`, do you plan on offering a debug version in future versions?

**Comment by msintuneappsdk** [comment]
Hi Utsira, there are no plans today on making the debug version available in future releases through GitHub. Please feel free to give us more insights on your use case of the debug version of `libIntuneMAM.a`.

**Comment by jonhocking** [comment]
Thanks for the update @msintuneappsdk. We'll make sure to remove references to it and use the single version of the library.
