### ISSUE TITLE
IntuneMAMSwift Framework bitcode support

### ISSUE THREAD

**Issue by fergalrooney** [msintuneappsdk/ms-intune-app-sdk-ios#60]
Can a version of the IntuneMAMSwift.framework be provided with bitcode enabled? We require this for internal enterprise purposes.

**Comment by Kyle-Reis** [comment]
Hey @fergalrooney. Unfortunately, this is not possible. Please see issue #9.

**Comment by fergalrooney** [comment]
Thanks for confirmation. Does the same apply for the objective C version?

**Comment by Kyle-Reis** [comment]
Yes.
