### ISSUE TITLE
Crash in Intune framework with __CRASHING_DUE_TO_PRIVACY_VIOLATION__

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#61]
name: Crash in Intune framework with __CRASHING_DUE_TO_PRIVACY_VIOLATION__
about: Create a report to help us improve

Intune SDK seems writing to photo library in a rare case which causing a crash. I dodn't get this crash for me but I see about 10 crashes(production app) with same log.

**Expected behavior:**
 Does Intune SDK integrated app needed  to add **NSPhotoLibraryAddUsageDescription**  in app plist file?

**Screenshots and logs:**

Date/Time:           2019-11-29 13:18:48.5563 +0800
Launch Time:         2019-11-29 12:57:33.2504 +0800
OS Version:          iPhone OS 13.1.3 (17A878)
Release Type:        User
Baseband Version:    2.01.08
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.
Triggered by Thread:  6

Thread 0 name:
Thread 0:
0   QuartzCore                    	0x00000001b0f08f04 CA::AttrList::get(unsigned int, _CAValueType, void*) const + 40 (CAAttrList.cpp:544)
1   QuartzCore                    	0x00000001b0ede1ac CAAnimation_getter(CAAnimation*, unsigned int, _CAValueType, void*) + 116 (CAAttrList.h:103)
2   QuartzCore                    	0x00000001b0ede1ac CAAnimation_getter(CAAnimation*, unsigned int, _CAValueType, void*) + 116 (CAAttrList.h:103)
3   QuartzCore                    	0x00000001b0ede10c -[CAAnimation delegate] + 48 (CAAnimation.mm:112)
4   UIKitCore                     	0x00000001ae8e5c50 mapTrackedAnimations + 476 (UIView.m:2880)
5   UIKitCore                     	0x00000001ae8e59e0 +[UIView modifyTrackedAnimations:removeOnCompletion:animationFactory:block:] + 212 (UIView.m:2938)
6   UIKitCore                     	0x00000001adabde74 -[UIViewPropertyAnimator setFractionComplete:] + 292 (UIViewPropertyAnimator.m:3134)
7   UIKitCore                     	0x00000001ae36fbe0 __97-[_UIPreviewPlatterPresentationAnimator _actuallyPerformTransitionFromView:toView:containerVi... + 124 (_UIPreviewPlatterPresentationAnimator.m:405)
8   UIKitCore                     	0x00000001ae370ab4 __82-[_UIPreviewPlatterPresentationAnimator _prepareAnimatablePropertyBasedAnimations]_block_invoke + 252 (_UIPreviewPlatterPresentationAnimator.m:586)
9   UIKitCore                     	0x00000001ae842c9c __107-[_UIViewAnimatablePropertyTransformer initWithInputAnimatableProperties:presentationValueCh... + 116 (_UIViewAnimatablePropertyTransformer.m:87)
10  UIKitCore                     	0x00000001ae84ef44 __68+[UIViewInProcessAnimationManager _dispatchAsyncOntoMainBeforeExit:]_block_invoke_4 + 300 (UIViewInProcessAnimationManager.m:620)
11  libdispatch.dylib             	0x00000001aa06bbb0 _dispatch_call_block_and_release + 32 (init.c:1408)
12  libdispatch.dylib             	0x00000001aa06d00c _dispatch_client_callout + 20 (object.m:495)
13  libdispatch.dylib             	0x00000001aa078cd8 _dispatch_main_queue_callback_4CF + 968 (inline_internal.h:2487)
14  CoreFoundation                	0x00000001aa340e20 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1749)
15  CoreFoundation                	0x00000001aa33bb7c __CFRunLoopRun + 1980 (CFRunLoop.c:3069)
16  CoreFoundation                	0x00000001aa33b098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
17  GraphicsServices              	0x00000001b44a5534 GSEventRunModal + 108 (GSEvent.c:2246)
18  UIKitCore                     	0x00000001ae45b7ac UIApplicationMain + 1940 (UIApplication.m:4753)
19  IntuneMAM                     	0x000000010524b07c Intune_UIApplicationMain + 212
20  Infor Go                      	0x000000010463b34c specialized closure #1 in  + 176 (main.swift:15)
21  Infor Go                      	0x000000010463aa84 main + 20 (<compiler-generated>:0)
22  libdyld.dylib                 	0x00000001aa1baf30 start + 4

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001aa1b0cc4 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001aa0d4508 _pthread_cond_wait + 680 (pthread_cond.c:591)
2   IntuneMAM                     	0x00000001051c0e84 -[CMARAppRestrictionsBaseLogger processLogEntries] + 180
3   libdispatch.dylib             	0x00000001aa06bbb0 _dispatch_call_block_and_release + 32 (init.c:1408)
4   libdispatch.dylib             	0x00000001aa06d00c _dispatch_client_callout + 20 (object.m:495)
5   libdispatch.dylib             	0x00000001aa073484 _dispatch_lane_serial_drain + 568 (inline_internal.h:2487)
6   libdispatch.dylib             	0x00000001aa073eb0 _dispatch_lane_invoke + 368 (inline_internal.h:1854)
7   libdispatch.dylib             	0x00000001aa07cf20 _dispatch_workloop_worker_thread + 580 (queue.c:6386)
8   libsystem_pthread.dylib       	0x00000001aa0d2aa0 _pthread_wqthread + 280 (pthread.c:2323)
9   libsystem_pthread.dylib       	0x00000001aa0d8c78 start_wqthread + 8

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001aa18ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001aa18dfe0 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x00000001aa340abc __CFRunLoopServiceMachPort + 220 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001aa33b954 __CFRunLoopRun + 1428 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001aa33b098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
5   Foundation                    	0x00000001aa680580 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232 (NSRunLoop.m:374)
6   Foundation                    	0x00000001aa680458 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92 (NSRunLoop.m:421)
7   UIKitCore                     	0x00000001ae4f6668 -[UIEventFetcher threadMain] + 156 (UIEventFetcher.m:637)
8   Foundation                    	0x00000001aa67f1e4 -[NSThread main] + 40 (NSThread.m:760)
9   Foundation                    	0x00000001aa7baa84 __NSThread__start__ + 852 (NSThread.m:724)
10  libsystem_pthread.dylib       	0x00000001aa0d0d5c _pthread_start + 128 (pthread.c:895)
11  libsystem_pthread.dylib       	0x00000001aa0d8c84 thread_start + 8

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib        	0x00000001aa18ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001aa18dfe0 mach_msg + 76 (mach_msg.c:103)
2   Infor Go                      	0x00000001046d2924 CLSMachExceptionServer + 100
3   libsystem_pthread.dylib       	0x00000001aa0d0d5c _pthread_start + 128 (pthread.c:895)
4   libsystem_pthread.dylib       	0x00000001aa0d8c84 thread_start + 8

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x00000001aa1b0cc4 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001aa0d4508 _pthread_cond_wait + 680 (pthread_cond.c:591)
2   libc++.1.dylib                	0x00000001aa204d04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (__threading_support:287)
3   JavaScriptCore                	0x00000001b93e095c void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::uni... + 104 (condition_variable:204)
4   JavaScriptCore                	0x00000001b93e43c0 bmalloc::Scavenger::threadRunLoop() + 196 (condition_variable:213)
5   JavaScriptCore                	0x00000001b93e40b8 bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 16 (Scavenger.cpp:295)
6   JavaScriptCore                	0x00000001b93e53fc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, st... + 44 (type_traits:4361)
7   libsystem_pthread.dylib       	0x00000001aa0d0d5c _pthread_start + 128 (pthread.c:895)
8   libsystem_pthread.dylib       	0x00000001aa0d8c84 thread_start + 8

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001aa18ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001aa18dfe0 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x00000001aa340abc __CFRunLoopServiceMachPort + 220 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001aa33b954 __CFRunLoopRun + 1428 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001aa33b098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
5   CFNetwork                     	0x00000001ad5fdbc8 -[__CoreSchedulingSetRunnable runForever] + 192 (CoreSchedulingSet.mm:1372)
6   Foundation                    	0x00000001aa67f1e4 -[NSThread main] + 40 (NSThread.m:760)
7   Foundation                    	0x00000001aa7baa84 __NSThread__start__ + 852 (NSThread.m:724)
8   libsystem_pthread.dylib       	0x00000001aa0d0d5c _pthread_start + 128 (pthread.c:895)
9   libsystem_pthread.dylib       	0x00000001aa0d8c84 thread_start + 8

Thread 6 name:
Thread 6 Crashed:
0   libsystem_kernel.dylib        	0x00000001aa1b1870 __terminate_with_payload + 8
1   libsystem_kernel.dylib        	0x00000001aa1b3f8c abort_with_payload_wrapper_internal + 136 (terminate_with_reason.c:76)
2   libsystem_kernel.dylib        	0x00000001aa1b3fa0 abort_with_payload + 16 (terminate_with_reason.c:94)
3   TCC                           	0x00000001b05f7be8 __CRASHING_DUE_TO_PRIVACY_VIOLATION__ + 196 (TCC.c:431)
4   TCC                           	0x00000001b05f7b24 __TCCAccessRequest_block_invoke.128 + 556 (TCC.c:575)
5   TCC                           	0x00000001b05fbd58 __tccd_send_message_block_invoke + 264 (TCC.c:0)
6   libxpc.dylib                  	0x00000001a9fcf7c4 _xpc_connection_reply_callout + 92 (serializer.c:119)
7   libxpc.dylib                  	0x00000001a9fc3284 _xpc_connection_call_reply_async + 88 (connection.c:695)
8   libdispatch.dylib             	0x00000001aa06d094 _dispatch_client_callout3 + 20 (object.m:521)
9   libdispatch.dylib             	0x00000001aa084ed4 _dispatch_mach_msg_async_reply_invoke + 344 (mach.c:2442)
10  libdispatch.dylib             	0x00000001aa07c870 _dispatch_kevent_worker_thread + 1184 (inline_internal.h:2528)
11  libsystem_pthread.dylib       	0x00000001aa0d2ad8 _pthread_wqthread + 336 (pthread.c:2329)
12  libsystem_pthread.dylib       	0x00000001aa0d8c78 start_wqthread + 8

Thread 7 name:
Thread 7:
0   libsystem_kernel.dylib        	0x00000001aa18ec00 semaphore_wait_trap + 8
1   libdispatch.dylib             	0x00000001aa06d548 _dispatch_sema4_wait + 28 (lock.c:139)
2   libdispatch.dylib             	0x00000001aa06dbc0 _dispatch_semaphore_wait_slow + 132 (semaphore.c:132)
3   AssetsLibraryServices         	0x00000001bed160e8 __79-[PLPrivacy _isPhotosAccessAllowedWithScope:forceHandler:accessAllowedHandler:]_block_invoke.14 + 344 (PLPrivacy.m:130)
4   AssetsLibraryServices         	0x00000001bece0644 __pl_dispatch_async_block_invoke + 44 (PLDispatchHelpers.m:23)
5   libdispatch.dylib             	0x00000001aa06bbb0 _dispatch_call_block_and_release + 32 (init.c:1408)
6   libdispatch.dylib             	0x00000001aa06d00c _dispatch_client_callout + 20 (object.m:495)
7   libdispatch.dylib             	0x00000001aa073484 _dispatch_lane_serial_drain + 568 (inline_internal.h:2487)
8   libdispatch.dylib             	0x00000001aa073eb0 _dispatch_lane_invoke + 368 (inline_internal.h:1854)
9   libdispatch.dylib             	0x00000001aa07cf20 _dispatch_workloop_worker_thread + 580 (queue.c:6386)
10  libsystem_pthread.dylib       	0x00000001aa0d2aa0 _pthread_wqthread + 280 (pthread.c:2323)
11  libsystem_pthread.dylib       	0x00000001aa0d8c78 start_wqthread + 8

Thread 8 name:
Thread 8:
0   libsystem_kernel.dylib        	0x00000001aa18ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001aa18dfe0 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x00000001aa340abc __CFRunLoopServiceMachPort + 220 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001aa33b954 __CFRunLoopRun + 1428 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001aa33b098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
5   AVFAudio                      	0x00000001b71661b4 GenericRunLoopThread::Entry(void*) + 160 (GenericRunLoopThread.h:91)
6   AVFAudio                      	0x00000001b71b728c CAPThread::Entry(CAPThread*) + 208 (CAPThread.cpp:286)
7   libsystem_pthread.dylib       	0x00000001aa0d0d5c _pthread_start + 128 (pthread.c:895)
8   libsystem_pthread.dylib       	0x00000001aa0d8c84 thread_start + 8

Thread 9 name:
Thread 9:
0   libdispatch.dylib             	0x00000001aa06c0ac _os_object_retain_with_resurrect + 0 (object.c:78)
1   libxpc.dylib                  	0x00000001a9fb7e44 _xpc_received_message_set_connection + 68 (message.c:290)
2   libxpc.dylib                  	0x00000001a9fb8010 xpc_receive_mach_msg + 196 (message.c:360)
3   libxpc.dylib                  	0x00000001a9fc31f0 _xpc_connection_unpack_message + 128 (connection.c:1175)
4   libxpc.dylib                  	0x00000001a9fc3c08 _xpc_connection_mach_event + 860 (connection.c:1205)
5   libdispatch.dylib             	0x00000001aa06d0d8 _dispatch_client_callout4 + 20 (object.m:535)
6   libdispatch.dylib             	0x00000001aa0838e4 _dispatch_mach_msg_invoke + 376 (mach.c:2442)
7   libdispatch.dylib             	0x00000001aa073354 _dispatch_lane_serial_drain + 264 (inline_internal.h:2528)
8   libdispatch.dylib             	0x00000001aa084898 _dispatch_mach_invoke2 + 256 (mach.c:2764)
9   libdispatch.dylib             	0x00000001aa0844f0 _dispatch_mach_invoke + 424 (inline_internal.h:1854)
10  libdispatch.dylib             	0x00000001aa073354 _dispatch_lane_serial_drain + 264 (inline_internal.h:2528)
11  libdispatch.dylib             	0x00000001aa073ee8 _dispatch_lane_invoke + 424 (inline_internal.h:1854)
12  libdispatch.dylib             	0x00000001aa07cf20 _dispatch_workloop_worker_thread + 580 (queue.c:6386)
13  libsystem_pthread.dylib       	0x00000001aa0d2aa0 _pthread_wqthread + 280 (pthread.c:2323)
14  libsystem_pthread.dylib       	0x00000001aa0d8c78 start_wqthread + 8

Thread 10:
0   libsystem_pthread.dylib       	0x00000001aa0d8c70 start_wqthread + 0

Thread 11 name:
Thread 11:
0   libsystem_kernel.dylib        	0x00000001aa18ebc4 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001aa18dfe0 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x00000001aa340abc __CFRunLoopServiceMachPort + 220 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001aa33b954 __CFRunLoopRun + 1428 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001aa33b098 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
5   Foundation                    	0x00000001aa680580 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232 (NSRunLoop.m:374)
6   Foundation                    	0x00000001aa6bb7d0 -[NSRunLoop(NSRunLoop) run] + 92 (NSRunLoop.m:399)
7   UIKitCore                     	0x00000001ae84f970 __66-[UIViewInProcessAnimationManager startAdvancingAnimationManager:]_block_invoke_4 + 148 (UIViewInProcessAnimationManager.m:719)
8   CoreFoundation                	0x00000001aa2bd254 -[NSBlock invoke] + 24 (NSBlock.m:46)
9   Foundation                    	0x00000001aa67f1e4 -[NSThread main] + 40 (NSThread.m:760)
10  Foundation                    	0x00000001aa7baa84 __NSThread__start__ + 852 (NSThread.m:724)
11  libsystem_pthread.dylib       	0x00000001aa0d0d5c _pthread_start + 128 (pthread.c:895)
12  libsystem_pthread.dylib       	0x00000001aa0d8c84 thread_start + 8

Thread 6 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x00000001073c3418
    x4: 0x0000000000000022   x5: 0x00000001073c344c   x6: 0x0000000000000200   x7: 0x00000000000003f8
    x8: 0x0000000000000020   x9: 0x00000001f246ad1c  x10: 0x0100000100000000  x11: 0x776f682072657375
   x12: 0x20776f6820726573  x13: 0x2070706120656874  x14: 0x6968742073657375  x15: 0x002e617461642073
   x16: 0x0000000000000208  x17: 0x00000001e8592570  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x00000001073c344c  x21: 0x0000000000000022  x22: 0x00000001073c3418  x23: 0x0000000000000000
   x24: 0x000000000000000b  x25: 0x0000000281ce6e00  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016bb666a0   lr: 0x00000001aa1b3f8c
    sp: 0x000000016bb66660   pc: 0x00000001aa1b1870 cpsr: 0x00000000
   esr: 0x56000080  Address size fault

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 12.0.12
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Xcode, Swift

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, it says this crash was triggered by Thread 6. Do you have the call stack for that thread?

**Comment by Nookaraju** [comment]
@Kyle-Reis updated with all threads.

**Comment by Kyle-Reis** [comment]
@Nookaraju, this does not look Intune-related. Does your app contain functionality to access the camera and save images taken to the camera roll?

**Comment by Nookaraju** [comment]
Nope

**Comment by patlewis-MSFT** [comment]
@Nookaraju  : Be sure to add the  NSFaceIDUsageDescription in your info.plist. See step#6 here:   https://docs.microsoft.com/en-us/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app

**Comment by Nookaraju** [comment]
@patlewis-MSFT yes, its already there in plist.

**Comment by Kyle-Reis** [comment]
@Nookaraju does your Info.plist contain this key: NSPhotoLibraryUsageDescription
 Note that it is different from the key referenced in the exception

**Comment by Nookaraju** [comment]
@Kyle-Reis yes we have NSPhotoLibraryUsageDescription in plist already. we don't have NSPhotoLibraryAddUsageDescription because we don't save any photos to Photo Gallery.

**Comment by Kyle-Reis** [comment]
@Nookaraju, So your app imports photos from the camera roll? Do users have the ability to take a new photo with camera and import that as well?

**Comment by Nookaraju** [comment]
@Kyle-Reis Yes and we have camera privacy description in plist already.

**Comment by Kyle-Reis** [comment]
@Nookaraju are the photos taken saved to the camera roll? Some APIs that allow user access to the camera will also automatically save photos taken to the camera roll. Have you tested this scenario recently to verify it isn’t crashing on newer versions of iOS? It sounds like the NSPhotoLibraryAddUsageDescription key was introduced with iOS 11, so the NSPhotoLibraryUsageDescription may have covered this scenario before. The Intune SDK does not attempt to save any data to the camera roll, so this is most likely caused by some functionality in the app.

**Comment by Nookaraju** [comment]
Just added NSPhotoLibraryAddUsageDescription even though our app don't save images to photo library.
