### ISSUE TITLE
SDK support for Mac Catalyst

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#62]
name: Bug report
about: SDK support for Mac Catalyst

**Describe the bug:**
When we tried to add Mac Catalyst support for our app getting this error ".xcodeproj Building for Mac Catalyst, but the linked and embedded framework 'IntuneMAM.framework' was built for iOS + iOS Simulator. You may need to restrict the platforms for which this framework should be linked and embedded in the target editor, or replace it with an XCFramework that supports both platforms."

**Expected behavior:**
Is it possible to have catalyst sdk support?

-

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, this SDK is for iOS only and does not support MacOS. You should not link it against your MacOS build target.

**Comment by Nookaraju** [comment]
I understand that, do you have plan for macOS Catalyst support?

**Comment by Kyle-Reis** [comment]
Not at this time
