### ISSUE TITLE
Certificate-based SSO fails with Intune SDK / iOS

### ISSUE THREAD

**Issue by fastharper** [msintuneappsdk/ms-intune-app-sdk-ios#64]
<<<<<<< HEAD
=======
---
name: Certificate-based SSO fails with Intune SDK
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**
Our mutual customer (law firm Duane Morris) uses AirWatch for their MDM and Workspace One Access (formerly VMware Identity Manager) as their SSO. They have SSO configured for certificate-based authentication. But something in the Intune SDK is breaking this link: They cannot successfully login to O365 when the IntuneMAMEnrollmentManager.loginAndEnrollAccount() method is called. Instead, they see a white screen.

If they are not using the Intune SDK, they can login (e.g. within Word/Excel/Powerpoint) on iOS.

**To Reproduce**

**Expected behavior:**
We expect their SSO configuration to work and for the O365 login to succeed within the Intune SDK app.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
<<<<<<< HEAD
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
=======
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3

**Smartphone (please complete the following information):**

<<<<<<< HEAD
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?
=======
**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? v12 - the latest

- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Native iOS code, using Swift

- For pre-wrapping errors, does the app build without being wrapped?
Not using app wrapping.

- For post-wrapping errors, does the app launch without being wrapped?
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
- Who is the customer? Duane Morris
- Do you see a trend with it only being reproduced on a specific device? Any device.

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hey @fastharper, do you still need help with this?

**Comment by Kyle-Reis** [comment]
Hey @fastharper, checking in again before closing this one out. Do you still need help here?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you're still experiencing this issue.
