### ISSUE TITLE
Sample code without ADAL Integration

### ISSUE THREAD

**Issue by madhurtiwari** [msintuneappsdk/ms-intune-app-sdk-ios#65]
The   github sample code shares the implementation details for the application  which has ADAL authentication, is there any sample code which has the   integration details for the application without ADAL integration?
--

**Comment by Kyle-Reis** [comment]
Hey @madhurtiwari, what sample are you referring to?

**Comment by madhurtiwari** [comment]
How to proceed with the intune sdk integration without ADAL integration

**Comment by Kyle-Reis** [comment]
@madhurtiwari, I'm not sure what you meant by "the GitHub sample code", but the [Chatr sample app](https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App) is an example of an app that does not directly use ADAL for its own auth. It relies on Intune to handle auth for it. ADAL is a required dependency of the Intune SDK, so if you're asking for a sample app that does not link to ADAL at all, such a sample does not exist. I strongly recommend that you read the [iOS developer guide](https://docs.microsoft.com/intune/developer/app-sdk-ios) to understand how the SDK works and what all of its required dependencies are.
