### ISSUE TITLE
ADSTS650056 	 MFA claim has expired due to the policies configured on tenant

### ISSUE THREAD

**Issue by stevenmonk** [msintuneappsdk/ms-intune-app-sdk-ios#68]
Hello,

We are testing a third party app assigned from the apple store via MAM when launching the app after calling the Microsoft auth broker, the app presents the error ADSTS650056 and crashes. the admin consent the error points to is approved. 

Conditional access has been bypassed to rule it out of the equation. we are using onsite MFA and a Hybrid environment

**Comment by Kyle-Reis** [comment]
Hey @stevenmonk , are you still experiencing this issue?

**Comment by Kyle-Reis** [comment]
Hey @stevenmonk, checking in again before closing out this issue. Do you still need help here?

**Comment by stevenmonk** [comment]
Hi Kyle,

Yes we solved the issue, it was a multi tenant app, we solved it by creating an admin consent URL and generating the Enterprise app through that process.

Thanks

Steven

**Comment by Kyle-Reis** [comment]
Great to hear you were able to work it out! Please reach out if you have any more issues!
