### ISSUE TITLE
Sample app to test Intune SDK functionality

### ISSUE THREAD

**Issue by Durgaprasad-Budhwani** [msintuneappsdk/ms-intune-app-sdk-ios#7]
Hi team,
Can we get sample app to test Intune SDK functionality?

**Comment by lateAtNight** [comment]
Second that. Please?

**Comment by velikara** [comment]
How come a sample Project is missing! We follow the steps but not able to add it so far. a Sample Project that opens www.msn.com on a full screen.

**Comment by yaroslavbabenko** [comment]
+1

**Comment by jravi** [comment]
+1

**Comment by deeyodc-symphony** [comment]
+1

**Comment by idcuesta** [comment]
+1

**Comment by Kyle-Reis** [comment]
We now have a public Swift sample app available here:
https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App
