### ISSUE TITLE
File Provider Extension

### ISSUE THREAD

**Issue by artgal** [msintuneappsdk/ms-intune-app-sdk-ios#70]
I would like to enable the users to add attachments to an email in Outlook from my custom file storage app (running with Intune). As far as I understand, I need to create a File Provider Extension to provide access to the files stored in the app. Could you please advise the correct flow for enabling this capability?

A couple of questions that I have about the file provider extension:
1. What needs to be done to make the extension Intune managed? I was able to find the instructions only for the share extension - [Share data via uiactivityviewcontroller](https://docs.microsoft.com/en-us/intune/developer/app-sdk-ios#share-data-via-uiactivityviewcontroller)?
2. Based on the documentation, I should use IntuneMAMFileProtectionManager class to encrypt the file for the identity before providing the file, is that correct? Does Intune not handle it automatically?
3. How can I retrieve the enrolled identity from an extension, needed to encrypt the file? In the app itself I could use the enrolledAccount method from IntuneMAMEnrollmentManager, but in the extension it returns nil.
4. Since the extension won’t have access to the app’s document directory, should I store the files in the [shared container](https://developer.apple.com/documentation/foundation/nsfilemanager/1412643-containerurlforsecurityapplicati?language=objc)?

**Comment by Kyle-Reis** [comment]
Hey @artgal, do you still need help with this?

**Comment by Kyle-Reis** [comment]
Hey @artgal, checking in again if you need help here before closing out this issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still having issues.
