### ISSUE TITLE
Deprecated API Usage - WKWebView

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#71]
I uploaded App to Appstore today which have 12.0.18 Intune SDK and got a warning message from Apple :

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

When I checked which libraries using UIWebView:

I see this on `grep -r "UIWebView" .`
Binary file ./<myApp>/IntuneMAM.framework/IntuneMAM matches

Can you please confirm? is really Intune SDK uses UIWebview? when we can expect the update?

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, we are tracking this issue. we don't use UIWebView directly but we do have code which hooks it in case the app is using it.

**Comment by Nookaraju** [comment]
@Kyle-Reis Can we have a fix soon? As you know Apple will reject the apps now onwards with UIWebview references

**Comment by tritter** [comment]
Yes we need this update soon! Otherwise updates get **rejected**, please move this to the highest priority!

`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju and @tritter, we've checked in a fix for this and it should be available in our next release.

**Comment by apecodingman** [comment]
@Kyle-Reis Could you help to advice what's the date of next release?

**Comment by ScottBishop** [comment]
We need this update soon!

The Apple documentation mentions that new apps with UIWebView will be rejected!

**Comment by Kyle-Reis** [comment]
Hey folks ETA for the fix is end of this week.

**Comment by Kyle-Reis** [comment]
Hey everyone, this issue should be addressed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (12.4.0).
