### ISSUE TITLE
Enable Bitcode

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#72]
Currently bitcode is disabled in the frameworks the Intune SDK is providing. Would it be possible to add this option in a next release? This would shrink the downloads and at the moment disables  bitcode signing for other frameworks too. In bigger projects the app size increases a lot on our side (100MB) just by adding the Intune SDK.

```IntuneMAM.framework/IntuneMAM' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file 'IntuneMAM.framework/IntuneMAM' for architecture arm64```

**Comment by Kyle-Reis** [comment]
Hey @tritter, unfortunately we cannot support BitCode. Please see issue #9.
