### ISSUE TITLE
Unable to open Url Scheme from app when app is enrolled.

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#73]
---
name: Unable to open the Url Scheme from the app when the app is enrolled.
about: Launching a URL scheme is not working when the app is Intune MAM enrolled.

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**
Our app tries to launch the other apps using (App URL Scheme) and its not working if the app is enrolled.

```
 UIApplication.shared.open(appURL, options: [:]) { (status) in
                        if status {

                        }
                        else{
                         }
}
```

Error in console:

[default] Failed to open URL com.infor.mingle-intunemam://com%2Einfor%2EMingle%3A%2F%2Fgo?com.microsoft.intune.mam.appmdmmgtstate=0&com.microsoft.intune.mam.policysource=2&com.microsoft.intune.mam.identity=nookaraju%40manjunathganimastyinfor%2Eonmicrosoft%2Ecom&com.microsoft.intune.mam.policy=1&com.microsoft.intune.mam.identity.oid=df9f44ee%2Dcb10%2D4c42%2Db7f5%2Deafdf98ee8c8: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=247, _LSFunction=-[_LSDOpenClient openURL:options:completionHandler:]}
2020-04-14 12:47:51.313935+0530 App [87469:14066854] -canOpenURL: failed for URL: "com.infor.myapp-intunemam://com%2Einfor%2EmyApp%3A%2F%2Fgo?com.microsoft.intune.mam.appmdmmgtstate=0&com.microsoft.intune.mam.policysource=2&com.microsoft.intune.mam.identity=nookaraju%40manjunathganimastyinfor%2Eonmicrosoft%2Ecom&com.microsoft.intune.mam.policy=1&com.microsoft.intune.mam.identity.oid=df9f44ee%2Dcb10%2D4c42%2Db7f5%2Deafdf98ee8c8" - error: "This app is not allowed to query for scheme com.infor.myapp-intunemam"
2020-04-14 12:47:51.315183+0530 App [87469:14066854] -canOpenURL: failed for URL: "com.infor.myApp://go" - error: "This app is not allowed to query for scheme com.infor.myApp"

**To Reproduce**
Enroll the app and try to launch any app scheme.

**Expected behavior:**
It should allow launching the app scheme.

**Smartphone (please complete the following information):**
 - Device: IPhone
 - OS: iOS 13.3.

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 12.3.1
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Xcode
- For errors during build, does the app build without Intune SDK integration? No
- For errors post build, does the app launch without being Intune SDK integrated? No

- Who is the customer? Infor

**Comment by Kyle-Reis** [comment]
Hey @Nookaraju, does this scenario work when the app is not managed?  Does the target app include the Intune SDK as well?

**Comment by Nookaraju** [comment]
@Kyle-Reis Yes, it works when the app is not managed. The target app doesn't include the Intune SDK.

**Comment by Kyle-Reis** [comment]
@Nookaraju, then this sounds by-design. The SDK is likely enforcing outgoing data transfer policy. If outgoing data is unrestricted, this scenario should work. IT admins can also specify url protocol exceptions in the policy settings.

**Comment by Nookaraju** [comment]
@Kyle-Reis It is working if I change the data policy setting "Send org data to other apps" to **All Apps**.

Thank you.
