### ISSUE TITLE
froze app in case of lock screen

### ISSUE THREAD

**Issue by sansky99** [msintuneappsdk/ms-intune-app-sdk-ios#74]
<<<<<<< HEAD
=======
---
name: Bug report
about: SDK lock screen
title: 'froze app in case of lock screen'
labels: ''
assignees: ''

---

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**

My app has integrated IntuneMAM SDK 12.2.0 and Apple CallKit.

In case the app enroll Intune account and active MAM, 
    1). App receives a call through CallKit when screen not locked, CallKit UI will pop up
    2). App receives a call through CallKit when screen locked, CallKit UI will not pop. After I unlock screen and switch the app to foreground, the app is frozen and killed by system after 10s.

In case app not enroll Intune account and not active MAM, 
  3). App receives a call through CallKit, CallKit UI will pop up no matter screen locked or not.

**Expected behavior:**
pop up CallKit UI in 2).

**Smartphone (please complete the following information):**

**Additional context:**
What does the SDK do when lock screen? Will it block app from access files, memory, or certain resources?

**Comment by Kyle-Reis** [comment]
Hey @sansky99, could you try setting the following key/string pair under the IntuneMAMSettings dictionary in the Info.plist of your app?

MaxFileProtectionLevel : NSFileProtectionCompleteUntilFirstUserAuthentication

**Comment by Kyle-Reis** [comment]
Hey @sansky99, did that address the issue for you?

**Comment by Kyle-Reis** [comment]
@sansky99, checking in again before closing out this issue if the above setting addressed this this.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing this issue.
