### ISSUE TITLE
 Intune protection fails on older devices

### ISSUE THREAD

**Issue by tritter** [msintuneappsdk/ms-intune-app-sdk-ios#75]
---
name: Bug report
about: Intune protection fails on older devices
title: 'App Crash on older devices'
labels: 'urgent'
assignees: ''

---
**Describe the bug:**

**To Reproduce**
1. Register compliance app using `loginAndEnrollAccount:nil`
2. Restart App
3. App crashes! when its trying to load the App Status. 

**Expected behavior:**
No crash

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
Whenever the app is restarted after the alert, its crashing on the last step always with the same crash:
-[CMARMSAL0_6_0Wrapper acquireTokenWithContext:resource:clientId:redirectUri:promptBehavior:userIdentifier:extraQueryParameters:claims:completionBlock:]: unrecognized selector sent to instance 0x283513d00

<img width="1276" alt="step1" src="https://user-images.githubusercontent.com/1229109/79637272-53cc9400-817e-11ea-9902-71d4ed0a87b8.png">
<img width="1276" alt="step2" src="https://user-images.githubusercontent.com/1229109/79637274-55965780-817e-11ea-8ce2-58172b167d5e.png">
<img width="1276" alt="step3" src="https://user-images.githubusercontent.com/1229109/79637276-55965780-817e-11ea-8066-58a724ab2ddc.png">

**Smartphone (please complete the following information):**
 - Device: [iPad Air 2|iPad mini]
 - OS: [iOS13.4| iOS12]

**Intune App SDK for iOS (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? 
12.3.1
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Objective-C
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrappedThe app isn't wrapped.

- Who is the customer?
iPad users
- Do you see a trend with it only being reproduced on a specific device?
Yes it happens more on older devices, seems like a Javascript issue which is slower on the older ones.

**Comment by Kyle-Reis** [comment]
Hey @tritter, could you list some of the device types you see this on? What version of ADAL or MSAL is your app using?

**Comment by tritter** [comment]
Hi @Kyle-Reis,

Devices: [iPad Air 2|iPad mini]

I used MSAL it was on the latest (1.1.1), I thought but I just saw there is a new one released.
I now switched back to ADAL (4.0.6), there the issue doesn't appear. The page is rendering over there. We use a conditional access policy with the brokerage/authenticator app as a requirement. After changing to the older `x-msauth` scheme everything seems to work. Is the authenticator brokerage SSO feature already supported under MSAL?

Thanks,
Thom

**Comment by Kyle-Reis** [comment]
Hi @tritter, I'm working on a fix for this issue.

**Comment by Kyle-Reis** [comment]
Hi @tritter, could you try out the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 12.6.1). This crash should be fixed there.

**Comment by tritter** [comment]
Hi @Kyle-Reis it seems to be fixed! Thanks a lot :)
