### ISSUE TITLE
Warning email from the Apple review team about UIWebView

### ISSUE THREAD

**Issue by misitegj** [msintuneappsdk/ms-intune-app-sdk-ios#76]
Dear Microsoft Developers,

I have received a warning email from the Apple review team after uploading the IPA to iTunes connect. Just want to confirm that v12.3.1 the lastest SDK still using UIWebView?

Please kindly let us know the schedule then we can evaluate because we have an urgent project to release recently. Thanks indeed.
![IMG_5098](https://user-images.githubusercontent.com/14830452/79754646-71e6ef80-834a-11ea-8989-57dee567d4ef.jpg)

**Comment by Kyle-Reis** [comment]
Hey @misitegj, this is being tracked by issue #71. Closing this one out since it is a duplicate.
