### ISSUE TITLE
Intune SDK - data protection policy enforced and data exchange no longer working

### ISSUE THREAD

**Issue by lucac-apps** [msintuneappsdk/ms-intune-app-sdk-ios#77]
We are developing a custom corporate app for iOS platform that needs to pass, for editing purposes, documents to Microsoft Office apps like Word, Excel, PowerPoint, OneNote and get back the newer versions user may create.

In order to do so we integrated the Intune SDK (version: 12.3.1) in our App.

We added to the info.plist the following lines:

LSSupportsOpeningDocumentsInPlace = true

UISupportsDocumentBrowser = true

and use the following code to open in a test document in MS Word:

 @IBAction func openDocument() {
        guard let location = Bundle.main.url(forResource:"test", withExtension: "docx") else {return}
        let documentsPath = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let destinationURL = documentsPath.appendingPathComponent("test-document.docx")
        // delete original copy
        try? FileManager.default.removeItem(at: destinationURL)
        // copy from temp to Document
        do {
            try FileManager.default.copyItem(at: location, to: destinationURL)
        } catch let error {
            print("Copy Error: \(error.localizedDescription)")
        }
        
        let activityViewController = UIActivityViewController(activityItems: [destinationURL], applicationActivities: nil)   // and present it
        if let popoverController = activityViewController.popoverPresentationController {
            popoverController.sourceRect = CGRect(x: UIScreen.main.bounds.width / 2, y: UIScreen.main.bounds.height / 2, width: 0, height: 0)
            popoverController.sourceView = self.view
            popoverController.permittedArrowDirections = UIPopoverArrowDirection(rawValue: 0)
        }
        present(activityViewController, animated: true, completion: nil)
    }

Every thing works fine until we use Intune policy to protect our corporate data.
More specifically, once we change the policy in Intune, setting the parameter "Sending org (corporate) data to other apps"  to “Policy managed apps with Openin/Share Filtering”
the behavior of Microsoft Word changes completely and in the share sheet we find only "Copy to" instead of "Open-in" and with copying to Word we are no longer able to edit the document we pass to Word which opens it in read only mode.

To facilitate the comprehension of our problem we created two videos showing the issue.
Please notice that the only difference in the 2 scenarios is the data protection policy
configured on Intune.

In this [first video](https://bitdrome-my.sharepoint.com/:v:/g/personal/l_ciuccio_bitdrome_onmicrosoft_com/ETuhAF-wwztMj37JL2TPBV0BBAuoLazAqTHj-FzAKs1V0A?e=bEr9Ba) the data protection policy on Intune, has the parameter sending
org (corporate) data to other apps set to “all apps” and in this case we can edit documents
sent to Word from our app (as expected).

In this [second video](https://bitdrome-my.sharepoint.com/:v:/g/personal/l_ciuccio_bitdrome_onmicrosoft_com/EcQGuMBiq2xBjKpBwKpVJVkBvOBMXLQLsqo3TYx1-hgJ2Q?e=q6gzTB), the data protection policy on Intune, has the parameter
sending org (corporate) data to other apps set to “Policy managed apps with Open-in/
Share Filtering” and in this condition (the one we need) we cannot edit the documents
sent to Word from our App.

Can you please help us to solve this issue?

**Comment by Kyle-Reis** [comment]
Hey @lucac-apps, unfortunately, this kind of in-place editing is not supported with restricted Intune share policy. When outgoing data is restricted by policy, we must encrypt it, which requires us to make a new copy of the document and send it to Word so it can be decrypted there.
