### ISSUE TITLE
Microsoft Apps not Keeping up to date with the SDK

### ISSUE THREAD

**Issue by nickp85** [msintuneappsdk/ms-intune-app-sdk-ios#78]
Most important features like the new MDM control for work accounts in 12.3.1 are not available in most Microsoft first party apps, only OneDrive.  Microsoft needs to keep their own apps up to date with the SDK so there is a consistent experience across the platform of services.

**Comment by Kyle-Reis** [comment]
Hey @nickp85, while our 1st party partners do update the MAM SDK regularly, they are each on different release cycles, which can lead to this sort of situation when a new feature is being rolled out. Is there a particular set of apps you'd like to see this feature in?

**Comment by nickp85** [comment]
The require accounts option should be in all first party apps so we have a
consistent set of controls. Most important are Office apps, OneNote,
OneDrive, Teams.

Thanks

**Comment by Kyle-Reis** [comment]
Closing out this issue since all of the above apps are now on version 12.3.1 or later.
