### ISSUE TITLE
library not found for -lIntuneMAM

### ISSUE THREAD

**Issue by ashu2451990** [msintuneappsdk/ms-intune-app-sdk-ios#79]
followed all steps on  https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios to integrate it in project getting following error :

ld: library not found for -lIntuneMAM
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Kyle-Reis** [comment]
Hey @ashu245199, are you linking against our static library (libIntuneMAM.a)?

**Comment by ashu2451990** [comment]
@Kyle-Reis  yes I am using libIntuneMAM.a because our project using xcode 10.

**Comment by Kyle-Reis** [comment]
@ashu2451990, have you double checked that the path provided to the -force_load option in the "Other Linker Flags" build setting is correct?

**Comment by ashu2451990** [comment]
@Kyle-Reis  yes I checked it ...but its not working

**Comment by Kyle-Reis** [comment]
Hi @ashu2451990, are you still having trouble linking?

**Comment by Kyle-Reis** [comment]
Hi @ashu2451990, checking in again before closing out this issue. Were you able to successfully link the SDK?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still having issues linking!
