### ISSUE TITLE
How to use Intune SDK with MSAL?

### ISSUE THREAD

**Issue by yaroslavbabenko** [msintuneappsdk/ms-intune-app-sdk-ios#8]
How to use Intune SDK with MSAL?

**Comment by yaroslavbabenko** [comment]
As I figured out, unfortunately, it's not yet supported because Intune SDK itself would need to do updates. Refer this issue to Github: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/245

**Comment by viveknegi51288** [comment]
@yaroslavbabenko  Can we use msal library with intunes sdk in xamarin forms (android)
