### ISSUE TITLE
Still seeing references for UIWebView

### ISSUE THREAD

**Issue by rjvishnu87** [msintuneappsdk/ms-intune-app-sdk-ios#80]
I have downloaded latest 12.4.0 version, from the release notes I could see references for UIWebView has been removed. 

But when I use strings or nm command, I could see two references for UIWebView. 
Can you please confirm why it is still visible?

**Comment by Kyle-Reis** [comment]
Hey @rjvishnu87, are you having an issue submitting your app to the app store? We've removed all direct references to the UIWebView class, but still have code which will handle apps that are still using it.

**Comment by rjvishnu87** [comment]
I am not having an issue submitting to the app store. But I want to make sure these references to UIWebView should not be problem in the future appstore releases.

May I know which api still uses UIWebView?
or how to migrate to WKWebView to use?

**Comment by Kyle-Reis** [comment]
@rjvishnu87, as long as your app is not directly using UIWebView, you should be fine. None of our APIs will cause a UIWebView to be instantiated. However, using an older version of ADAL might cause this. Which version of ADAL are you linking against?

**Comment by rjvishnu87** [comment]
@Kyle-Reis Thanks for the clarification, 
We are currently using ADAL 4.0.2 in the production.
We are trying to update to the latest one for ms-intune-app-sdk and ADAL. Thats why we are analysing the release notes and finding the impact on our app.

**Comment by Kyle-Reis** [comment]
4.0.2 should be fine for the purposes of UIWebView avoidance :) Please reach out if you run into any more issues.
