### ISSUE TITLE
PhotosLibrary Usage

### ISSUE THREAD

**Issue by rjvishnu87** [msintuneappsdk/ms-intune-app-sdk-ios#81]
> Added new PhotoLibrary hooks to manage apps saving photos to unmanaged locations.

As per the new version, saving photos to PhotoLibrary is restricted and PhotoLibrary is considered as unmanaged locations.
In my company app, sending and receiving MMS support is available. After receiving the MMS, we are storing the Photos into Device album. 
If we upgrade to new SDK, where the Photos should be stored and how the photos can be shared between managed apps?

**Comment by Kyle-Reis** [comment]
Hey @rjvishnu87, in version 12.6.1, we've introduced a new save location for the camera roll. Your app should call isSaveToAllowedForLocation to determine whether saving to the camera roll is allowed by policy before doing so. Outgoing share policy should be entirely handled by the Intune SDK. So if your app contains functionality to share images out to other apps, the Intune SDK should handle ensuring that only policy managed apps can accept the image when policy is configured as such. The SDK will also handle the scenario where sharing is completely blocked. Hope this helps!
