### ISSUE TITLE
Intune 12.4.0 still references UIWebView

### ISSUE THREAD

**Issue by fowlerp-qlik** [msintuneappsdk/ms-intune-app-sdk-ios#82]
I downloaded the Intune 12.4.0 release from 

https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/12.4.0

and I found that IntuneMAM is still referencing UIWebView:

grep  UIWebView IntuneMAM 
 => Binary file IntuneMAM matches

Is this expected?

**Comment by ws752958369** [comment]
我也有同样的问题，我们这边通过ABM分发，需要上传至App Store Connect审核，但是审核标准中明确规定不允许使用UIWebViewle .

**Comment by Kyle-Reis** [comment]
Hello @fowlerp-qlik and @ws752958369, have either of your apps actually been rejected? Our SDK no longer uses UIWebView directly, however we do still need to support apps that may be using it, as not all apps integrating the SDK are submitted to the app store. I do know of apps that have integrated 12.4 and successfully submitted to the app store, so I'd be interested to know if your apps are actually being rejected. Thanks!

**Comment by fowlerp-qlik** [comment]
Last week we successfully submitted to the App Store. So I am closing this issue.
