### ISSUE TITLE
Is the ms-intune sdk mandatory for an app to pass DEVICE ID information 

### ISSUE THREAD

**Issue by amansharmacs** [msintuneappsdk/ms-intune-app-sdk-ios#83]
Hello, 
I was wondering if there is a way to pass device id information for CA policy to distribute the app through MS Intune MDM without integrating Intune sdk as we have a universal app for our clients which they distribute through different MDMs. Not sure about the impact of MS Intune sdk on other MDMs. Looking forward to the help.

**Comment by Kyle-Reis** [comment]
Hey @amansharmacs this should be possible, however the app would not support Intune app protection policy. Would that be acceptable?

**Comment by amansharmacs** [comment]
Yes, it is. It seems integrating the SDK is the only option for smooth operations.

**Comment by Kyle-Reis** [comment]
@amansharmacs have you integrated either ADAL or MSAL into your app?

**Comment by amansharmacs** [comment]
Not yet @Kyle-Reis

**Comment by Kyle-Reis** [comment]
Hey @amansharmacs, this should be possible using MSAL + broker by passing the deviceID essential claim to the acquireToken API
