### ISSUE TITLE
Issues with Xamarin support - getting random error AADSTS650057

### ISSUE THREAD

**Issue by costoda-ey** [msintuneappsdk/ms-intune-app-sdk-ios#84]
Randomly end users are getting an error when we try to enroll a user into Microsoft InTune using the enrollment API stating:

AADSTS650057: Invalid resource.  The client has requested access to a resource which is not listed in the requested permissions in the client's application registration.  The URL it's pointing to is a Graph API from InTune:

https://intunemam.microsoftonline.com 

This error will continue to happen again in a loop until we get Org Data Removed message - of which the application then closes.  Once the application opens again the app works without issues.  

The API we are calling is:
IntuneMAMEnrollmentManager.Instance.RegisterAndEnrollAccount

We are also using the Broker pattern and have ADAL cache configured properly.

**To Reproduce**
1. Launch application
2. If user isn't enrolled, run Register and Enroll Account API
3. User receives two different errors
4. See above

**Expected behavior:**
We expect the user to be enrolled into InTune and be able to use the application.

**Screenshots and logs:**
Both Screenshots and logs contain sensitive information.  Can provide via secure channel (Microsoft Teams)

**Smartphone (please complete the following information):**
Device:  
iOS Version:  13.3.1

**Intune App SDK for iOS (please complete the following information):**
Microsoft.Intune.MAM.Xamarin.iOS - 12.2.0
Microsoft.IdentityModel.Clients.ActiveDirectory - 5.2.7
Builds work without issues.  Not all users are reporting the problem - but users that are looks like they are very close to our "you must use use within 14 days or have it removed" policy.

- Who is the customer?
Many end users have reported the problem. Some are simply removing and reinstalling the app to resolve it.  

- Do you see a trend with it only being reproduced on a specific device?
It seems to affect iOS users - we haven't had any Android users specifically complain.

**Additional context:**
I can provide logs and screen shots via Microsoft Teams.

**Comment by Kyle-Reis** [comment]
Hey @costoda-ey, just wanted to verify with you that someone reached out and got your client ID access to this resource.

**Comment by costoda-ey** [comment]
No one has yet @Kyle-Reis.

**Comment by Kyle-Reis** [comment]
Hey @costoda-ey, checking in to make sure you're unblocked now

**Comment by Kyle-Reis** [comment]
Closing out this issue as I've verified the client ID was granted access.
