### ISSUE TITLE
Cannot add frameworks to Swift project

### ISSUE THREAD

**Issue by sameertotey** [msintuneappsdk/ms-intune-app-sdk-ios#86]
<<<<<<< HEAD
=======
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
**Describe the bug:**
Cannot link my project after adding the swift frameworks.  Get a error related to including Bitcode

**To Reproduce**
1 Add the frameworks: IntuneMAMSwift.framework and IntuneMAMSwiftStub.framework
2 Try to build the project: 
ld: '/Users/sameer/projects/cropplanning/iOS/cropplanner/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/sameer/projects/cropplanning/iOS/cropplanner/IntuneMAMSwiftStub.framework/IntuneMAMSwiftStub' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Expected behavior:**
Expect the project to compile

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
<<<<<<< HEAD
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
=======
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3

**Smartphone (please complete the following information):**

<<<<<<< HEAD
**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?
=======
**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
>>>>>>> 511b242021f1d11850b980b64714960a6c1158a3
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Kyle-Reis** [comment]
Hey @sameertotey. Bitcode is not supported by the Intune App SDK. Please see issue #9. You'll need to disable BitCode in your project to integrate the SDK.

**Comment by sameertotey** [comment]
Thank you for the quick response.  
Would be nice to include it in the external documentation guide at: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios
