### ISSUE TITLE
Intunes with Xamairn forms + msal

### ISSUE THREAD

**Issue by viveknegi51288** [msintuneappsdk/ms-intune-app-sdk-ios#87]
I have an application with msal configuration and now i need to add intune sdk, but after my splash screen its block , nothing happened , please provide some sample app with

Xamarin forms + msal + Intune SDK

**Comment by Kyle-Reis** [comment]
Closing this issue out as it appears to be a duplicate of t[his one](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/41) in our Xamarin bindings repository.
