### ISSUE TITLE
Cannot use MFMailComposeViewController

### ISSUE THREAD

**Issue by yurarodionov** [msintuneappsdk/ms-intune-app-sdk-ios#88]
Cannot use MFMailComposeViewController when Policy managed apps is chosen in app protection policy.
=======

Here is an app protection policy
<img width="487" alt="Screen Shot 2020-03-13 at 3 24 59 PM" src="https://user-images.githubusercontent.com/65158725/82556460-69b0e880-9b72-11ea-8dc1-d628635e36c8.png">

Here is code that doesn't work.

        `let mailComposerVC = MFMailComposeViewController()
        mailComposerVC.mailComposeDelegate = self
        mailComposerVC.setToRecipients(recipients)
        mailComposerVC.setSubject(subject)
        mailComposerVC.setMessageBody(body, isHTML: false)

        if let data = gzippedData {
            mailComposerVC.addAttachmentData(data, mimeType: "application/x-gzip", fileName: "Logs.txt.gz")
        }

        if let screenshot = screenshot,
            let data = UIImageJPEGRepresentation(screenshot, 0.8) {
            mailComposerVC.addAttachmentData(data, mimeType: "image/jpeg", fileName: "screenshot.jpg")
        }

        self.present(mailComposerVC, animated: true, completion: nil)`

This worked fine on 9.0.11 SDK
When I updated to the latest I started receiving the following behavior. 

<img width="451" alt="Screenshot 2020-05-21 at 14 54 38" src="https://user-images.githubusercontent.com/65158725/82556733-007da500-9b73-11ea-9212-0c1c46700210.png">

[Untitled.mp4.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/4662291/Untitled.mp4.zip)

**Comment by Kyle-Reis** [comment]
Hi @yurarodionov, this behavior is by-design. The MFMailComposeViewController essentially transfers data to the unmanaged native mail app. If policy is configured to prohibit this, we block it. The controller was allowed to present with the older version of the SDK because of a previous bug that was introduced by changes in iOS. On older iOS versions, version 9.0.11 of our SDK will block this. This is why it's important to keep the Intune SDK up-to-date! :) Hope this helps.

**Comment by yurarodionov** [comment]
Hi @Kyle-Reis 

This doesn't help since this is the only way to send logs from our app. Is there a way to exclude blocking MFMailComposeViewController? Your answer is much appreciated.

**Comment by Kyle-Reis** [comment]
Hey @yurarodionov, could you simply allow the user to share the file out to an app of their choosing rather than using the MFMailComposeViewController? This way Intune policy will allow them to share the file to the appropriate app (e.g. Outlook) if outgoing data is restricted.

**Comment by yurarodionov** [comment]
@Kyle-Reis what happens if a policy will have sharing option disabled? Will there still be a way to share file?

**Comment by Kyle-Reis** [comment]
If sharing is completely blocked by policy, then this will not be allowed.

**Comment by shafersystems** [comment]
@Kyle-Reis since you are swizzling this method already, it would be great if instead of blocking it, you routed the email compose request to Outlook.  That way, third party apps wouldn't have to implement a separate way to send emails.

**Comment by Kyle-Reis** [comment]
Hi @shafersystems, thanks for the suggestion. Not all of our customers use Outlook for their mail client, so unfortunately we can't just route to Outlook.

**Comment by shafersystems** [comment]
Hi @Kyle Reis,

We have a customer that is using Intune with Native iOS email.  Is there a recommended way of being able to send a file to email without requiring them to totally relax their app protection policy?

**Comment by Kyle-Reis** [comment]
Hey @shafersystems, if all of their users are on enrolled devices, they can use MDM share policy to choose which apps can share data with one another, and set the outgoing MAM share policy for Intune apps to "Policy managed apps with OS sharing". This will turn off Intune encryption in outgoing share scenarios with the expectation that MDM policy has been configured to restrict data. Note: This requires that the IntuneMAMUPN setting is configured and targeted in MDM app config as mentioned [here](https://docs.microsoft.com/mem/intune/apps/data-transfer-between-apps-manage-ios#configure-user-upn-setting-for-microsoft-intune-or-third-party-emm).

**Comment by shafersystems** [comment]
@Kyle-Reis thank you!!!
