### ISSUE TITLE
Intune SDK register MAM

### ISSUE THREAD

**Issue by ws752958369** [msintuneappsdk/ms-intune-app-sdk-ios#89]
MSAL SDK Version:.1.1.2
Intune SDK Version:12.4.0
Question:
当App想要去注册MAM功能时，Intune SDk 报错:
The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token.
statusCode:203
麻烦帮忙查找下问题，谢谢！

**Comment by ws752958369** [comment]
已经在Info.Plist中设置过了MAMSetings。
<key>IntuneMAMSettings</key>
	<dict>
		<key>ADALClientId</key>
		<string>2a498427-76d7-4512-b8ad-7d87e359d507</string>
		<key>ADALAuthority</key>
		<string>https://login.microsoftonline.com/common</string>
		<key>ADALRedirectUri</key>
		<string>msauth.com.wantong.dev://auth</string>
	</dict>

**Comment by Kyle-Reis** [comment]
Hi @ws752958369,  is your application calling registerAndEnrollAccount?

**Comment by ws752958369** [comment]
@Kyle-Reis  yes,i called [[IntuneMAMEnrollmentManager instance] registerAndEnrollAccount:account];

**Comment by Kyle-Reis** [comment]
@ws752958369, have you already acquired a token with MSAL? registerAndEnrollAccount is meant to be used for silent enrollment if the application has already authenticated. This error indicates that we can't find an existing token in the cache.

**Comment by ws752958369** [comment]
@Kyle-Reis  yes,i have called acquireTokenWithParameters,and this method will return a completionBlock with MSALResult, then i called  - (void)registerAndEnrollAccount  with params MSALAccount.account.username

**Comment by Kyle-Reis** [comment]
Hi @ws752958369. Have you verified that the username property evaluates to the expected UPN of the user? Also, did you include com.microsoft.adalcache and com.microsoft.intune.mam in the application's keychain sharing groups as mentioned in step 4 [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app)?

**Comment by ws752958369** [comment]
@Kyle-Reis  Hi,the application's keychain settings:
<string>$(AppIdentifierPrefix)com.wantong.dev</string>
<string>$(AppIdentifierPrefix)com.microsoft.intune.mam</string>
<string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>

**Comment by ws752958369** [comment]
@Kyle-Reis  i have contact your staff service and verified  that the username property is the expected UPN .

**Comment by Kyle-Reis** [comment]
@ws752958369, I meant to set a breakpoint while debugging the app to verify the value you get is what is expected. Also, could you double check to ensure the ADAL settings you've specified in the IntuneMAMSettings match what you're using with MSAL auth?

**Comment by ws752958369** [comment]
@Kyle-Reis  Thanks,now it's okay.The specific reason is that we forget to Intune protection services provide application access

**Comment by ws752958369** [comment]
But another problem came into being: the App crash when launching
Thread 0 Crashed:
0   IntuneMAM                     	0x000000010590a4e4 0x10583c000 + 845028
1   IntuneMAM                     	0x000000010590a4dc 0x10583c000 + 845020
2   libdispatch.dylib             	0x0000000216e5e484 _dispatch_client_callout + 16
3   libdispatch.dylib             	0x0000000216e006d8 _dispatch_once_callout + 28
4   IntuneMAM                     	0x0000000105909100 0x10583c000 + 839936
5   libobjc.A.dylib               	0x00000002165f1024 CALLING_SOME_+initialize_METHOD + 24
6   libobjc.A.dylib               	0x00000002165f6f84 _class_initialize + 296
7   libobjc.A.dylib               	0x00000002166008f8 lookUpImpOrForward + 280
8   libobjc.A.dylib               	0x000000021660d098 _objc_msgSend_uncached + 56
9   Hippius                       	0x0000000104a867ac 0x104614000 + 4663212
10  Hippius                       	0x000000010464bc08 0x104614000 + 228360
11  Hippius                       	0x000000010464b3cc 0x104614000 + 226252
12  IntuneMAM                     	0x0000000105a186d8 0x10583c000 + 1951448
13  IntuneMAM                     	0x0000000105a19308 0x10583c000 + 1954568
14  IntuneMAM                     	0x0000000105a1b6ec 0x10583c000 + 1963756
15  UIKitCore                     	0x00000002444a00f4 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 412
16  UIKitCore                     	0x00000002444a185c -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3340
17  UIKitCore                     	0x00000002444a72a8 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1552
18  UIKitCore                     	0x0000000243d43358 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 784
19  UIKitCore                     	0x0000000243d4bfd8 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 160
20  UIKitCore                     	0x0000000243d42fd4 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 240
21  UIKitCore                     	0x0000000243d43974 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1076
22  UIKitCore                     	0x0000000243d41a74 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 772
23  UIKitCore                     	0x0000000243d41720 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 432
24  UIKitCore                     	0x0000000243d468e0 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 220
25  UIKitCore                     	0x0000000243d47840 _performActionsWithDelayForTransitionContext + 112
26  UIKitCore                     	0x0000000243d46798 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 248
27  UIKitCore                     	0x0000000243d4b684 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 368
28  UIKitCore                     	0x00000002444a57a0 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 540
29  UIKitCore                     	0x000000024408ebac -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 364
30  FrontBoardServices            	0x0000000219e589d4 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 444
31  FrontBoardServices            	0x0000000219e6379c __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 260
32  FrontBoardServices            	0x0000000219e62e94 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 64
33  libdispatch.dylib             	0x0000000216e5e484 _dispatch_client_callout + 16
34  libdispatch.dylib             	0x0000000216e01e20 _dispatch_block_invoke_direct$VARIANT$mp + 224
35  FrontBoardServices            	0x0000000219e97a9c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
36  FrontBoardServices            	0x0000000219e97728 -[FBSSerialQueue _performNext] + 416
37  FrontBoardServices            	0x0000000219e97d44 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
38  CoreFoundation                	0x00000002173b41cc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
39  CoreFoundation                	0x00000002173b414c __CFRunLoopDoSource0 + 88
40  CoreFoundation                	0x00000002173b3a30 __CFRunLoopDoSources0 + 176
41  CoreFoundation                	0x00000002173ae8fc __CFRunLoopRun + 1040
42  CoreFoundation                	0x00000002173ae1cc CFRunLoopRunSpecific + 436
43  GraphicsServices              	0x0000000219625584 GSEventRunModal + 100
44  UIKitCore                     	0x00000002444a9054 UIApplicationMain + 212
45  IntuneMAM                     	0x0000000105a2e664 0x10583c000 + 2041444
46  Hippius                       	0x00000001046388f4 0x104614000 + 149748
47  libdyld.dylib                 	0x0000000216e6ebb4 start + 4

**Comment by ws752958369** [comment]
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4368449536
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000104614000-000000010516c000 [ 11.3M] r-x/r-x SM=COW  ...s.app/Hippius

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [372]
Triggered by Thread:  0

**Comment by ws752958369** [comment]
@Kyle-Reis  could you help me ?

**Comment by Kyle-Reis** [comment]
Hi @ws752958369, glad to hear you were able to get past the enrollment issue. Could you share the crash log for the other issue?

**Comment by ws752958369** [comment]
[Hippius  2020-6-1, 1-46 PM.TXT](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/4714306/Hippius.2020-6-1.1-46.PM.TXT)

**Comment by ws752958369** [comment]
@Kyle-Reis That's a complete crash log
