### ISSUE TITLE
Could you please provide a "bitcode" enabled version?

### ISSUE THREAD

**Issue by ddrdjboy** [msintuneappsdk/ms-intune-app-sdk-ios#9]
Could you please provide a "bitcode" enabled version?

**Comment by paulw11** [comment]
+1 to this.  Bitcode was introduced 2 years ago and this is the only framework preventing me from enabling Bitcode for my app.

**Comment by OxyFlax** [comment]
+1 Should definitely be enabled now

**Comment by megamingus** [comment]
+1

**Comment by Kyle-Reis** [comment]
Unfortunately, enabling bitcode introduces an intermediate language layer which our SDK simply cannot hook. Therefore, we do not support bitcode-enabled apps.

**Comment by amadeu01** [comment]
+1
