### ISSUE TITLE
Undocumented error dialog, nothing printed to iOS console: "Error" "Unexpected failure. Contact your IT administrator for help."

### ISSUE THREAD

**Issue by BenLeggiero** [msintuneappsdk/ms-intune-app-sdk-ios#90]
**Describe the bug:**
The following error dialog appears when the app launches:

**To Reproduce**
1. Start our app which integrates [version 12.4.0 of this repository](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/tree/12.4.0)
2. It might be relevant to use [MSAL 1.1.3](https://github.com/AzureAD/microsoft-authentication-library-for-objc/tree/1.1.3), but I'm not sure
3. See error

**Expected behavior:**
Intune takes over and presents the user with a Microsoft login webpage

**Screenshots and logs:**
- ![image](https://user-images.githubusercontent.com/10189808/83558681-9c42d580-a4d0-11ea-91a0-b4dbac996782.png)
- It's unclear to me if there are any iOS console message from Intune (most are from Google services like Firebase and Crashlytics). Below are all the ones I suspect Intune logged to the iOS console:
```plain
2020-06-02 13:00:46.380877-0600 <<REDACTED APP NAME>>[1491:730899] WF: === Starting WebFilter logging for process <<REDACTED APP NAME>>
2020-06-02 13:00:46.380908-0600 <<REDACTED APP NAME>>[1491:730899] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-06-02 13:00:46.380977-0600 <<REDACTED APP NAME>>[1491:730899] WF: _WebFilterIsActive returning: NO
2020-06-02 13:00:46.425800-0600 Smartcrypt for Intune[1491:730899] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-06-02 13:00:46.425826-0600 Smartcrypt for Intune[1491:730899] WF: _WebFilterIsActive returning: NO
```

**Smartphone (please complete the following information):**
 - Device: iPhone 11, iPad Air (3rd generation), iOS Simulator (iPhone 11), iOS Simulator (iPhone SE [2nd generation])
 - OS: iOS 13.5

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? **12.4.0** Are you using the latest version? **As far as I know, yes**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? **UIKit: Swift, Objective-C, Objective-C++, C++**
- ~~For errors during build, does the app build without Intune SDK integration?~~
- For errors post build, does the app launch without being Intune SDK integrated? **Yes**
- Who is the customer? **Please be more specific**
- Do you see a trend with it only being reproduced on a specific device? **No; this happens on all my test devices and on the Simulator. This happens with and without the Company Portal app installed/setup.**

**Additional context:**
When I roll our codebase back to an older version with a different integration approach, Intune works as expected (then, it was version **12.0.18**).

This error is not documented on this page: https://docs.microsoft.com/en-us/mem/intune/apps/troubleshoot-mam

**Comment by Kyle-Reis** [comment]
Hi @BenLeggiero, with the code which uses 12.0.18, were you also using MSAL 1.1.3? Or was it a different version of ADAL/MSAL?

**Comment by BenLeggiero** [comment]
@Kyle-Reis It was not code that I maintained; I'm new to the project. It appears ADAL 4.0.4 integration was started but not finished. MSAL was not yet introduced.

**Comment by Kyle-Reis** [comment]
Hey @BenLeggiero, have you reviewed [these instructions](https://docs.microsoft.com//mem/intune/developer/app-sdk-ios#configure-adalmsal-settings-for-the-intune-app-sdk) when transitioning over to MSAL? There are some additional requirements for MSAL that did not apply to ADAL. App developers need to create a custom app registration and give it access to the Intune MAM service. Then the ADALClientId ADALRedirectUri settings must be specified in the IntuneMAMSettings.

**Comment by BenLeggiero** [comment]
Yes I have, @Kyle-Reis. I'll try reverting to a commit before the transition and perform the steps again.

**Comment by BenLeggiero** [comment]
Okay, @Kyle-Reis , I've done exactly that! Now the error dialog in this screenshot is no longer appearing, but the app won't let me sign in (infinite sign-in loop).

Should I open a separate issue for that?

**Comment by Kyle-Reis** [comment]
Hey @BenLeggiero, any luck here? If you're still seeing this issue, could you try out our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 12.6.1)? We made a few MSAL related fixes there.

**Comment by mci92** [comment]
I got the same error after I removed the tenant id (left only https://login.microsoftonline.com/) in the ADALAutority property from the plist file.

**Comment by BenLeggiero** [comment]
@Kyle-Reis I have encountered a plethora of strange and undocumented errors, empty `NSError` objects on failure, bizarre rejection messages, opaque behavior, and even repeated debugger glitches which caused the physical device to be disconnected.

But, I've not seen this particular error again since sending that comment.

**Comment by Kyle-Reis** [comment]
@BenLeggiero, I'd be glad to help with the other errors as well. Are these all happening immediately at startup during auth as well? Is an alert shown with any sort of error message?

**Comment by BenLeggiero** [comment]
@Kyle-Reis currently, we're trying to figure out why it's not accepting the auth/Bearer token we're passing in the `Authorization` header field, instead we're getting back an HTML login page every time.

**Comment by Kyle-Reis** [comment]
Hey @BenLeggiero, are you calling an MSAL API with this token? Or is this something in Intune?

**Comment by BenLeggiero** [comment]
@Kyle-Reis we're trying to go through an app proxy. I think we've cleared all the MSAL stuff at this point.

**Comment by Kyle-Reis** [comment]
Closing out this issue as original problem was addressed. Please do open another issue if you're having any other problems.

**Comment by amadeu01** [comment]
@Kyle-Reis I am getting this error. How can I dismiss the dialog? It kept retiring forever. I do not have a option for dismiss the dialog.

**Comment by Kyle-Reis** [comment]
Hi @amadeu01, which version of Intune and MSAL is your application linking to?
