### ISSUE TITLE
Intune MAM 12.4.0 + MSAL 1.0.3 + Swift 5.0 crash on registerAndEnrollAccount

### ISSUE THREAD

**Issue by jagrutiJ** [msintuneappsdk/ms-intune-app-sdk-ios#91]
@msintuneappsdk

IntuneMAMEnrollmentManager.instance().registerAndEnrollAccount("xyz@test.com")
I am initialising IntuneMAMEnrollmentManager after successfully login with MSAL
Passing email id to above funtion and it is crashing.
Need your assistance @msintuneappsdk

**Comment by Kyle-Reis** [comment]
Hi @jagrutiJ, could you share the exception details of the crash and a crash log if possible?

**Comment by Kyle-Reis** [comment]
Hey @jagrutiJ, are you still experiencing this issue?

**Comment by jagrutiJ** [comment]
I changed the implementation of swift to objective c
Now it is working
Thanks for your support

**Comment by Kyle-Reis** [comment]
@jagrutiJ,  Apps should be able to call our APIs from both Objective-C and Swift. Does the app contain any Swift code now? Or is it all Objective-C? If it does contain Swift, are you linking against the Swift version of our SDK?

**Comment by Kyle-Reis** [comment]
Closing out this issue as the problem appears to have been resolved.
