### ISSUE TITLE
Stuck on "refresh policies" error message 

### ISSUE THREAD

**Issue by mci92** [msintuneappsdk/ms-intune-app-sdk-ios#94]
**Describe the bug:**
The refresh policies error dialog appears when the app launches.
If the OK button is taped, the same dialog is still opened. If OK is pressed again the dialog is closed and the app is stuck on the "Application logon" screen but nothing is displayed the entire page is white. 
The strange part is that the login flow worked without any issue until now. 
No code change or device OS upgrade was done but this issue started occurring after a certain amount of time (days) in which I didn't used the app or phone at all. 

**Expected behavior:**
Intune takes over and opens a broker app in order to login 

**To Reproduce**

1. Integrate InTune SDK version 12.4.0 with MSAL 1.0.7 
2. Don't use the app for several days 

**Screenshots and logs:**
![intune issue](https://user-images.githubusercontent.com/30295097/84778328-8282b180-afeb-11ea-8f67-845050e1f466.PNG)

- No XCode console log is written when the error dialog is displayed. 

**Devices:** 
- iphone 6 plus OS 12.4.6

**Intune App SDK for iOS (please complete the following information):**

- What version of the Intune SDK are you using? 12.4.0 
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? UIKit: **Objective-C + cordova + ExtsJS**  
- For errors post build, does the app launch without being Intune SDK integrated? **Yes**
- Do you see a trend with it only being reproduced on a specific device? **So far I managed to reproduce it only on specified device**

**Additional context:**
The "loginAndEnrollAccount" method is not called when the error screen is display. This appears as soon as the app is launched.

**Comment by Kyle-Reis** [comment]
Hi @mci92, this looks to be the same issue as this:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/922

We’re working on a fix and will have an update available soon which should address it.

**Comment by mci92** [comment]
Great, waiting on an update. 
Let me know if I can help with any logs or debug info.

**Comment by Kyle-Reis** [comment]
Hi @mci92, could you give the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 12.6.1) a try? Thanks

**Comment by mci92** [comment]
Hi, I replaced the framework with the latest and I am now able to enter my credentials.
But after I do that I get the following error: "the reply URL specified in the request does not match the reply URLs configured for the application:...". 
Our application is configured as single tenant so in the .plist file besides ADPRedirectSchema and ADAPClientID, we have the ADAPAutority as https://login.microsoftonline.com/<tenant id>.
It is also strange that we have a broker app install on the device  (both "comp portal" and "authenticator")  but they are not launched for the login . 
Using Safari on the mac I see that the web browser on the device is accessing https://login.microsoftonline.com/ without the tenant id. 

Please advice.

**Comment by mci92** [comment]
This is what I have configured in the azure console 
![image](https://user-images.githubusercontent.com/30295097/86255274-96b7d880-bbbf-11ea-8a9b-6373f0c75f20.png)
If I change the ADALRedirectScheme from msauth.com.ag.MiPlanAG://auth to msauth.com.ag.MiPlanAG the broker app launches but I still get the same error message.

**Comment by Kyle-Reis** [comment]
Hi @mci92. The ADALRedirectScheme setting is meant for applications that have a redirect URI in the format of [scheme]://[bundle. ID]. Your application's redirect URI does not appear to be in this format. You should instead use the ADALRedirectUri setting to specify the full redirect URI.

If your application will only be used in a single tenant, you should configure the ADALAuthority setting as well. The value of this setting should be in the format of "https://login.microsoftonline.com/[tenant]/", where [tenant] is the tenant ID of the AAD tenant or a domain associated with the AAD tenant. 

More information on these and other ADAL settings for the Intune SDK can be found here: https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-adalmsal-settings-for-the-intune-app-sdk

**Comment by mci92** [comment]
After changing the property from ADALRedirectScheme  to ADALRedirectUri it fixed the issue. 

Thank you!
