### ISSUE TITLE
ver 12.6.1: Error running IntuneMANConfigurator ("unrecognized selector sent to instance")

### ISSUE THREAD

**Issue by slmille4** [msintuneappsdk/ms-intune-app-sdk-ios#95]
I'm trying to run the IntuneMANConfigurator and I get the following error. Both myself and another iOS developer have gotten this same error:

2020-07-09 11:44:26.573 IntuneMAMConfigurator[25381:864801] -[__NSCFString count]: unrecognized selector sent to instance 0x7feef0e0fe90
2020-07-09 11:44:26.573 IntuneMAMConfigurator[25381:864801] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x7feef0e0fe90'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff32434d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6b1585bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff324b3c97 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff3239957b ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff32398f58 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fff3239d41b +[NSSet setWithArray:] + 41
	6   IntuneMAMConfigurator               0x000000010bfe905a convertToMAMConfiguredPlist + 2058
	7   IntuneMAMConfigurator               0x000000010bfe7a2f configureInfoPlist + 383
	8   IntuneMAMConfigurator               0x000000010bfe7f2c main + 476
	9   libdyld.dylib                       0x00007fff6c2ffcc9 start + 1
	10  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by Kyle-Reis** [comment]
Hey @slmille4, what do you have configured for LSApplicationQueriesSchemes in your Info.plist?

**Comment by slmille4** [comment]
just <string>ms-outlook</string>

**Comment by Kyle-Reis** [comment]
@slmille4, this crash seems to indicate that LSApplicationQueriesSchemes is configured as a string value. It should be an array of strings. See https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/plist/info/LSApplicationQueriesSchemes

**Comment by slmille4** [comment]
@Kyle-Reis that fixed it!
