### ISSUE TITLE
REDIST.txt file is missing

### ISSUE THREAD

**Issue by KyLeggiero** [msintuneappsdk/ms-intune-app-sdk-ios#96]
[Paragraph 2-b of this repository's license](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/blob/master/Microsoft%20License%20Terms%20Intune%20App%20SDK%20for%20iOS.pdf) requires that code within this repository which is redistributed must be among those listed in `REDIST.txt`. However, [`REDIST.txt` does not appear in this repository](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/search?q=REDIST.txt&unscoped_q=REDIST.txt). This makes it against the license to distribute any of the frameworks in this repository (including distribution within an app bundle), as all the frameworks contain code (for instance, `.h` and `.plist` files, which contain C code and property list code, respectively).

**Comment by Abhinay1997** [comment]
Can someone help with getting the 'REDIST.txt' file ?

**Comment by Abhinay1997** [comment]
@msintuneappsdk @Kyle-Reis , any help on this is appreciated as our organization is not signing off on Intune because of this.

**Comment by Abhinay1997** [comment]
@KyLeggiero were you able to sort it out ?

@Kyle-Reis @msintuneappsdk please help out on this.

**Comment by KyLeggiero** [comment]
> @KyLeggiero were you able to sort it out ?

Nope, not at all

**Comment by KyLeggiero** [comment]
Reopening

**Comment by KyLeggiero** [comment]
@ShruthiAchutha this issue is still relevant. It's not "stale"; it has just been ignored.

Also it seems I have insufficient permissions and cannot reopen this issue.

**Comment by wangxiaoms** [comment]
@KyLeggiero REDIST.txt file is added, closing the issue.
https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/blob/main/REDIST.txt
