### ISSUE TITLE
Is any user info available after calling loginAndEnrollAccount(nil)?

### ISSUE THREAD

**Issue by slmille4** [msintuneappsdk/ms-intune-app-sdk-ios#99]
Is it possible to get any Intune information such as what user an iOS device is associated with after calling loginAndEnrollAccount(nil)? It would be great if that were possible so that I could do things like associated biometrics with a particular login ID. BTW, I'm using OAUTH not ADAL for authentication.

**Comment by Kyle-Reis** [comment]
Hi @slmille4, you can call IntuneMAMEnrollmentManager.instance().enrolledAccount() after a successful enrollment to retrieve the UPN of the enrolled user. All of the Intune SDK's public APIs can be found here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/tree/master/Headers

**Comment by slmille4** [comment]
> Hi @slmille4, you can call IntuneMAMEnrollmentManager.instance().enrolledAccount() after a successful enrollment to retrieve the UPN of the enrolled user. All of the Intune SDK's public APIs can be found here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/tree/master/Headers

Should that still be called for apps that don't use ADAL? I'm following this part of the App SDD for iOS Developer Guide:

"Apps that do not use ADAL or MSAL
Apps that do not sign in the user using ADAL or MSAL can still receive app protection policy from the Intune MAM service by calling the API to have the SDK handle that authentication. Apps should use this technique when they have not authenticated a user with Azure AD but still need to retrieve app protection policy to help protect data. An example is if another authentication service is being used for app sign-in, or if the app does not support signing in at all. To do this, the application can call the loginAndEnrollAccount method on the IntuneMAMEnrollmentManager instance:"

but the enrollmentRequest(with status:...) function in my IntuneMAMEEnrollmentDelegate class never gets called. I'm not seeing any errors getting logged though?

**Comment by Kyle-Reis** [comment]
Hey @slmille4, is your app linking to ADAL or MSAL? Even if your app does not explicitly call into ADAL/MSAL, linking against one of these libraries is a required dependency of the Intune SDK.

For the enrollmentRequestWithStatus issue, did you set the IntuneMAMEnrollmentManager.instance().delegate property to an instance of a class which implements this method? You can see an [example of this](https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App/blob/master/chatr/AppDelegate.swift) in our Chatr sample app.

**Comment by slmille4** [comment]
@Kyle-Reis Yes, the app is linking to ADAL. For the the IntuneMAMEnrollmentManager.instance().delegate property, I just copied the sample file from Chatr and set delegate in willFinishLaunchingWithOptions. I'm calling loginAndEnrollAccount from the didFinishLaunchingWithOptions function.

**Comment by Kyle-Reis** [comment]
Hey @slmille4, is the enrollmentRequestWithStatus method getting called after enrollment now?

**Comment by slmille4** [comment]
@Kyle-Reis No, none of the delegate methods are called after calling loginAndEnrollAccount(nil)

**Comment by Kyle-Reis** [comment]
@slmille4, are you able to share the code which sets the delegate property as well as the delegate implementation?

**Comment by slmille4** [comment]
@Kyle-Reis sure but it's extremely basic and just a copy and paste from chatr at the moment
class AppDelegate: UIResponder, UIApplicationDelegate {
    let enrollmentDelegate = EnrollmentDelegateClass()
    let policyDelegate = PolicyDelegateClass()
...
func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        IntuneMAMPolicyManager.instance().delegate = self.policyDelegate
        IntuneMAMEnrollmentManager.instance().delegate = self.enrollmentDelegate
...
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)
...
EnrollmentDelegateClass/PolicyDelegateClass are just a copy/paste from chatr.

I've attached a screenshot of the linked libraries
<img width="253" alt="Screen Shot 2020-08-10 at 9 09 51 PM" src="https://user-images.githubusercontent.com/6100072/89845932-d8885700-db4d-11ea-8186-a89957344d39.png">

**Comment by alexwalpole** [comment]
I am having a similar issue as well. Without linking ADAL.framework i get this error with loginandenrollaccount(nil). Even if i link MSAL.framework instead. 
![Screen Shot 2020-09-16 at 4 01 29 PM](https://user-images.githubusercontent.com/30059432/93386572-e492c300-f835-11ea-89f8-dde37537f3f7.png)

**Comment by Kyle-Reis** [comment]
Hi @laveur and @alexwalpole, do your apps specify [these schemes](https://docs.microsoft.com/azure/active-directory/develop/scenario-mobile-app-configuration#step-3-add-lsapplicationqueriesschemes) under LSApplicationQueriesSchemes in the Info.plist?

**Comment by Kyle-Reis** [comment]
@slmille4, @alexwalpole, @laveur - checking in to see if you're still having issues here.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you are still experiencing issues.
